package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PaymentMethod;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Voucher;
import com.tc.app.exchangemonitor.model.cayenne.persistent.VoucherPayment;

/**
 * Class _AccountBankInfo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AccountBankInfo extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ACCT_BANK_ID_PK_COLUMN = "acct_bank_id";

	public static final Property<String> ACCT_BANK_CITY = new Property<>("acctBankCity");
	public static final Property<String> ACCT_BANK_COUNTRY_CODE = new Property<>("acctBankCountryCode");
	public static final Property<String> ACCT_BANK_IBAN_NUM = new Property<>("acctBankIbanNum");
	public static final Property<String> ACCT_BANK_INFO_STATUS = new Property<>("acctBankInfoStatus");
	public static final Property<String> ACCT_BANK_ROUTING_NUM = new Property<>("acctBankRoutingNum");
	public static final Property<Short> ADDR_ACCT_ADDR_NUM = new Property<>("addrAcctAddrNum");
	public static final Property<Integer> ADDR_ACCT_NUM = new Property<>("addrAcctNum");
	public static final Property<String> BANK_ACCT_NO = new Property<>("bankAcctNo");
	public static final Property<Integer> BANK_ACCT_NUM = new Property<>("bankAcctNum");
	public static final Property<String> BANK_ADDR = new Property<>("bankAddr");
	public static final Property<String> BANK_NAME = new Property<>("bankName");
	public static final Property<String> BANK_SHORT_NAME = new Property<>("bankShortName");
	public static final Property<String> CORRESP_BANK_ACCT_NO = new Property<>("correspBankAcctNo");
	public static final Property<String> CORRESP_BANK_CITY = new Property<>("correspBankCity");
	public static final Property<String> CORRESP_BANK_COUNTRY_CODE = new Property<>("correspBankCountryCode");
	public static final Property<String> CORRESP_BANK_IBAN_NUM = new Property<>("correspBankIbanNum");
	public static final Property<String> CORRESP_BANK_INSTR_TYPE_ID = new Property<>("correspBankInstrTypeId");
	public static final Property<String> CORRESP_BANK_NAME = new Property<>("correspBankName");
	public static final Property<String> CORRESP_BANK_ROUTING_NUM = new Property<>("correspBankRoutingNum");
	public static final Property<String> CORRESP_SWIFT_CODE = new Property<>("correspSwiftCode");
	public static final Property<Short> COST_SEND_ID = new Property<>("costSendId");
	public static final Property<String> FURTHER_CREDIT_TO = new Property<>("furtherCreditTo");
	public static final Property<String> FURTHER_CREDIT_TO_EXT_ACCT_KEY = new Property<>("furtherCreditToExtAcctKey");
	public static final Property<String> GL_ACCT_CODE = new Property<>("glAcctCode");
	public static final Property<String> GL_ACCT_DESCR = new Property<>("glAcctDescr");
	public static final Property<String> P_OR_RIND = new Property<>("pOrRInd");
	public static final Property<Short> SELLING_OFFICE_NUM = new Property<>("sellingOfficeNum");
	public static final Property<String> SPECIAL_PAYMENT_INSTR = new Property<>("specialPaymentInstr");
	public static final Property<String> SWIFT_CODE = new Property<>("swiftCode");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<Integer> VC_ACCT_NUM = new Property<>("vcAcctNum");
	public static final Property<Account> ACCOUNT = new Property<>("account");
	public static final Property<Account> ACCOUNT1 = new Property<>("account1");
	public static final Property<Commodity> COMMODITY = new Property<>("commodity");
	public static final Property<PaymentMethod> PAYMENT_METHOD = new Property<>("paymentMethod");
	public static final Property<List<VoucherPayment>> VOUCHER_PAYMENTS = new Property<>("voucherPayments");
	public static final Property<List<Voucher>> VOUCHERS = new Property<>("vouchers");
	public static final Property<List<Voucher>> VOUCHERS1 = new Property<>("vouchers1");
	public static final Property<List<Voucher>> VOUCHERS2 = new Property<>("vouchers2");

	public void setAcctBankCity(final String acctBankCity)
	{
		this.writeProperty("acctBankCity", acctBankCity);
	}

	public String getAcctBankCity()
	{
		return (String) this.readProperty("acctBankCity");
	}

	public void setAcctBankCountryCode(final String acctBankCountryCode)
	{
		this.writeProperty("acctBankCountryCode", acctBankCountryCode);
	}

	public String getAcctBankCountryCode()
	{
		return (String) this.readProperty("acctBankCountryCode");
	}

	public void setAcctBankIbanNum(final String acctBankIbanNum)
	{
		this.writeProperty("acctBankIbanNum", acctBankIbanNum);
	}

	public String getAcctBankIbanNum()
	{
		return (String) this.readProperty("acctBankIbanNum");
	}

	public void setAcctBankInfoStatus(final String acctBankInfoStatus)
	{
		this.writeProperty("acctBankInfoStatus", acctBankInfoStatus);
	}

	public String getAcctBankInfoStatus()
	{
		return (String) this.readProperty("acctBankInfoStatus");
	}

	public void setAcctBankRoutingNum(final String acctBankRoutingNum)
	{
		this.writeProperty("acctBankRoutingNum", acctBankRoutingNum);
	}

	public String getAcctBankRoutingNum()
	{
		return (String) this.readProperty("acctBankRoutingNum");
	}

	public void setAddrAcctAddrNum(final Short addrAcctAddrNum)
	{
		this.writeProperty("addrAcctAddrNum", addrAcctAddrNum);
	}

	public Short getAddrAcctAddrNum()
	{
		return (Short) this.readProperty("addrAcctAddrNum");
	}

	public void setAddrAcctNum(final Integer addrAcctNum)
	{
		this.writeProperty("addrAcctNum", addrAcctNum);
	}

	public Integer getAddrAcctNum()
	{
		return (Integer) this.readProperty("addrAcctNum");
	}

	public void setBankAcctNo(final String bankAcctNo)
	{
		this.writeProperty("bankAcctNo", bankAcctNo);
	}

	public String getBankAcctNo()
	{
		return (String) this.readProperty("bankAcctNo");
	}

	public void setBankAcctNum(final Integer bankAcctNum)
	{
		this.writeProperty("bankAcctNum", bankAcctNum);
	}

	public Integer getBankAcctNum()
	{
		return (Integer) this.readProperty("bankAcctNum");
	}

	public void setBankAddr(final String bankAddr)
	{
		this.writeProperty("bankAddr", bankAddr);
	}

	public String getBankAddr()
	{
		return (String) this.readProperty("bankAddr");
	}

	public void setBankName(final String bankName)
	{
		this.writeProperty("bankName", bankName);
	}

	public String getBankName()
	{
		return (String) this.readProperty("bankName");
	}

	public void setBankShortName(final String bankShortName)
	{
		this.writeProperty("bankShortName", bankShortName);
	}

	public String getBankShortName()
	{
		return (String) this.readProperty("bankShortName");
	}

	public void setCorrespBankAcctNo(final String correspBankAcctNo)
	{
		this.writeProperty("correspBankAcctNo", correspBankAcctNo);
	}

	public String getCorrespBankAcctNo()
	{
		return (String) this.readProperty("correspBankAcctNo");
	}

	public void setCorrespBankCity(final String correspBankCity)
	{
		this.writeProperty("correspBankCity", correspBankCity);
	}

	public String getCorrespBankCity()
	{
		return (String) this.readProperty("correspBankCity");
	}

	public void setCorrespBankCountryCode(final String correspBankCountryCode)
	{
		this.writeProperty("correspBankCountryCode", correspBankCountryCode);
	}

	public String getCorrespBankCountryCode()
	{
		return (String) this.readProperty("correspBankCountryCode");
	}

	public void setCorrespBankIbanNum(final String correspBankIbanNum)
	{
		this.writeProperty("correspBankIbanNum", correspBankIbanNum);
	}

	public String getCorrespBankIbanNum()
	{
		return (String) this.readProperty("correspBankIbanNum");
	}

	public void setCorrespBankInstrTypeId(final String correspBankInstrTypeId)
	{
		this.writeProperty("correspBankInstrTypeId", correspBankInstrTypeId);
	}

	public String getCorrespBankInstrTypeId()
	{
		return (String) this.readProperty("correspBankInstrTypeId");
	}

	public void setCorrespBankName(final String correspBankName)
	{
		this.writeProperty("correspBankName", correspBankName);
	}

	public String getCorrespBankName()
	{
		return (String) this.readProperty("correspBankName");
	}

	public void setCorrespBankRoutingNum(final String correspBankRoutingNum)
	{
		this.writeProperty("correspBankRoutingNum", correspBankRoutingNum);
	}

	public String getCorrespBankRoutingNum()
	{
		return (String) this.readProperty("correspBankRoutingNum");
	}

	public void setCorrespSwiftCode(final String correspSwiftCode)
	{
		this.writeProperty("correspSwiftCode", correspSwiftCode);
	}

	public String getCorrespSwiftCode()
	{
		return (String) this.readProperty("correspSwiftCode");
	}

	public void setCostSendId(final Short costSendId)
	{
		this.writeProperty("costSendId", costSendId);
	}

	public Short getCostSendId()
	{
		return (Short) this.readProperty("costSendId");
	}

	public void setFurtherCreditTo(final String furtherCreditTo)
	{
		this.writeProperty("furtherCreditTo", furtherCreditTo);
	}

	public String getFurtherCreditTo()
	{
		return (String) this.readProperty("furtherCreditTo");
	}

	public void setFurtherCreditToExtAcctKey(final String furtherCreditToExtAcctKey)
	{
		this.writeProperty("furtherCreditToExtAcctKey", furtherCreditToExtAcctKey);
	}

	public String getFurtherCreditToExtAcctKey()
	{
		return (String) this.readProperty("furtherCreditToExtAcctKey");
	}

	public void setGlAcctCode(final String glAcctCode)
	{
		this.writeProperty("glAcctCode", glAcctCode);
	}

	public String getGlAcctCode()
	{
		return (String) this.readProperty("glAcctCode");
	}

	public void setGlAcctDescr(final String glAcctDescr)
	{
		this.writeProperty("glAcctDescr", glAcctDescr);
	}

	public String getGlAcctDescr()
	{
		return (String) this.readProperty("glAcctDescr");
	}

	public void setPOrRInd(final String pOrRInd)
	{
		this.writeProperty("pOrRInd", pOrRInd);
	}

	public String getPOrRInd()
	{
		return (String) this.readProperty("pOrRInd");
	}

	public void setSellingOfficeNum(final Short sellingOfficeNum)
	{
		this.writeProperty("sellingOfficeNum", sellingOfficeNum);
	}

	public Short getSellingOfficeNum()
	{
		return (Short) this.readProperty("sellingOfficeNum");
	}

	public void setSpecialPaymentInstr(final String specialPaymentInstr)
	{
		this.writeProperty("specialPaymentInstr", specialPaymentInstr);
	}

	public String getSpecialPaymentInstr()
	{
		return (String) this.readProperty("specialPaymentInstr");
	}

	public void setSwiftCode(final String swiftCode)
	{
		this.writeProperty("swiftCode", swiftCode);
	}

	public String getSwiftCode()
	{
		return (String) this.readProperty("swiftCode");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setVcAcctNum(final Integer vcAcctNum)
	{
		this.writeProperty("vcAcctNum", vcAcctNum);
	}

	public Integer getVcAcctNum()
	{
		return (Integer) this.readProperty("vcAcctNum");
	}

	public void setAccount(final Account account)
	{
		this.setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) this.readProperty("account");
	}

	public void setAccount1(final Account account1)
	{
		this.setToOneTarget("account1", account1, true);
	}

	public Account getAccount1()
	{
		return (Account) this.readProperty("account1");
	}

	public void setCommodity(final Commodity commodity)
	{
		this.setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) this.readProperty("commodity");
	}

	public void setPaymentMethod(final PaymentMethod paymentMethod)
	{
		this.setToOneTarget("paymentMethod", paymentMethod, true);
	}

	public PaymentMethod getPaymentMethod()
	{
		return (PaymentMethod) this.readProperty("paymentMethod");
	}

	public void addToVoucherPayments(final VoucherPayment obj)
	{
		this.addToManyTarget("voucherPayments", obj, true);
	}

	public void removeFromVoucherPayments(final VoucherPayment obj)
	{
		this.removeToManyTarget("voucherPayments", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<VoucherPayment> getVoucherPayments()
	{
		return (List<VoucherPayment>) this.readProperty("voucherPayments");
	}

	public void addToVouchers(final Voucher obj)
	{
		this.addToManyTarget("vouchers", obj, true);
	}

	public void removeFromVouchers(final Voucher obj)
	{
		this.removeToManyTarget("vouchers", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<Voucher> getVouchers()
	{
		return (List<Voucher>) this.readProperty("vouchers");
	}

	public void addToVouchers1(final Voucher obj)
	{
		this.addToManyTarget("vouchers1", obj, true);
	}

	public void removeFromVouchers1(final Voucher obj)
	{
		this.removeToManyTarget("vouchers1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<Voucher> getVouchers1()
	{
		return (List<Voucher>) this.readProperty("vouchers1");
	}

	public void addToVouchers2(final Voucher obj)
	{
		this.addToManyTarget("vouchers2", obj, true);
	}

	public void removeFromVouchers2(final Voucher obj)
	{
		this.removeToManyTarget("vouchers2", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<Voucher> getVouchers2()
	{
		return (List<Voucher>) this.readProperty("vouchers2");
	}

}
