package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Accisa;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;

/**
 * Class _AccisaGroup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AccisaGroup extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_REC_ID_PK_COLUMN = "fldchrRecId";

	public static final Property<Accisa> ACCISA = new Property<>("accisa");
	public static final Property<Commodity> COMMODITY = new Property<>("commodity");

	public void setAccisa(final Accisa accisa)
	{
		this.setToOneTarget("accisa", accisa, true);
	}

	public Accisa getAccisa()
	{
		return (Accisa) this.readProperty("accisa");
	}

	public void setCommodity(final Commodity commodity)
	{
		this.setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) this.readProperty("commodity");
	}

}
