package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.AcctSubTypeRef;

/**
 * Class _AccountType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AccountType extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ACCT_TYPE_CODE_PK_COLUMN = "acct_type_code";

	public static final Property<String> ACCT_TYPE_DESC = new Property<String>("acctTypeDesc");
	public static final Property<Short> ACCT_TYPE_NUM = new Property<Short>("acctTypeNum");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<List<Account>> ACCOUNTS = new Property<List<Account>>("accounts");
	public static final Property<List<AcctSubTypeRef>> ACCT_SUB_TYPE_REFS = new Property<List<AcctSubTypeRef>>("acctSubTypeRefs");

	public void setAcctTypeDesc(String acctTypeDesc)
	{
		writeProperty("acctTypeDesc", acctTypeDesc);
	}

	public String getAcctTypeDesc()
	{
		return (String) readProperty("acctTypeDesc");
	}

	public void setAcctTypeNum(Short acctTypeNum)
	{
		writeProperty("acctTypeNum", acctTypeNum);
	}

	public Short getAcctTypeNum()
	{
		return (Short) readProperty("acctTypeNum");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void addToAccounts(Account obj)
	{
		addToManyTarget("accounts", obj, true);
	}

	public void removeFromAccounts(Account obj)
	{
		removeToManyTarget("accounts", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<Account> getAccounts()
	{
		return (List<Account>) readProperty("accounts");
	}

	public void addToAcctSubTypeRefs(AcctSubTypeRef obj)
	{
		addToManyTarget("acctSubTypeRefs", obj, true);
	}

	public void removeFromAcctSubTypeRefs(AcctSubTypeRef obj)
	{
		removeToManyTarget("acctSubTypeRefs", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AcctSubTypeRef> getAcctSubTypeRefs()
	{
		return (List<AcctSubTypeRef>) readProperty("acctSubTypeRefs");
	}

}
