package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.AiEstActualVat;
import com.tc.app.exchangemonitor.model.cayenne.persistent.AllocationItemVat;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Country;
import com.tc.app.exchangemonitor.model.cayenne.persistent.VatType;

/**
 * Class _AcctVatNumber was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AcctVatNumber extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ACCT_VAT_NUM_PK_COLUMN = "acct_vat_num";

	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<String> VAT_ID = new Property<String>("vatId");
	public static final Property<Account> ACCOUNT = new Property<Account>("account");
	public static final Property<List<AiEstActualVat>> AI_EST_ACTUAL_VATS = new Property<List<AiEstActualVat>>("aiEstActualVats");
	public static final Property<List<AiEstActualVat>> AI_EST_ACTUAL_VATS1 = new Property<List<AiEstActualVat>>("aiEstActualVats1");
	public static final Property<List<AiEstActualVat>> AI_EST_ACTUAL_VATS2 = new Property<List<AiEstActualVat>>("aiEstActualVats2");
	public static final Property<List<AiEstActualVat>> AI_EST_ACTUAL_VATS3 = new Property<List<AiEstActualVat>>("aiEstActualVats3");
	public static final Property<List<AllocationItemVat>> ALLOCATION_ITEM_VATS = new Property<List<AllocationItemVat>>("allocationItemVats");
	public static final Property<List<AllocationItemVat>> ALLOCATION_ITEM_VATS1 = new Property<List<AllocationItemVat>>("allocationItemVats1");
	public static final Property<List<AllocationItemVat>> ALLOCATION_ITEM_VATS2 = new Property<List<AllocationItemVat>>("allocationItemVats2");
	public static final Property<List<AllocationItemVat>> ALLOCATION_ITEM_VATS3 = new Property<List<AllocationItemVat>>("allocationItemVats3");
	public static final Property<Country> COUNTRY = new Property<Country>("country");
	public static final Property<VatType> VAT_TYPE = new Property<VatType>("vatType");

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setVatId(String vatId)
	{
		writeProperty("vatId", vatId);
	}

	public String getVatId()
	{
		return (String) readProperty("vatId");
	}

	public void setAccount(Account account)
	{
		setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) readProperty("account");
	}

	public void addToAiEstActualVats(AiEstActualVat obj)
	{
		addToManyTarget("aiEstActualVats", obj, true);
	}

	public void removeFromAiEstActualVats(AiEstActualVat obj)
	{
		removeToManyTarget("aiEstActualVats", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AiEstActualVat> getAiEstActualVats()
	{
		return (List<AiEstActualVat>) readProperty("aiEstActualVats");
	}

	public void addToAiEstActualVats1(AiEstActualVat obj)
	{
		addToManyTarget("aiEstActualVats1", obj, true);
	}

	public void removeFromAiEstActualVats1(AiEstActualVat obj)
	{
		removeToManyTarget("aiEstActualVats1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AiEstActualVat> getAiEstActualVats1()
	{
		return (List<AiEstActualVat>) readProperty("aiEstActualVats1");
	}

	public void addToAiEstActualVats2(AiEstActualVat obj)
	{
		addToManyTarget("aiEstActualVats2", obj, true);
	}

	public void removeFromAiEstActualVats2(AiEstActualVat obj)
	{
		removeToManyTarget("aiEstActualVats2", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AiEstActualVat> getAiEstActualVats2()
	{
		return (List<AiEstActualVat>) readProperty("aiEstActualVats2");
	}

	public void addToAiEstActualVats3(AiEstActualVat obj)
	{
		addToManyTarget("aiEstActualVats3", obj, true);
	}

	public void removeFromAiEstActualVats3(AiEstActualVat obj)
	{
		removeToManyTarget("aiEstActualVats3", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AiEstActualVat> getAiEstActualVats3()
	{
		return (List<AiEstActualVat>) readProperty("aiEstActualVats3");
	}

	public void addToAllocationItemVats(AllocationItemVat obj)
	{
		addToManyTarget("allocationItemVats", obj, true);
	}

	public void removeFromAllocationItemVats(AllocationItemVat obj)
	{
		removeToManyTarget("allocationItemVats", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AllocationItemVat> getAllocationItemVats()
	{
		return (List<AllocationItemVat>) readProperty("allocationItemVats");
	}

	public void addToAllocationItemVats1(AllocationItemVat obj)
	{
		addToManyTarget("allocationItemVats1", obj, true);
	}

	public void removeFromAllocationItemVats1(AllocationItemVat obj)
	{
		removeToManyTarget("allocationItemVats1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AllocationItemVat> getAllocationItemVats1()
	{
		return (List<AllocationItemVat>) readProperty("allocationItemVats1");
	}

	public void addToAllocationItemVats2(AllocationItemVat obj)
	{
		addToManyTarget("allocationItemVats2", obj, true);
	}

	public void removeFromAllocationItemVats2(AllocationItemVat obj)
	{
		removeToManyTarget("allocationItemVats2", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AllocationItemVat> getAllocationItemVats2()
	{
		return (List<AllocationItemVat>) readProperty("allocationItemVats2");
	}

	public void addToAllocationItemVats3(AllocationItemVat obj)
	{
		addToManyTarget("allocationItemVats3", obj, true);
	}

	public void removeFromAllocationItemVats3(AllocationItemVat obj)
	{
		removeToManyTarget("allocationItemVats3", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AllocationItemVat> getAllocationItemVats3()
	{
		return (List<AllocationItemVat>) readProperty("allocationItemVats3");
	}

	public void setCountry(Country country)
	{
		setToOneTarget("country", country, true);
	}

	public Country getCountry()
	{
		return (Country) readProperty("country");
	}

	public void setVatType(VatType vatType)
	{
		setToOneTarget("vatType", vatType, true);
	}

	public VatType getVatType()
	{
		return (VatType) readProperty("vatType");
	}

}
