package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.AccountAlias;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CommktFutureAttr;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CommktOptionAttr;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CommktPhysicalAttr;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CommktSourceAlias;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CommodityAlias;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CommodityMarketAlias;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CommodityMarketSource;
import com.tc.app.exchangemonitor.model.cayenne.persistent.DeliveryTermAlias;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ExtRefdataMapping;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ExtTrandataMapping;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ExternalTradeSource;
import com.tc.app.exchangemonitor.model.cayenne.persistent.FeedRefdataMapping;
import com.tc.app.exchangemonitor.model.cayenne.persistent.LocationAlias;
import com.tc.app.exchangemonitor.model.cayenne.persistent.LocationTankInfoAlias;
import com.tc.app.exchangemonitor.model.cayenne.persistent.MarketAlias;
import com.tc.app.exchangemonitor.model.cayenne.persistent.MotAlias;
import com.tc.app.exchangemonitor.model.cayenne.persistent.OptionStrikeAlias;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PortfolioAlias;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TradingPeriodAlias;
import com.tc.app.exchangemonitor.model.cayenne.persistent.VoucherAlias;

/**
 * Class _AliasSource was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AliasSource extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ALIAS_SOURCE_CODE_PK_COLUMN = "alias_source_code";

	public static final Property<String> ALIAS_SOURCE_DESC = new Property<String>("aliasSourceDesc");
	public static final Property<String> ALIAS_SOURCE_TYPE = new Property<String>("aliasSourceType");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<List<AccountAlias>> ACCOUNT_ALIASS = new Property<List<AccountAlias>>("accountAliass");
	public static final Property<List<CommktFutureAttr>> COMMKT_FUTURE_ATTRS = new Property<List<CommktFutureAttr>>("commktFutureAttrs");
	public static final Property<List<CommktOptionAttr>> COMMKT_OPTION_ATTRS = new Property<List<CommktOptionAttr>>("commktOptionAttrs");
	public static final Property<List<CommktPhysicalAttr>> COMMKT_PHYSICAL_ATTRS = new Property<List<CommktPhysicalAttr>>("commktPhysicalAttrs");
	public static final Property<List<CommktSourceAlias>> COMMKT_SOURCE_ALIASS = new Property<List<CommktSourceAlias>>("commktSourceAliass");
	public static final Property<List<CommodityAlias>> COMMODITY_ALIASS = new Property<List<CommodityAlias>>("commodityAliass");
	public static final Property<List<CommodityMarketAlias>> COMMODITY_MARKET_ALIASS = new Property<List<CommodityMarketAlias>>("commodityMarketAliass");
	public static final Property<List<CommodityMarketSource>> COMMODITY_MARKET_SOURCES = new Property<List<CommodityMarketSource>>("commodityMarketSources");
	public static final Property<List<DeliveryTermAlias>> DELIVERY_TERM_ALIASS = new Property<List<DeliveryTermAlias>>("deliveryTermAliass");
	public static final Property<List<ExtRefdataMapping>> EXT_REFDATA_MAPPINGS = new Property<List<ExtRefdataMapping>>("extRefdataMappings");
	public static final Property<List<ExtTrandataMapping>> EXT_TRANDATA_MAPPINGS = new Property<List<ExtTrandataMapping>>("extTrandataMappings");
	public static final Property<List<ExternalTradeSource>> EXTERNAL_TRADE_SOURCES = new Property<List<ExternalTradeSource>>("externalTradeSources");
	public static final Property<List<FeedRefdataMapping>> FEED_REFDATA_MAPPINGS = new Property<List<FeedRefdataMapping>>("feedRefdataMappings");
	public static final Property<List<LocationAlias>> LOCATION_ALIASS = new Property<List<LocationAlias>>("locationAliass");
	public static final Property<List<LocationTankInfoAlias>> LOCATION_TANK_INFO_ALIASS = new Property<List<LocationTankInfoAlias>>("locationTankInfoAliass");
	public static final Property<List<MarketAlias>> MARKET_ALIASS = new Property<List<MarketAlias>>("marketAliass");
	public static final Property<List<MotAlias>> MOT_ALIASS = new Property<List<MotAlias>>("motAliass");
	public static final Property<List<OptionStrikeAlias>> OPTION_STRIKE_ALIASS = new Property<List<OptionStrikeAlias>>("optionStrikeAliass");
	public static final Property<List<PortfolioAlias>> PORTFOLIO_ALIASS = new Property<List<PortfolioAlias>>("portfolioAliass");
	public static final Property<List<TradingPeriodAlias>> TRADING_PERIOD_ALIASS = new Property<List<TradingPeriodAlias>>("tradingPeriodAliass");
	public static final Property<List<VoucherAlias>> VOUCHER_ALIASS = new Property<List<VoucherAlias>>("voucherAliass");

	public void setAliasSourceDesc(String aliasSourceDesc)
	{
		writeProperty("aliasSourceDesc", aliasSourceDesc);
	}

	public String getAliasSourceDesc()
	{
		return (String) readProperty("aliasSourceDesc");
	}

	public void setAliasSourceType(String aliasSourceType)
	{
		writeProperty("aliasSourceType", aliasSourceType);
	}

	public String getAliasSourceType()
	{
		return (String) readProperty("aliasSourceType");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void addToAccountAliass(AccountAlias obj)
	{
		addToManyTarget("accountAliass", obj, true);
	}

	public void removeFromAccountAliass(AccountAlias obj)
	{
		removeToManyTarget("accountAliass", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AccountAlias> getAccountAliass()
	{
		return (List<AccountAlias>) readProperty("accountAliass");
	}

	public void addToCommktFutureAttrs(CommktFutureAttr obj)
	{
		addToManyTarget("commktFutureAttrs", obj, true);
	}

	public void removeFromCommktFutureAttrs(CommktFutureAttr obj)
	{
		removeToManyTarget("commktFutureAttrs", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<CommktFutureAttr> getCommktFutureAttrs()
	{
		return (List<CommktFutureAttr>) readProperty("commktFutureAttrs");
	}

	public void addToCommktOptionAttrs(CommktOptionAttr obj)
	{
		addToManyTarget("commktOptionAttrs", obj, true);
	}

	public void removeFromCommktOptionAttrs(CommktOptionAttr obj)
	{
		removeToManyTarget("commktOptionAttrs", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<CommktOptionAttr> getCommktOptionAttrs()
	{
		return (List<CommktOptionAttr>) readProperty("commktOptionAttrs");
	}

	public void addToCommktPhysicalAttrs(CommktPhysicalAttr obj)
	{
		addToManyTarget("commktPhysicalAttrs", obj, true);
	}

	public void removeFromCommktPhysicalAttrs(CommktPhysicalAttr obj)
	{
		removeToManyTarget("commktPhysicalAttrs", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<CommktPhysicalAttr> getCommktPhysicalAttrs()
	{
		return (List<CommktPhysicalAttr>) readProperty("commktPhysicalAttrs");
	}

	public void addToCommktSourceAliass(CommktSourceAlias obj)
	{
		addToManyTarget("commktSourceAliass", obj, true);
	}

	public void removeFromCommktSourceAliass(CommktSourceAlias obj)
	{
		removeToManyTarget("commktSourceAliass", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<CommktSourceAlias> getCommktSourceAliass()
	{
		return (List<CommktSourceAlias>) readProperty("commktSourceAliass");
	}

	public void addToCommodityAliass(CommodityAlias obj)
	{
		addToManyTarget("commodityAliass", obj, true);
	}

	public void removeFromCommodityAliass(CommodityAlias obj)
	{
		removeToManyTarget("commodityAliass", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<CommodityAlias> getCommodityAliass()
	{
		return (List<CommodityAlias>) readProperty("commodityAliass");
	}

	public void addToCommodityMarketAliass(CommodityMarketAlias obj)
	{
		addToManyTarget("commodityMarketAliass", obj, true);
	}

	public void removeFromCommodityMarketAliass(CommodityMarketAlias obj)
	{
		removeToManyTarget("commodityMarketAliass", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<CommodityMarketAlias> getCommodityMarketAliass()
	{
		return (List<CommodityMarketAlias>) readProperty("commodityMarketAliass");
	}

	public void addToCommodityMarketSources(CommodityMarketSource obj)
	{
		addToManyTarget("commodityMarketSources", obj, true);
	}

	public void removeFromCommodityMarketSources(CommodityMarketSource obj)
	{
		removeToManyTarget("commodityMarketSources", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<CommodityMarketSource> getCommodityMarketSources()
	{
		return (List<CommodityMarketSource>) readProperty("commodityMarketSources");
	}

	public void addToDeliveryTermAliass(DeliveryTermAlias obj)
	{
		addToManyTarget("deliveryTermAliass", obj, true);
	}

	public void removeFromDeliveryTermAliass(DeliveryTermAlias obj)
	{
		removeToManyTarget("deliveryTermAliass", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<DeliveryTermAlias> getDeliveryTermAliass()
	{
		return (List<DeliveryTermAlias>) readProperty("deliveryTermAliass");
	}

	public void addToExtRefdataMappings(ExtRefdataMapping obj)
	{
		addToManyTarget("extRefdataMappings", obj, true);
	}

	public void removeFromExtRefdataMappings(ExtRefdataMapping obj)
	{
		removeToManyTarget("extRefdataMappings", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ExtRefdataMapping> getExtRefdataMappings()
	{
		return (List<ExtRefdataMapping>) readProperty("extRefdataMappings");
	}

	public void addToExtTrandataMappings(ExtTrandataMapping obj)
	{
		addToManyTarget("extTrandataMappings", obj, true);
	}

	public void removeFromExtTrandataMappings(ExtTrandataMapping obj)
	{
		removeToManyTarget("extTrandataMappings", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ExtTrandataMapping> getExtTrandataMappings()
	{
		return (List<ExtTrandataMapping>) readProperty("extTrandataMappings");
	}

	public void addToExternalTradeSources(ExternalTradeSource obj)
	{
		addToManyTarget("externalTradeSources", obj, true);
	}

	public void removeFromExternalTradeSources(ExternalTradeSource obj)
	{
		removeToManyTarget("externalTradeSources", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ExternalTradeSource> getExternalTradeSources()
	{
		return (List<ExternalTradeSource>) readProperty("externalTradeSources");
	}

	public void addToFeedRefdataMappings(FeedRefdataMapping obj)
	{
		addToManyTarget("feedRefdataMappings", obj, true);
	}

	public void removeFromFeedRefdataMappings(FeedRefdataMapping obj)
	{
		removeToManyTarget("feedRefdataMappings", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FeedRefdataMapping> getFeedRefdataMappings()
	{
		return (List<FeedRefdataMapping>) readProperty("feedRefdataMappings");
	}

	public void addToLocationAliass(LocationAlias obj)
	{
		addToManyTarget("locationAliass", obj, true);
	}

	public void removeFromLocationAliass(LocationAlias obj)
	{
		removeToManyTarget("locationAliass", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<LocationAlias> getLocationAliass()
	{
		return (List<LocationAlias>) readProperty("locationAliass");
	}

	public void addToLocationTankInfoAliass(LocationTankInfoAlias obj)
	{
		addToManyTarget("locationTankInfoAliass", obj, true);
	}

	public void removeFromLocationTankInfoAliass(LocationTankInfoAlias obj)
	{
		removeToManyTarget("locationTankInfoAliass", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<LocationTankInfoAlias> getLocationTankInfoAliass()
	{
		return (List<LocationTankInfoAlias>) readProperty("locationTankInfoAliass");
	}

	public void addToMarketAliass(MarketAlias obj)
	{
		addToManyTarget("marketAliass", obj, true);
	}

	public void removeFromMarketAliass(MarketAlias obj)
	{
		removeToManyTarget("marketAliass", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<MarketAlias> getMarketAliass()
	{
		return (List<MarketAlias>) readProperty("marketAliass");
	}

	public void addToMotAliass(MotAlias obj)
	{
		addToManyTarget("motAliass", obj, true);
	}

	public void removeFromMotAliass(MotAlias obj)
	{
		removeToManyTarget("motAliass", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<MotAlias> getMotAliass()
	{
		return (List<MotAlias>) readProperty("motAliass");
	}

	public void addToOptionStrikeAliass(OptionStrikeAlias obj)
	{
		addToManyTarget("optionStrikeAliass", obj, true);
	}

	public void removeFromOptionStrikeAliass(OptionStrikeAlias obj)
	{
		removeToManyTarget("optionStrikeAliass", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<OptionStrikeAlias> getOptionStrikeAliass()
	{
		return (List<OptionStrikeAlias>) readProperty("optionStrikeAliass");
	}

	public void addToPortfolioAliass(PortfolioAlias obj)
	{
		addToManyTarget("portfolioAliass", obj, true);
	}

	public void removeFromPortfolioAliass(PortfolioAlias obj)
	{
		removeToManyTarget("portfolioAliass", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<PortfolioAlias> getPortfolioAliass()
	{
		return (List<PortfolioAlias>) readProperty("portfolioAliass");
	}

	public void addToTradingPeriodAliass(TradingPeriodAlias obj)
	{
		addToManyTarget("tradingPeriodAliass", obj, true);
	}

	public void removeFromTradingPeriodAliass(TradingPeriodAlias obj)
	{
		removeToManyTarget("tradingPeriodAliass", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<TradingPeriodAlias> getTradingPeriodAliass()
	{
		return (List<TradingPeriodAlias>) readProperty("tradingPeriodAliass");
	}

	public void addToVoucherAliass(VoucherAlias obj)
	{
		addToManyTarget("voucherAliass", obj, true);
	}

	public void removeFromVoucherAliass(VoucherAlias obj)
	{
		removeToManyTarget("voucherAliass", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<VoucherAlias> getVoucherAliass()
	{
		return (List<VoucherAlias>) readProperty("voucherAliass");
	}

}
