package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CreditTerm;
import com.tc.app.exchangemonitor.model.cayenne.persistent.DeliveryTerm;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsUser;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Location;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PaymentTerm;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PlOpsCargoDetails;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ScenarioItem;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TiBulkIgnore;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _AllocationItem was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AllocationItem extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ALLOC_ITEM_NUM_PK_COLUMN = "alloc_item_num";
	public static final String ALLOC_NUM_PK_COLUMN = "alloc_num";

	public static final Property<String> ACCT_REF_NUM = new Property<>("acctRefNum");
	public static final Property<Double> ACTUAL_GROSS_QTY = new Property<>("actualGrossQty");
	public static final Property<String> ALLOC_ITEM_CONFIRM = new Property<>("allocItemConfirm");
	public static final Property<String> ALLOC_ITEM_SHORT_CMNT = new Property<>("allocItemShortCmnt");
	public static final Property<String> ALLOC_ITEM_STATUS = new Property<>("allocItemStatus");
	public static final Property<String> ALLOC_ITEM_TYPE = new Property<>("allocItemType");
	public static final Property<String> ALLOC_ITEM_VERIFY = new Property<>("allocItemVerify");
	public static final Property<Short> AR_ALLOC_ITEM_NUM = new Property<>("arAllocItemNum");
	public static final Property<Integer> AR_ALLOC_NUM = new Property<>("arAllocNum");
	public static final Property<String> AUTO_RECEIPT_ACTUAL_IND = new Property<>("autoReceiptActualInd");
	public static final Property<String> AUTO_RECEIPT_IND = new Property<>("autoReceiptInd");
	public static final Property<Integer> AUTO_SAMPLING_COMP_NUM = new Property<>("autoSamplingCompNum");
	public static final Property<String> AUTO_SAMPLING_IND = new Property<>("autoSamplingInd");
	public static final Property<Integer> CMNT_NUM = new Property<>("cmntNum");
	public static final Property<Date> CONFIRMATION_DATE = new Property<>("confirmationDate");
	public static final Property<String> CR_CLEAR_IND = new Property<>("crClearInd");
	public static final Property<Date> ESTIMATE_EVENT_DATE = new Property<>("estimateEventDate");
	public static final Property<String> FULLY_ACTUALIZED = new Property<>("fullyActualized");
	public static final Property<String> IMP_REC_IND = new Property<>("impRecInd");
	public static final Property<Integer> IMP_REC_REASON_OID = new Property<>("impRecReasonOid");
	public static final Property<Date> INSPECTION_DATE = new Property<>("inspectionDate");
	public static final Property<Short> INSPECTOR_PERCENT = new Property<>("inspectorPercent");
	public static final Property<Integer> INV_NUM = new Property<>("invNum");
	public static final Property<Short> ITEM_NUM = new Property<>("itemNum");
	public static final Property<Integer> LC_NUM = new Property<>("lcNum");
	public static final Property<String> LOAD_PORT_LOC_CODE = new Property<>("loadPortLocCode");
	public static final Property<Short> MAX_AI_EST_ACTUAL_NUM = new Property<>("maxAiEstActualNum");
	public static final Property<Short> NET_NOM_NUM = new Property<>("netNomNum");
	public static final Property<Date> NOMIN_DATE_FROM = new Property<>("nominDateFrom");
	public static final Property<Date> NOMIN_DATE_TO = new Property<>("nominDateTo");
	public static final Property<Double> NOMIN_QTY_MAX = new Property<>("nominQtyMax");
	public static final Property<Double> NOMIN_QTY_MIN = new Property<>("nominQtyMin");
	public static final Property<Short> ORDER_NUM = new Property<>("orderNum");
	public static final Property<Short> PAY_DAYS = new Property<>("payDays");
	public static final Property<String> PURCHASING_GROUP = new Property<>("purchasingGroup");
	public static final Property<Integer> RECAP_ITEM_NUM = new Property<>("recapItemNum");
	public static final Property<Date> REPORTING_DATE = new Property<>("reportingDate");
	public static final Property<String> SAP_DELIVERY_LINE_ITEM_NUM = new Property<>("sapDeliveryLineItemNum");
	public static final Property<String> SAP_DELIVERY_NUM = new Property<>("sapDeliveryNum");
	public static final Property<Double> SCH_QTY = new Property<>("schQty");
	public static final Property<String> SCH_QTY_PERIODICITY = new Property<>("schQtyPeriodicity");
	public static final Property<Double> SECONDARY_ACTUAL_QTY = new Property<>("secondaryActualQty");
	public static final Property<Integer> SHIP_AGENT_COMP_NUM = new Property<>("shipAgentCompNum");
	public static final Property<Integer> SHIP_BROKER_COMP_NUM = new Property<>("shipBrokerCompNum");
	public static final Property<Short> SUB_ALLOC_NUM = new Property<>("subAllocNum");
	public static final Property<Date> TITLE_TRAN_DATE = new Property<>("titleTranDate");
	public static final Property<Integer> TRADE_NUM = new Property<>("tradeNum");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<BigDecimal> TRANSFER_PRICE = new Property<>("transferPrice");
	public static final Property<String> TRANSFER_PRICE_CURR_CODE = new Property<>("transferPriceCurrCode");
	public static final Property<Double> TRANSFER_PRICE_CURRENCY_RATE = new Property<>("transferPriceCurrencyRate");
	public static final Property<String> TRANSFER_PRICE_UOM_CODE = new Property<>("transferPriceUomCode");
	public static final Property<Boolean> VAT_IND = new Property<>("vatInd");
	public static final Property<Account> ACCOUNT = new Property<>("account");
	public static final Property<Account> ACCOUNT1 = new Property<>("account1");
	public static final Property<Account> ACCOUNT2 = new Property<>("account2");
	public static final Property<Commodity> COMMODITY = new Property<>("commodity");
	public static final Property<Commodity> COMMODITY1 = new Property<>("commodity1");
	public static final Property<CreditTerm> CREDIT_TERM = new Property<>("creditTerm");
	public static final Property<DeliveryTerm> DELIVERY_TERM = new Property<>("deliveryTerm");
	public static final Property<IctsUser> ICTS_USER = new Property<>("ictsUser");
	public static final Property<Location> LOCATION = new Property<>("location");
	public static final Property<Location> LOCATION1 = new Property<>("location1");
	public static final Property<Location> LOCATION2 = new Property<>("location2");
	public static final Property<Location> LOCATION3 = new Property<>("location3");
	public static final Property<PaymentTerm> PAYMENT_TERM = new Property<>("paymentTerm");
	public static final Property<List<PlOpsCargoDetails>> PL_OPS_CARGO_DETAILSS = new Property<>("plOpsCargoDetailss");
	public static final Property<List<PlOpsCargoDetails>> PL_OPS_CARGO_DETAILSS1 = new Property<>("plOpsCargoDetailss1");
	public static final Property<List<ScenarioItem>> SCENARIO_ITEMS = new Property<>("scenarioItems");
	public static final Property<List<ScenarioItem>> SCENARIO_ITEMS1 = new Property<>("scenarioItems1");
	public static final Property<List<TiBulkIgnore>> TI_BULK_IGNORES = new Property<>("tiBulkIgnores");
	public static final Property<List<TiBulkIgnore>> TI_BULK_IGNORES1 = new Property<>("tiBulkIgnores1");
	public static final Property<Uom> UOM = new Property<>("uom");
	public static final Property<Uom> UOM1 = new Property<>("uom1");
	public static final Property<Uom> UOM2 = new Property<>("uom2");
	public static final Property<Uom> UOM3 = new Property<>("uom3");
	public static final Property<Uom> UOM4 = new Property<>("uom4");

	public void setAcctRefNum(final String acctRefNum)
	{
		this.writeProperty("acctRefNum", acctRefNum);
	}

	public String getAcctRefNum()
	{
		return (String) this.readProperty("acctRefNum");
	}

	public void setActualGrossQty(final Double actualGrossQty)
	{
		this.writeProperty("actualGrossQty", actualGrossQty);
	}

	public Double getActualGrossQty()
	{
		return (Double) this.readProperty("actualGrossQty");
	}

	public void setAllocItemConfirm(final String allocItemConfirm)
	{
		this.writeProperty("allocItemConfirm", allocItemConfirm);
	}

	public String getAllocItemConfirm()
	{
		return (String) this.readProperty("allocItemConfirm");
	}

	public void setAllocItemShortCmnt(final String allocItemShortCmnt)
	{
		this.writeProperty("allocItemShortCmnt", allocItemShortCmnt);
	}

	public String getAllocItemShortCmnt()
	{
		return (String) this.readProperty("allocItemShortCmnt");
	}

	public void setAllocItemStatus(final String allocItemStatus)
	{
		this.writeProperty("allocItemStatus", allocItemStatus);
	}

	public String getAllocItemStatus()
	{
		return (String) this.readProperty("allocItemStatus");
	}

	public void setAllocItemType(final String allocItemType)
	{
		this.writeProperty("allocItemType", allocItemType);
	}

	public String getAllocItemType()
	{
		return (String) this.readProperty("allocItemType");
	}

	public void setAllocItemVerify(final String allocItemVerify)
	{
		this.writeProperty("allocItemVerify", allocItemVerify);
	}

	public String getAllocItemVerify()
	{
		return (String) this.readProperty("allocItemVerify");
	}

	public void setArAllocItemNum(final Short arAllocItemNum)
	{
		this.writeProperty("arAllocItemNum", arAllocItemNum);
	}

	public Short getArAllocItemNum()
	{
		return (Short) this.readProperty("arAllocItemNum");
	}

	public void setArAllocNum(final Integer arAllocNum)
	{
		this.writeProperty("arAllocNum", arAllocNum);
	}

	public Integer getArAllocNum()
	{
		return (Integer) this.readProperty("arAllocNum");
	}

	public void setAutoReceiptActualInd(final String autoReceiptActualInd)
	{
		this.writeProperty("autoReceiptActualInd", autoReceiptActualInd);
	}

	public String getAutoReceiptActualInd()
	{
		return (String) this.readProperty("autoReceiptActualInd");
	}

	public void setAutoReceiptInd(final String autoReceiptInd)
	{
		this.writeProperty("autoReceiptInd", autoReceiptInd);
	}

	public String getAutoReceiptInd()
	{
		return (String) this.readProperty("autoReceiptInd");
	}

	public void setAutoSamplingCompNum(final Integer autoSamplingCompNum)
	{
		this.writeProperty("autoSamplingCompNum", autoSamplingCompNum);
	}

	public Integer getAutoSamplingCompNum()
	{
		return (Integer) this.readProperty("autoSamplingCompNum");
	}

	public void setAutoSamplingInd(final String autoSamplingInd)
	{
		this.writeProperty("autoSamplingInd", autoSamplingInd);
	}

	public String getAutoSamplingInd()
	{
		return (String) this.readProperty("autoSamplingInd");
	}

	public void setCmntNum(final Integer cmntNum)
	{
		this.writeProperty("cmntNum", cmntNum);
	}

	public Integer getCmntNum()
	{
		return (Integer) this.readProperty("cmntNum");
	}

	public void setConfirmationDate(final Date confirmationDate)
	{
		this.writeProperty("confirmationDate", confirmationDate);
	}

	public Date getConfirmationDate()
	{
		return (Date) this.readProperty("confirmationDate");
	}

	public void setCrClearInd(final String crClearInd)
	{
		this.writeProperty("crClearInd", crClearInd);
	}

	public String getCrClearInd()
	{
		return (String) this.readProperty("crClearInd");
	}

	public void setEstimateEventDate(final Date estimateEventDate)
	{
		this.writeProperty("estimateEventDate", estimateEventDate);
	}

	public Date getEstimateEventDate()
	{
		return (Date) this.readProperty("estimateEventDate");
	}

	public void setFullyActualized(final String fullyActualized)
	{
		this.writeProperty("fullyActualized", fullyActualized);
	}

	public String getFullyActualized()
	{
		return (String) this.readProperty("fullyActualized");
	}

	public void setImpRecInd(final String impRecInd)
	{
		this.writeProperty("impRecInd", impRecInd);
	}

	public String getImpRecInd()
	{
		return (String) this.readProperty("impRecInd");
	}

	public void setImpRecReasonOid(final Integer impRecReasonOid)
	{
		this.writeProperty("impRecReasonOid", impRecReasonOid);
	}

	public Integer getImpRecReasonOid()
	{
		return (Integer) this.readProperty("impRecReasonOid");
	}

	public void setInspectionDate(final Date inspectionDate)
	{
		this.writeProperty("inspectionDate", inspectionDate);
	}

	public Date getInspectionDate()
	{
		return (Date) this.readProperty("inspectionDate");
	}

	public void setInspectorPercent(final Short inspectorPercent)
	{
		this.writeProperty("inspectorPercent", inspectorPercent);
	}

	public Short getInspectorPercent()
	{
		return (Short) this.readProperty("inspectorPercent");
	}

	public void setInvNum(final Integer invNum)
	{
		this.writeProperty("invNum", invNum);
	}

	public Integer getInvNum()
	{
		return (Integer) this.readProperty("invNum");
	}

	public void setItemNum(final Short itemNum)
	{
		this.writeProperty("itemNum", itemNum);
	}

	public Short getItemNum()
	{
		return (Short) this.readProperty("itemNum");
	}

	public void setLcNum(final Integer lcNum)
	{
		this.writeProperty("lcNum", lcNum);
	}

	public Integer getLcNum()
	{
		return (Integer) this.readProperty("lcNum");
	}

	public void setLoadPortLocCode(final String loadPortLocCode)
	{
		this.writeProperty("loadPortLocCode", loadPortLocCode);
	}

	public String getLoadPortLocCode()
	{
		return (String) this.readProperty("loadPortLocCode");
	}

	public void setMaxAiEstActualNum(final Short maxAiEstActualNum)
	{
		this.writeProperty("maxAiEstActualNum", maxAiEstActualNum);
	}

	public Short getMaxAiEstActualNum()
	{
		return (Short) this.readProperty("maxAiEstActualNum");
	}

	public void setNetNomNum(final Short netNomNum)
	{
		this.writeProperty("netNomNum", netNomNum);
	}

	public Short getNetNomNum()
	{
		return (Short) this.readProperty("netNomNum");
	}

	public void setNominDateFrom(final Date nominDateFrom)
	{
		this.writeProperty("nominDateFrom", nominDateFrom);
	}

	public Date getNominDateFrom()
	{
		return (Date) this.readProperty("nominDateFrom");
	}

	public void setNominDateTo(final Date nominDateTo)
	{
		this.writeProperty("nominDateTo", nominDateTo);
	}

	public Date getNominDateTo()
	{
		return (Date) this.readProperty("nominDateTo");
	}

	public void setNominQtyMax(final Double nominQtyMax)
	{
		this.writeProperty("nominQtyMax", nominQtyMax);
	}

	public Double getNominQtyMax()
	{
		return (Double) this.readProperty("nominQtyMax");
	}

	public void setNominQtyMin(final Double nominQtyMin)
	{
		this.writeProperty("nominQtyMin", nominQtyMin);
	}

	public Double getNominQtyMin()
	{
		return (Double) this.readProperty("nominQtyMin");
	}

	public void setOrderNum(final Short orderNum)
	{
		this.writeProperty("orderNum", orderNum);
	}

	public Short getOrderNum()
	{
		return (Short) this.readProperty("orderNum");
	}

	public void setPayDays(final Short payDays)
	{
		this.writeProperty("payDays", payDays);
	}

	public Short getPayDays()
	{
		return (Short) this.readProperty("payDays");
	}

	public void setPurchasingGroup(final String purchasingGroup)
	{
		this.writeProperty("purchasingGroup", purchasingGroup);
	}

	public String getPurchasingGroup()
	{
		return (String) this.readProperty("purchasingGroup");
	}

	public void setRecapItemNum(final Integer recapItemNum)
	{
		this.writeProperty("recapItemNum", recapItemNum);
	}

	public Integer getRecapItemNum()
	{
		return (Integer) this.readProperty("recapItemNum");
	}

	public void setReportingDate(final Date reportingDate)
	{
		this.writeProperty("reportingDate", reportingDate);
	}

	public Date getReportingDate()
	{
		return (Date) this.readProperty("reportingDate");
	}

	public void setSapDeliveryLineItemNum(final String sapDeliveryLineItemNum)
	{
		this.writeProperty("sapDeliveryLineItemNum", sapDeliveryLineItemNum);
	}

	public String getSapDeliveryLineItemNum()
	{
		return (String) this.readProperty("sapDeliveryLineItemNum");
	}

	public void setSapDeliveryNum(final String sapDeliveryNum)
	{
		this.writeProperty("sapDeliveryNum", sapDeliveryNum);
	}

	public String getSapDeliveryNum()
	{
		return (String) this.readProperty("sapDeliveryNum");
	}

	public void setSchQty(final Double schQty)
	{
		this.writeProperty("schQty", schQty);
	}

	public Double getSchQty()
	{
		return (Double) this.readProperty("schQty");
	}

	public void setSchQtyPeriodicity(final String schQtyPeriodicity)
	{
		this.writeProperty("schQtyPeriodicity", schQtyPeriodicity);
	}

	public String getSchQtyPeriodicity()
	{
		return (String) this.readProperty("schQtyPeriodicity");
	}

	public void setSecondaryActualQty(final Double secondaryActualQty)
	{
		this.writeProperty("secondaryActualQty", secondaryActualQty);
	}

	public Double getSecondaryActualQty()
	{
		return (Double) this.readProperty("secondaryActualQty");
	}

	public void setShipAgentCompNum(final Integer shipAgentCompNum)
	{
		this.writeProperty("shipAgentCompNum", shipAgentCompNum);
	}

	public Integer getShipAgentCompNum()
	{
		return (Integer) this.readProperty("shipAgentCompNum");
	}

	public void setShipBrokerCompNum(final Integer shipBrokerCompNum)
	{
		this.writeProperty("shipBrokerCompNum", shipBrokerCompNum);
	}

	public Integer getShipBrokerCompNum()
	{
		return (Integer) this.readProperty("shipBrokerCompNum");
	}

	public void setSubAllocNum(final Short subAllocNum)
	{
		this.writeProperty("subAllocNum", subAllocNum);
	}

	public Short getSubAllocNum()
	{
		return (Short) this.readProperty("subAllocNum");
	}

	public void setTitleTranDate(final Date titleTranDate)
	{
		this.writeProperty("titleTranDate", titleTranDate);
	}

	public Date getTitleTranDate()
	{
		return (Date) this.readProperty("titleTranDate");
	}

	public void setTradeNum(final Integer tradeNum)
	{
		this.writeProperty("tradeNum", tradeNum);
	}

	public Integer getTradeNum()
	{
		return (Integer) this.readProperty("tradeNum");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setTransferPrice(final BigDecimal transferPrice)
	{
		this.writeProperty("transferPrice", transferPrice);
	}

	public BigDecimal getTransferPrice()
	{
		return (BigDecimal) this.readProperty("transferPrice");
	}

	public void setTransferPriceCurrCode(final String transferPriceCurrCode)
	{
		this.writeProperty("transferPriceCurrCode", transferPriceCurrCode);
	}

	public String getTransferPriceCurrCode()
	{
		return (String) this.readProperty("transferPriceCurrCode");
	}

	public void setTransferPriceCurrencyRate(final Double transferPriceCurrencyRate)
	{
		this.writeProperty("transferPriceCurrencyRate", transferPriceCurrencyRate);
	}

	public Double getTransferPriceCurrencyRate()
	{
		return (Double) this.readProperty("transferPriceCurrencyRate");
	}

	public void setTransferPriceUomCode(final String transferPriceUomCode)
	{
		this.writeProperty("transferPriceUomCode", transferPriceUomCode);
	}

	public String getTransferPriceUomCode()
	{
		return (String) this.readProperty("transferPriceUomCode");
	}

	public void setVatInd(final Boolean vatInd)
	{
		this.writeProperty("vatInd", vatInd);
	}

	public Boolean getVatInd()
	{
		return (Boolean) this.readProperty("vatInd");
	}

	public void setAccount(final Account account)
	{
		this.setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) this.readProperty("account");
	}

	public void setAccount1(final Account account1)
	{
		this.setToOneTarget("account1", account1, true);
	}

	public Account getAccount1()
	{
		return (Account) this.readProperty("account1");
	}

	public void setAccount2(final Account account2)
	{
		this.setToOneTarget("account2", account2, true);
	}

	public Account getAccount2()
	{
		return (Account) this.readProperty("account2");
	}

	public void setCommodity(final Commodity commodity)
	{
		this.setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) this.readProperty("commodity");
	}

	public void setCommodity1(final Commodity commodity1)
	{
		this.setToOneTarget("commodity1", commodity1, true);
	}

	public Commodity getCommodity1()
	{
		return (Commodity) this.readProperty("commodity1");
	}

	public void setCreditTerm(final CreditTerm creditTerm)
	{
		this.setToOneTarget("creditTerm", creditTerm, true);
	}

	public CreditTerm getCreditTerm()
	{
		return (CreditTerm) this.readProperty("creditTerm");
	}

	public void setDeliveryTerm(final DeliveryTerm deliveryTerm)
	{
		this.setToOneTarget("deliveryTerm", deliveryTerm, true);
	}

	public DeliveryTerm getDeliveryTerm()
	{
		return (DeliveryTerm) this.readProperty("deliveryTerm");
	}

	public void setIctsUser(final IctsUser ictsUser)
	{
		this.setToOneTarget("ictsUser", ictsUser, true);
	}

	public IctsUser getIctsUser()
	{
		return (IctsUser) this.readProperty("ictsUser");
	}

	public void setLocation(final Location location)
	{
		this.setToOneTarget("location", location, true);
	}

	public Location getLocation()
	{
		return (Location) this.readProperty("location");
	}

	public void setLocation1(final Location location1)
	{
		this.setToOneTarget("location1", location1, true);
	}

	public Location getLocation1()
	{
		return (Location) this.readProperty("location1");
	}

	public void setLocation2(final Location location2)
	{
		this.setToOneTarget("location2", location2, true);
	}

	public Location getLocation2()
	{
		return (Location) this.readProperty("location2");
	}

	public void setLocation3(final Location location3)
	{
		this.setToOneTarget("location3", location3, true);
	}

	public Location getLocation3()
	{
		return (Location) this.readProperty("location3");
	}

	public void setPaymentTerm(final PaymentTerm paymentTerm)
	{
		this.setToOneTarget("paymentTerm", paymentTerm, true);
	}

	public PaymentTerm getPaymentTerm()
	{
		return (PaymentTerm) this.readProperty("paymentTerm");
	}

	public void addToPlOpsCargoDetailss(final PlOpsCargoDetails obj)
	{
		this.addToManyTarget("plOpsCargoDetailss", obj, true);
	}

	public void removeFromPlOpsCargoDetailss(final PlOpsCargoDetails obj)
	{
		this.removeToManyTarget("plOpsCargoDetailss", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<PlOpsCargoDetails> getPlOpsCargoDetailss()
	{
		return (List<PlOpsCargoDetails>) this.readProperty("plOpsCargoDetailss");
	}

	public void addToPlOpsCargoDetailss1(final PlOpsCargoDetails obj)
	{
		this.addToManyTarget("plOpsCargoDetailss1", obj, true);
	}

	public void removeFromPlOpsCargoDetailss1(final PlOpsCargoDetails obj)
	{
		this.removeToManyTarget("plOpsCargoDetailss1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<PlOpsCargoDetails> getPlOpsCargoDetailss1()
	{
		return (List<PlOpsCargoDetails>) this.readProperty("plOpsCargoDetailss1");
	}

	public void addToScenarioItems(final ScenarioItem obj)
	{
		this.addToManyTarget("scenarioItems", obj, true);
	}

	public void removeFromScenarioItems(final ScenarioItem obj)
	{
		this.removeToManyTarget("scenarioItems", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ScenarioItem> getScenarioItems()
	{
		return (List<ScenarioItem>) this.readProperty("scenarioItems");
	}

	public void addToScenarioItems1(final ScenarioItem obj)
	{
		this.addToManyTarget("scenarioItems1", obj, true);
	}

	public void removeFromScenarioItems1(final ScenarioItem obj)
	{
		this.removeToManyTarget("scenarioItems1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ScenarioItem> getScenarioItems1()
	{
		return (List<ScenarioItem>) this.readProperty("scenarioItems1");
	}

	public void addToTiBulkIgnores(final TiBulkIgnore obj)
	{
		this.addToManyTarget("tiBulkIgnores", obj, true);
	}

	public void removeFromTiBulkIgnores(final TiBulkIgnore obj)
	{
		this.removeToManyTarget("tiBulkIgnores", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<TiBulkIgnore> getTiBulkIgnores()
	{
		return (List<TiBulkIgnore>) this.readProperty("tiBulkIgnores");
	}

	public void addToTiBulkIgnores1(final TiBulkIgnore obj)
	{
		this.addToManyTarget("tiBulkIgnores1", obj, true);
	}

	public void removeFromTiBulkIgnores1(final TiBulkIgnore obj)
	{
		this.removeToManyTarget("tiBulkIgnores1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<TiBulkIgnore> getTiBulkIgnores1()
	{
		return (List<TiBulkIgnore>) this.readProperty("tiBulkIgnores1");
	}

	public void setUom(final Uom uom)
	{
		this.setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) this.readProperty("uom");
	}

	public void setUom1(final Uom uom1)
	{
		this.setToOneTarget("uom1", uom1, true);
	}

	public Uom getUom1()
	{
		return (Uom) this.readProperty("uom1");
	}

	public void setUom2(final Uom uom2)
	{
		this.setToOneTarget("uom2", uom2, true);
	}

	public Uom getUom2()
	{
		return (Uom) this.readProperty("uom2");
	}

	public void setUom3(final Uom uom3)
	{
		this.setToOneTarget("uom3", uom3, true);
	}

	public Uom getUom3()
	{
		return (Uom) this.readProperty("uom3");
	}

	public void setUom4(final Uom uom4)
	{
		this.setToOneTarget("uom4", uom4, true);
	}

	public Uom getUom4()
	{
		return (Uom) this.readProperty("uom4");
	}

}
