package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.ApplicantFunction;

/**
 * Class _ApplicantFunctionCounter was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ApplicantFunctionCounter extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_APPLICANT_FUNC_CODE_PK_COLUMN = "fldchrApplicantFuncCode";
	public static final String FLDCHR_APPLICANT_FUNC_REF_YEAR_PK_COLUMN = "fldchrApplicantFuncRefYear";

	public static final Property<String> FLDCHR_APPLICANT_FUNC_KEY = new Property<String>("fldchrApplicantFuncKey");
	public static final Property<Integer> FLDINT_APPLICANT_FUNC_COUNTER = new Property<Integer>("fldintApplicantFuncCounter");
	public static final Property<ApplicantFunction> APPLICANT_FUNCTION = new Property<ApplicantFunction>("applicantFunction");

	public void setFldchrApplicantFuncKey(String fldchrApplicantFuncKey)
	{
		writeProperty("fldchrApplicantFuncKey", fldchrApplicantFuncKey);
	}

	public String getFldchrApplicantFuncKey()
	{
		return (String) readProperty("fldchrApplicantFuncKey");
	}

	public void setFldintApplicantFuncCounter(Integer fldintApplicantFuncCounter)
	{
		writeProperty("fldintApplicantFuncCounter", fldintApplicantFuncCounter);
	}

	public Integer getFldintApplicantFuncCounter()
	{
		return (Integer) readProperty("fldintApplicantFuncCounter");
	}

	public void setApplicantFunction(ApplicantFunction applicantFunction)
	{
		setToOneTarget("applicantFunction", applicantFunction, true);
	}

	public ApplicantFunction getApplicantFunction()
	{
		return (ApplicantFunction) readProperty("applicantFunction");
	}

}
