package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudWbContractVessels was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudWbContractVessels extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Date> DATE_OP = new Property<Date>("dateOp");
	public static final Property<String> FLDCHR_CONTR_KEY = new Property<String>("fldchrContrKey");
	public static final Property<String> FLDCHR_CONTR_VSL_KEY = new Property<String>("fldchrContrVslKey");
	public static final Property<String> FLDCHR_DELIVERY_LOCT = new Property<String>("fldchrDeliveryLoct");
	public static final Property<String> FLDCHR_DEMRG_LTIM_LOADING_DESCR = new Property<String>("fldchrDemrgLtimLoadingDescr");
	public static final Property<String> FLDCHR_DEMRG_LTIM_TOTAL_DESCR = new Property<String>("fldchrDemrgLtimTotalDescr");
	public static final Property<String> FLDCHR_DEMRG_LTIM_UMCODE = new Property<String>("fldchrDemrgLtimUMCode");
	public static final Property<String> FLDCHR_DEMRG_LTIM_UNLD_DESCR = new Property<String>("fldchrDemrgLtimUnldDescr");
	public static final Property<String> FLDCHR_DEMRG_RATE_CRNCY_CODE = new Property<String>("fldchrDemrgRateCrncyCode");
	public static final Property<String> FLDCHR_DEMRG_RATE_UMCODE = new Property<String>("fldchrDemrgRateUMCode");
	public static final Property<String> FLDCHR_FREIGHT_CRNCY_CODE = new Property<String>("fldchrFreightCrncyCode");
	public static final Property<String> FLDCHR_FREIGHT_STD_ACTUAL_FLAG = new Property<String>("fldchrFreightStdActualFlag");
	public static final Property<String> FLDCHR_GOODS_CHEMICAL_FLAG = new Property<String>("fldchrGoodsChemicalFlag");
	public static final Property<String> FLDCHR_GOODS_CLEAN_FLAG = new Property<String>("fldchrGoodsCleanFlag");
	public static final Property<String> FLDCHR_GOODS_CRUDES_FLAG = new Property<String>("fldchrGoodsCrudesFlag");
	public static final Property<String> FLDCHR_GOODS_DIRTY_FLAG = new Property<String>("fldchrGoodsDirtyFlag");
	public static final Property<String> FLDCHR_GOODS_GAS_FLAG = new Property<String>("fldchrGoodsGasFlag");
	public static final Property<String> FLDCHR_GOODS_LUBRICANTS_FLAG = new Property<String>("fldchrGoodsLubricantsFlag");
	public static final Property<String> FLDCHR_GOODS_MASTER_FLAG = new Property<String>("fldchrGoodsMasterFlag");
	public static final Property<String> FLDCHR_GOODS_SEMIREFINED_FLAG = new Property<String>("fldchrGoodsSemirefinedFlag");
	public static final Property<String> FLDCHR_LLOYDS_REF_NUM = new Property<String>("fldchrLloydsRefNum");
	public static final Property<String> FLDCHR_MIN_QTY_UMCODE = new Property<String>("fldchrMinQtyUMCode");
	public static final Property<String> FLDCHR_PSHARE_PRC_CRNCY_CODE = new Property<String>("fldchrPSharePrcCrncyCode");
	public static final Property<String> FLDCHR_PSHARE_TIME_UMCODE = new Property<String>("fldchrPShareTimeUMCode");
	public static final Property<String> FLDCHR_PRESSURE_RATE_UMCODE = new Property<String>("fldchrPressureRateUMCode");
	public static final Property<String> FLDCHR_PUMP_RATE_TIME_UNIT_UMCODE = new Property<String>("fldchrPumpRateTimeUnitUMCode");
	public static final Property<String> FLDCHR_PUMP_RATE_UMCODE = new Property<String>("fldchrPumpRateUMCode");
	public static final Property<String> FLDCHR_REDELIVERY_LOCT = new Property<String>("fldchrRedeliveryLoct");
	public static final Property<String> FLDCHR_REF_CONTR_KEY_CHARTER_IN = new Property<String>("fldchrRefContrKeyCharterIn");
	public static final Property<String> FLDCHR_USER_NAME = new Property<String>("fldchrUserName");
	public static final Property<BigDecimal> FLDDEC_DEMRG_RATE = new Property<BigDecimal>("flddecDemrgRate");
	public static final Property<BigDecimal> FLDDEC_FLAT_RATE_STD = new Property<BigDecimal>("flddecFlatRateStd");
	public static final Property<BigDecimal> FLDDEC_FREIGHT_EQV_DAILY_RATE = new Property<BigDecimal>("flddecFreightEqvDailyRate");
	public static final Property<BigDecimal> FLDDEC_FREIGHT_STD = new Property<BigDecimal>("flddecFreightStd");
	public static final Property<BigDecimal> FLDDEC_MIN_FLAT_RATE = new Property<BigDecimal>("flddecMinFlatRate");
	public static final Property<BigDecimal> FLDDEC_MIN_QTY = new Property<BigDecimal>("flddecMinQty");
	public static final Property<BigDecimal> FLDDEC_PSHARE_BASE_RATE = new Property<BigDecimal>("flddecPShareBaseRate");
	public static final Property<BigDecimal> FLDDEC_PSHARE_PCTG = new Property<BigDecimal>("flddecPSharePctg");
	public static final Property<BigDecimal> FLDDEC_PRESSURE_RATE = new Property<BigDecimal>("flddecPressureRate");
	public static final Property<BigDecimal> FLDDEC_PUMP_RATE = new Property<BigDecimal>("flddecPumpRate");
	public static final Property<BigDecimal> FLDDEC_WS_RATE_STD = new Property<BigDecimal>("flddecWsRateStd");
	public static final Property<Date> FLDSDT_DELIVERY_LCAN_END = new Property<Date>("fldsdtDeliveryLcanEnd");
	public static final Property<Date> FLDSDT_DELIVERY_LCAN_START = new Property<Date>("fldsdtDeliveryLcanStart");
	public static final Property<Date> FLDSDT_REDELIVERY_LCAN_END = new Property<Date>("fldsdtRedeliveryLcanEnd");
	public static final Property<Date> FLDSDT_REDELIVERY_LCAN_START = new Property<Date>("fldsdtRedeliveryLcanStart");
	public static final Property<Date> FLDSDT_TIME_STAMP = new Property<Date>("fldsdtTimeStamp");
	public static final Property<Short> FLDSMI_DEMRG_LTIM_LOADING = new Property<Short>("fldsmiDemrgLtimLoading");
	public static final Property<BigDecimal> FLDSMI_DEMRG_LTIM_TOTAL = new Property<BigDecimal>("fldsmiDemrgLtimTotal");
	public static final Property<Short> FLDSMI_DEMRG_LTIM_UNLD = new Property<Short>("fldsmiDemrgLtimUnld");
	public static final Property<String> FLDVCH_VSL_TRADING_LIMITS = new Property<String>("fldvchVslTradingLimits");
	public static final Property<String> OPERATION = new Property<String>("operation");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<String> USERID = new Property<String>("userid");

	public void setDateOp(Date dateOp)
	{
		writeProperty("dateOp", dateOp);
	}

	public Date getDateOp()
	{
		return (Date) readProperty("dateOp");
	}

	public void setFldchrContrKey(String fldchrContrKey)
	{
		writeProperty("fldchrContrKey", fldchrContrKey);
	}

	public String getFldchrContrKey()
	{
		return (String) readProperty("fldchrContrKey");
	}

	public void setFldchrContrVslKey(String fldchrContrVslKey)
	{
		writeProperty("fldchrContrVslKey", fldchrContrVslKey);
	}

	public String getFldchrContrVslKey()
	{
		return (String) readProperty("fldchrContrVslKey");
	}

	public void setFldchrDeliveryLoct(String fldchrDeliveryLoct)
	{
		writeProperty("fldchrDeliveryLoct", fldchrDeliveryLoct);
	}

	public String getFldchrDeliveryLoct()
	{
		return (String) readProperty("fldchrDeliveryLoct");
	}

	public void setFldchrDemrgLtimLoadingDescr(String fldchrDemrgLtimLoadingDescr)
	{
		writeProperty("fldchrDemrgLtimLoadingDescr", fldchrDemrgLtimLoadingDescr);
	}

	public String getFldchrDemrgLtimLoadingDescr()
	{
		return (String) readProperty("fldchrDemrgLtimLoadingDescr");
	}

	public void setFldchrDemrgLtimTotalDescr(String fldchrDemrgLtimTotalDescr)
	{
		writeProperty("fldchrDemrgLtimTotalDescr", fldchrDemrgLtimTotalDescr);
	}

	public String getFldchrDemrgLtimTotalDescr()
	{
		return (String) readProperty("fldchrDemrgLtimTotalDescr");
	}

	public void setFldchrDemrgLtimUMCode(String fldchrDemrgLtimUMCode)
	{
		writeProperty("fldchrDemrgLtimUMCode", fldchrDemrgLtimUMCode);
	}

	public String getFldchrDemrgLtimUMCode()
	{
		return (String) readProperty("fldchrDemrgLtimUMCode");
	}

	public void setFldchrDemrgLtimUnldDescr(String fldchrDemrgLtimUnldDescr)
	{
		writeProperty("fldchrDemrgLtimUnldDescr", fldchrDemrgLtimUnldDescr);
	}

	public String getFldchrDemrgLtimUnldDescr()
	{
		return (String) readProperty("fldchrDemrgLtimUnldDescr");
	}

	public void setFldchrDemrgRateCrncyCode(String fldchrDemrgRateCrncyCode)
	{
		writeProperty("fldchrDemrgRateCrncyCode", fldchrDemrgRateCrncyCode);
	}

	public String getFldchrDemrgRateCrncyCode()
	{
		return (String) readProperty("fldchrDemrgRateCrncyCode");
	}

	public void setFldchrDemrgRateUMCode(String fldchrDemrgRateUMCode)
	{
		writeProperty("fldchrDemrgRateUMCode", fldchrDemrgRateUMCode);
	}

	public String getFldchrDemrgRateUMCode()
	{
		return (String) readProperty("fldchrDemrgRateUMCode");
	}

	public void setFldchrFreightCrncyCode(String fldchrFreightCrncyCode)
	{
		writeProperty("fldchrFreightCrncyCode", fldchrFreightCrncyCode);
	}

	public String getFldchrFreightCrncyCode()
	{
		return (String) readProperty("fldchrFreightCrncyCode");
	}

	public void setFldchrFreightStdActualFlag(String fldchrFreightStdActualFlag)
	{
		writeProperty("fldchrFreightStdActualFlag", fldchrFreightStdActualFlag);
	}

	public String getFldchrFreightStdActualFlag()
	{
		return (String) readProperty("fldchrFreightStdActualFlag");
	}

	public void setFldchrGoodsChemicalFlag(String fldchrGoodsChemicalFlag)
	{
		writeProperty("fldchrGoodsChemicalFlag", fldchrGoodsChemicalFlag);
	}

	public String getFldchrGoodsChemicalFlag()
	{
		return (String) readProperty("fldchrGoodsChemicalFlag");
	}

	public void setFldchrGoodsCleanFlag(String fldchrGoodsCleanFlag)
	{
		writeProperty("fldchrGoodsCleanFlag", fldchrGoodsCleanFlag);
	}

	public String getFldchrGoodsCleanFlag()
	{
		return (String) readProperty("fldchrGoodsCleanFlag");
	}

	public void setFldchrGoodsCrudesFlag(String fldchrGoodsCrudesFlag)
	{
		writeProperty("fldchrGoodsCrudesFlag", fldchrGoodsCrudesFlag);
	}

	public String getFldchrGoodsCrudesFlag()
	{
		return (String) readProperty("fldchrGoodsCrudesFlag");
	}

	public void setFldchrGoodsDirtyFlag(String fldchrGoodsDirtyFlag)
	{
		writeProperty("fldchrGoodsDirtyFlag", fldchrGoodsDirtyFlag);
	}

	public String getFldchrGoodsDirtyFlag()
	{
		return (String) readProperty("fldchrGoodsDirtyFlag");
	}

	public void setFldchrGoodsGasFlag(String fldchrGoodsGasFlag)
	{
		writeProperty("fldchrGoodsGasFlag", fldchrGoodsGasFlag);
	}

	public String getFldchrGoodsGasFlag()
	{
		return (String) readProperty("fldchrGoodsGasFlag");
	}

	public void setFldchrGoodsLubricantsFlag(String fldchrGoodsLubricantsFlag)
	{
		writeProperty("fldchrGoodsLubricantsFlag", fldchrGoodsLubricantsFlag);
	}

	public String getFldchrGoodsLubricantsFlag()
	{
		return (String) readProperty("fldchrGoodsLubricantsFlag");
	}

	public void setFldchrGoodsMasterFlag(String fldchrGoodsMasterFlag)
	{
		writeProperty("fldchrGoodsMasterFlag", fldchrGoodsMasterFlag);
	}

	public String getFldchrGoodsMasterFlag()
	{
		return (String) readProperty("fldchrGoodsMasterFlag");
	}

	public void setFldchrGoodsSemirefinedFlag(String fldchrGoodsSemirefinedFlag)
	{
		writeProperty("fldchrGoodsSemirefinedFlag", fldchrGoodsSemirefinedFlag);
	}

	public String getFldchrGoodsSemirefinedFlag()
	{
		return (String) readProperty("fldchrGoodsSemirefinedFlag");
	}

	public void setFldchrLloydsRefNum(String fldchrLloydsRefNum)
	{
		writeProperty("fldchrLloydsRefNum", fldchrLloydsRefNum);
	}

	public String getFldchrLloydsRefNum()
	{
		return (String) readProperty("fldchrLloydsRefNum");
	}

	public void setFldchrMinQtyUMCode(String fldchrMinQtyUMCode)
	{
		writeProperty("fldchrMinQtyUMCode", fldchrMinQtyUMCode);
	}

	public String getFldchrMinQtyUMCode()
	{
		return (String) readProperty("fldchrMinQtyUMCode");
	}

	public void setFldchrPSharePrcCrncyCode(String fldchrPSharePrcCrncyCode)
	{
		writeProperty("fldchrPSharePrcCrncyCode", fldchrPSharePrcCrncyCode);
	}

	public String getFldchrPSharePrcCrncyCode()
	{
		return (String) readProperty("fldchrPSharePrcCrncyCode");
	}

	public void setFldchrPShareTimeUMCode(String fldchrPShareTimeUMCode)
	{
		writeProperty("fldchrPShareTimeUMCode", fldchrPShareTimeUMCode);
	}

	public String getFldchrPShareTimeUMCode()
	{
		return (String) readProperty("fldchrPShareTimeUMCode");
	}

	public void setFldchrPressureRateUMCode(String fldchrPressureRateUMCode)
	{
		writeProperty("fldchrPressureRateUMCode", fldchrPressureRateUMCode);
	}

	public String getFldchrPressureRateUMCode()
	{
		return (String) readProperty("fldchrPressureRateUMCode");
	}

	public void setFldchrPumpRateTimeUnitUMCode(String fldchrPumpRateTimeUnitUMCode)
	{
		writeProperty("fldchrPumpRateTimeUnitUMCode", fldchrPumpRateTimeUnitUMCode);
	}

	public String getFldchrPumpRateTimeUnitUMCode()
	{
		return (String) readProperty("fldchrPumpRateTimeUnitUMCode");
	}

	public void setFldchrPumpRateUMCode(String fldchrPumpRateUMCode)
	{
		writeProperty("fldchrPumpRateUMCode", fldchrPumpRateUMCode);
	}

	public String getFldchrPumpRateUMCode()
	{
		return (String) readProperty("fldchrPumpRateUMCode");
	}

	public void setFldchrRedeliveryLoct(String fldchrRedeliveryLoct)
	{
		writeProperty("fldchrRedeliveryLoct", fldchrRedeliveryLoct);
	}

	public String getFldchrRedeliveryLoct()
	{
		return (String) readProperty("fldchrRedeliveryLoct");
	}

	public void setFldchrRefContrKeyCharterIn(String fldchrRefContrKeyCharterIn)
	{
		writeProperty("fldchrRefContrKeyCharterIn", fldchrRefContrKeyCharterIn);
	}

	public String getFldchrRefContrKeyCharterIn()
	{
		return (String) readProperty("fldchrRefContrKeyCharterIn");
	}

	public void setFldchrUserName(String fldchrUserName)
	{
		writeProperty("fldchrUserName", fldchrUserName);
	}

	public String getFldchrUserName()
	{
		return (String) readProperty("fldchrUserName");
	}

	public void setFlddecDemrgRate(BigDecimal flddecDemrgRate)
	{
		writeProperty("flddecDemrgRate", flddecDemrgRate);
	}

	public BigDecimal getFlddecDemrgRate()
	{
		return (BigDecimal) readProperty("flddecDemrgRate");
	}

	public void setFlddecFlatRateStd(BigDecimal flddecFlatRateStd)
	{
		writeProperty("flddecFlatRateStd", flddecFlatRateStd);
	}

	public BigDecimal getFlddecFlatRateStd()
	{
		return (BigDecimal) readProperty("flddecFlatRateStd");
	}

	public void setFlddecFreightEqvDailyRate(BigDecimal flddecFreightEqvDailyRate)
	{
		writeProperty("flddecFreightEqvDailyRate", flddecFreightEqvDailyRate);
	}

	public BigDecimal getFlddecFreightEqvDailyRate()
	{
		return (BigDecimal) readProperty("flddecFreightEqvDailyRate");
	}

	public void setFlddecFreightStd(BigDecimal flddecFreightStd)
	{
		writeProperty("flddecFreightStd", flddecFreightStd);
	}

	public BigDecimal getFlddecFreightStd()
	{
		return (BigDecimal) readProperty("flddecFreightStd");
	}

	public void setFlddecMinFlatRate(BigDecimal flddecMinFlatRate)
	{
		writeProperty("flddecMinFlatRate", flddecMinFlatRate);
	}

	public BigDecimal getFlddecMinFlatRate()
	{
		return (BigDecimal) readProperty("flddecMinFlatRate");
	}

	public void setFlddecMinQty(BigDecimal flddecMinQty)
	{
		writeProperty("flddecMinQty", flddecMinQty);
	}

	public BigDecimal getFlddecMinQty()
	{
		return (BigDecimal) readProperty("flddecMinQty");
	}

	public void setFlddecPShareBaseRate(BigDecimal flddecPShareBaseRate)
	{
		writeProperty("flddecPShareBaseRate", flddecPShareBaseRate);
	}

	public BigDecimal getFlddecPShareBaseRate()
	{
		return (BigDecimal) readProperty("flddecPShareBaseRate");
	}

	public void setFlddecPSharePctg(BigDecimal flddecPSharePctg)
	{
		writeProperty("flddecPSharePctg", flddecPSharePctg);
	}

	public BigDecimal getFlddecPSharePctg()
	{
		return (BigDecimal) readProperty("flddecPSharePctg");
	}

	public void setFlddecPressureRate(BigDecimal flddecPressureRate)
	{
		writeProperty("flddecPressureRate", flddecPressureRate);
	}

	public BigDecimal getFlddecPressureRate()
	{
		return (BigDecimal) readProperty("flddecPressureRate");
	}

	public void setFlddecPumpRate(BigDecimal flddecPumpRate)
	{
		writeProperty("flddecPumpRate", flddecPumpRate);
	}

	public BigDecimal getFlddecPumpRate()
	{
		return (BigDecimal) readProperty("flddecPumpRate");
	}

	public void setFlddecWsRateStd(BigDecimal flddecWsRateStd)
	{
		writeProperty("flddecWsRateStd", flddecWsRateStd);
	}

	public BigDecimal getFlddecWsRateStd()
	{
		return (BigDecimal) readProperty("flddecWsRateStd");
	}

	public void setFldsdtDeliveryLcanEnd(Date fldsdtDeliveryLcanEnd)
	{
		writeProperty("fldsdtDeliveryLcanEnd", fldsdtDeliveryLcanEnd);
	}

	public Date getFldsdtDeliveryLcanEnd()
	{
		return (Date) readProperty("fldsdtDeliveryLcanEnd");
	}

	public void setFldsdtDeliveryLcanStart(Date fldsdtDeliveryLcanStart)
	{
		writeProperty("fldsdtDeliveryLcanStart", fldsdtDeliveryLcanStart);
	}

	public Date getFldsdtDeliveryLcanStart()
	{
		return (Date) readProperty("fldsdtDeliveryLcanStart");
	}

	public void setFldsdtRedeliveryLcanEnd(Date fldsdtRedeliveryLcanEnd)
	{
		writeProperty("fldsdtRedeliveryLcanEnd", fldsdtRedeliveryLcanEnd);
	}

	public Date getFldsdtRedeliveryLcanEnd()
	{
		return (Date) readProperty("fldsdtRedeliveryLcanEnd");
	}

	public void setFldsdtRedeliveryLcanStart(Date fldsdtRedeliveryLcanStart)
	{
		writeProperty("fldsdtRedeliveryLcanStart", fldsdtRedeliveryLcanStart);
	}

	public Date getFldsdtRedeliveryLcanStart()
	{
		return (Date) readProperty("fldsdtRedeliveryLcanStart");
	}

	public void setFldsdtTimeStamp(Date fldsdtTimeStamp)
	{
		writeProperty("fldsdtTimeStamp", fldsdtTimeStamp);
	}

	public Date getFldsdtTimeStamp()
	{
		return (Date) readProperty("fldsdtTimeStamp");
	}

	public void setFldsmiDemrgLtimLoading(Short fldsmiDemrgLtimLoading)
	{
		writeProperty("fldsmiDemrgLtimLoading", fldsmiDemrgLtimLoading);
	}

	public Short getFldsmiDemrgLtimLoading()
	{
		return (Short) readProperty("fldsmiDemrgLtimLoading");
	}

	public void setFldsmiDemrgLtimTotal(BigDecimal fldsmiDemrgLtimTotal)
	{
		writeProperty("fldsmiDemrgLtimTotal", fldsmiDemrgLtimTotal);
	}

	public BigDecimal getFldsmiDemrgLtimTotal()
	{
		return (BigDecimal) readProperty("fldsmiDemrgLtimTotal");
	}

	public void setFldsmiDemrgLtimUnld(Short fldsmiDemrgLtimUnld)
	{
		writeProperty("fldsmiDemrgLtimUnld", fldsmiDemrgLtimUnld);
	}

	public Short getFldsmiDemrgLtimUnld()
	{
		return (Short) readProperty("fldsmiDemrgLtimUnld");
	}

	public void setFldvchVslTradingLimits(String fldvchVslTradingLimits)
	{
		writeProperty("fldvchVslTradingLimits", fldvchVslTradingLimits);
	}

	public String getFldvchVslTradingLimits()
	{
		return (String) readProperty("fldvchVslTradingLimits");
	}

	public void setOperation(String operation)
	{
		writeProperty("operation", operation);
	}

	public String getOperation()
	{
		return (String) readProperty("operation");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setUserid(String userid)
	{
		writeProperty("userid", userid);
	}

	public String getUserid()
	{
		return (String) readProperty("userid");
	}

}
