package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudContract was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudContract extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Integer> ACCT_NUM = new Property<Integer>("acctNum");
	public static final Property<String> CONTR_CONFIRMED_BY = new Property<String>("contrConfirmedBy");
	public static final Property<Date> CONTR_CONFIRMED_DATE = new Property<Date>("contrConfirmedDate");
	public static final Property<Date> CONTR_CREATION_DATE = new Property<Date>("contrCreationDate");
	public static final Property<String> CONTR_CREATOR_INIT = new Property<String>("contrCreatorInit");
	public static final Property<String> CONTR_NAME = new Property<String>("contrName");
	public static final Property<Integer> CONTR_NUM = new Property<Integer>("contrNum");
	public static final Property<String> CONTR_ON_HOLD_INDS = new Property<String>("contrOnHoldInds");
	public static final Property<Integer> CONTR_REV_NUM = new Property<Integer>("contrRevNum");
	public static final Property<String> CONTR_REVIEWER_INIT = new Property<String>("contrReviewerInit");
	public static final Property<String> CONTR_STATUS_CODE = new Property<String>("contrStatusCode");
	public static final Property<String> CONTR_TYPE = new Property<String>("contrType");
	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setAcctNum(Integer acctNum)
	{
		writeProperty("acctNum", acctNum);
	}

	public Integer getAcctNum()
	{
		return (Integer) readProperty("acctNum");
	}

	public void setContrConfirmedBy(String contrConfirmedBy)
	{
		writeProperty("contrConfirmedBy", contrConfirmedBy);
	}

	public String getContrConfirmedBy()
	{
		return (String) readProperty("contrConfirmedBy");
	}

	public void setContrConfirmedDate(Date contrConfirmedDate)
	{
		writeProperty("contrConfirmedDate", contrConfirmedDate);
	}

	public Date getContrConfirmedDate()
	{
		return (Date) readProperty("contrConfirmedDate");
	}

	public void setContrCreationDate(Date contrCreationDate)
	{
		writeProperty("contrCreationDate", contrCreationDate);
	}

	public Date getContrCreationDate()
	{
		return (Date) readProperty("contrCreationDate");
	}

	public void setContrCreatorInit(String contrCreatorInit)
	{
		writeProperty("contrCreatorInit", contrCreatorInit);
	}

	public String getContrCreatorInit()
	{
		return (String) readProperty("contrCreatorInit");
	}

	public void setContrName(String contrName)
	{
		writeProperty("contrName", contrName);
	}

	public String getContrName()
	{
		return (String) readProperty("contrName");
	}

	public void setContrNum(Integer contrNum)
	{
		writeProperty("contrNum", contrNum);
	}

	public Integer getContrNum()
	{
		return (Integer) readProperty("contrNum");
	}

	public void setContrOnHoldInds(String contrOnHoldInds)
	{
		writeProperty("contrOnHoldInds", contrOnHoldInds);
	}

	public String getContrOnHoldInds()
	{
		return (String) readProperty("contrOnHoldInds");
	}

	public void setContrRevNum(Integer contrRevNum)
	{
		writeProperty("contrRevNum", contrRevNum);
	}

	public Integer getContrRevNum()
	{
		return (Integer) readProperty("contrRevNum");
	}

	public void setContrReviewerInit(String contrReviewerInit)
	{
		writeProperty("contrReviewerInit", contrReviewerInit);
	}

	public String getContrReviewerInit()
	{
		return (String) readProperty("contrReviewerInit");
	}

	public void setContrStatusCode(String contrStatusCode)
	{
		writeProperty("contrStatusCode", contrStatusCode);
	}

	public String getContrStatusCode()
	{
		return (String) readProperty("contrStatusCode");
	}

	public void setContrType(String contrType)
	{
		writeProperty("contrType", contrType);
	}

	public String getContrType()
	{
		return (String) readProperty("contrType");
	}

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
