package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudCollateralPledged was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudCollateralPledged extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Integer> CASH_COLL_NUM = new Property<Integer>("cashCollNum");
	public static final Property<String> COLL_PARTY_TYPE = new Property<String>("collPartyType");
	public static final Property<Integer> COLL_PLEDGED_NUM = new Property<Integer>("collPledgedNum");
	public static final Property<String> COLL_PLEDGED_TYPE = new Property<String>("collPledgedType");
	public static final Property<Integer> COST_NUM = new Property<Integer>("costNum");
	public static final Property<Integer> LC_NUM = new Property<Integer>("lcNum");
	public static final Property<Integer> MARGIN_CALL_NUM = new Property<Integer>("marginCallNum");
	public static final Property<Integer> MCA_NUM = new Property<Integer>("mcaNum");
	public static final Property<Integer> MKT_SECURITY_NUM = new Property<Integer>("mktSecurityNum");
	public static final Property<Integer> PG_NUM = new Property<Integer>("pgNum");
	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setCashCollNum(Integer cashCollNum)
	{
		writeProperty("cashCollNum", cashCollNum);
	}

	public Integer getCashCollNum()
	{
		return (Integer) readProperty("cashCollNum");
	}

	public void setCollPartyType(String collPartyType)
	{
		writeProperty("collPartyType", collPartyType);
	}

	public String getCollPartyType()
	{
		return (String) readProperty("collPartyType");
	}

	public void setCollPledgedNum(Integer collPledgedNum)
	{
		writeProperty("collPledgedNum", collPledgedNum);
	}

	public Integer getCollPledgedNum()
	{
		return (Integer) readProperty("collPledgedNum");
	}

	public void setCollPledgedType(String collPledgedType)
	{
		writeProperty("collPledgedType", collPledgedType);
	}

	public String getCollPledgedType()
	{
		return (String) readProperty("collPledgedType");
	}

	public void setCostNum(Integer costNum)
	{
		writeProperty("costNum", costNum);
	}

	public Integer getCostNum()
	{
		return (Integer) readProperty("costNum");
	}

	public void setLcNum(Integer lcNum)
	{
		writeProperty("lcNum", lcNum);
	}

	public Integer getLcNum()
	{
		return (Integer) readProperty("lcNum");
	}

	public void setMarginCallNum(Integer marginCallNum)
	{
		writeProperty("marginCallNum", marginCallNum);
	}

	public Integer getMarginCallNum()
	{
		return (Integer) readProperty("marginCallNum");
	}

	public void setMcaNum(Integer mcaNum)
	{
		writeProperty("mcaNum", mcaNum);
	}

	public Integer getMcaNum()
	{
		return (Integer) readProperty("mcaNum");
	}

	public void setMktSecurityNum(Integer mktSecurityNum)
	{
		writeProperty("mktSecurityNum", mktSecurityNum);
	}

	public Integer getMktSecurityNum()
	{
		return (Integer) readProperty("mktSecurityNum");
	}

	public void setPgNum(Integer pgNum)
	{
		writeProperty("pgNum", pgNum);
	}

	public Integer getPgNum()
	{
		return (Integer) readProperty("pgNum");
	}

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
