package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudLcStatusHistory was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudLcStatusHistory extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Integer> LC_NUM = new Property<Integer>("lcNum");
	public static final Property<String> LC_STATUS_CODE = new Property<String>("lcStatusCode");
	public static final Property<Date> LC_STATUS_DATE = new Property<Date>("lcStatusDate");
	public static final Property<String> LC_STATUS_SHORT_CMNT = new Property<String>("lcStatusShortCmnt");
	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setLcNum(Integer lcNum)
	{
		writeProperty("lcNum", lcNum);
	}

	public Integer getLcNum()
	{
		return (Integer) readProperty("lcNum");
	}

	public void setLcStatusCode(String lcStatusCode)
	{
		writeProperty("lcStatusCode", lcStatusCode);
	}

	public String getLcStatusCode()
	{
		return (String) readProperty("lcStatusCode");
	}

	public void setLcStatusDate(Date lcStatusDate)
	{
		writeProperty("lcStatusDate", lcStatusDate);
	}

	public Date getLcStatusDate()
	{
		return (Date) readProperty("lcStatusDate");
	}

	public void setLcStatusShortCmnt(String lcStatusShortCmnt)
	{
		writeProperty("lcStatusShortCmnt", lcStatusShortCmnt);
	}

	public String getLcStatusShortCmnt()
	{
		return (String) readProperty("lcStatusShortCmnt");
	}

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
