package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudAllocationInsp was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudAllocationInsp extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> ALLOC_INSP_SHORT_CMNT = new Property<String>("allocInspShortCmnt");
	public static final Property<Integer> ALLOC_NUM = new Property<Integer>("allocNum");
	public static final Property<Integer> CMNT_NUM = new Property<Integer>("cmntNum");
	public static final Property<Integer> INSP_COMP_NUM = new Property<Integer>("inspCompNum");
	public static final Property<String> INSP_COMP_SHORT_NAME = new Property<String>("inspCompShortName");
	public static final Property<Double> INSP_FEE_AMT = new Property<Double>("inspFeeAmt");
	public static final Property<String> INSP_FEE_CURR_CODE = new Property<String>("inspFeeCurrCode");
	public static final Property<Short> INSP_FEE_SPLIT_COUNT = new Property<Short>("inspFeeSplitCount");
	public static final Property<String> INSP_FEE_UOM_CODE = new Property<String>("inspFeeUomCode");
	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setAllocInspShortCmnt(String allocInspShortCmnt)
	{
		writeProperty("allocInspShortCmnt", allocInspShortCmnt);
	}

	public String getAllocInspShortCmnt()
	{
		return (String) readProperty("allocInspShortCmnt");
	}

	public void setAllocNum(Integer allocNum)
	{
		writeProperty("allocNum", allocNum);
	}

	public Integer getAllocNum()
	{
		return (Integer) readProperty("allocNum");
	}

	public void setCmntNum(Integer cmntNum)
	{
		writeProperty("cmntNum", cmntNum);
	}

	public Integer getCmntNum()
	{
		return (Integer) readProperty("cmntNum");
	}

	public void setInspCompNum(Integer inspCompNum)
	{
		writeProperty("inspCompNum", inspCompNum);
	}

	public Integer getInspCompNum()
	{
		return (Integer) readProperty("inspCompNum");
	}

	public void setInspCompShortName(String inspCompShortName)
	{
		writeProperty("inspCompShortName", inspCompShortName);
	}

	public String getInspCompShortName()
	{
		return (String) readProperty("inspCompShortName");
	}

	public void setInspFeeAmt(Double inspFeeAmt)
	{
		writeProperty("inspFeeAmt", inspFeeAmt);
	}

	public Double getInspFeeAmt()
	{
		return (Double) readProperty("inspFeeAmt");
	}

	public void setInspFeeCurrCode(String inspFeeCurrCode)
	{
		writeProperty("inspFeeCurrCode", inspFeeCurrCode);
	}

	public String getInspFeeCurrCode()
	{
		return (String) readProperty("inspFeeCurrCode");
	}

	public void setInspFeeSplitCount(Short inspFeeSplitCount)
	{
		writeProperty("inspFeeSplitCount", inspFeeSplitCount);
	}

	public Short getInspFeeSplitCount()
	{
		return (Short) readProperty("inspFeeSplitCount");
	}

	public void setInspFeeUomCode(String inspFeeUomCode)
	{
		writeProperty("inspFeeUomCode", inspFeeUomCode);
	}

	public String getInspFeeUomCode()
	{
		return (String) readProperty("inspFeeUomCode");
	}

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
