package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudCostTemplateGrpItem was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudCostTemplateGrpItem extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Integer> COST_TEMPLATE_GROUP_OID = new Property<Integer>("costTemplateGroupOid");
	public static final Property<Integer> COST_TEMPLATE_OID = new Property<Integer>("costTemplateOid");
	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setCostTemplateGroupOid(Integer costTemplateGroupOid)
	{
		writeProperty("costTemplateGroupOid", costTemplateGroupOid);
	}

	public Integer getCostTemplateGroupOid()
	{
		return (Integer) readProperty("costTemplateGroupOid");
	}

	public void setCostTemplateOid(Integer costTemplateOid)
	{
		writeProperty("costTemplateOid", costTemplateOid);
	}

	public Integer getCostTemplateOid()
	{
		return (Integer) readProperty("costTemplateOid");
	}

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
