package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudLocationStorages was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudLocationStorages extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> A_BCPORT_CODE = new Property<String>("aBCPortCode");
	public static final Property<Date> DATE_OP = new Property<Date>("dateOp");
	public static final Property<String> FLDCHR_DUTY_CODE = new Property<String>("fldchrDutyCode");
	public static final Property<String> FLDCHR_LOCT_KEY = new Property<String>("fldchrLoctKey");
	public static final Property<String> FLDCHR_STORAGE_CODE = new Property<String>("fldchrStorageCode");
	public static final Property<String> FLDCHR_STORAGE_COST_CENTER_CODE = new Property<String>("fldchrStorageCostCenterCode");
	public static final Property<String> FLDVCH_STORAGE_DESC = new Property<String>("fldvchStorageDesc");
	public static final Property<String> FLDVCH_STORAGE_SAP_ALIAS = new Property<String>("fldvchStorageSapAlias");
	public static final Property<String> OPERATION = new Property<String>("operation");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<String> USERID = new Property<String>("userid");

	public void setABCPortCode(String aBCPortCode)
	{
		writeProperty("aBCPortCode", aBCPortCode);
	}

	public String getABCPortCode()
	{
		return (String) readProperty("aBCPortCode");
	}

	public void setDateOp(Date dateOp)
	{
		writeProperty("dateOp", dateOp);
	}

	public Date getDateOp()
	{
		return (Date) readProperty("dateOp");
	}

	public void setFldchrDutyCode(String fldchrDutyCode)
	{
		writeProperty("fldchrDutyCode", fldchrDutyCode);
	}

	public String getFldchrDutyCode()
	{
		return (String) readProperty("fldchrDutyCode");
	}

	public void setFldchrLoctKey(String fldchrLoctKey)
	{
		writeProperty("fldchrLoctKey", fldchrLoctKey);
	}

	public String getFldchrLoctKey()
	{
		return (String) readProperty("fldchrLoctKey");
	}

	public void setFldchrStorageCode(String fldchrStorageCode)
	{
		writeProperty("fldchrStorageCode", fldchrStorageCode);
	}

	public String getFldchrStorageCode()
	{
		return (String) readProperty("fldchrStorageCode");
	}

	public void setFldchrStorageCostCenterCode(String fldchrStorageCostCenterCode)
	{
		writeProperty("fldchrStorageCostCenterCode", fldchrStorageCostCenterCode);
	}

	public String getFldchrStorageCostCenterCode()
	{
		return (String) readProperty("fldchrStorageCostCenterCode");
	}

	public void setFldvchStorageDesc(String fldvchStorageDesc)
	{
		writeProperty("fldvchStorageDesc", fldvchStorageDesc);
	}

	public String getFldvchStorageDesc()
	{
		return (String) readProperty("fldvchStorageDesc");
	}

	public void setFldvchStorageSapAlias(String fldvchStorageSapAlias)
	{
		writeProperty("fldvchStorageSapAlias", fldvchStorageSapAlias);
	}

	public String getFldvchStorageSapAlias()
	{
		return (String) readProperty("fldvchStorageSapAlias");
	}

	public void setOperation(String operation)
	{
		writeProperty("operation", operation);
	}

	public String getOperation()
	{
		return (String) readProperty("operation");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setUserid(String userid)
	{
		writeProperty("userid", userid);
	}

	public String getUserid()
	{
		return (String) readProperty("userid");
	}

}
