package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudAccountGroup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudAccountGroup extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> ACCT_GROUP_RELATION = new Property<String>("acctGroupRelation");
	public static final Property<String> ACCT_GROUP_TYPE_CODE = new Property<String>("acctGroupTypeCode");
	public static final Property<Integer> ACCT_NUM = new Property<Integer>("acctNum");
	public static final Property<Double> PARENT_ACCT_OWN_PCNT = new Property<Double>("parentAcctOwnPcnt");
	public static final Property<Integer> RELATED_ACCT_NUM = new Property<Integer>("relatedAcctNum");
	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setAcctGroupRelation(String acctGroupRelation)
	{
		writeProperty("acctGroupRelation", acctGroupRelation);
	}

	public String getAcctGroupRelation()
	{
		return (String) readProperty("acctGroupRelation");
	}

	public void setAcctGroupTypeCode(String acctGroupTypeCode)
	{
		writeProperty("acctGroupTypeCode", acctGroupTypeCode);
	}

	public String getAcctGroupTypeCode()
	{
		return (String) readProperty("acctGroupTypeCode");
	}

	public void setAcctNum(Integer acctNum)
	{
		writeProperty("acctNum", acctNum);
	}

	public Integer getAcctNum()
	{
		return (Integer) readProperty("acctNum");
	}

	public void setParentAcctOwnPcnt(Double parentAcctOwnPcnt)
	{
		writeProperty("parentAcctOwnPcnt", parentAcctOwnPcnt);
	}

	public Double getParentAcctOwnPcnt()
	{
		return (Double) readProperty("parentAcctOwnPcnt");
	}

	public void setRelatedAcctNum(Integer relatedAcctNum)
	{
		writeProperty("relatedAcctNum", relatedAcctNum);
	}

	public Integer getRelatedAcctNum()
	{
		return (Integer) readProperty("relatedAcctNum");
	}

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
