package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudLcSpecialCondition was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudLcSpecialCondition extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Integer> LC_NUM = new Property<Integer>("lcNum");
	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<Integer> SPECIAL_COND_NUM = new Property<Integer>("specialCondNum");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setLcNum(Integer lcNum)
	{
		writeProperty("lcNum", lcNum);
	}

	public Integer getLcNum()
	{
		return (Integer) readProperty("lcNum");
	}

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setSpecialCondNum(Integer specialCondNum)
	{
		writeProperty("specialCondNum", specialCondNum);
	}

	public Integer getSpecialCondNum()
	{
		return (Integer) readProperty("specialCondNum");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
