package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudWbTimesheetReasons was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudWbTimesheetReasons extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Date> DATE_OP = new Property<Date>("dateOp");
	public static final Property<String> FLDCHR_TSHT_REASON_ID = new Property<String>("fldchrTshtReasonId");
	public static final Property<String> FLDVCH_TSHT_REASON_DESC = new Property<String>("fldvchTshtReasonDesc");
	public static final Property<String> OPERATION = new Property<String>("operation");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<String> USERID = new Property<String>("userid");

	public void setDateOp(Date dateOp)
	{
		writeProperty("dateOp", dateOp);
	}

	public Date getDateOp()
	{
		return (Date) readProperty("dateOp");
	}

	public void setFldchrTshtReasonId(String fldchrTshtReasonId)
	{
		writeProperty("fldchrTshtReasonId", fldchrTshtReasonId);
	}

	public String getFldchrTshtReasonId()
	{
		return (String) readProperty("fldchrTshtReasonId");
	}

	public void setFldvchTshtReasonDesc(String fldvchTshtReasonDesc)
	{
		writeProperty("fldvchTshtReasonDesc", fldvchTshtReasonDesc);
	}

	public String getFldvchTshtReasonDesc()
	{
		return (String) readProperty("fldvchTshtReasonDesc");
	}

	public void setOperation(String operation)
	{
		writeProperty("operation", operation);
	}

	public String getOperation()
	{
		return (String) readProperty("operation");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setUserid(String userid)
	{
		writeProperty("userid", userid);
	}

	public String getUserid()
	{
		return (String) readProperty("userid");
	}

}
