package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudWbContractFixtures was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudWbContractFixtures extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Date> DATE_OP = new Property<Date>("dateOp");
	public static final Property<String> FLDCHR_CONTR_KEY = new Property<String>("fldchrContrKey");
	public static final Property<String> FLDCHR_FIXTURE_UMCODE = new Property<String>("fldchrFixtureUMCode");
	public static final Property<String> FLDCHR_FREIGHT_CRNCY = new Property<String>("fldchrFreightCrncy");
	public static final Property<Integer> FLDCHR_REC_ID = new Property<Integer>("fldchrRecId");
	public static final Property<BigDecimal> FLDDEC_DWT_TNE = new Property<BigDecimal>("flddecDwtTNE");
	public static final Property<BigDecimal> FLDDEC_FIXTURE_MIN_QTY = new Property<BigDecimal>("flddecFixtureMinQty");
	public static final Property<BigDecimal> FLDDEC_FREIGHT = new Property<BigDecimal>("flddecFreight");
	public static final Property<Date> FLDSDT_FIXTURE_DATE = new Property<Date>("fldsdtFixtureDate");
	public static final Property<String> FLDVCH_COMP = new Property<String>("fldvchComp");
	public static final Property<String> FLDVCH_FIXTURE_TYPE = new Property<String>("fldvchFixtureType");
	public static final Property<String> FLDVCH_LCAN_START = new Property<String>("fldvchLcanStart");
	public static final Property<String> FLDVCH_MARKET = new Property<String>("fldvchMarket");
	public static final Property<String> FLDVCH_ROUTE = new Property<String>("fldvchRoute");
	public static final Property<String> FLDVCH_VESSEL = new Property<String>("fldvchVessel");
	public static final Property<String> OPERATION = new Property<String>("operation");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<String> USERID = new Property<String>("userid");

	public void setDateOp(Date dateOp)
	{
		writeProperty("dateOp", dateOp);
	}

	public Date getDateOp()
	{
		return (Date) readProperty("dateOp");
	}

	public void setFldchrContrKey(String fldchrContrKey)
	{
		writeProperty("fldchrContrKey", fldchrContrKey);
	}

	public String getFldchrContrKey()
	{
		return (String) readProperty("fldchrContrKey");
	}

	public void setFldchrFixtureUMCode(String fldchrFixtureUMCode)
	{
		writeProperty("fldchrFixtureUMCode", fldchrFixtureUMCode);
	}

	public String getFldchrFixtureUMCode()
	{
		return (String) readProperty("fldchrFixtureUMCode");
	}

	public void setFldchrFreightCrncy(String fldchrFreightCrncy)
	{
		writeProperty("fldchrFreightCrncy", fldchrFreightCrncy);
	}

	public String getFldchrFreightCrncy()
	{
		return (String) readProperty("fldchrFreightCrncy");
	}

	public void setFldchrRecId(Integer fldchrRecId)
	{
		writeProperty("fldchrRecId", fldchrRecId);
	}

	public Integer getFldchrRecId()
	{
		return (Integer) readProperty("fldchrRecId");
	}

	public void setFlddecDwtTNE(BigDecimal flddecDwtTNE)
	{
		writeProperty("flddecDwtTNE", flddecDwtTNE);
	}

	public BigDecimal getFlddecDwtTNE()
	{
		return (BigDecimal) readProperty("flddecDwtTNE");
	}

	public void setFlddecFixtureMinQty(BigDecimal flddecFixtureMinQty)
	{
		writeProperty("flddecFixtureMinQty", flddecFixtureMinQty);
	}

	public BigDecimal getFlddecFixtureMinQty()
	{
		return (BigDecimal) readProperty("flddecFixtureMinQty");
	}

	public void setFlddecFreight(BigDecimal flddecFreight)
	{
		writeProperty("flddecFreight", flddecFreight);
	}

	public BigDecimal getFlddecFreight()
	{
		return (BigDecimal) readProperty("flddecFreight");
	}

	public void setFldsdtFixtureDate(Date fldsdtFixtureDate)
	{
		writeProperty("fldsdtFixtureDate", fldsdtFixtureDate);
	}

	public Date getFldsdtFixtureDate()
	{
		return (Date) readProperty("fldsdtFixtureDate");
	}

	public void setFldvchComp(String fldvchComp)
	{
		writeProperty("fldvchComp", fldvchComp);
	}

	public String getFldvchComp()
	{
		return (String) readProperty("fldvchComp");
	}

	public void setFldvchFixtureType(String fldvchFixtureType)
	{
		writeProperty("fldvchFixtureType", fldvchFixtureType);
	}

	public String getFldvchFixtureType()
	{
		return (String) readProperty("fldvchFixtureType");
	}

	public void setFldvchLcanStart(String fldvchLcanStart)
	{
		writeProperty("fldvchLcanStart", fldvchLcanStart);
	}

	public String getFldvchLcanStart()
	{
		return (String) readProperty("fldvchLcanStart");
	}

	public void setFldvchMarket(String fldvchMarket)
	{
		writeProperty("fldvchMarket", fldvchMarket);
	}

	public String getFldvchMarket()
	{
		return (String) readProperty("fldvchMarket");
	}

	public void setFldvchRoute(String fldvchRoute)
	{
		writeProperty("fldvchRoute", fldvchRoute);
	}

	public String getFldvchRoute()
	{
		return (String) readProperty("fldvchRoute");
	}

	public void setFldvchVessel(String fldvchVessel)
	{
		writeProperty("fldvchVessel", fldvchVessel);
	}

	public String getFldvchVessel()
	{
		return (String) readProperty("fldvchVessel");
	}

	public void setOperation(String operation)
	{
		writeProperty("operation", operation);
	}

	public String getOperation()
	{
		return (String) readProperty("operation");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setUserid(String userid)
	{
		writeProperty("userid", userid);
	}

	public String getUserid()
	{
		return (String) readProperty("userid");
	}

}
