package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudVatTransNature was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudVatTransNature extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<String> TRANS_NATURE_CODE = new Property<String>("transNatureCode");
	public static final Property<String> TRANS_NATURE_DESC = new Property<String>("transNatureDesc");

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setTransNatureCode(String transNatureCode)
	{
		writeProperty("transNatureCode", transNatureCode);
	}

	public String getTransNatureCode()
	{
		return (String) readProperty("transNatureCode");
	}

	public void setTransNatureDesc(String transNatureDesc)
	{
		writeProperty("transNatureDesc", transNatureDesc);
	}

	public String getTransNatureDesc()
	{
		return (String) readProperty("transNatureDesc");
	}

}
