package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudAcctSubType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudAcctSubType extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> ACCT_SUB_TYPE_CODE = new Property<String>("acctSubTypeCode");
	public static final Property<String> ACCT_SUB_TYPE_DESC = new Property<String>("acctSubTypeDesc");
	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setAcctSubTypeCode(String acctSubTypeCode)
	{
		writeProperty("acctSubTypeCode", acctSubTypeCode);
	}

	public String getAcctSubTypeCode()
	{
		return (String) readProperty("acctSubTypeCode");
	}

	public void setAcctSubTypeDesc(String acctSubTypeDesc)
	{
		writeProperty("acctSubTypeDesc", acctSubTypeDesc);
	}

	public String getAcctSubTypeDesc()
	{
		return (String) readProperty("acctSubTypeDesc");
	}

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
