package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudWbContractTcPositions was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudWbContractTcPositions extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<BigDecimal> ACTUAL_POSITION = new Property<BigDecimal>("actualPosition");
	public static final Property<BigDecimal> ADJUSTMENT = new Property<BigDecimal>("adjustment");
	public static final Property<String> CONTRACT_KEY = new Property<String>("contractKey");
	public static final Property<Date> DATE_OP = new Property<Date>("dateOp");
	public static final Property<BigDecimal> INITIAL_POSITION = new Property<BigDecimal>("initialPosition");
	public static final Property<Date> LAST_RUN_DATE = new Property<Date>("lastRunDate");
	public static final Property<Date> MONTH_YEAR = new Property<Date>("monthYear");
	public static final Property<String> OPERATION = new Property<String>("operation");
	public static final Property<BigDecimal> OTHER_OFFSET = new Property<BigDecimal>("otherOffset");
	public static final Property<String> POSITION_KEY = new Property<String>("positionKey");
	public static final Property<String> TRADING_PERIOD = new Property<String>("tradingPeriod");
	public static final Property<String> USERID = new Property<String>("userid");
	public static final Property<BigDecimal> VOYAGE_OFFSET = new Property<BigDecimal>("voyageOffset");

	public void setActualPosition(BigDecimal actualPosition)
	{
		writeProperty("actualPosition", actualPosition);
	}

	public BigDecimal getActualPosition()
	{
		return (BigDecimal) readProperty("actualPosition");
	}

	public void setAdjustment(BigDecimal adjustment)
	{
		writeProperty("adjustment", adjustment);
	}

	public BigDecimal getAdjustment()
	{
		return (BigDecimal) readProperty("adjustment");
	}

	public void setContractKey(String contractKey)
	{
		writeProperty("contractKey", contractKey);
	}

	public String getContractKey()
	{
		return (String) readProperty("contractKey");
	}

	public void setDateOp(Date dateOp)
	{
		writeProperty("dateOp", dateOp);
	}

	public Date getDateOp()
	{
		return (Date) readProperty("dateOp");
	}

	public void setInitialPosition(BigDecimal initialPosition)
	{
		writeProperty("initialPosition", initialPosition);
	}

	public BigDecimal getInitialPosition()
	{
		return (BigDecimal) readProperty("initialPosition");
	}

	public void setLastRunDate(Date lastRunDate)
	{
		writeProperty("lastRunDate", lastRunDate);
	}

	public Date getLastRunDate()
	{
		return (Date) readProperty("lastRunDate");
	}

	public void setMonthYear(Date monthYear)
	{
		writeProperty("monthYear", monthYear);
	}

	public Date getMonthYear()
	{
		return (Date) readProperty("monthYear");
	}

	public void setOperation(String operation)
	{
		writeProperty("operation", operation);
	}

	public String getOperation()
	{
		return (String) readProperty("operation");
	}

	public void setOtherOffset(BigDecimal otherOffset)
	{
		writeProperty("otherOffset", otherOffset);
	}

	public BigDecimal getOtherOffset()
	{
		return (BigDecimal) readProperty("otherOffset");
	}

	public void setPositionKey(String positionKey)
	{
		writeProperty("positionKey", positionKey);
	}

	public String getPositionKey()
	{
		return (String) readProperty("positionKey");
	}

	public void setTradingPeriod(String tradingPeriod)
	{
		writeProperty("tradingPeriod", tradingPeriod);
	}

	public String getTradingPeriod()
	{
		return (String) readProperty("tradingPeriod");
	}

	public void setUserid(String userid)
	{
		writeProperty("userid", userid);
	}

	public String getUserid()
	{
		return (String) readProperty("userid");
	}

	public void setVoyageOffset(BigDecimal voyageOffset)
	{
		writeProperty("voyageOffset", voyageOffset);
	}

	public BigDecimal getVoyageOffset()
	{
		return (BigDecimal) readProperty("voyageOffset");
	}

}
