package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudCalendar was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudCalendar extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> CALENDAR_CODE = new Property<String>("calendarCode");
	public static final Property<String> CALENDAR_DATE_MASK = new Property<String>("calendarDateMask");
	public static final Property<String> CALENDAR_DESC = new Property<String>("calendarDesc");
	public static final Property<String> CALENDAR_NAME = new Property<String>("calendarName");
	public static final Property<String> CALENDAR_STATUS = new Property<String>("calendarStatus");
	public static final Property<String> CALENDAR_TYPE = new Property<String>("calendarType");
	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setCalendarCode(String calendarCode)
	{
		writeProperty("calendarCode", calendarCode);
	}

	public String getCalendarCode()
	{
		return (String) readProperty("calendarCode");
	}

	public void setCalendarDateMask(String calendarDateMask)
	{
		writeProperty("calendarDateMask", calendarDateMask);
	}

	public String getCalendarDateMask()
	{
		return (String) readProperty("calendarDateMask");
	}

	public void setCalendarDesc(String calendarDesc)
	{
		writeProperty("calendarDesc", calendarDesc);
	}

	public String getCalendarDesc()
	{
		return (String) readProperty("calendarDesc");
	}

	public void setCalendarName(String calendarName)
	{
		writeProperty("calendarName", calendarName);
	}

	public String getCalendarName()
	{
		return (String) readProperty("calendarName");
	}

	public void setCalendarStatus(String calendarStatus)
	{
		writeProperty("calendarStatus", calendarStatus);
	}

	public String getCalendarStatus()
	{
		return (String) readProperty("calendarStatus");
	}

	public void setCalendarType(String calendarType)
	{
		writeProperty("calendarType", calendarType);
	}

	public String getCalendarType()
	{
		return (String) readProperty("calendarType");
	}

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
