package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudQuote was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudQuote extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Integer> ID = new Property<Integer>("id");
	public static final Property<String> LOC_CODE = new Property<String>("locCode");
	public static final Property<Integer> PL_QMDS_ID = new Property<Integer>("plQmdsId");
	public static final Property<Integer> PRODUCT_ID = new Property<Integer>("productId");
	public static final Property<Integer> REPORT_QMDS_ID = new Property<Integer>("reportQmdsId");
	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<String> STATUS = new Property<String>("status");
	public static final Property<String> SYMBOL = new Property<String>("symbol");
	public static final Property<String> SYMBOL_REGEX = new Property<String>("symbolRegex");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Boolean> USE_FOR_PL = new Property<Boolean>("useForPl");
	public static final Property<Integer> VENUE_ID = new Property<Integer>("venueId");

	public void setId(Integer id)
	{
		writeProperty("id", id);
	}

	public Integer getId()
	{
		return (Integer) readProperty("id");
	}

	public void setLocCode(String locCode)
	{
		writeProperty("locCode", locCode);
	}

	public String getLocCode()
	{
		return (String) readProperty("locCode");
	}

	public void setPlQmdsId(Integer plQmdsId)
	{
		writeProperty("plQmdsId", plQmdsId);
	}

	public Integer getPlQmdsId()
	{
		return (Integer) readProperty("plQmdsId");
	}

	public void setProductId(Integer productId)
	{
		writeProperty("productId", productId);
	}

	public Integer getProductId()
	{
		return (Integer) readProperty("productId");
	}

	public void setReportQmdsId(Integer reportQmdsId)
	{
		writeProperty("reportQmdsId", reportQmdsId);
	}

	public Integer getReportQmdsId()
	{
		return (Integer) readProperty("reportQmdsId");
	}

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setStatus(String status)
	{
		writeProperty("status", status);
	}

	public String getStatus()
	{
		return (String) readProperty("status");
	}

	public void setSymbol(String symbol)
	{
		writeProperty("symbol", symbol);
	}

	public String getSymbol()
	{
		return (String) readProperty("symbol");
	}

	public void setSymbolRegex(String symbolRegex)
	{
		writeProperty("symbolRegex", symbolRegex);
	}

	public String getSymbolRegex()
	{
		return (String) readProperty("symbolRegex");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setUseForPl(Boolean useForPl)
	{
		writeProperty("useForPl", useForPl);
	}

	public Boolean getUseForPl()
	{
		return (Boolean) readProperty("useForPl");
	}

	public void setVenueId(Integer venueId)
	{
		writeProperty("venueId", venueId);
	}

	public Integer getVenueId()
	{
		return (Integer) readProperty("venueId");
	}

}
