package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudCargoTemplateTimesheet was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudCargoTemplateTimesheet extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Date> DATE_OP = new Property<Date>("dateOp");
	public static final Property<Integer> DISTANCE = new Property<Integer>("distance");
	public static final Property<Integer> DURATION_TO_NEXT_WP = new Property<Integer>("durationToNextWp");
	public static final Property<String> OPERATION = new Property<String>("operation");
	public static final Property<String> PORT_CODE = new Property<String>("portCode");
	public static final Property<BigDecimal> SPEED = new Property<BigDecimal>("speed");
	public static final Property<Integer> TEMPLATE_ID = new Property<Integer>("templateId");
	public static final Property<Integer> TIME_IN_PORT = new Property<Integer>("timeInPort");
	public static final Property<String> USERID = new Property<String>("userid");
	public static final Property<Integer> WAYPOINT_ORDER = new Property<Integer>("waypointOrder");
	public static final Property<String> WAYPOINT_TYPE = new Property<String>("waypointType");

	public void setDateOp(Date dateOp)
	{
		writeProperty("dateOp", dateOp);
	}

	public Date getDateOp()
	{
		return (Date) readProperty("dateOp");
	}

	public void setDistance(Integer distance)
	{
		writeProperty("distance", distance);
	}

	public Integer getDistance()
	{
		return (Integer) readProperty("distance");
	}

	public void setDurationToNextWp(Integer durationToNextWp)
	{
		writeProperty("durationToNextWp", durationToNextWp);
	}

	public Integer getDurationToNextWp()
	{
		return (Integer) readProperty("durationToNextWp");
	}

	public void setOperation(String operation)
	{
		writeProperty("operation", operation);
	}

	public String getOperation()
	{
		return (String) readProperty("operation");
	}

	public void setPortCode(String portCode)
	{
		writeProperty("portCode", portCode);
	}

	public String getPortCode()
	{
		return (String) readProperty("portCode");
	}

	public void setSpeed(BigDecimal speed)
	{
		writeProperty("speed", speed);
	}

	public BigDecimal getSpeed()
	{
		return (BigDecimal) readProperty("speed");
	}

	public void setTemplateId(Integer templateId)
	{
		writeProperty("templateId", templateId);
	}

	public Integer getTemplateId()
	{
		return (Integer) readProperty("templateId");
	}

	public void setTimeInPort(Integer timeInPort)
	{
		writeProperty("timeInPort", timeInPort);
	}

	public Integer getTimeInPort()
	{
		return (Integer) readProperty("timeInPort");
	}

	public void setUserid(String userid)
	{
		writeProperty("userid", userid);
	}

	public String getUserid()
	{
		return (String) readProperty("userid");
	}

	public void setWaypointOrder(Integer waypointOrder)
	{
		writeProperty("waypointOrder", waypointOrder);
	}

	public Integer getWaypointOrder()
	{
		return (Integer) readProperty("waypointOrder");
	}

	public void setWaypointType(String waypointType)
	{
		writeProperty("waypointType", waypointType);
	}

	public String getWaypointType()
	{
		return (String) readProperty("waypointType");
	}

}
