package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudAllocationChain was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudAllocationChain extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Integer> ACCT_NUM = new Property<Integer>("acctNum");
	public static final Property<Short> ALLOC_CHAIN_ACCT_SEQ_NUM = new Property<Short>("allocChainAcctSeqNum");
	public static final Property<Short> ALLOC_CHAIN_NUM = new Property<Short>("allocChainNum");
	public static final Property<Date> ALLOC_CONFIRMED_DATE = new Property<Date>("allocConfirmedDate");
	public static final Property<Integer> ALLOC_NUM = new Property<Integer>("allocNum");
	public static final Property<BigDecimal> CIRCLED_QTY = new Property<BigDecimal>("circledQty");
	public static final Property<String> CIRCLED_QTY_UOM_CODE = new Property<String>("circledQtyUomCode");
	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setAcctNum(Integer acctNum)
	{
		writeProperty("acctNum", acctNum);
	}

	public Integer getAcctNum()
	{
		return (Integer) readProperty("acctNum");
	}

	public void setAllocChainAcctSeqNum(Short allocChainAcctSeqNum)
	{
		writeProperty("allocChainAcctSeqNum", allocChainAcctSeqNum);
	}

	public Short getAllocChainAcctSeqNum()
	{
		return (Short) readProperty("allocChainAcctSeqNum");
	}

	public void setAllocChainNum(Short allocChainNum)
	{
		writeProperty("allocChainNum", allocChainNum);
	}

	public Short getAllocChainNum()
	{
		return (Short) readProperty("allocChainNum");
	}

	public void setAllocConfirmedDate(Date allocConfirmedDate)
	{
		writeProperty("allocConfirmedDate", allocConfirmedDate);
	}

	public Date getAllocConfirmedDate()
	{
		return (Date) readProperty("allocConfirmedDate");
	}

	public void setAllocNum(Integer allocNum)
	{
		writeProperty("allocNum", allocNum);
	}

	public Integer getAllocNum()
	{
		return (Integer) readProperty("allocNum");
	}

	public void setCircledQty(BigDecimal circledQty)
	{
		writeProperty("circledQty", circledQty);
	}

	public BigDecimal getCircledQty()
	{
		return (BigDecimal) readProperty("circledQty");
	}

	public void setCircledQtyUomCode(String circledQtyUomCode)
	{
		writeProperty("circledQtyUomCode", circledQtyUomCode);
	}

	public String getCircledQtyUomCode()
	{
		return (String) readProperty("circledQtyUomCode");
	}

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
