package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudIceTrade was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudIceTrade extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Date> BEGIN_DATE = new Property<Date>("beginDate");
	public static final Property<String> BUYER_COMPANY_NAME = new Property<String>("buyerCompanyName");
	public static final Property<String> BUYER_FIRST_NAME = new Property<String>("buyerFirstName");
	public static final Property<String> BUYER_LAST_NAME = new Property<String>("buyerLastName");
	public static final Property<String> BUYER_USER_ID = new Property<String>("buyerUserId");
	public static final Property<String> CLEARING_FIRM_NAME = new Property<String>("clearingFirmName");
	public static final Property<Date> CONSUMMATE_DATE = new Property<Date>("consummateDate");
	public static final Property<String> DEAL_ID = new Property<String>("dealId");
	public static final Property<Integer> DEAL_LOT_SIZE = new Property<Integer>("dealLotSize");
	public static final Property<Date> END_DATE = new Property<Date>("endDate");
	public static final Property<Integer> EXTERNAL_TRADE_OID = new Property<Integer>("externalTradeOid");
	public static final Property<String> HUB = new Property<String>("hub");
	public static final Property<Integer> MARKET_ID = new Property<Integer>("marketId");
	public static final Property<Integer> MARKET_LOT_SIZE = new Property<Integer>("marketLotSize");
	public static final Property<String> MKT_BPROD_CURRENCY = new Property<String>("mktBprodCurrency");
	public static final Property<String> MKT_BPROD_UNIT_PRICE = new Property<String>("mktBprodUnitPrice");
	public static final Property<String> MKT_BPROD_UNITS = new Property<String>("mktBprodUnits");
	public static final Property<Integer> NUMBER_OF_CYCLES = new Property<Integer>("numberOfCycles");
	public static final Property<String> ORDER_TYPE = new Property<String>("orderType");
	public static final Property<Double> PRICE = new Property<Double>("price");
	public static final Property<String> QTY_MULTIPLIED_OUT = new Property<String>("qtyMultipliedOut");
	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<String> SELLER_COMPANY_NAME = new Property<String>("sellerCompanyName");
	public static final Property<String> SELLER_FIRST_NAME = new Property<String>("sellerFirstName");
	public static final Property<String> SELLER_LAST_NAME = new Property<String>("sellerLastName");
	public static final Property<String> SELLER_USER_ID = new Property<String>("sellerUserId");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setBeginDate(Date beginDate)
	{
		writeProperty("beginDate", beginDate);
	}

	public Date getBeginDate()
	{
		return (Date) readProperty("beginDate");
	}

	public void setBuyerCompanyName(String buyerCompanyName)
	{
		writeProperty("buyerCompanyName", buyerCompanyName);
	}

	public String getBuyerCompanyName()
	{
		return (String) readProperty("buyerCompanyName");
	}

	public void setBuyerFirstName(String buyerFirstName)
	{
		writeProperty("buyerFirstName", buyerFirstName);
	}

	public String getBuyerFirstName()
	{
		return (String) readProperty("buyerFirstName");
	}

	public void setBuyerLastName(String buyerLastName)
	{
		writeProperty("buyerLastName", buyerLastName);
	}

	public String getBuyerLastName()
	{
		return (String) readProperty("buyerLastName");
	}

	public void setBuyerUserId(String buyerUserId)
	{
		writeProperty("buyerUserId", buyerUserId);
	}

	public String getBuyerUserId()
	{
		return (String) readProperty("buyerUserId");
	}

	public void setClearingFirmName(String clearingFirmName)
	{
		writeProperty("clearingFirmName", clearingFirmName);
	}

	public String getClearingFirmName()
	{
		return (String) readProperty("clearingFirmName");
	}

	public void setConsummateDate(Date consummateDate)
	{
		writeProperty("consummateDate", consummateDate);
	}

	public Date getConsummateDate()
	{
		return (Date) readProperty("consummateDate");
	}

	public void setDealId(String dealId)
	{
		writeProperty("dealId", dealId);
	}

	public String getDealId()
	{
		return (String) readProperty("dealId");
	}

	public void setDealLotSize(Integer dealLotSize)
	{
		writeProperty("dealLotSize", dealLotSize);
	}

	public Integer getDealLotSize()
	{
		return (Integer) readProperty("dealLotSize");
	}

	public void setEndDate(Date endDate)
	{
		writeProperty("endDate", endDate);
	}

	public Date getEndDate()
	{
		return (Date) readProperty("endDate");
	}

	public void setExternalTradeOid(Integer externalTradeOid)
	{
		writeProperty("externalTradeOid", externalTradeOid);
	}

	public Integer getExternalTradeOid()
	{
		return (Integer) readProperty("externalTradeOid");
	}

	public void setHub(String hub)
	{
		writeProperty("hub", hub);
	}

	public String getHub()
	{
		return (String) readProperty("hub");
	}

	public void setMarketId(Integer marketId)
	{
		writeProperty("marketId", marketId);
	}

	public Integer getMarketId()
	{
		return (Integer) readProperty("marketId");
	}

	public void setMarketLotSize(Integer marketLotSize)
	{
		writeProperty("marketLotSize", marketLotSize);
	}

	public Integer getMarketLotSize()
	{
		return (Integer) readProperty("marketLotSize");
	}

	public void setMktBprodCurrency(String mktBprodCurrency)
	{
		writeProperty("mktBprodCurrency", mktBprodCurrency);
	}

	public String getMktBprodCurrency()
	{
		return (String) readProperty("mktBprodCurrency");
	}

	public void setMktBprodUnitPrice(String mktBprodUnitPrice)
	{
		writeProperty("mktBprodUnitPrice", mktBprodUnitPrice);
	}

	public String getMktBprodUnitPrice()
	{
		return (String) readProperty("mktBprodUnitPrice");
	}

	public void setMktBprodUnits(String mktBprodUnits)
	{
		writeProperty("mktBprodUnits", mktBprodUnits);
	}

	public String getMktBprodUnits()
	{
		return (String) readProperty("mktBprodUnits");
	}

	public void setNumberOfCycles(Integer numberOfCycles)
	{
		writeProperty("numberOfCycles", numberOfCycles);
	}

	public Integer getNumberOfCycles()
	{
		return (Integer) readProperty("numberOfCycles");
	}

	public void setOrderType(String orderType)
	{
		writeProperty("orderType", orderType);
	}

	public String getOrderType()
	{
		return (String) readProperty("orderType");
	}

	public void setPrice(Double price)
	{
		writeProperty("price", price);
	}

	public Double getPrice()
	{
		return (Double) readProperty("price");
	}

	public void setQtyMultipliedOut(String qtyMultipliedOut)
	{
		writeProperty("qtyMultipliedOut", qtyMultipliedOut);
	}

	public String getQtyMultipliedOut()
	{
		return (String) readProperty("qtyMultipliedOut");
	}

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setSellerCompanyName(String sellerCompanyName)
	{
		writeProperty("sellerCompanyName", sellerCompanyName);
	}

	public String getSellerCompanyName()
	{
		return (String) readProperty("sellerCompanyName");
	}

	public void setSellerFirstName(String sellerFirstName)
	{
		writeProperty("sellerFirstName", sellerFirstName);
	}

	public String getSellerFirstName()
	{
		return (String) readProperty("sellerFirstName");
	}

	public void setSellerLastName(String sellerLastName)
	{
		writeProperty("sellerLastName", sellerLastName);
	}

	public String getSellerLastName()
	{
		return (String) readProperty("sellerLastName");
	}

	public void setSellerUserId(String sellerUserId)
	{
		writeProperty("sellerUserId", sellerUserId);
	}

	public String getSellerUserId()
	{
		return (String) readProperty("sellerUserId");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
