package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudCargoPositionPriceCurve was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudCargoPositionPriceCurve extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Date> DATE_OP = new Property<Date>("dateOp");
	public static final Property<Integer> ID = new Property<Integer>("id");
	public static final Property<BigDecimal> IFO_PRICE = new Property<BigDecimal>("ifoPrice");
	public static final Property<BigDecimal> MDO_PRICE = new Property<BigDecimal>("mdoPrice");
	public static final Property<String> OPERATION = new Property<String>("operation");
	public static final Property<Date> PRICE_DATE = new Property<Date>("priceDate");
	public static final Property<BigDecimal> PRICE_VALUE = new Property<BigDecimal>("priceValue");
	public static final Property<Integer> TEMPLATE_ID = new Property<Integer>("templateId");
	public static final Property<String> USERID = new Property<String>("userid");
	public static final Property<BigDecimal> VOYAGE_COST_DAY_PRICE = new Property<BigDecimal>("voyageCostDayPrice");

	public void setDateOp(Date dateOp)
	{
		writeProperty("dateOp", dateOp);
	}

	public Date getDateOp()
	{
		return (Date) readProperty("dateOp");
	}

	public void setId(Integer id)
	{
		writeProperty("id", id);
	}

	public Integer getId()
	{
		return (Integer) readProperty("id");
	}

	public void setIfoPrice(BigDecimal ifoPrice)
	{
		writeProperty("ifoPrice", ifoPrice);
	}

	public BigDecimal getIfoPrice()
	{
		return (BigDecimal) readProperty("ifoPrice");
	}

	public void setMdoPrice(BigDecimal mdoPrice)
	{
		writeProperty("mdoPrice", mdoPrice);
	}

	public BigDecimal getMdoPrice()
	{
		return (BigDecimal) readProperty("mdoPrice");
	}

	public void setOperation(String operation)
	{
		writeProperty("operation", operation);
	}

	public String getOperation()
	{
		return (String) readProperty("operation");
	}

	public void setPriceDate(Date priceDate)
	{
		writeProperty("priceDate", priceDate);
	}

	public Date getPriceDate()
	{
		return (Date) readProperty("priceDate");
	}

	public void setPriceValue(BigDecimal priceValue)
	{
		writeProperty("priceValue", priceValue);
	}

	public BigDecimal getPriceValue()
	{
		return (BigDecimal) readProperty("priceValue");
	}

	public void setTemplateId(Integer templateId)
	{
		writeProperty("templateId", templateId);
	}

	public Integer getTemplateId()
	{
		return (Integer) readProperty("templateId");
	}

	public void setUserid(String userid)
	{
		writeProperty("userid", userid);
	}

	public String getUserid()
	{
		return (String) readProperty("userid");
	}

	public void setVoyageCostDayPrice(BigDecimal voyageCostDayPrice)
	{
		writeProperty("voyageCostDayPrice", voyageCostDayPrice);
	}

	public BigDecimal getVoyageCostDayPrice()
	{
		return (BigDecimal) readProperty("voyageCostDayPrice");
	}

}
