package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudFxLinking was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudFxLinking extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> FROM_CURR_CODE = new Property<String>("fromCurrCode");
	public static final Property<BigDecimal> FX_LINK_RATE = new Property<BigDecimal>("fxLinkRate");
	public static final Property<String> FX_RATE_MDIND = new Property<String>("fxRateMDInd");
	public static final Property<String> NEED_RATE_COMPUTATION = new Property<String>("needRateComputation");
	public static final Property<Integer> OID = new Property<Integer>("oid");
	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<String> TO_CURR_CODE = new Property<String>("toCurrCode");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setFromCurrCode(String fromCurrCode)
	{
		writeProperty("fromCurrCode", fromCurrCode);
	}

	public String getFromCurrCode()
	{
		return (String) readProperty("fromCurrCode");
	}

	public void setFxLinkRate(BigDecimal fxLinkRate)
	{
		writeProperty("fxLinkRate", fxLinkRate);
	}

	public BigDecimal getFxLinkRate()
	{
		return (BigDecimal) readProperty("fxLinkRate");
	}

	public void setFxRateMDInd(String fxRateMDInd)
	{
		writeProperty("fxRateMDInd", fxRateMDInd);
	}

	public String getFxRateMDInd()
	{
		return (String) readProperty("fxRateMDInd");
	}

	public void setNeedRateComputation(String needRateComputation)
	{
		writeProperty("needRateComputation", needRateComputation);
	}

	public String getNeedRateComputation()
	{
		return (String) readProperty("needRateComputation");
	}

	public void setOid(Integer oid)
	{
		writeProperty("oid", oid);
	}

	public Integer getOid()
	{
		return (Integer) readProperty("oid");
	}

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setToCurrCode(String toCurrCode)
	{
		writeProperty("toCurrCode", toCurrCode);
	}

	public String getToCurrCode()
	{
		return (String) readProperty("toCurrCode");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
