package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _AudWbContractBunkers was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AudWbContractBunkers extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Integer> ACCOUNT_DELIVERER = new Property<Integer>("accountDeliverer");
	public static final Property<BigDecimal> ADDITIONAL_SERVICES = new Property<BigDecimal>("additionalServices");
	public static final Property<Date> DATE_OP = new Property<Date>("dateOp");
	public static final Property<String> FLDBOL_ROB = new Property<String>("fldbolRob");
	public static final Property<Integer> FLDCHR_BUNKER_OP_KEY = new Property<Integer>("fldchrBunkerOpKey");
	public static final Property<String> FLDCHR_CMDTY_CODE = new Property<String>("fldchrCmdtyCode");
	public static final Property<String> FLDCHR_CMDTY_UOM = new Property<String>("fldchrCmdtyUom");
	public static final Property<String> FLDCHR_CONTR_KEY = new Property<String>("fldchrContrKey");
	public static final Property<String> FLDCHR_PRICE_UOM = new Property<String>("fldchrPriceUom");
	public static final Property<String> FLDCHR_TEXT = new Property<String>("fldchrText");
	public static final Property<String> FLDCHR_USER_NAME = new Property<String>("fldchrUserName");
	public static final Property<BigDecimal> FLDDBL_CMDTY_QTY = new Property<BigDecimal>("flddblCmdtyQty");
	public static final Property<BigDecimal> FLDDBL_PRICE = new Property<BigDecimal>("flddblPrice");
	public static final Property<Double> FLDFLO_CONVERSION_RATE_VALUE = new Property<Double>("fldfloConversionRateValue");
	public static final Property<Integer> FLDINT_COST_NUM = new Property<Integer>("fldintCostNum");
	public static final Property<Date> FLDSDT_TIME_STAMP = new Property<Date>("fldsdtTimeStamp");
	public static final Property<Date> FLDSDT_TIMEOFOPS = new Property<Date>("fldsdtTimeofops");
	public static final Property<String> OPERATION = new Property<String>("operation");
	public static final Property<String> PORT_CODE = new Property<String>("portCode");
	public static final Property<String> USERID = new Property<String>("userid");

	public void setAccountDeliverer(Integer accountDeliverer)
	{
		writeProperty("accountDeliverer", accountDeliverer);
	}

	public Integer getAccountDeliverer()
	{
		return (Integer) readProperty("accountDeliverer");
	}

	public void setAdditionalServices(BigDecimal additionalServices)
	{
		writeProperty("additionalServices", additionalServices);
	}

	public BigDecimal getAdditionalServices()
	{
		return (BigDecimal) readProperty("additionalServices");
	}

	public void setDateOp(Date dateOp)
	{
		writeProperty("dateOp", dateOp);
	}

	public Date getDateOp()
	{
		return (Date) readProperty("dateOp");
	}

	public void setFldbolRob(String fldbolRob)
	{
		writeProperty("fldbolRob", fldbolRob);
	}

	public String getFldbolRob()
	{
		return (String) readProperty("fldbolRob");
	}

	public void setFldchrBunkerOpKey(Integer fldchrBunkerOpKey)
	{
		writeProperty("fldchrBunkerOpKey", fldchrBunkerOpKey);
	}

	public Integer getFldchrBunkerOpKey()
	{
		return (Integer) readProperty("fldchrBunkerOpKey");
	}

	public void setFldchrCmdtyCode(String fldchrCmdtyCode)
	{
		writeProperty("fldchrCmdtyCode", fldchrCmdtyCode);
	}

	public String getFldchrCmdtyCode()
	{
		return (String) readProperty("fldchrCmdtyCode");
	}

	public void setFldchrCmdtyUom(String fldchrCmdtyUom)
	{
		writeProperty("fldchrCmdtyUom", fldchrCmdtyUom);
	}

	public String getFldchrCmdtyUom()
	{
		return (String) readProperty("fldchrCmdtyUom");
	}

	public void setFldchrContrKey(String fldchrContrKey)
	{
		writeProperty("fldchrContrKey", fldchrContrKey);
	}

	public String getFldchrContrKey()
	{
		return (String) readProperty("fldchrContrKey");
	}

	public void setFldchrPriceUom(String fldchrPriceUom)
	{
		writeProperty("fldchrPriceUom", fldchrPriceUom);
	}

	public String getFldchrPriceUom()
	{
		return (String) readProperty("fldchrPriceUom");
	}

	public void setFldchrText(String fldchrText)
	{
		writeProperty("fldchrText", fldchrText);
	}

	public String getFldchrText()
	{
		return (String) readProperty("fldchrText");
	}

	public void setFldchrUserName(String fldchrUserName)
	{
		writeProperty("fldchrUserName", fldchrUserName);
	}

	public String getFldchrUserName()
	{
		return (String) readProperty("fldchrUserName");
	}

	public void setFlddblCmdtyQty(BigDecimal flddblCmdtyQty)
	{
		writeProperty("flddblCmdtyQty", flddblCmdtyQty);
	}

	public BigDecimal getFlddblCmdtyQty()
	{
		return (BigDecimal) readProperty("flddblCmdtyQty");
	}

	public void setFlddblPrice(BigDecimal flddblPrice)
	{
		writeProperty("flddblPrice", flddblPrice);
	}

	public BigDecimal getFlddblPrice()
	{
		return (BigDecimal) readProperty("flddblPrice");
	}

	public void setFldfloConversionRateValue(Double fldfloConversionRateValue)
	{
		writeProperty("fldfloConversionRateValue", fldfloConversionRateValue);
	}

	public Double getFldfloConversionRateValue()
	{
		return (Double) readProperty("fldfloConversionRateValue");
	}

	public void setFldintCostNum(Integer fldintCostNum)
	{
		writeProperty("fldintCostNum", fldintCostNum);
	}

	public Integer getFldintCostNum()
	{
		return (Integer) readProperty("fldintCostNum");
	}

	public void setFldsdtTimeStamp(Date fldsdtTimeStamp)
	{
		writeProperty("fldsdtTimeStamp", fldsdtTimeStamp);
	}

	public Date getFldsdtTimeStamp()
	{
		return (Date) readProperty("fldsdtTimeStamp");
	}

	public void setFldsdtTimeofops(Date fldsdtTimeofops)
	{
		writeProperty("fldsdtTimeofops", fldsdtTimeofops);
	}

	public Date getFldsdtTimeofops()
	{
		return (Date) readProperty("fldsdtTimeofops");
	}

	public void setOperation(String operation)
	{
		writeProperty("operation", operation);
	}

	public String getOperation()
	{
		return (String) readProperty("operation");
	}

	public void setPortCode(String portCode)
	{
		writeProperty("portCode", portCode);
	}

	public String getPortCode()
	{
		return (String) readProperty("portCode");
	}

	public void setUserid(String userid)
	{
		writeProperty("userid", userid);
	}

	public String getUserid()
	{
		return (String) readProperty("userid");
	}

}
