package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.LcType;

/**
 * Class _BankExposure was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BankExposure extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String BANK_EXP_NUM_PK_COLUMN = "bank_exp_num";

	public static final Property<Double> BANK_EXP_AMT = new Property<Double>("bankExpAmt");
	public static final Property<Date> BANK_EXP_DATE = new Property<Date>("bankExpDate");
	public static final Property<String> BANK_EXP_IMP_EXP_IND = new Property<String>("bankExpImpExpInd");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Account> ACCOUNT = new Property<Account>("account");
	public static final Property<Account> ACCOUNT1 = new Property<Account>("account1");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<LcType> LC_TYPE = new Property<LcType>("lcType");

	public void setBankExpAmt(Double bankExpAmt)
	{
		writeProperty("bankExpAmt", bankExpAmt);
	}

	public Double getBankExpAmt()
	{
		return (Double) readProperty("bankExpAmt");
	}

	public void setBankExpDate(Date bankExpDate)
	{
		writeProperty("bankExpDate", bankExpDate);
	}

	public Date getBankExpDate()
	{
		return (Date) readProperty("bankExpDate");
	}

	public void setBankExpImpExpInd(String bankExpImpExpInd)
	{
		writeProperty("bankExpImpExpInd", bankExpImpExpInd);
	}

	public String getBankExpImpExpInd()
	{
		return (String) readProperty("bankExpImpExpInd");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setAccount(Account account)
	{
		setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) readProperty("account");
	}

	public void setAccount1(Account account1)
	{
		setToOneTarget("account1", account1, true);
	}

	public Account getAccount1()
	{
		return (Account) readProperty("account1");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setLcType(LcType lcType)
	{
		setToOneTarget("lcType", lcType, true);
	}

	public LcType getLcType()
	{
		return (LcType) readProperty("lcType");
	}

}
