package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _BrokerInfo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BrokerInfo extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ACCT_NUM_PK_COLUMN = "acct_num";

	public static final Property<Double> DFLT_COMM_AMT = new Property<Double>("dfltCommAmt");
	public static final Property<String> DFLT_COMM_CURR_CODE = new Property<String>("dfltCommCurrCode");
	public static final Property<String> DFLT_COMM_UOM_CODE = new Property<String>("dfltCommUomCode");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setDfltCommAmt(Double dfltCommAmt)
	{
		writeProperty("dfltCommAmt", dfltCommAmt);
	}

	public Double getDfltCommAmt()
	{
		return (Double) readProperty("dfltCommAmt");
	}

	public void setDfltCommCurrCode(String dfltCommCurrCode)
	{
		writeProperty("dfltCommCurrCode", dfltCommCurrCode);
	}

	public String getDfltCommCurrCode()
	{
		return (String) readProperty("dfltCommCurrCode");
	}

	public void setDfltCommUomCode(String dfltCommUomCode)
	{
		writeProperty("dfltCommUomCode", dfltCommUomCode);
	}

	public String getDfltCommUomCode()
	{
		return (String) readProperty("dfltCommUomCode");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
