package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.BusCostFateDate;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Cost;

/**
 * Class _BusCostFate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BusCostFate extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String BC_FATE_NUM_PK_COLUMN = "bc_fate_num";

	public static final Property<String> BC_FATE_CODE = new Property<String>("bcFateCode");
	public static final Property<String> BC_FATE_DESC = new Property<String>("bcFateDesc");
	public static final Property<String> BC_FATE_FULL_NAME = new Property<String>("bcFateFullName");
	public static final Property<String> BC_FATE_GROUP_CODE = new Property<String>("bcFateGroupCode");
	public static final Property<String> BC_FATE_MAN_AUTO_IND = new Property<String>("bcFateManAutoInd");
	public static final Property<Short> BC_FATE_PAY_DAYS = new Property<Short>("bcFatePayDays");
	public static final Property<String> BC_FATE_PROC_SPEC = new Property<String>("bcFateProcSpec");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<BusCostFateDate> BUS_COST_FATE_DATE = new Property<BusCostFateDate>("busCostFateDate");
	public static final Property<List<Cost>> COSTS = new Property<List<Cost>>("costs");

	public void setBcFateCode(String bcFateCode)
	{
		writeProperty("bcFateCode", bcFateCode);
	}

	public String getBcFateCode()
	{
		return (String) readProperty("bcFateCode");
	}

	public void setBcFateDesc(String bcFateDesc)
	{
		writeProperty("bcFateDesc", bcFateDesc);
	}

	public String getBcFateDesc()
	{
		return (String) readProperty("bcFateDesc");
	}

	public void setBcFateFullName(String bcFateFullName)
	{
		writeProperty("bcFateFullName", bcFateFullName);
	}

	public String getBcFateFullName()
	{
		return (String) readProperty("bcFateFullName");
	}

	public void setBcFateGroupCode(String bcFateGroupCode)
	{
		writeProperty("bcFateGroupCode", bcFateGroupCode);
	}

	public String getBcFateGroupCode()
	{
		return (String) readProperty("bcFateGroupCode");
	}

	public void setBcFateManAutoInd(String bcFateManAutoInd)
	{
		writeProperty("bcFateManAutoInd", bcFateManAutoInd);
	}

	public String getBcFateManAutoInd()
	{
		return (String) readProperty("bcFateManAutoInd");
	}

	public void setBcFatePayDays(Short bcFatePayDays)
	{
		writeProperty("bcFatePayDays", bcFatePayDays);
	}

	public Short getBcFatePayDays()
	{
		return (Short) readProperty("bcFatePayDays");
	}

	public void setBcFateProcSpec(String bcFateProcSpec)
	{
		writeProperty("bcFateProcSpec", bcFateProcSpec);
	}

	public String getBcFateProcSpec()
	{
		return (String) readProperty("bcFateProcSpec");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setBusCostFateDate(BusCostFateDate busCostFateDate)
	{
		setToOneTarget("busCostFateDate", busCostFateDate, true);
	}

	public BusCostFateDate getBusCostFateDate()
	{
		return (BusCostFateDate) readProperty("busCostFateDate");
	}

	public void addToCosts(Cost obj)
	{
		addToManyTarget("costs", obj, true);
	}

	public void removeFromCosts(Cost obj)
	{
		removeToManyTarget("costs", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<Cost> getCosts()
	{
		return (List<Cost>) readProperty("costs");
	}

}
