package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.BusCostType;
import com.tc.app.exchangemonitor.model.cayenne.persistent.OrderTypeGrpDesc;

/**
 * Class _BusCostOrderGroup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BusCostOrderGroup extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String BC_TYPE_NUM_PK_COLUMN = "bc_type_num";

	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<BusCostType> BUS_COST_TYPE = new Property<BusCostType>("busCostType");
	public static final Property<OrderTypeGrpDesc> ORDER_TYPE_GRP_DESC = new Property<OrderTypeGrpDesc>("orderTypeGrpDesc");

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setBusCostType(BusCostType busCostType)
	{
		setToOneTarget("busCostType", busCostType, true);
	}

	public BusCostType getBusCostType()
	{
		return (BusCostType) readProperty("busCostType");
	}

	public void setOrderTypeGrpDesc(OrderTypeGrpDesc orderTypeGrpDesc)
	{
		setToOneTarget("orderTypeGrpDesc", orderTypeGrpDesc, true);
	}

	public OrderTypeGrpDesc getOrderTypeGrpDesc()
	{
		return (OrderTypeGrpDesc) readProperty("orderTypeGrpDesc");
	}

}
