package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Contexts;
import com.tc.app.exchangemonitor.model.cayenne.persistent.QualityAssessments;

/**
 * Class _CargoInspection was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CargoInspection extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_ASSMT_PHASE_FLAG_PK_COLUMN = "fldchrAssmtPhaseFlag";
	public static final String FLDCHR_OP_KEY_PK_COLUMN = "fldchrOpKey";
	public static final String FLDINT_INSP_COMP_ACCT_NUM_PK_COLUMN = "fldintInspCompAcctNum";

	public static final Property<String> FLDCHR_DENSITY_UMCODE = new Property<String>("fldchrDensityUMCode");
	public static final Property<String> FLDCHR_INSP_TYPE_ID = new Property<String>("fldchrInspTypeId");
	public static final Property<String> FLDCHR_TEMP_UMCODE = new Property<String>("fldchrTempUMCode");
	public static final Property<BigDecimal> FLDDEC_API_DEGREE = new Property<BigDecimal>("flddecApiDegree");
	public static final Property<BigDecimal> FLDDEC_DENSITY = new Property<BigDecimal>("flddecDensity");
	public static final Property<BigDecimal> FLDDEC_GRS_QTY_BLL = new Property<BigDecimal>("flddecGrsQtyBLL");
	public static final Property<BigDecimal> FLDDEC_GRS_QTY_MTQ = new Property<BigDecimal>("flddecGrsQtyMTQ");
	public static final Property<BigDecimal> FLDDEC_GRS_QTY_TNE = new Property<BigDecimal>("flddecGrsQtyTNE");
	public static final Property<BigDecimal> FLDDEC_NET_QTY_BLL = new Property<BigDecimal>("flddecNetQtyBLL");
	public static final Property<BigDecimal> FLDDEC_NET_QTY_MTQ = new Property<BigDecimal>("flddecNetQtyMTQ");
	public static final Property<BigDecimal> FLDDEC_NET_QTY_TNE = new Property<BigDecimal>("flddecNetQtyTNE");
	public static final Property<BigDecimal> FLDDEC_TEMP = new Property<BigDecimal>("flddecTemp");
	public static final Property<Date> FLDSDT_INSP_END = new Property<Date>("fldsdtInspEnd");
	public static final Property<Date> FLDSDT_INSP_START = new Property<Date>("fldsdtInspStart");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Contexts> FLDCHR_CONTEXT = new Property<Contexts>("fldchrContext");
	public static final Property<List<QualityAssessments>> QUALITY_ASSESSMENTSS = new Property<List<QualityAssessments>>("qualityAssessmentss");

	public void setFldchrDensityUMCode(String fldchrDensityUMCode)
	{
		writeProperty("fldchrDensityUMCode", fldchrDensityUMCode);
	}

	public String getFldchrDensityUMCode()
	{
		return (String) readProperty("fldchrDensityUMCode");
	}

	public void setFldchrInspTypeId(String fldchrInspTypeId)
	{
		writeProperty("fldchrInspTypeId", fldchrInspTypeId);
	}

	public String getFldchrInspTypeId()
	{
		return (String) readProperty("fldchrInspTypeId");
	}

	public void setFldchrTempUMCode(String fldchrTempUMCode)
	{
		writeProperty("fldchrTempUMCode", fldchrTempUMCode);
	}

	public String getFldchrTempUMCode()
	{
		return (String) readProperty("fldchrTempUMCode");
	}

	public void setFlddecApiDegree(BigDecimal flddecApiDegree)
	{
		writeProperty("flddecApiDegree", flddecApiDegree);
	}

	public BigDecimal getFlddecApiDegree()
	{
		return (BigDecimal) readProperty("flddecApiDegree");
	}

	public void setFlddecDensity(BigDecimal flddecDensity)
	{
		writeProperty("flddecDensity", flddecDensity);
	}

	public BigDecimal getFlddecDensity()
	{
		return (BigDecimal) readProperty("flddecDensity");
	}

	public void setFlddecGrsQtyBLL(BigDecimal flddecGrsQtyBLL)
	{
		writeProperty("flddecGrsQtyBLL", flddecGrsQtyBLL);
	}

	public BigDecimal getFlddecGrsQtyBLL()
	{
		return (BigDecimal) readProperty("flddecGrsQtyBLL");
	}

	public void setFlddecGrsQtyMTQ(BigDecimal flddecGrsQtyMTQ)
	{
		writeProperty("flddecGrsQtyMTQ", flddecGrsQtyMTQ);
	}

	public BigDecimal getFlddecGrsQtyMTQ()
	{
		return (BigDecimal) readProperty("flddecGrsQtyMTQ");
	}

	public void setFlddecGrsQtyTNE(BigDecimal flddecGrsQtyTNE)
	{
		writeProperty("flddecGrsQtyTNE", flddecGrsQtyTNE);
	}

	public BigDecimal getFlddecGrsQtyTNE()
	{
		return (BigDecimal) readProperty("flddecGrsQtyTNE");
	}

	public void setFlddecNetQtyBLL(BigDecimal flddecNetQtyBLL)
	{
		writeProperty("flddecNetQtyBLL", flddecNetQtyBLL);
	}

	public BigDecimal getFlddecNetQtyBLL()
	{
		return (BigDecimal) readProperty("flddecNetQtyBLL");
	}

	public void setFlddecNetQtyMTQ(BigDecimal flddecNetQtyMTQ)
	{
		writeProperty("flddecNetQtyMTQ", flddecNetQtyMTQ);
	}

	public BigDecimal getFlddecNetQtyMTQ()
	{
		return (BigDecimal) readProperty("flddecNetQtyMTQ");
	}

	public void setFlddecNetQtyTNE(BigDecimal flddecNetQtyTNE)
	{
		writeProperty("flddecNetQtyTNE", flddecNetQtyTNE);
	}

	public BigDecimal getFlddecNetQtyTNE()
	{
		return (BigDecimal) readProperty("flddecNetQtyTNE");
	}

	public void setFlddecTemp(BigDecimal flddecTemp)
	{
		writeProperty("flddecTemp", flddecTemp);
	}

	public BigDecimal getFlddecTemp()
	{
		return (BigDecimal) readProperty("flddecTemp");
	}

	public void setFldsdtInspEnd(Date fldsdtInspEnd)
	{
		writeProperty("fldsdtInspEnd", fldsdtInspEnd);
	}

	public Date getFldsdtInspEnd()
	{
		return (Date) readProperty("fldsdtInspEnd");
	}

	public void setFldsdtInspStart(Date fldsdtInspStart)
	{
		writeProperty("fldsdtInspStart", fldsdtInspStart);
	}

	public Date getFldsdtInspStart()
	{
		return (Date) readProperty("fldsdtInspStart");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setFldchrContext(Contexts fldchrContext)
	{
		setToOneTarget("fldchrContext", fldchrContext, true);
	}

	public Contexts getFldchrContext()
	{
		return (Contexts) readProperty("fldchrContext");
	}

	public void addToQualityAssessmentss(QualityAssessments obj)
	{
		addToManyTarget("qualityAssessmentss", obj, true);
	}

	public void removeFromQualityAssessmentss(QualityAssessments obj)
	{
		removeToManyTarget("qualityAssessmentss", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<QualityAssessments> getQualityAssessmentss()
	{
		return (List<QualityAssessments>) readProperty("qualityAssessmentss");
	}

}
