package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.ShipSpeedConsumption;

/**
 * Class _ClarksonShipParticulars was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ClarksonShipParticulars extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_LLOYDS_REF_NUM_PK_COLUMN = "fldchrLloydsRefNum";

	public static final Property<Double> BEN_OWNER_ID = new Property<Double>("benOwnerId");
	public static final Property<String> BEN_OWNERS_ADD_R02SHORT_NAME = new Property<String>("benOwnersAddR02ShortName");
	public static final Property<Double> BREADTH_M = new Property<Double>("breadthM");
	public static final Property<String> CARGO_BARRELS_NO = new Property<String>("cargoBarrelsNo");
	public static final Property<Double> CARGO_CAP_CU_M = new Property<Double>("cargoCapCuM");
	public static final Property<String> CLASS_SOC1CODE = new Property<String>("classSoc1Code");
	public static final Property<String> CLEAN_BALLAST_TANKS_IND = new Property<String>("cleanBallastTanksInd");
	public static final Property<String> COATED_EPOXY_IND = new Property<String>("coatedEpoxyInd");
	public static final Property<String> COATED_POLY_TANKS_IND = new Property<String>("coatedPolyTanksInd");
	public static final Property<String> COATED_ZINC_TANKS_IND = new Property<String>("coatedZincTanksInd");
	public static final Property<String> CURRENT_NAME = new Property<String>("currentName");
	public static final Property<Double> DRAFT_M = new Property<Double>("draftM");
	public static final Property<Double> DWT_TONNES = new Property<Double>("dwtTonnes");
	public static final Property<String> EXNAME = new Property<String>("exname");
	public static final Property<String> FLAG_CODE = new Property<String>("flagCode");
	public static final Property<Double> GT = new Property<Double>("gt");
	public static final Property<Double> HP_TOTAL = new Property<Double>("hpTotal");
	public static final Property<String> HULL_TYPE_IND = new Property<String>("hullTypeInd");
	public static final Property<String> ICE_CLASS_IND = new Property<String>("iceClassInd");
	public static final Property<Double> IMMERSION_TONNES_PER_CM = new Property<Double>("immersionTonnesPerCm");
	public static final Property<String> IMO_CLASS1IND = new Property<String>("imoClass1Ind");
	public static final Property<String> IMO_CLASS2IND = new Property<String>("imoClass2Ind");
	public static final Property<String> IMO_CLASS3IND = new Property<String>("imoClass3Ind");
	public static final Property<Double> IMO_NUMBER = new Property<Double>("imoNumber");
	public static final Property<Double> LBP_M = new Property<Double>("lbpM");
	public static final Property<Double> LOA_M = new Property<Double>("loaM");
	public static final Property<String> MAIN_ENGINE_MAKE = new Property<String>("mainEngineMake");
	public static final Property<Double> MAIN_FUEL_CONSUMPTION_TPD = new Property<Double>("mainFuelConsumptionTpd");
	public static final Property<Double> PUMP_CAP_CU_M = new Property<Double>("pumpCapCuM");
	public static final Property<Double> PUMPS_TOTAL_NO = new Property<Double>("pumpsTotalNo");
	public static final Property<String> SEGREGATED_BALLAST_TANKS_IND = new Property<String>("segregatedBallastTanksInd");
	public static final Property<String> SHIP_BUILDERS_ADD_P01YARD = new Property<String>("shipBuildersAddP01Yard");
	public static final Property<Double> SPEED_KNOTS = new Property<Double>("speedKnots");
	public static final Property<String> STAINLESS_TANKS_IND = new Property<String>("stainlessTanksInd");
	public static final Property<Double> SUEZ_NT = new Property<Double>("suezNt");
	public static final Property<Double> TANKS_TOTAL_NO = new Property<Double>("tanksTotalNo");
	public static final Property<String> VESSEL_TYPE = new Property<String>("vesselType");
	public static final Property<Double> YEAR_BUILT = new Property<Double>("yearBuilt");
	public static final Property<List<ShipSpeedConsumption>> SHIP_SPEED_CONSUMPTIONS = new Property<List<ShipSpeedConsumption>>("shipSpeedConsumptions");

	public void setBenOwnerId(Double benOwnerId)
	{
		writeProperty("benOwnerId", benOwnerId);
	}

	public Double getBenOwnerId()
	{
		return (Double) readProperty("benOwnerId");
	}

	public void setBenOwnersAddR02ShortName(String benOwnersAddR02ShortName)
	{
		writeProperty("benOwnersAddR02ShortName", benOwnersAddR02ShortName);
	}

	public String getBenOwnersAddR02ShortName()
	{
		return (String) readProperty("benOwnersAddR02ShortName");
	}

	public void setBreadthM(Double breadthM)
	{
		writeProperty("breadthM", breadthM);
	}

	public Double getBreadthM()
	{
		return (Double) readProperty("breadthM");
	}

	public void setCargoBarrelsNo(String cargoBarrelsNo)
	{
		writeProperty("cargoBarrelsNo", cargoBarrelsNo);
	}

	public String getCargoBarrelsNo()
	{
		return (String) readProperty("cargoBarrelsNo");
	}

	public void setCargoCapCuM(Double cargoCapCuM)
	{
		writeProperty("cargoCapCuM", cargoCapCuM);
	}

	public Double getCargoCapCuM()
	{
		return (Double) readProperty("cargoCapCuM");
	}

	public void setClassSoc1Code(String classSoc1Code)
	{
		writeProperty("classSoc1Code", classSoc1Code);
	}

	public String getClassSoc1Code()
	{
		return (String) readProperty("classSoc1Code");
	}

	public void setCleanBallastTanksInd(String cleanBallastTanksInd)
	{
		writeProperty("cleanBallastTanksInd", cleanBallastTanksInd);
	}

	public String getCleanBallastTanksInd()
	{
		return (String) readProperty("cleanBallastTanksInd");
	}

	public void setCoatedEpoxyInd(String coatedEpoxyInd)
	{
		writeProperty("coatedEpoxyInd", coatedEpoxyInd);
	}

	public String getCoatedEpoxyInd()
	{
		return (String) readProperty("coatedEpoxyInd");
	}

	public void setCoatedPolyTanksInd(String coatedPolyTanksInd)
	{
		writeProperty("coatedPolyTanksInd", coatedPolyTanksInd);
	}

	public String getCoatedPolyTanksInd()
	{
		return (String) readProperty("coatedPolyTanksInd");
	}

	public void setCoatedZincTanksInd(String coatedZincTanksInd)
	{
		writeProperty("coatedZincTanksInd", coatedZincTanksInd);
	}

	public String getCoatedZincTanksInd()
	{
		return (String) readProperty("coatedZincTanksInd");
	}

	public void setCurrentName(String currentName)
	{
		writeProperty("currentName", currentName);
	}

	public String getCurrentName()
	{
		return (String) readProperty("currentName");
	}

	public void setDraftM(Double draftM)
	{
		writeProperty("draftM", draftM);
	}

	public Double getDraftM()
	{
		return (Double) readProperty("draftM");
	}

	public void setDwtTonnes(Double dwtTonnes)
	{
		writeProperty("dwtTonnes", dwtTonnes);
	}

	public Double getDwtTonnes()
	{
		return (Double) readProperty("dwtTonnes");
	}

	public void setExname(String exname)
	{
		writeProperty("exname", exname);
	}

	public String getExname()
	{
		return (String) readProperty("exname");
	}

	public void setFlagCode(String flagCode)
	{
		writeProperty("flagCode", flagCode);
	}

	public String getFlagCode()
	{
		return (String) readProperty("flagCode");
	}

	public void setGt(Double gt)
	{
		writeProperty("gt", gt);
	}

	public Double getGt()
	{
		return (Double) readProperty("gt");
	}

	public void setHpTotal(Double hpTotal)
	{
		writeProperty("hpTotal", hpTotal);
	}

	public Double getHpTotal()
	{
		return (Double) readProperty("hpTotal");
	}

	public void setHullTypeInd(String hullTypeInd)
	{
		writeProperty("hullTypeInd", hullTypeInd);
	}

	public String getHullTypeInd()
	{
		return (String) readProperty("hullTypeInd");
	}

	public void setIceClassInd(String iceClassInd)
	{
		writeProperty("iceClassInd", iceClassInd);
	}

	public String getIceClassInd()
	{
		return (String) readProperty("iceClassInd");
	}

	public void setImmersionTonnesPerCm(Double immersionTonnesPerCm)
	{
		writeProperty("immersionTonnesPerCm", immersionTonnesPerCm);
	}

	public Double getImmersionTonnesPerCm()
	{
		return (Double) readProperty("immersionTonnesPerCm");
	}

	public void setImoClass1Ind(String imoClass1Ind)
	{
		writeProperty("imoClass1Ind", imoClass1Ind);
	}

	public String getImoClass1Ind()
	{
		return (String) readProperty("imoClass1Ind");
	}

	public void setImoClass2Ind(String imoClass2Ind)
	{
		writeProperty("imoClass2Ind", imoClass2Ind);
	}

	public String getImoClass2Ind()
	{
		return (String) readProperty("imoClass2Ind");
	}

	public void setImoClass3Ind(String imoClass3Ind)
	{
		writeProperty("imoClass3Ind", imoClass3Ind);
	}

	public String getImoClass3Ind()
	{
		return (String) readProperty("imoClass3Ind");
	}

	public void setImoNumber(Double imoNumber)
	{
		writeProperty("imoNumber", imoNumber);
	}

	public Double getImoNumber()
	{
		return (Double) readProperty("imoNumber");
	}

	public void setLbpM(Double lbpM)
	{
		writeProperty("lbpM", lbpM);
	}

	public Double getLbpM()
	{
		return (Double) readProperty("lbpM");
	}

	public void setLoaM(Double loaM)
	{
		writeProperty("loaM", loaM);
	}

	public Double getLoaM()
	{
		return (Double) readProperty("loaM");
	}

	public void setMainEngineMake(String mainEngineMake)
	{
		writeProperty("mainEngineMake", mainEngineMake);
	}

	public String getMainEngineMake()
	{
		return (String) readProperty("mainEngineMake");
	}

	public void setMainFuelConsumptionTpd(Double mainFuelConsumptionTpd)
	{
		writeProperty("mainFuelConsumptionTpd", mainFuelConsumptionTpd);
	}

	public Double getMainFuelConsumptionTpd()
	{
		return (Double) readProperty("mainFuelConsumptionTpd");
	}

	public void setPumpCapCuM(Double pumpCapCuM)
	{
		writeProperty("pumpCapCuM", pumpCapCuM);
	}

	public Double getPumpCapCuM()
	{
		return (Double) readProperty("pumpCapCuM");
	}

	public void setPumpsTotalNo(Double pumpsTotalNo)
	{
		writeProperty("pumpsTotalNo", pumpsTotalNo);
	}

	public Double getPumpsTotalNo()
	{
		return (Double) readProperty("pumpsTotalNo");
	}

	public void setSegregatedBallastTanksInd(String segregatedBallastTanksInd)
	{
		writeProperty("segregatedBallastTanksInd", segregatedBallastTanksInd);
	}

	public String getSegregatedBallastTanksInd()
	{
		return (String) readProperty("segregatedBallastTanksInd");
	}

	public void setShipBuildersAddP01Yard(String shipBuildersAddP01Yard)
	{
		writeProperty("shipBuildersAddP01Yard", shipBuildersAddP01Yard);
	}

	public String getShipBuildersAddP01Yard()
	{
		return (String) readProperty("shipBuildersAddP01Yard");
	}

	public void setSpeedKnots(Double speedKnots)
	{
		writeProperty("speedKnots", speedKnots);
	}

	public Double getSpeedKnots()
	{
		return (Double) readProperty("speedKnots");
	}

	public void setStainlessTanksInd(String stainlessTanksInd)
	{
		writeProperty("stainlessTanksInd", stainlessTanksInd);
	}

	public String getStainlessTanksInd()
	{
		return (String) readProperty("stainlessTanksInd");
	}

	public void setSuezNt(Double suezNt)
	{
		writeProperty("suezNt", suezNt);
	}

	public Double getSuezNt()
	{
		return (Double) readProperty("suezNt");
	}

	public void setTanksTotalNo(Double tanksTotalNo)
	{
		writeProperty("tanksTotalNo", tanksTotalNo);
	}

	public Double getTanksTotalNo()
	{
		return (Double) readProperty("tanksTotalNo");
	}

	public void setVesselType(String vesselType)
	{
		writeProperty("vesselType", vesselType);
	}

	public String getVesselType()
	{
		return (String) readProperty("vesselType");
	}

	public void setYearBuilt(Double yearBuilt)
	{
		writeProperty("yearBuilt", yearBuilt);
	}

	public Double getYearBuilt()
	{
		return (Double) readProperty("yearBuilt");
	}

	public void addToShipSpeedConsumptions(ShipSpeedConsumption obj)
	{
		addToManyTarget("shipSpeedConsumptions", obj, true);
	}

	public void removeFromShipSpeedConsumptions(ShipSpeedConsumption obj)
	{
		removeToManyTarget("shipSpeedConsumptions", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ShipSpeedConsumption> getShipSpeedConsumptions()
	{
		return (List<ShipSpeedConsumption>) readProperty("shipSpeedConsumptions");
	}

}
