package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.PriceSource;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TradingPeriod;

/**
 * Class _CommodityMarketFormula was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CommodityMarketFormula extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String COMMKT_KEY_PK_COLUMN = "commkt_key";
	public static final String PRICE_SOURCE_CODE_PK_COLUMN = "price_source_code";
	public static final String TRADING_PRD_PK_COLUMN = "trading_prd";

	public static final Property<Integer> AVG_CLOSED_FORMULA_NUM = new Property<Integer>("avgClosedFormulaNum");
	public static final Property<Integer> AVG_CLOSED_SIMPLE_FORMULA_NUM = new Property<Integer>("avgClosedSimpleFormulaNum");
	public static final Property<Integer> CMF_NUM = new Property<Integer>("cmfNum");
	public static final Property<Integer> HIGH_ASKED_FORMULA_NUM = new Property<Integer>("highAskedFormulaNum");
	public static final Property<Integer> HIGH_ASKED_SIMPLE_FORMULA_NUM = new Property<Integer>("highAskedSimpleFormulaNum");
	public static final Property<Integer> LOW_BID_FORMULA_NUM = new Property<Integer>("lowBidFormulaNum");
	public static final Property<Integer> LOW_BID_SIMPLE_FORMULA_NUM = new Property<Integer>("lowBidSimpleFormulaNum");
	public static final Property<Integer> MPT_NUM = new Property<Integer>("mptNum");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<PriceSource> PRICE_SOURCE = new Property<PriceSource>("priceSource");
	public static final Property<TradingPeriod> TRADING_PERIOD = new Property<TradingPeriod>("tradingPeriod");
	public static final Property<TradingPeriod> TRADING_PERIOD1 = new Property<TradingPeriod>("tradingPeriod1");

	public void setAvgClosedFormulaNum(Integer avgClosedFormulaNum)
	{
		writeProperty("avgClosedFormulaNum", avgClosedFormulaNum);
	}

	public Integer getAvgClosedFormulaNum()
	{
		return (Integer) readProperty("avgClosedFormulaNum");
	}

	public void setAvgClosedSimpleFormulaNum(Integer avgClosedSimpleFormulaNum)
	{
		writeProperty("avgClosedSimpleFormulaNum", avgClosedSimpleFormulaNum);
	}

	public Integer getAvgClosedSimpleFormulaNum()
	{
		return (Integer) readProperty("avgClosedSimpleFormulaNum");
	}

	public void setCmfNum(Integer cmfNum)
	{
		writeProperty("cmfNum", cmfNum);
	}

	public Integer getCmfNum()
	{
		return (Integer) readProperty("cmfNum");
	}

	public void setHighAskedFormulaNum(Integer highAskedFormulaNum)
	{
		writeProperty("highAskedFormulaNum", highAskedFormulaNum);
	}

	public Integer getHighAskedFormulaNum()
	{
		return (Integer) readProperty("highAskedFormulaNum");
	}

	public void setHighAskedSimpleFormulaNum(Integer highAskedSimpleFormulaNum)
	{
		writeProperty("highAskedSimpleFormulaNum", highAskedSimpleFormulaNum);
	}

	public Integer getHighAskedSimpleFormulaNum()
	{
		return (Integer) readProperty("highAskedSimpleFormulaNum");
	}

	public void setLowBidFormulaNum(Integer lowBidFormulaNum)
	{
		writeProperty("lowBidFormulaNum", lowBidFormulaNum);
	}

	public Integer getLowBidFormulaNum()
	{
		return (Integer) readProperty("lowBidFormulaNum");
	}

	public void setLowBidSimpleFormulaNum(Integer lowBidSimpleFormulaNum)
	{
		writeProperty("lowBidSimpleFormulaNum", lowBidSimpleFormulaNum);
	}

	public Integer getLowBidSimpleFormulaNum()
	{
		return (Integer) readProperty("lowBidSimpleFormulaNum");
	}

	public void setMptNum(Integer mptNum)
	{
		writeProperty("mptNum", mptNum);
	}

	public Integer getMptNum()
	{
		return (Integer) readProperty("mptNum");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setPriceSource(PriceSource priceSource)
	{
		setToOneTarget("priceSource", priceSource, true);
	}

	public PriceSource getPriceSource()
	{
		return (PriceSource) readProperty("priceSource");
	}

	public void setTradingPeriod(TradingPeriod tradingPeriod)
	{
		setToOneTarget("tradingPeriod", tradingPeriod, true);
	}

	public TradingPeriod getTradingPeriod()
	{
		return (TradingPeriod) readProperty("tradingPeriod");
	}

	public void setTradingPeriod1(TradingPeriod tradingPeriod1)
	{
		setToOneTarget("tradingPeriod1", tradingPeriod1, true);
	}

	public TradingPeriod getTradingPeriod1()
	{
		return (TradingPeriod) readProperty("tradingPeriod1");
	}

}
