package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Cost;
import com.tc.app.exchangemonitor.model.cayenne.persistent.EomPostingBatch;

/**
 * Class _CostStatus was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CostStatus extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String COST_STATUS_CODE_PK_COLUMN = "cost_status_code";

	public static final Property<String> COST_STATUS_DESC = new Property<String>("costStatusDesc");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<List<Cost>> COSTS = new Property<List<Cost>>("costs");
	public static final Property<List<EomPostingBatch>> EOM_POSTING_BATCHES = new Property<List<EomPostingBatch>>("eomPostingBatches");

	public void setCostStatusDesc(String costStatusDesc)
	{
		writeProperty("costStatusDesc", costStatusDesc);
	}

	public String getCostStatusDesc()
	{
		return (String) readProperty("costStatusDesc");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void addToCosts(Cost obj)
	{
		addToManyTarget("costs", obj, true);
	}

	public void removeFromCosts(Cost obj)
	{
		removeToManyTarget("costs", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<Cost> getCosts()
	{
		return (List<Cost>) readProperty("costs");
	}

	public void addToEomPostingBatches(EomPostingBatch obj)
	{
		addToManyTarget("eomPostingBatches", obj, true);
	}

	public void removeFromEomPostingBatches(EomPostingBatch obj)
	{
		removeToManyTarget("eomPostingBatches", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<EomPostingBatch> getEomPostingBatches()
	{
		return (List<EomPostingBatch>) readProperty("eomPostingBatches");
	}

}
