package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsUser;
import com.tc.app.exchangemonitor.model.cayenne.persistent.OrderType;

/**
 * Class _CreditReserve was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CreditReserve extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<BigDecimal> RESERVED_AMT = new Property<BigDecimal>("reservedAmt");
	public static final Property<String> STATUS = new Property<String>("status");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Date> VALUE_DATE = new Property<Date>("valueDate");
	public static final Property<Account> ACCOUNT = new Property<Account>("account");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<IctsUser> ICTS_USER = new Property<IctsUser>("ictsUser");
	public static final Property<OrderType> ORDER_TYPE = new Property<OrderType>("orderType");

	public void setReservedAmt(BigDecimal reservedAmt)
	{
		writeProperty("reservedAmt", reservedAmt);
	}

	public BigDecimal getReservedAmt()
	{
		return (BigDecimal) readProperty("reservedAmt");
	}

	public void setStatus(String status)
	{
		writeProperty("status", status);
	}

	public String getStatus()
	{
		return (String) readProperty("status");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setValueDate(Date valueDate)
	{
		writeProperty("valueDate", valueDate);
	}

	public Date getValueDate()
	{
		return (Date) readProperty("valueDate");
	}

	public void setAccount(Account account)
	{
		setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) readProperty("account");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setIctsUser(IctsUser ictsUser)
	{
		setToOneTarget("ictsUser", ictsUser, true);
	}

	public IctsUser getIctsUser()
	{
		return (IctsUser) readProperty("ictsUser");
	}

	public void setOrderType(OrderType orderType)
	{
		setToOneTarget("orderType", orderType, true);
	}

	public OrderType getOrderType()
	{
		return (OrderType) readProperty("orderType");
	}

}
