package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.DefaultsDomain;
import com.tc.app.exchangemonitor.model.cayenne.persistent.SysResources;
import com.tc.app.exchangemonitor.model.cayenne.persistent.UserDefault;
import com.tc.app.exchangemonitor.model.cayenne.persistent.UserResources;

/**
 * Class _DefaultsDomain was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DefaultsDomain extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> NAME = new Property<String>("name");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<List<DefaultsDomain>> DEFAULTS_DOMAINS = new Property<List<DefaultsDomain>>("defaultsDomains");
	public static final Property<DefaultsDomain> PARENT = new Property<DefaultsDomain>("parent");
	public static final Property<List<SysResources>> SYS_RESOURCESES = new Property<List<SysResources>>("sysResourceses");
	public static final Property<List<UserDefault>> USER_DEFAULTS = new Property<List<UserDefault>>("userDefaults");
	public static final Property<List<UserResources>> USER_RESOURCESES = new Property<List<UserResources>>("userResourceses");

	public void setName(String name)
	{
		writeProperty("name", name);
	}

	public String getName()
	{
		return (String) readProperty("name");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void addToDefaultsDomains(DefaultsDomain obj)
	{
		addToManyTarget("defaultsDomains", obj, true);
	}

	public void removeFromDefaultsDomains(DefaultsDomain obj)
	{
		removeToManyTarget("defaultsDomains", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<DefaultsDomain> getDefaultsDomains()
	{
		return (List<DefaultsDomain>) readProperty("defaultsDomains");
	}

	public void setParent(DefaultsDomain parent)
	{
		setToOneTarget("parent", parent, true);
	}

	public DefaultsDomain getParent()
	{
		return (DefaultsDomain) readProperty("parent");
	}

	public void addToSysResourceses(SysResources obj)
	{
		addToManyTarget("sysResourceses", obj, true);
	}

	public void removeFromSysResourceses(SysResources obj)
	{
		removeToManyTarget("sysResourceses", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<SysResources> getSysResourceses()
	{
		return (List<SysResources>) readProperty("sysResourceses");
	}

	public void addToUserDefaults(UserDefault obj)
	{
		addToManyTarget("userDefaults", obj, true);
	}

	public void removeFromUserDefaults(UserDefault obj)
	{
		removeToManyTarget("userDefaults", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<UserDefault> getUserDefaults()
	{
		return (List<UserDefault>) readProperty("userDefaults");
	}

	public void addToUserResourceses(UserResources obj)
	{
		addToManyTarget("userResourceses", obj, true);
	}

	public void removeFromUserResourceses(UserResources obj)
	{
		removeToManyTarget("userResourceses", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<UserResources> getUserResourceses()
	{
		return (List<UserResources>) readProperty("userResourceses");
	}

}
