package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Desk;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Location;

/**
 * Class _DeskLocation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DeskLocation extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String DESK_CODE_PK_COLUMN = "desk_code";
	public static final String LOC_CODE_PK_COLUMN = "loc_code";

	public static final Property<Integer> DESK_LOC_NUM = new Property<>("deskLocNum");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<Desk> DESK = new Property<>("desk");
	public static final Property<Location> LOCATION = new Property<>("location");

	public void setDeskLocNum(final Integer deskLocNum)
	{
		this.writeProperty("deskLocNum", deskLocNum);
	}

	public Integer getDeskLocNum()
	{
		return (Integer) this.readProperty("deskLocNum");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setDesk(final Desk desk)
	{
		this.setToOneTarget("desk", desk, true);
	}

	public Desk getDesk()
	{
		return (Desk) this.readProperty("desk");
	}

	public void setLocation(final Location location)
	{
		this.setToOneTarget("location", location, true);
	}

	public Location getLocation()
	{
		return (Location) this.readProperty("location");
	}

}
