package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _EmptySeqFiles was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EmptySeqFiles extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> DATE_TIME = new Property<String>("dateTime");
	public static final Property<String> FILE = new Property<String>("file");

	public void setDateTime(String dateTime)
	{
		writeProperty("dateTime", dateTime);
	}

	public String getDateTime()
	{
		return (String) readProperty("dateTime");
	}

	public void setFile(String file)
	{
		writeProperty("file", file);
	}

	public String getFile()
	{
		return (String) readProperty("file");
	}

}
