package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.AliasSource;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ExtRefKeys;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsEntityName;

/**
 * Class _ExtRefdataMapping was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ExtRefdataMapping extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> EXTERNAL_KEY1 = new Property<>("externalKey1");
	public static final Property<String> EXTERNAL_KEY2 = new Property<>("externalKey2");
	public static final Property<String> EXTERNAL_KEY3 = new Property<>("externalKey3");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<AliasSource> ALIAS_SOURCE = new Property<>("aliasSource");
	public static final Property<IctsEntityName> ENTITY = new Property<>("entity");
	public static final Property<ExtRefKeys> ENTITY_KEY1VALUE = new Property<>("entityKey1Value");
	public static final Property<ExtRefKeys> ENTITY_KEY2VALUE = new Property<>("entityKey2Value");
	public static final Property<ExtRefKeys> ENTITY_KEY3VALUE = new Property<>("entityKey3Value");
	public static final Property<ExtRefKeys> ENTITY_KEY4VALUE = new Property<>("entityKey4Value");
	public static final Property<ExtRefKeys> ENTITY_KEY5VALUE = new Property<>("entityKey5Value");
	public static final Property<ExtRefKeys> ENTITY_KEY6VALUE = new Property<>("entityKey6Value");

	public void setExternalKey1(final String externalKey1)
	{
		this.writeProperty("externalKey1", externalKey1);
	}

	public String getExternalKey1()
	{
		return (String) this.readProperty("externalKey1");
	}

	public void setExternalKey2(final String externalKey2)
	{
		this.writeProperty("externalKey2", externalKey2);
	}

	public String getExternalKey2()
	{
		return (String) this.readProperty("externalKey2");
	}

	public void setExternalKey3(final String externalKey3)
	{
		this.writeProperty("externalKey3", externalKey3);
	}

	public String getExternalKey3()
	{
		return (String) this.readProperty("externalKey3");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setAliasSource(final AliasSource aliasSource)
	{
		this.setToOneTarget("aliasSource", aliasSource, true);
	}

	public AliasSource getAliasSource()
	{
		return (AliasSource) this.readProperty("aliasSource");
	}

	public void setEntity(final IctsEntityName entity)
	{
		this.setToOneTarget("entity", entity, true);
	}

	public IctsEntityName getEntity()
	{
		return (IctsEntityName) this.readProperty("entity");
	}

	public void setEntityKey1Value(final ExtRefKeys entityKey1Value)
	{
		this.setToOneTarget("entityKey1Value", entityKey1Value, true);
	}

	public ExtRefKeys getEntityKey1Value()
	{
		return (ExtRefKeys) this.readProperty("entityKey1Value");
	}

	public void setEntityKey2Value(final ExtRefKeys entityKey2Value)
	{
		this.setToOneTarget("entityKey2Value", entityKey2Value, true);
	}

	public ExtRefKeys getEntityKey2Value()
	{
		return (ExtRefKeys) this.readProperty("entityKey2Value");
	}

	public void setEntityKey3Value(final ExtRefKeys entityKey3Value)
	{
		this.setToOneTarget("entityKey3Value", entityKey3Value, true);
	}

	public ExtRefKeys getEntityKey3Value()
	{
		return (ExtRefKeys) this.readProperty("entityKey3Value");
	}

	public void setEntityKey4Value(final ExtRefKeys entityKey4Value)
	{
		this.setToOneTarget("entityKey4Value", entityKey4Value, true);
	}

	public ExtRefKeys getEntityKey4Value()
	{
		return (ExtRefKeys) this.readProperty("entityKey4Value");
	}

	public void setEntityKey5Value(final ExtRefKeys entityKey5Value)
	{
		this.setToOneTarget("entityKey5Value", entityKey5Value, true);
	}

	public ExtRefKeys getEntityKey5Value()
	{
		return (ExtRefKeys) this.readProperty("entityKey5Value");
	}

	public void setEntityKey6Value(final ExtRefKeys entityKey6Value)
	{
		this.setToOneTarget("entityKey6Value", entityKey6Value, true);
	}

	public ExtRefKeys getEntityKey6Value()
	{
		return (ExtRefKeys) this.readProperty("entityKey6Value");
	}

}
