package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.AliasSource;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ExtTradeLoadingSched;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ExternalMapping;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ExternalTrade;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ExternalTradeSystem;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ExternalTradeType;

/**
 * Class _ExternalTradeSource was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ExternalTradeSource extends CayenneDataObject
{
	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> EXTERNAL_TRADE_SRC_NAME = new Property<>("externalTradeSrcName");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<AliasSource> ALIAS_SOURCE = new Property<>("aliasSource");
	public static final Property<List<ExtTradeLoadingSched>> EXT_TRADE_LOADING_SCHEDS = new Property<>("extTradeLoadingScheds");
	public static final Property<List<ExternalMapping>> EXTERNAL_MAPPINGS = new Property<>("externalMappings");
	public static final Property<ExternalTradeSystem> EXTERNAL_TRADE_SYSTEM_O = new Property<>("externalTradeSystemO");
	public static final Property<List<ExternalTradeType>> EXTERNAL_TRADE_TYPES = new Property<>("externalTradeTypes");
	public static final Property<List<ExternalTrade>> EXTERNAL_TRADES = new Property<>("externalTrades");

	public void setExternalTradeSrcName(final String externalTradeSrcName)
	{
		this.writeProperty("externalTradeSrcName", externalTradeSrcName);
	}

	public String getExternalTradeSrcName()
	{
		return (String) this.readProperty("externalTradeSrcName");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setAliasSource(final AliasSource aliasSource)
	{
		this.setToOneTarget("aliasSource", aliasSource, true);
	}

	public AliasSource getAliasSource()
	{
		return (AliasSource) this.readProperty("aliasSource");
	}

	public void addToExtTradeLoadingScheds(final ExtTradeLoadingSched obj)
	{
		this.addToManyTarget("extTradeLoadingScheds", obj, true);
	}

	public void removeFromExtTradeLoadingScheds(final ExtTradeLoadingSched obj)
	{
		this.removeToManyTarget("extTradeLoadingScheds", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ExtTradeLoadingSched> getExtTradeLoadingScheds()
	{
		return (List<ExtTradeLoadingSched>) this.readProperty("extTradeLoadingScheds");
	}

	public void addToExternalMappings(final ExternalMapping obj)
	{
		this.addToManyTarget("externalMappings", obj, true);
	}

	public void removeFromExternalMappings(final ExternalMapping obj)
	{
		this.removeToManyTarget("externalMappings", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ExternalMapping> getExternalMappings()
	{
		return (List<ExternalMapping>) this.readProperty("externalMappings");
	}

	public void setExternalTradeSystemO(final ExternalTradeSystem externalTradeSystemO)
	{
		this.setToOneTarget("externalTradeSystemO", externalTradeSystemO, true);
	}

	public ExternalTradeSystem getExternalTradeSystemO()
	{
		return (ExternalTradeSystem) this.readProperty("externalTradeSystemO");
	}

	public void addToExternalTradeTypes(final ExternalTradeType obj)
	{
		this.addToManyTarget("externalTradeTypes", obj, true);
	}

	public void removeFromExternalTradeTypes(final ExternalTradeType obj)
	{
		this.removeToManyTarget("externalTradeTypes", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ExternalTradeType> getExternalTradeTypes()
	{
		return (List<ExternalTradeType>) this.readProperty("externalTradeTypes");
	}

	public void addToExternalTrades(final ExternalTrade obj)
	{
		this.addToManyTarget("externalTrades", obj, true);
	}

	public void removeFromExternalTrades(final ExternalTrade obj)
	{
		this.removeToManyTarget("externalTrades", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ExternalTrade> getExternalTrades()
	{
		return (List<ExternalTrade>) this.readProperty("externalTrades");
	}

}
