package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.TiInboundDataXml;

/**
 * Class _FeedCashInbound was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FeedCashInbound extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<Integer> COST_NUM = new Property<Integer>("costNum");
	public static final Property<String> COST_PRICE_CURRENCY_CODE = new Property<String>("costPriceCurrencyCode");
	public static final Property<String> SAP_INVOICE_NUM = new Property<String>("sapInvoiceNum");
	public static final Property<String> STATUS = new Property<String>("status");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Integer> VOUCHER_NUM = new Property<Integer>("voucherNum");
	public static final Property<TiInboundDataXml> INBOUND_DATA_O = new Property<TiInboundDataXml>("inboundDataO");

	public void setCostNum(Integer costNum)
	{
		writeProperty("costNum", costNum);
	}

	public Integer getCostNum()
	{
		return (Integer) readProperty("costNum");
	}

	public void setCostPriceCurrencyCode(String costPriceCurrencyCode)
	{
		writeProperty("costPriceCurrencyCode", costPriceCurrencyCode);
	}

	public String getCostPriceCurrencyCode()
	{
		return (String) readProperty("costPriceCurrencyCode");
	}

	public void setSapInvoiceNum(String sapInvoiceNum)
	{
		writeProperty("sapInvoiceNum", sapInvoiceNum);
	}

	public String getSapInvoiceNum()
	{
		return (String) readProperty("sapInvoiceNum");
	}

	public void setStatus(String status)
	{
		writeProperty("status", status);
	}

	public String getStatus()
	{
		return (String) readProperty("status");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setVoucherNum(Integer voucherNum)
	{
		writeProperty("voucherNum", voucherNum);
	}

	public Integer getVoucherNum()
	{
		return (Integer) readProperty("voucherNum");
	}

	public void setInboundDataO(TiInboundDataXml inboundDataO)
	{
		setToOneTarget("inboundDataO", inboundDataO, true);
	}

	public TiInboundDataXml getInboundDataO()
	{
		return (TiInboundDataXml) readProperty("inboundDataO");
	}

}
