package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.FeedData;
import com.tc.app.exchangemonitor.model.cayenne.persistent.FeedDetailData;
import com.tc.app.exchangemonitor.model.cayenne.persistent.MsiFeedData;

/**
 * Class _FeedXsdXmlText was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FeedXsdXmlText extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> DOC_TEXT = new Property<String>("docText");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<List<FeedData>> FEED_DATAS = new Property<List<FeedData>>("feedDatas");
	public static final Property<List<FeedData>> FEED_DATAS1 = new Property<List<FeedData>>("feedDatas1");
	public static final Property<List<FeedDetailData>> FEED_DETAIL_DATAS = new Property<List<FeedDetailData>>("feedDetailDatas");
	public static final Property<List<MsiFeedData>> MSI_FEED_DATAS = new Property<List<MsiFeedData>>("msiFeedDatas");

	public void setDocText(String docText)
	{
		writeProperty("docText", docText);
	}

	public String getDocText()
	{
		return (String) readProperty("docText");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void addToFeedDatas(FeedData obj)
	{
		addToManyTarget("feedDatas", obj, true);
	}

	public void removeFromFeedDatas(FeedData obj)
	{
		removeToManyTarget("feedDatas", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FeedData> getFeedDatas()
	{
		return (List<FeedData>) readProperty("feedDatas");
	}

	public void addToFeedDatas1(FeedData obj)
	{
		addToManyTarget("feedDatas1", obj, true);
	}

	public void removeFromFeedDatas1(FeedData obj)
	{
		removeToManyTarget("feedDatas1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FeedData> getFeedDatas1()
	{
		return (List<FeedData>) readProperty("feedDatas1");
	}

	public void addToFeedDetailDatas(FeedDetailData obj)
	{
		addToManyTarget("feedDetailDatas", obj, true);
	}

	public void removeFromFeedDetailDatas(FeedDetailData obj)
	{
		removeToManyTarget("feedDetailDatas", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FeedDetailData> getFeedDetailDatas()
	{
		return (List<FeedDetailData>) readProperty("feedDetailDatas");
	}

	public void addToMsiFeedDatas(MsiFeedData obj)
	{
		addToManyTarget("msiFeedDatas", obj, true);
	}

	public void removeFromMsiFeedDatas(MsiFeedData obj)
	{
		removeToManyTarget("msiFeedDatas", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<MsiFeedData> getMsiFeedDatas()
	{
		return (List<MsiFeedData>) readProperty("msiFeedDatas");
	}

}
