package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Cost;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Portfolio;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TradeItem;

/**
 * Class _FinancialReconcil was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FinancialReconcil extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<BigDecimal> CONDITION_RATE = new Property<BigDecimal>("conditionRate");
	public static final Property<String> CONDITION_TYPE = new Property<String>("conditionType");
	public static final Property<BigDecimal> CONDITION_VALUE = new Property<BigDecimal>("conditionValue");
	public static final Property<String> CURRENCY = new Property<String>("currency");
	public static final Property<Date> DOCUMENT_DATE = new Property<Date>("documentDate");
	public static final Property<Date> ETL_TIMESTAMP = new Property<Date>("etlTimestamp");
	public static final Property<String> GL_ACCT_CODE = new Property<String>("glAcctCode");
	public static final Property<String> LOC_CODE = new Property<String>("locCode");
	public static final Property<String> MATERIAL_CODE = new Property<String>("materialCode");
	public static final Property<Integer> MATERIAL_DOC_ITEM = new Property<Integer>("materialDocItem");
	public static final Property<String> MATERIAL_DOC_NUM = new Property<String>("materialDocNum");
	public static final Property<Integer> MATERIAL_DOC_YEAR = new Property<Integer>("materialDocYear");
	public static final Property<String> MOVEMENT_TYPE = new Property<String>("movementType");
	public static final Property<String> PROFIT_CENTER = new Property<String>("profitCenter");
	public static final Property<String> SAP_AGREEMENT_NUM = new Property<String>("sapAgreementNum");
	public static final Property<String> SAP_CONTRACT_NUM = new Property<String>("sapContractNum");
	public static final Property<String> SAP_LINE_ITEM_NUM = new Property<String>("sapLineItemNum");
	public static final Property<String> SOURCE_FEED = new Property<String>("sourceFeed");
	public static final Property<String> STATUS = new Property<String>("status");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<String> UOM = new Property<String>("uom");
	public static final Property<Cost> COST = new Property<Cost>("cost");
	public static final Property<Portfolio> PORTFOLIO = new Property<Portfolio>("portfolio");
	public static final Property<TradeItem> TRADE_ITEM = new Property<TradeItem>("tradeItem");
	public static final Property<TradeItem> TRADE_ITEM1 = new Property<TradeItem>("tradeItem1");
	public static final Property<TradeItem> TRADE_ITEM2 = new Property<TradeItem>("tradeItem2");

	public void setConditionRate(BigDecimal conditionRate)
	{
		writeProperty("conditionRate", conditionRate);
	}

	public BigDecimal getConditionRate()
	{
		return (BigDecimal) readProperty("conditionRate");
	}

	public void setConditionType(String conditionType)
	{
		writeProperty("conditionType", conditionType);
	}

	public String getConditionType()
	{
		return (String) readProperty("conditionType");
	}

	public void setConditionValue(BigDecimal conditionValue)
	{
		writeProperty("conditionValue", conditionValue);
	}

	public BigDecimal getConditionValue()
	{
		return (BigDecimal) readProperty("conditionValue");
	}

	public void setCurrency(String currency)
	{
		writeProperty("currency", currency);
	}

	public String getCurrency()
	{
		return (String) readProperty("currency");
	}

	public void setDocumentDate(Date documentDate)
	{
		writeProperty("documentDate", documentDate);
	}

	public Date getDocumentDate()
	{
		return (Date) readProperty("documentDate");
	}

	public void setEtlTimestamp(Date etlTimestamp)
	{
		writeProperty("etlTimestamp", etlTimestamp);
	}

	public Date getEtlTimestamp()
	{
		return (Date) readProperty("etlTimestamp");
	}

	public void setGlAcctCode(String glAcctCode)
	{
		writeProperty("glAcctCode", glAcctCode);
	}

	public String getGlAcctCode()
	{
		return (String) readProperty("glAcctCode");
	}

	public void setLocCode(String locCode)
	{
		writeProperty("locCode", locCode);
	}

	public String getLocCode()
	{
		return (String) readProperty("locCode");
	}

	public void setMaterialCode(String materialCode)
	{
		writeProperty("materialCode", materialCode);
	}

	public String getMaterialCode()
	{
		return (String) readProperty("materialCode");
	}

	public void setMaterialDocItem(Integer materialDocItem)
	{
		writeProperty("materialDocItem", materialDocItem);
	}

	public Integer getMaterialDocItem()
	{
		return (Integer) readProperty("materialDocItem");
	}

	public void setMaterialDocNum(String materialDocNum)
	{
		writeProperty("materialDocNum", materialDocNum);
	}

	public String getMaterialDocNum()
	{
		return (String) readProperty("materialDocNum");
	}

	public void setMaterialDocYear(Integer materialDocYear)
	{
		writeProperty("materialDocYear", materialDocYear);
	}

	public Integer getMaterialDocYear()
	{
		return (Integer) readProperty("materialDocYear");
	}

	public void setMovementType(String movementType)
	{
		writeProperty("movementType", movementType);
	}

	public String getMovementType()
	{
		return (String) readProperty("movementType");
	}

	public void setProfitCenter(String profitCenter)
	{
		writeProperty("profitCenter", profitCenter);
	}

	public String getProfitCenter()
	{
		return (String) readProperty("profitCenter");
	}

	public void setSapAgreementNum(String sapAgreementNum)
	{
		writeProperty("sapAgreementNum", sapAgreementNum);
	}

	public String getSapAgreementNum()
	{
		return (String) readProperty("sapAgreementNum");
	}

	public void setSapContractNum(String sapContractNum)
	{
		writeProperty("sapContractNum", sapContractNum);
	}

	public String getSapContractNum()
	{
		return (String) readProperty("sapContractNum");
	}

	public void setSapLineItemNum(String sapLineItemNum)
	{
		writeProperty("sapLineItemNum", sapLineItemNum);
	}

	public String getSapLineItemNum()
	{
		return (String) readProperty("sapLineItemNum");
	}

	public void setSourceFeed(String sourceFeed)
	{
		writeProperty("sourceFeed", sourceFeed);
	}

	public String getSourceFeed()
	{
		return (String) readProperty("sourceFeed");
	}

	public void setStatus(String status)
	{
		writeProperty("status", status);
	}

	public String getStatus()
	{
		return (String) readProperty("status");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setUom(String uom)
	{
		writeProperty("uom", uom);
	}

	public String getUom()
	{
		return (String) readProperty("uom");
	}

	public void setCost(Cost cost)
	{
		setToOneTarget("cost", cost, true);
	}

	public Cost getCost()
	{
		return (Cost) readProperty("cost");
	}

	public void setPortfolio(Portfolio portfolio)
	{
		setToOneTarget("portfolio", portfolio, true);
	}

	public Portfolio getPortfolio()
	{
		return (Portfolio) readProperty("portfolio");
	}

	public void setTradeItem(TradeItem tradeItem)
	{
		setToOneTarget("tradeItem", tradeItem, true);
	}

	public TradeItem getTradeItem()
	{
		return (TradeItem) readProperty("tradeItem");
	}

	public void setTradeItem1(TradeItem tradeItem1)
	{
		setToOneTarget("tradeItem1", tradeItem1, true);
	}

	public TradeItem getTradeItem1()
	{
		return (TradeItem) readProperty("tradeItem1");
	}

	public void setTradeItem2(TradeItem tradeItem2)
	{
		setToOneTarget("tradeItem2", tradeItem2, true);
	}

	public TradeItem getTradeItem2()
	{
		return (TradeItem) readProperty("tradeItem2");
	}

}
