package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.RealizaPriceFrgCost;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _FlatRates was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FlatRates extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLAT_CODE_PK_COLUMN = "flat_code";

	public static final Property<Double> FLAT_VALUE = new Property<Double>("flatValue");
	public static final Property<Date> FROM_DATE = new Property<Date>("fromDate");
	public static final Property<Date> TO_DATE = new Property<Date>("toDate");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<List<RealizaPriceFrgCost>> REALIZA_PRICE_FRG_COSTS = new Property<List<RealizaPriceFrgCost>>("realizaPriceFrgCosts");
	public static final Property<Uom> UOM = new Property<Uom>("uom");

	public void setFlatValue(Double flatValue)
	{
		writeProperty("flatValue", flatValue);
	}

	public Double getFlatValue()
	{
		return (Double) readProperty("flatValue");
	}

	public void setFromDate(Date fromDate)
	{
		writeProperty("fromDate", fromDate);
	}

	public Date getFromDate()
	{
		return (Date) readProperty("fromDate");
	}

	public void setToDate(Date toDate)
	{
		writeProperty("toDate", toDate);
	}

	public Date getToDate()
	{
		return (Date) readProperty("toDate");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void addToRealizaPriceFrgCosts(RealizaPriceFrgCost obj)
	{
		addToManyTarget("realizaPriceFrgCosts", obj, true);
	}

	public void removeFromRealizaPriceFrgCosts(RealizaPriceFrgCost obj)
	{
		removeToManyTarget("realizaPriceFrgCosts", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<RealizaPriceFrgCost> getRealizaPriceFrgCosts()
	{
		return (List<RealizaPriceFrgCost>) readProperty("realizaPriceFrgCosts");
	}

	public void setUom(Uom uom)
	{
		setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) readProperty("uom");
	}

}
