package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _FlDepManaged was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FlDepManaged extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ID_ROW_PK_COLUMN = "IdRow";

	public static final Property<String> DEP_NAME = new Property<String>("depName");
	public static final Property<String> MANAGER = new Property<String>("manager");

	public void setDepName(String depName)
	{
		writeProperty("depName", depName);
	}

	public String getDepName()
	{
		return (String) readProperty("depName");
	}

	public void setManager(String manager)
	{
		writeProperty("manager", manager);
	}

	public String getManager()
	{
		return (String) readProperty("manager");
	}

}
