package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.FlGroupsRoles;
import com.tc.app.exchangemonitor.model.cayenne.persistent.FlUsers;

/**
 * Class _FlGroups was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FlGroups extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String GROUP_NAME_PK_COLUMN = "groupName";

	public static final Property<Integer> BUILTIN = new Property<Integer>("builtin");
	public static final Property<String> DESCRIPTION = new Property<String>("description");
	public static final Property<List<FlGroupsRoles>> FL_GROUPS_ROLESES = new Property<List<FlGroupsRoles>>("flGroupsRoleses");
	public static final Property<List<FlUsers>> FL_USERSS = new Property<List<FlUsers>>("flUserss");

	public void setBuiltin(Integer builtin)
	{
		writeProperty("builtin", builtin);
	}

	public Integer getBuiltin()
	{
		return (Integer) readProperty("builtin");
	}

	public void setDescription(String description)
	{
		writeProperty("description", description);
	}

	public String getDescription()
	{
		return (String) readProperty("description");
	}

	public void addToFlGroupsRoleses(FlGroupsRoles obj)
	{
		addToManyTarget("flGroupsRoleses", obj, true);
	}

	public void removeFromFlGroupsRoleses(FlGroupsRoles obj)
	{
		removeToManyTarget("flGroupsRoleses", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FlGroupsRoles> getFlGroupsRoleses()
	{
		return (List<FlGroupsRoles>) readProperty("flGroupsRoleses");
	}

	public void addToFlUserss(FlUsers obj)
	{
		addToManyTarget("flUserss", obj, true);
	}

	public void removeFromFlUserss(FlUsers obj)
	{
		removeToManyTarget("flUserss", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FlUsers> getFlUserss()
	{
		return (List<FlUsers>) readProperty("flUserss");
	}

}
