package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _FlPermissionsAdv was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FlPermissionsAdv extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String USER_INIT_PK_COLUMN = "user_init";

	public static final Property<String> BOCE = new Property<String>("boce");
	public static final Property<String> BOCN = new Property<String>("bocn");
	public static final Property<String> BOE = new Property<String>("boe");
	public static final Property<String> BON = new Property<String>("bon");
	public static final Property<String> CC = new Property<String>("cc");
	public static final Property<String> EC = new Property<String>("ec");
	public static final Property<String> RC = new Property<String>("rc");
	public static final Property<String> SCA = new Property<String>("sca");
	public static final Property<String> SCC = new Property<String>("scc");
	public static final Property<String> SCCIE = new Property<String>("sccie");
	public static final Property<String> SCCIR = new Property<String>("sccir");
	public static final Property<String> SCCO = new Property<String>("scco");
	public static final Property<String> SCCOE = new Property<String>("sccoe");
	public static final Property<String> SCCOR = new Property<String>("sccor");
	public static final Property<String> SCD = new Property<String>("scd");
	public static final Property<String> SCE = new Property<String>("sce");
	public static final Property<String> SCIN = new Property<String>("scin");
	public static final Property<String> TA = new Property<String>("ta");
	public static final Property<String> TCCI = new Property<String>("tcci");
	public static final Property<String> TCCIE = new Property<String>("tccie");
	public static final Property<String> TCCIR = new Property<String>("tccir");
	public static final Property<String> TCCO = new Property<String>("tcco");
	public static final Property<String> TCCOE = new Property<String>("tccoe");
	public static final Property<String> TCCOR = new Property<String>("tccor");
	public static final Property<String> TCPCE = new Property<String>("tcpce");
	public static final Property<String> TCPCN = new Property<String>("tcpcn");
	public static final Property<String> TCRE = new Property<String>("tcre");
	public static final Property<String> TCRN = new Property<String>("tcrn");
	public static final Property<String> TE = new Property<String>("te");

	public void setBoce(String boce)
	{
		writeProperty("boce", boce);
	}

	public String getBoce()
	{
		return (String) readProperty("boce");
	}

	public void setBocn(String bocn)
	{
		writeProperty("bocn", bocn);
	}

	public String getBocn()
	{
		return (String) readProperty("bocn");
	}

	public void setBoe(String boe)
	{
		writeProperty("boe", boe);
	}

	public String getBoe()
	{
		return (String) readProperty("boe");
	}

	public void setBon(String bon)
	{
		writeProperty("bon", bon);
	}

	public String getBon()
	{
		return (String) readProperty("bon");
	}

	public void setCc(String cc)
	{
		writeProperty("cc", cc);
	}

	public String getCc()
	{
		return (String) readProperty("cc");
	}

	public void setEc(String ec)
	{
		writeProperty("ec", ec);
	}

	public String getEc()
	{
		return (String) readProperty("ec");
	}

	public void setRc(String rc)
	{
		writeProperty("rc", rc);
	}

	public String getRc()
	{
		return (String) readProperty("rc");
	}

	public void setSca(String sca)
	{
		writeProperty("sca", sca);
	}

	public String getSca()
	{
		return (String) readProperty("sca");
	}

	public void setScc(String scc)
	{
		writeProperty("scc", scc);
	}

	public String getScc()
	{
		return (String) readProperty("scc");
	}

	public void setSccie(String sccie)
	{
		writeProperty("sccie", sccie);
	}

	public String getSccie()
	{
		return (String) readProperty("sccie");
	}

	public void setSccir(String sccir)
	{
		writeProperty("sccir", sccir);
	}

	public String getSccir()
	{
		return (String) readProperty("sccir");
	}

	public void setScco(String scco)
	{
		writeProperty("scco", scco);
	}

	public String getScco()
	{
		return (String) readProperty("scco");
	}

	public void setSccoe(String sccoe)
	{
		writeProperty("sccoe", sccoe);
	}

	public String getSccoe()
	{
		return (String) readProperty("sccoe");
	}

	public void setSccor(String sccor)
	{
		writeProperty("sccor", sccor);
	}

	public String getSccor()
	{
		return (String) readProperty("sccor");
	}

	public void setScd(String scd)
	{
		writeProperty("scd", scd);
	}

	public String getScd()
	{
		return (String) readProperty("scd");
	}

	public void setSce(String sce)
	{
		writeProperty("sce", sce);
	}

	public String getSce()
	{
		return (String) readProperty("sce");
	}

	public void setScin(String scin)
	{
		writeProperty("scin", scin);
	}

	public String getScin()
	{
		return (String) readProperty("scin");
	}

	public void setTa(String ta)
	{
		writeProperty("ta", ta);
	}

	public String getTa()
	{
		return (String) readProperty("ta");
	}

	public void setTcci(String tcci)
	{
		writeProperty("tcci", tcci);
	}

	public String getTcci()
	{
		return (String) readProperty("tcci");
	}

	public void setTccie(String tccie)
	{
		writeProperty("tccie", tccie);
	}

	public String getTccie()
	{
		return (String) readProperty("tccie");
	}

	public void setTccir(String tccir)
	{
		writeProperty("tccir", tccir);
	}

	public String getTccir()
	{
		return (String) readProperty("tccir");
	}

	public void setTcco(String tcco)
	{
		writeProperty("tcco", tcco);
	}

	public String getTcco()
	{
		return (String) readProperty("tcco");
	}

	public void setTccoe(String tccoe)
	{
		writeProperty("tccoe", tccoe);
	}

	public String getTccoe()
	{
		return (String) readProperty("tccoe");
	}

	public void setTccor(String tccor)
	{
		writeProperty("tccor", tccor);
	}

	public String getTccor()
	{
		return (String) readProperty("tccor");
	}

	public void setTcpce(String tcpce)
	{
		writeProperty("tcpce", tcpce);
	}

	public String getTcpce()
	{
		return (String) readProperty("tcpce");
	}

	public void setTcpcn(String tcpcn)
	{
		writeProperty("tcpcn", tcpcn);
	}

	public String getTcpcn()
	{
		return (String) readProperty("tcpcn");
	}

	public void setTcre(String tcre)
	{
		writeProperty("tcre", tcre);
	}

	public String getTcre()
	{
		return (String) readProperty("tcre");
	}

	public void setTcrn(String tcrn)
	{
		writeProperty("tcrn", tcrn);
	}

	public String getTcrn()
	{
		return (String) readProperty("tcrn");
	}

	public void setTe(String te)
	{
		writeProperty("te", te);
	}

	public String getTe()
	{
		return (String) readProperty("te");
	}

}
