package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Location;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PriceSource;

/**
 * Class _FormulaComponentExt was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FormulaComponentExt extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FORMULA_BODY_NUM_PK_COLUMN = "formula_body_num";
	public static final String FORMULA_COMP_NUM_PK_COLUMN = "formula_comp_num";
	public static final String FORMULA_NUM_PK_COLUMN = "formula_num";

	public static final Property<Double> DEEMED_GRAVITY = new Property<>("deemedGravity");
	public static final Property<String> GRAVITY_ADJ_IND = new Property<>("gravityAdjInd");
	public static final Property<String> GRAVITY_TABLE_NAME = new Property<>("gravityTableName");
	public static final Property<Double> POSTED_GRAVITY = new Property<>("postedGravity");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<Location> LOCATION = new Property<>("location");
	public static final Property<PriceSource> PRICE_SOURCE = new Property<>("priceSource");

	public void setDeemedGravity(final Double deemedGravity)
	{
		this.writeProperty("deemedGravity", deemedGravity);
	}

	public Double getDeemedGravity()
	{
		return (Double) this.readProperty("deemedGravity");
	}

	public void setGravityAdjInd(final String gravityAdjInd)
	{
		this.writeProperty("gravityAdjInd", gravityAdjInd);
	}

	public String getGravityAdjInd()
	{
		return (String) this.readProperty("gravityAdjInd");
	}

	public void setGravityTableName(final String gravityTableName)
	{
		this.writeProperty("gravityTableName", gravityTableName);
	}

	public String getGravityTableName()
	{
		return (String) this.readProperty("gravityTableName");
	}

	public void setPostedGravity(final Double postedGravity)
	{
		this.writeProperty("postedGravity", postedGravity);
	}

	public Double getPostedGravity()
	{
		return (Double) this.readProperty("postedGravity");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setLocation(final Location location)
	{
		this.setToOneTarget("location", location, true);
	}

	public Location getLocation()
	{
		return (Location) this.readProperty("location");
	}

	public void setPriceSource(final PriceSource priceSource)
	{
		this.setToOneTarget("priceSource", priceSource, true);
	}

	public PriceSource getPriceSource()
	{
		return (PriceSource) this.readProperty("priceSource");
	}

}
