package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _FreightTradeCost was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FreightTradeCost extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String CARGO_KEY_PK_COLUMN = "cargo_key";
	public static final String COST_NUM_PK_COLUMN = "cost_num";

	public static final Property<String> COST_TYPE = new Property<String>("costType");
	public static final Property<Double> PERCENTAGE = new Property<Double>("percentage");
	public static final Property<Boolean> SYSTEM_HANDLED = new Property<Boolean>("systemHandled");

	public void setCostType(String costType)
	{
		writeProperty("costType", costType);
	}

	public String getCostType()
	{
		return (String) readProperty("costType");
	}

	public void setPercentage(Double percentage)
	{
		writeProperty("percentage", percentage);
	}

	public Double getPercentage()
	{
		return (Double) readProperty("percentage");
	}

	public void setSystemHandled(Boolean systemHandled)
	{
		writeProperty("systemHandled", systemHandled);
	}

	public Boolean getSystemHandled()
	{
		return (Boolean) readProperty("systemHandled");
	}

}
