package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.FunctionDetailValue;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsFunction;

/**
 * Class _FunctionDetail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FunctionDetail extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FD_ID_PK_COLUMN = "fd_id";

	public static final Property<String> ATTR_NAME = new Property<String>("attrName");
	public static final Property<Boolean> ENTITY_IND = new Property<Boolean>("entityInd");
	public static final Property<String> ENTITY_NAME = new Property<String>("entityName");
	public static final Property<String> OPERATION = new Property<String>("operation");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<List<FunctionDetailValue>> FUNCTION_DETAIL_VALUES = new Property<List<FunctionDetailValue>>("functionDetailValues");
	public static final Property<IctsFunction> ICTS_FUNCTION = new Property<IctsFunction>("ictsFunction");

	public void setAttrName(String attrName)
	{
		writeProperty("attrName", attrName);
	}

	public String getAttrName()
	{
		return (String) readProperty("attrName");
	}

	public void setEntityInd(Boolean entityInd)
	{
		writeProperty("entityInd", entityInd);
	}

	public Boolean getEntityInd()
	{
		return (Boolean) readProperty("entityInd");
	}

	public void setEntityName(String entityName)
	{
		writeProperty("entityName", entityName);
	}

	public String getEntityName()
	{
		return (String) readProperty("entityName");
	}

	public void setOperation(String operation)
	{
		writeProperty("operation", operation);
	}

	public String getOperation()
	{
		return (String) readProperty("operation");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void addToFunctionDetailValues(FunctionDetailValue obj)
	{
		addToManyTarget("functionDetailValues", obj, true);
	}

	public void removeFromFunctionDetailValues(FunctionDetailValue obj)
	{
		removeToManyTarget("functionDetailValues", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FunctionDetailValue> getFunctionDetailValues()
	{
		return (List<FunctionDetailValue>) readProperty("functionDetailValues");
	}

	public void setIctsFunction(IctsFunction ictsFunction)
	{
		setToOneTarget("ictsFunction", ictsFunction, true);
	}

	public IctsFunction getIctsFunction()
	{
		return (IctsFunction) readProperty("ictsFunction");
	}

}
