package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _FxExposurePl was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FxExposurePl extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String EXP_KEY_NUM_PK_COLUMN = "exp_key_num";
	public static final String EXP_KEY_TYPE_PK_COLUMN = "exp_key_type";
	public static final String PL_ASOF_DATE_PK_COLUMN = "pl_asof_date";

	public static final Property<BigDecimal> FOREX_OPEN_COMP_YR_PL = new Property<BigDecimal>("forexOpenCompYrPl");
	public static final Property<BigDecimal> FOREX_OPEN_DAY_PL = new Property<BigDecimal>("forexOpenDayPl");
	public static final Property<BigDecimal> FOREX_OPEN_LIFE_PL = new Property<BigDecimal>("forexOpenLifePl");
	public static final Property<BigDecimal> FOREX_OPEN_MONTH_PL = new Property<BigDecimal>("forexOpenMonthPl");
	public static final Property<BigDecimal> FOREX_OPEN_WEEK_PL = new Property<BigDecimal>("forexOpenWeekPl");
	public static final Property<BigDecimal> FOREX_OPEN_YEAR_PL = new Property<BigDecimal>("forexOpenYearPl");
	public static final Property<BigDecimal> FOREX_UNLOCKED_COMP_YR_PL = new Property<BigDecimal>("forexUnlockedCompYrPl");
	public static final Property<BigDecimal> FOREX_UNLOCKED_DAY_PL = new Property<BigDecimal>("forexUnlockedDayPl");
	public static final Property<BigDecimal> FOREX_UNLOCKED_LIFE_PL = new Property<BigDecimal>("forexUnlockedLifePl");
	public static final Property<BigDecimal> FOREX_UNLOCKED_MONTH_PL = new Property<BigDecimal>("forexUnlockedMonthPl");
	public static final Property<BigDecimal> FOREX_UNLOCKED_WEEK_PL = new Property<BigDecimal>("forexUnlockedWeekPl");
	public static final Property<BigDecimal> FOREX_UNLOCKED_YEAR_PL = new Property<BigDecimal>("forexUnlockedYearPl");
	public static final Property<BigDecimal> OTHER_OPEN_COMP_YR_PL = new Property<BigDecimal>("otherOpenCompYrPl");
	public static final Property<BigDecimal> OTHER_OPEN_DAY_PL = new Property<BigDecimal>("otherOpenDayPl");
	public static final Property<BigDecimal> OTHER_OPEN_LIFE_PL = new Property<BigDecimal>("otherOpenLifePl");
	public static final Property<BigDecimal> OTHER_OPEN_MONTH_PL = new Property<BigDecimal>("otherOpenMonthPl");
	public static final Property<BigDecimal> OTHER_OPEN_WEEK_PL = new Property<BigDecimal>("otherOpenWeekPl");
	public static final Property<BigDecimal> OTHER_OPEN_YEAR_PL = new Property<BigDecimal>("otherOpenYearPl");
	public static final Property<BigDecimal> OTHER_UNLOCKED_COMP_YR_PL = new Property<BigDecimal>("otherUnlockedCompYrPl");
	public static final Property<BigDecimal> OTHER_UNLOCKED_DAY_PL = new Property<BigDecimal>("otherUnlockedDayPl");
	public static final Property<BigDecimal> OTHER_UNLOCKED_LIFE_PL = new Property<BigDecimal>("otherUnlockedLifePl");
	public static final Property<BigDecimal> OTHER_UNLOCKED_MONTH_PL = new Property<BigDecimal>("otherUnlockedMonthPl");
	public static final Property<BigDecimal> OTHER_UNLOCKED_WEEK_PL = new Property<BigDecimal>("otherUnlockedWeekPl");
	public static final Property<BigDecimal> OTHER_UNLOCKED_YEAR_PL = new Property<BigDecimal>("otherUnlockedYearPl");
	public static final Property<BigDecimal> PRIMARY_OPEN_COMP_YR_PL = new Property<BigDecimal>("primaryOpenCompYrPl");
	public static final Property<BigDecimal> PRIMARY_OPEN_DAY_PL = new Property<BigDecimal>("primaryOpenDayPl");
	public static final Property<BigDecimal> PRIMARY_OPEN_LIFE_PL = new Property<BigDecimal>("primaryOpenLifePl");
	public static final Property<BigDecimal> PRIMARY_OPEN_MONTH_PL = new Property<BigDecimal>("primaryOpenMonthPl");
	public static final Property<BigDecimal> PRIMARY_OPEN_WEEK_PL = new Property<BigDecimal>("primaryOpenWeekPl");
	public static final Property<BigDecimal> PRIMARY_OPEN_YEAR_PL = new Property<BigDecimal>("primaryOpenYearPl");
	public static final Property<BigDecimal> PRIMARY_UNLOCKED_COMP_YR_PL = new Property<BigDecimal>("primaryUnlockedCompYrPl");
	public static final Property<BigDecimal> PRIMARY_UNLOCKED_DAY_PL = new Property<BigDecimal>("primaryUnlockedDayPl");
	public static final Property<BigDecimal> PRIMARY_UNLOCKED_LIFE_PL = new Property<BigDecimal>("primaryUnlockedLifePl");
	public static final Property<BigDecimal> PRIMARY_UNLOCKED_MONTH_PL = new Property<BigDecimal>("primaryUnlockedMonthPl");
	public static final Property<BigDecimal> PRIMARY_UNLOCKED_WEEK_PL = new Property<BigDecimal>("primaryUnlockedWeekPl");
	public static final Property<BigDecimal> PRIMARY_UNLOCKED_YEAR_PL = new Property<BigDecimal>("primaryUnlockedYearPl");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setForexOpenCompYrPl(BigDecimal forexOpenCompYrPl)
	{
		writeProperty("forexOpenCompYrPl", forexOpenCompYrPl);
	}

	public BigDecimal getForexOpenCompYrPl()
	{
		return (BigDecimal) readProperty("forexOpenCompYrPl");
	}

	public void setForexOpenDayPl(BigDecimal forexOpenDayPl)
	{
		writeProperty("forexOpenDayPl", forexOpenDayPl);
	}

	public BigDecimal getForexOpenDayPl()
	{
		return (BigDecimal) readProperty("forexOpenDayPl");
	}

	public void setForexOpenLifePl(BigDecimal forexOpenLifePl)
	{
		writeProperty("forexOpenLifePl", forexOpenLifePl);
	}

	public BigDecimal getForexOpenLifePl()
	{
		return (BigDecimal) readProperty("forexOpenLifePl");
	}

	public void setForexOpenMonthPl(BigDecimal forexOpenMonthPl)
	{
		writeProperty("forexOpenMonthPl", forexOpenMonthPl);
	}

	public BigDecimal getForexOpenMonthPl()
	{
		return (BigDecimal) readProperty("forexOpenMonthPl");
	}

	public void setForexOpenWeekPl(BigDecimal forexOpenWeekPl)
	{
		writeProperty("forexOpenWeekPl", forexOpenWeekPl);
	}

	public BigDecimal getForexOpenWeekPl()
	{
		return (BigDecimal) readProperty("forexOpenWeekPl");
	}

	public void setForexOpenYearPl(BigDecimal forexOpenYearPl)
	{
		writeProperty("forexOpenYearPl", forexOpenYearPl);
	}

	public BigDecimal getForexOpenYearPl()
	{
		return (BigDecimal) readProperty("forexOpenYearPl");
	}

	public void setForexUnlockedCompYrPl(BigDecimal forexUnlockedCompYrPl)
	{
		writeProperty("forexUnlockedCompYrPl", forexUnlockedCompYrPl);
	}

	public BigDecimal getForexUnlockedCompYrPl()
	{
		return (BigDecimal) readProperty("forexUnlockedCompYrPl");
	}

	public void setForexUnlockedDayPl(BigDecimal forexUnlockedDayPl)
	{
		writeProperty("forexUnlockedDayPl", forexUnlockedDayPl);
	}

	public BigDecimal getForexUnlockedDayPl()
	{
		return (BigDecimal) readProperty("forexUnlockedDayPl");
	}

	public void setForexUnlockedLifePl(BigDecimal forexUnlockedLifePl)
	{
		writeProperty("forexUnlockedLifePl", forexUnlockedLifePl);
	}

	public BigDecimal getForexUnlockedLifePl()
	{
		return (BigDecimal) readProperty("forexUnlockedLifePl");
	}

	public void setForexUnlockedMonthPl(BigDecimal forexUnlockedMonthPl)
	{
		writeProperty("forexUnlockedMonthPl", forexUnlockedMonthPl);
	}

	public BigDecimal getForexUnlockedMonthPl()
	{
		return (BigDecimal) readProperty("forexUnlockedMonthPl");
	}

	public void setForexUnlockedWeekPl(BigDecimal forexUnlockedWeekPl)
	{
		writeProperty("forexUnlockedWeekPl", forexUnlockedWeekPl);
	}

	public BigDecimal getForexUnlockedWeekPl()
	{
		return (BigDecimal) readProperty("forexUnlockedWeekPl");
	}

	public void setForexUnlockedYearPl(BigDecimal forexUnlockedYearPl)
	{
		writeProperty("forexUnlockedYearPl", forexUnlockedYearPl);
	}

	public BigDecimal getForexUnlockedYearPl()
	{
		return (BigDecimal) readProperty("forexUnlockedYearPl");
	}

	public void setOtherOpenCompYrPl(BigDecimal otherOpenCompYrPl)
	{
		writeProperty("otherOpenCompYrPl", otherOpenCompYrPl);
	}

	public BigDecimal getOtherOpenCompYrPl()
	{
		return (BigDecimal) readProperty("otherOpenCompYrPl");
	}

	public void setOtherOpenDayPl(BigDecimal otherOpenDayPl)
	{
		writeProperty("otherOpenDayPl", otherOpenDayPl);
	}

	public BigDecimal getOtherOpenDayPl()
	{
		return (BigDecimal) readProperty("otherOpenDayPl");
	}

	public void setOtherOpenLifePl(BigDecimal otherOpenLifePl)
	{
		writeProperty("otherOpenLifePl", otherOpenLifePl);
	}

	public BigDecimal getOtherOpenLifePl()
	{
		return (BigDecimal) readProperty("otherOpenLifePl");
	}

	public void setOtherOpenMonthPl(BigDecimal otherOpenMonthPl)
	{
		writeProperty("otherOpenMonthPl", otherOpenMonthPl);
	}

	public BigDecimal getOtherOpenMonthPl()
	{
		return (BigDecimal) readProperty("otherOpenMonthPl");
	}

	public void setOtherOpenWeekPl(BigDecimal otherOpenWeekPl)
	{
		writeProperty("otherOpenWeekPl", otherOpenWeekPl);
	}

	public BigDecimal getOtherOpenWeekPl()
	{
		return (BigDecimal) readProperty("otherOpenWeekPl");
	}

	public void setOtherOpenYearPl(BigDecimal otherOpenYearPl)
	{
		writeProperty("otherOpenYearPl", otherOpenYearPl);
	}

	public BigDecimal getOtherOpenYearPl()
	{
		return (BigDecimal) readProperty("otherOpenYearPl");
	}

	public void setOtherUnlockedCompYrPl(BigDecimal otherUnlockedCompYrPl)
	{
		writeProperty("otherUnlockedCompYrPl", otherUnlockedCompYrPl);
	}

	public BigDecimal getOtherUnlockedCompYrPl()
	{
		return (BigDecimal) readProperty("otherUnlockedCompYrPl");
	}

	public void setOtherUnlockedDayPl(BigDecimal otherUnlockedDayPl)
	{
		writeProperty("otherUnlockedDayPl", otherUnlockedDayPl);
	}

	public BigDecimal getOtherUnlockedDayPl()
	{
		return (BigDecimal) readProperty("otherUnlockedDayPl");
	}

	public void setOtherUnlockedLifePl(BigDecimal otherUnlockedLifePl)
	{
		writeProperty("otherUnlockedLifePl", otherUnlockedLifePl);
	}

	public BigDecimal getOtherUnlockedLifePl()
	{
		return (BigDecimal) readProperty("otherUnlockedLifePl");
	}

	public void setOtherUnlockedMonthPl(BigDecimal otherUnlockedMonthPl)
	{
		writeProperty("otherUnlockedMonthPl", otherUnlockedMonthPl);
	}

	public BigDecimal getOtherUnlockedMonthPl()
	{
		return (BigDecimal) readProperty("otherUnlockedMonthPl");
	}

	public void setOtherUnlockedWeekPl(BigDecimal otherUnlockedWeekPl)
	{
		writeProperty("otherUnlockedWeekPl", otherUnlockedWeekPl);
	}

	public BigDecimal getOtherUnlockedWeekPl()
	{
		return (BigDecimal) readProperty("otherUnlockedWeekPl");
	}

	public void setOtherUnlockedYearPl(BigDecimal otherUnlockedYearPl)
	{
		writeProperty("otherUnlockedYearPl", otherUnlockedYearPl);
	}

	public BigDecimal getOtherUnlockedYearPl()
	{
		return (BigDecimal) readProperty("otherUnlockedYearPl");
	}

	public void setPrimaryOpenCompYrPl(BigDecimal primaryOpenCompYrPl)
	{
		writeProperty("primaryOpenCompYrPl", primaryOpenCompYrPl);
	}

	public BigDecimal getPrimaryOpenCompYrPl()
	{
		return (BigDecimal) readProperty("primaryOpenCompYrPl");
	}

	public void setPrimaryOpenDayPl(BigDecimal primaryOpenDayPl)
	{
		writeProperty("primaryOpenDayPl", primaryOpenDayPl);
	}

	public BigDecimal getPrimaryOpenDayPl()
	{
		return (BigDecimal) readProperty("primaryOpenDayPl");
	}

	public void setPrimaryOpenLifePl(BigDecimal primaryOpenLifePl)
	{
		writeProperty("primaryOpenLifePl", primaryOpenLifePl);
	}

	public BigDecimal getPrimaryOpenLifePl()
	{
		return (BigDecimal) readProperty("primaryOpenLifePl");
	}

	public void setPrimaryOpenMonthPl(BigDecimal primaryOpenMonthPl)
	{
		writeProperty("primaryOpenMonthPl", primaryOpenMonthPl);
	}

	public BigDecimal getPrimaryOpenMonthPl()
	{
		return (BigDecimal) readProperty("primaryOpenMonthPl");
	}

	public void setPrimaryOpenWeekPl(BigDecimal primaryOpenWeekPl)
	{
		writeProperty("primaryOpenWeekPl", primaryOpenWeekPl);
	}

	public BigDecimal getPrimaryOpenWeekPl()
	{
		return (BigDecimal) readProperty("primaryOpenWeekPl");
	}

	public void setPrimaryOpenYearPl(BigDecimal primaryOpenYearPl)
	{
		writeProperty("primaryOpenYearPl", primaryOpenYearPl);
	}

	public BigDecimal getPrimaryOpenYearPl()
	{
		return (BigDecimal) readProperty("primaryOpenYearPl");
	}

	public void setPrimaryUnlockedCompYrPl(BigDecimal primaryUnlockedCompYrPl)
	{
		writeProperty("primaryUnlockedCompYrPl", primaryUnlockedCompYrPl);
	}

	public BigDecimal getPrimaryUnlockedCompYrPl()
	{
		return (BigDecimal) readProperty("primaryUnlockedCompYrPl");
	}

	public void setPrimaryUnlockedDayPl(BigDecimal primaryUnlockedDayPl)
	{
		writeProperty("primaryUnlockedDayPl", primaryUnlockedDayPl);
	}

	public BigDecimal getPrimaryUnlockedDayPl()
	{
		return (BigDecimal) readProperty("primaryUnlockedDayPl");
	}

	public void setPrimaryUnlockedLifePl(BigDecimal primaryUnlockedLifePl)
	{
		writeProperty("primaryUnlockedLifePl", primaryUnlockedLifePl);
	}

	public BigDecimal getPrimaryUnlockedLifePl()
	{
		return (BigDecimal) readProperty("primaryUnlockedLifePl");
	}

	public void setPrimaryUnlockedMonthPl(BigDecimal primaryUnlockedMonthPl)
	{
		writeProperty("primaryUnlockedMonthPl", primaryUnlockedMonthPl);
	}

	public BigDecimal getPrimaryUnlockedMonthPl()
	{
		return (BigDecimal) readProperty("primaryUnlockedMonthPl");
	}

	public void setPrimaryUnlockedWeekPl(BigDecimal primaryUnlockedWeekPl)
	{
		writeProperty("primaryUnlockedWeekPl", primaryUnlockedWeekPl);
	}

	public BigDecimal getPrimaryUnlockedWeekPl()
	{
		return (BigDecimal) readProperty("primaryUnlockedWeekPl");
	}

	public void setPrimaryUnlockedYearPl(BigDecimal primaryUnlockedYearPl)
	{
		writeProperty("primaryUnlockedYearPl", primaryUnlockedYearPl);
	}

	public BigDecimal getPrimaryUnlockedYearPl()
	{
		return (BigDecimal) readProperty("primaryUnlockedYearPl");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
