package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _GravityTableName was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _GravityTableName extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String GRAVITY_SOURCE_CODE_PK_COLUMN = "gravity_source_code";
	public static final String GRAVITY_TABLE_EFFECT_DATE_PK_COLUMN = "gravity_table_effect_date";
	public static final String GRAVITY_TABLE_NAME_PK_COLUMN = "gravity_table_name";

	public static final Property<String> GRAVITY_TABLE_STATUS = new Property<String>("gravityTableStatus");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<Uom> UOM = new Property<Uom>("uom");

	public void setGravityTableStatus(String gravityTableStatus)
	{
		writeProperty("gravityTableStatus", gravityTableStatus);
	}

	public String getGravityTableStatus()
	{
		return (String) readProperty("gravityTableStatus");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setUom(Uom uom)
	{
		setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) readProperty("uom");
	}

}
