package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _HistoricalVolatility was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _HistoricalVolatility extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String VOL_COMPUTE_DATE_PK_COLUMN = "vol_compute_date";

	public static final Property<Integer> COMMKT_KEY = new Property<Integer>("commktKey");
	public static final Property<String> TRADING_PRD = new Property<String>("tradingPrd");
	public static final Property<Double> VOLATILITY = new Property<Double>("volatility");

	public void setCommktKey(Integer commktKey)
	{
		writeProperty("commktKey", commktKey);
	}

	public Integer getCommktKey()
	{
		return (Integer) readProperty("commktKey");
	}

	public void setTradingPrd(String tradingPrd)
	{
		writeProperty("tradingPrd", tradingPrd);
	}

	public String getTradingPrd()
	{
		return (String) readProperty("tradingPrd");
	}

	public void setVolatility(Double volatility)
	{
		writeProperty("volatility", volatility);
	}

	public Double getVolatility()
	{
		return (Double) readProperty("volatility");
	}

}
