package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.EdplEvent;
import com.tc.app.exchangemonitor.model.cayenne.persistent.EntityTagDefinition;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ExtRefdataMapping;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ExtTrandataMapping;
import com.tc.app.exchangemonitor.model.cayenne.persistent.FeedRefdataMapping;
import com.tc.app.exchangemonitor.model.cayenne.persistent.FeedTransaction;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsMessageDetail;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TiFeedTransaction;
import com.tc.app.exchangemonitor.model.cayenne.persistent.UicReportModification;
import com.tc.app.exchangemonitor.model.cayenne.persistent.UicRptCriteria;
import com.tc.app.exchangemonitor.model.cayenne.persistent.UicRptCriteriaEntity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.UicRptValuesConfig;
import com.tc.app.exchangemonitor.model.cayenne.persistent.UicStatus;

/**
 * Class _IctsEntityName was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IctsEntityName extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> ENTITY_NAME = new Property<String>("entityName");
	public static final Property<String> ENTITY_STATUS = new Property<String>("entityStatus");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<List<EdplEvent>> EDPL_EVENTS = new Property<List<EdplEvent>>("edplEvents");
	public static final Property<UicStatus> ENTITY = new Property<UicStatus>("entity");
	public static final Property<List<EntityTagDefinition>> ENTITY_TAG_DEFINITIONS = new Property<List<EntityTagDefinition>>("entityTagDefinitions");
	public static final Property<List<EntityTagDefinition>> ENTITY_TAG_DEFINITIONS1 = new Property<List<EntityTagDefinition>>("entityTagDefinitions1");
	public static final Property<List<ExtRefdataMapping>> EXT_REFDATA_MAPPINGS = new Property<List<ExtRefdataMapping>>("extRefdataMappings");
	public static final Property<List<ExtTrandataMapping>> EXT_TRANDATA_MAPPINGS = new Property<List<ExtTrandataMapping>>("extTrandataMappings");
	public static final Property<List<FeedRefdataMapping>> FEED_REFDATA_MAPPINGS = new Property<List<FeedRefdataMapping>>("feedRefdataMappings");
	public static final Property<List<FeedTransaction>> FEED_TRANSACTIONS = new Property<List<FeedTransaction>>("feedTransactions");
	public static final Property<List<IctsMessageDetail>> ICTS_MESSAGE_DETAILS = new Property<List<IctsMessageDetail>>("ictsMessageDetails");
	public static final Property<List<TiFeedTransaction>> TI_FEED_TRANSACTIONS = new Property<List<TiFeedTransaction>>("tiFeedTransactions");
	public static final Property<List<UicReportModification>> UIC_REPORT_MODIFICATIONS = new Property<List<UicReportModification>>("uicReportModifications");
	public static final Property<List<UicRptCriteriaEntity>> UIC_RPT_CRITERIA_ENTITIES = new Property<List<UicRptCriteriaEntity>>("uicRptCriteriaEntities");
	public static final Property<List<UicRptCriteria>> UIC_RPT_CRITERIAS = new Property<List<UicRptCriteria>>("uicRptCriterias");
	public static final Property<List<UicRptValuesConfig>> UIC_RPT_VALUES_CONFIGS = new Property<List<UicRptValuesConfig>>("uicRptValuesConfigs");

	public void setEntityName(String entityName)
	{
		writeProperty("entityName", entityName);
	}

	public String getEntityName()
	{
		return (String) readProperty("entityName");
	}

	public void setEntityStatus(String entityStatus)
	{
		writeProperty("entityStatus", entityStatus);
	}

	public String getEntityStatus()
	{
		return (String) readProperty("entityStatus");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void addToEdplEvents(EdplEvent obj)
	{
		addToManyTarget("edplEvents", obj, true);
	}

	public void removeFromEdplEvents(EdplEvent obj)
	{
		removeToManyTarget("edplEvents", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<EdplEvent> getEdplEvents()
	{
		return (List<EdplEvent>) readProperty("edplEvents");
	}

	public void setEntity(UicStatus entity)
	{
		setToOneTarget("entity", entity, true);
	}

	public UicStatus getEntity()
	{
		return (UicStatus) readProperty("entity");
	}

	public void addToEntityTagDefinitions(EntityTagDefinition obj)
	{
		addToManyTarget("entityTagDefinitions", obj, true);
	}

	public void removeFromEntityTagDefinitions(EntityTagDefinition obj)
	{
		removeToManyTarget("entityTagDefinitions", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<EntityTagDefinition> getEntityTagDefinitions()
	{
		return (List<EntityTagDefinition>) readProperty("entityTagDefinitions");
	}

	public void addToEntityTagDefinitions1(EntityTagDefinition obj)
	{
		addToManyTarget("entityTagDefinitions1", obj, true);
	}

	public void removeFromEntityTagDefinitions1(EntityTagDefinition obj)
	{
		removeToManyTarget("entityTagDefinitions1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<EntityTagDefinition> getEntityTagDefinitions1()
	{
		return (List<EntityTagDefinition>) readProperty("entityTagDefinitions1");
	}

	public void addToExtRefdataMappings(ExtRefdataMapping obj)
	{
		addToManyTarget("extRefdataMappings", obj, true);
	}

	public void removeFromExtRefdataMappings(ExtRefdataMapping obj)
	{
		removeToManyTarget("extRefdataMappings", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ExtRefdataMapping> getExtRefdataMappings()
	{
		return (List<ExtRefdataMapping>) readProperty("extRefdataMappings");
	}

	public void addToExtTrandataMappings(ExtTrandataMapping obj)
	{
		addToManyTarget("extTrandataMappings", obj, true);
	}

	public void removeFromExtTrandataMappings(ExtTrandataMapping obj)
	{
		removeToManyTarget("extTrandataMappings", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ExtTrandataMapping> getExtTrandataMappings()
	{
		return (List<ExtTrandataMapping>) readProperty("extTrandataMappings");
	}

	public void addToFeedRefdataMappings(FeedRefdataMapping obj)
	{
		addToManyTarget("feedRefdataMappings", obj, true);
	}

	public void removeFromFeedRefdataMappings(FeedRefdataMapping obj)
	{
		removeToManyTarget("feedRefdataMappings", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FeedRefdataMapping> getFeedRefdataMappings()
	{
		return (List<FeedRefdataMapping>) readProperty("feedRefdataMappings");
	}

	public void addToFeedTransactions(FeedTransaction obj)
	{
		addToManyTarget("feedTransactions", obj, true);
	}

	public void removeFromFeedTransactions(FeedTransaction obj)
	{
		removeToManyTarget("feedTransactions", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FeedTransaction> getFeedTransactions()
	{
		return (List<FeedTransaction>) readProperty("feedTransactions");
	}

	public void addToIctsMessageDetails(IctsMessageDetail obj)
	{
		addToManyTarget("ictsMessageDetails", obj, true);
	}

	public void removeFromIctsMessageDetails(IctsMessageDetail obj)
	{
		removeToManyTarget("ictsMessageDetails", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<IctsMessageDetail> getIctsMessageDetails()
	{
		return (List<IctsMessageDetail>) readProperty("ictsMessageDetails");
	}

	public void addToTiFeedTransactions(TiFeedTransaction obj)
	{
		addToManyTarget("tiFeedTransactions", obj, true);
	}

	public void removeFromTiFeedTransactions(TiFeedTransaction obj)
	{
		removeToManyTarget("tiFeedTransactions", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<TiFeedTransaction> getTiFeedTransactions()
	{
		return (List<TiFeedTransaction>) readProperty("tiFeedTransactions");
	}

	public void addToUicReportModifications(UicReportModification obj)
	{
		addToManyTarget("uicReportModifications", obj, true);
	}

	public void removeFromUicReportModifications(UicReportModification obj)
	{
		removeToManyTarget("uicReportModifications", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<UicReportModification> getUicReportModifications()
	{
		return (List<UicReportModification>) readProperty("uicReportModifications");
	}

	public void addToUicRptCriteriaEntities(UicRptCriteriaEntity obj)
	{
		addToManyTarget("uicRptCriteriaEntities", obj, true);
	}

	public void removeFromUicRptCriteriaEntities(UicRptCriteriaEntity obj)
	{
		removeToManyTarget("uicRptCriteriaEntities", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<UicRptCriteriaEntity> getUicRptCriteriaEntities()
	{
		return (List<UicRptCriteriaEntity>) readProperty("uicRptCriteriaEntities");
	}

	public void addToUicRptCriterias(UicRptCriteria obj)
	{
		addToManyTarget("uicRptCriterias", obj, true);
	}

	public void removeFromUicRptCriterias(UicRptCriteria obj)
	{
		removeToManyTarget("uicRptCriterias", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<UicRptCriteria> getUicRptCriterias()
	{
		return (List<UicRptCriteria>) readProperty("uicRptCriterias");
	}

	public void addToUicRptValuesConfigs(UicRptValuesConfig obj)
	{
		addToManyTarget("uicRptValuesConfigs", obj, true);
	}

	public void removeFromUicRptValuesConfigs(UicRptValuesConfig obj)
	{
		removeToManyTarget("uicRptValuesConfigs", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<UicRptValuesConfig> getUicRptValuesConfigs()
	{
		return (List<UicRptValuesConfig>) readProperty("uicRptValuesConfigs");
	}

}
