package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _IctsTimezones was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IctsTimezones extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<String> TZ_ABBVR = new Property<String>("tzAbbvr");
	public static final Property<String> TZ_NAME = new Property<String>("tzName");
	public static final Property<Integer> TZ_UTC_OFFSET_HR = new Property<Integer>("tzUtcOffsetHr");
	public static final Property<Integer> TZ_UTC_OFFSET_MM = new Property<Integer>("tzUtcOffsetMm");

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setTzAbbvr(String tzAbbvr)
	{
		writeProperty("tzAbbvr", tzAbbvr);
	}

	public String getTzAbbvr()
	{
		return (String) readProperty("tzAbbvr");
	}

	public void setTzName(String tzName)
	{
		writeProperty("tzName", tzName);
	}

	public String getTzName()
	{
		return (String) readProperty("tzName");
	}

	public void setTzUtcOffsetHr(Integer tzUtcOffsetHr)
	{
		writeProperty("tzUtcOffsetHr", tzUtcOffsetHr);
	}

	public Integer getTzUtcOffsetHr()
	{
		return (Integer) readProperty("tzUtcOffsetHr");
	}

	public void setTzUtcOffsetMm(Integer tzUtcOffsetMm)
	{
		writeProperty("tzUtcOffsetMm", tzUtcOffsetMm);
	}

	public Integer getTzUtcOffsetMm()
	{
		return (Integer) readProperty("tzUtcOffsetMm");
	}

}
