package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _IctsTransportLog was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IctsTransportLog extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> FLDCHR_REC_ID = new Property<String>("fldchrRecId");
	public static final Property<Date> FLDDT_OP_DATA_TIME = new Property<Date>("flddtOpDataTime");
	public static final Property<String> FLDVCH_OPER_DESC = new Property<String>("fldvchOperDesc");
	public static final Property<String> FLDVCH_OPER_ENTITY = new Property<String>("fldvchOperEntity");
	public static final Property<String> FLDVCH_OPER_TYPE = new Property<String>("fldvchOperType");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<String> USER_LOGON_ID = new Property<String>("userLogonId");

	public void setFldchrRecId(String fldchrRecId)
	{
		writeProperty("fldchrRecId", fldchrRecId);
	}

	public String getFldchrRecId()
	{
		return (String) readProperty("fldchrRecId");
	}

	public void setFlddtOpDataTime(Date flddtOpDataTime)
	{
		writeProperty("flddtOpDataTime", flddtOpDataTime);
	}

	public Date getFlddtOpDataTime()
	{
		return (Date) readProperty("flddtOpDataTime");
	}

	public void setFldvchOperDesc(String fldvchOperDesc)
	{
		writeProperty("fldvchOperDesc", fldvchOperDesc);
	}

	public String getFldvchOperDesc()
	{
		return (String) readProperty("fldvchOperDesc");
	}

	public void setFldvchOperEntity(String fldvchOperEntity)
	{
		writeProperty("fldvchOperEntity", fldvchOperEntity);
	}

	public String getFldvchOperEntity()
	{
		return (String) readProperty("fldvchOperEntity");
	}

	public void setFldvchOperType(String fldvchOperType)
	{
		writeProperty("fldvchOperType", fldvchOperType);
	}

	public String getFldvchOperType()
	{
		return (String) readProperty("fldvchOperType");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setUserLogonId(String userLogonId)
	{
		writeProperty("userLogonId", userLogonId);
	}

	public String getUserLogonId()
	{
		return (String) readProperty("userLogonId");
	}

}
