package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsEntityName;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsMessage;

/**
 * Class _IctsMessageDetail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IctsMessageDetail extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> KEY1 = new Property<String>("key1");
	public static final Property<String> KEY2 = new Property<String>("key2");
	public static final Property<String> KEY3 = new Property<String>("key3");
	public static final Property<String> KEY4 = new Property<String>("key4");
	public static final Property<String> KEY5 = new Property<String>("key5");
	public static final Property<String> KEY6 = new Property<String>("key6");
	public static final Property<Integer> OP_TRANS_ID = new Property<Integer>("opTransId");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<IctsEntityName> ICTS_ENTITY = new Property<IctsEntityName>("ictsEntity");
	public static final Property<IctsMessage> MESSAGE = new Property<IctsMessage>("message");

	public void setKey1(String key1)
	{
		writeProperty("key1", key1);
	}

	public String getKey1()
	{
		return (String) readProperty("key1");
	}

	public void setKey2(String key2)
	{
		writeProperty("key2", key2);
	}

	public String getKey2()
	{
		return (String) readProperty("key2");
	}

	public void setKey3(String key3)
	{
		writeProperty("key3", key3);
	}

	public String getKey3()
	{
		return (String) readProperty("key3");
	}

	public void setKey4(String key4)
	{
		writeProperty("key4", key4);
	}

	public String getKey4()
	{
		return (String) readProperty("key4");
	}

	public void setKey5(String key5)
	{
		writeProperty("key5", key5);
	}

	public String getKey5()
	{
		return (String) readProperty("key5");
	}

	public void setKey6(String key6)
	{
		writeProperty("key6", key6);
	}

	public String getKey6()
	{
		return (String) readProperty("key6");
	}

	public void setOpTransId(Integer opTransId)
	{
		writeProperty("opTransId", opTransId);
	}

	public Integer getOpTransId()
	{
		return (Integer) readProperty("opTransId");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setIctsEntity(IctsEntityName ictsEntity)
	{
		setToOneTarget("ictsEntity", ictsEntity, true);
	}

	public IctsEntityName getIctsEntity()
	{
		return (IctsEntityName) readProperty("ictsEntity");
	}

	public void setMessage(IctsMessage message)
	{
		setToOneTarget("message", message, true);
	}

	public IctsMessage getMessage()
	{
		return (IctsMessage) readProperty("message");
	}

}
