package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsUser;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PriceSource;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TradingPeriod;

/**
 * Class _ImpliedPrCurve was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ImpliedPrCurve extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<BigDecimal> CLOSE_COLUMN = new Property<BigDecimal>("closeColumn");
	public static final Property<BigDecimal> HIGH = new Property<BigDecimal>("high");
	public static final Property<BigDecimal> IMPLIED = new Property<BigDecimal>("implied");
	public static final Property<BigDecimal> IMPLIED_CHANGE = new Property<BigDecimal>("impliedChange");
	public static final Property<BigDecimal> IMPLIED_SPREAD = new Property<BigDecimal>("impliedSpread");
	public static final Property<BigDecimal> LAST = new Property<BigDecimal>("last");
	public static final Property<BigDecimal> LOW = new Property<BigDecimal>("low");
	public static final Property<BigDecimal> NET_CHANGE = new Property<BigDecimal>("netChange");
	public static final Property<BigDecimal> NET_SPREAD = new Property<BigDecimal>("netSpread");
	public static final Property<BigDecimal> OPEN_INTEREST = new Property<BigDecimal>("openInterest");
	public static final Property<BigDecimal> OPEN_PRICE = new Property<BigDecimal>("openPrice");
	public static final Property<BigDecimal> PREVIOUS_CLOSE = new Property<BigDecimal>("previousClose");
	public static final Property<BigDecimal> SPREAD_CLOSE = new Property<BigDecimal>("spreadClose");
	public static final Property<BigDecimal> VOLUME_TRADED = new Property<BigDecimal>("volumeTraded");
	public static final Property<IctsUser> IMPLIED_EDITOR = new Property<IctsUser>("impliedEditor");
	public static final Property<IctsUser> IMPLIED_SPREAD_EDITOR = new Property<IctsUser>("impliedSpreadEditor");
	public static final Property<PriceSource> PRICE_SOURCE = new Property<PriceSource>("priceSource");
	public static final Property<TradingPeriod> TRADING_PERIOD = new Property<TradingPeriod>("tradingPeriod");
	public static final Property<TradingPeriod> TRADING_PERIOD1 = new Property<TradingPeriod>("tradingPeriod1");

	public void setCloseColumn(BigDecimal closeColumn)
	{
		writeProperty("closeColumn", closeColumn);
	}

	public BigDecimal getCloseColumn()
	{
		return (BigDecimal) readProperty("closeColumn");
	}

	public void setHigh(BigDecimal high)
	{
		writeProperty("high", high);
	}

	public BigDecimal getHigh()
	{
		return (BigDecimal) readProperty("high");
	}

	public void setImplied(BigDecimal implied)
	{
		writeProperty("implied", implied);
	}

	public BigDecimal getImplied()
	{
		return (BigDecimal) readProperty("implied");
	}

	public void setImpliedChange(BigDecimal impliedChange)
	{
		writeProperty("impliedChange", impliedChange);
	}

	public BigDecimal getImpliedChange()
	{
		return (BigDecimal) readProperty("impliedChange");
	}

	public void setImpliedSpread(BigDecimal impliedSpread)
	{
		writeProperty("impliedSpread", impliedSpread);
	}

	public BigDecimal getImpliedSpread()
	{
		return (BigDecimal) readProperty("impliedSpread");
	}

	public void setLast(BigDecimal last)
	{
		writeProperty("last", last);
	}

	public BigDecimal getLast()
	{
		return (BigDecimal) readProperty("last");
	}

	public void setLow(BigDecimal low)
	{
		writeProperty("low", low);
	}

	public BigDecimal getLow()
	{
		return (BigDecimal) readProperty("low");
	}

	public void setNetChange(BigDecimal netChange)
	{
		writeProperty("netChange", netChange);
	}

	public BigDecimal getNetChange()
	{
		return (BigDecimal) readProperty("netChange");
	}

	public void setNetSpread(BigDecimal netSpread)
	{
		writeProperty("netSpread", netSpread);
	}

	public BigDecimal getNetSpread()
	{
		return (BigDecimal) readProperty("netSpread");
	}

	public void setOpenInterest(BigDecimal openInterest)
	{
		writeProperty("openInterest", openInterest);
	}

	public BigDecimal getOpenInterest()
	{
		return (BigDecimal) readProperty("openInterest");
	}

	public void setOpenPrice(BigDecimal openPrice)
	{
		writeProperty("openPrice", openPrice);
	}

	public BigDecimal getOpenPrice()
	{
		return (BigDecimal) readProperty("openPrice");
	}

	public void setPreviousClose(BigDecimal previousClose)
	{
		writeProperty("previousClose", previousClose);
	}

	public BigDecimal getPreviousClose()
	{
		return (BigDecimal) readProperty("previousClose");
	}

	public void setSpreadClose(BigDecimal spreadClose)
	{
		writeProperty("spreadClose", spreadClose);
	}

	public BigDecimal getSpreadClose()
	{
		return (BigDecimal) readProperty("spreadClose");
	}

	public void setVolumeTraded(BigDecimal volumeTraded)
	{
		writeProperty("volumeTraded", volumeTraded);
	}

	public BigDecimal getVolumeTraded()
	{
		return (BigDecimal) readProperty("volumeTraded");
	}

	public void setImpliedEditor(IctsUser impliedEditor)
	{
		setToOneTarget("impliedEditor", impliedEditor, true);
	}

	public IctsUser getImpliedEditor()
	{
		return (IctsUser) readProperty("impliedEditor");
	}

	public void setImpliedSpreadEditor(IctsUser impliedSpreadEditor)
	{
		setToOneTarget("impliedSpreadEditor", impliedSpreadEditor, true);
	}

	public IctsUser getImpliedSpreadEditor()
	{
		return (IctsUser) readProperty("impliedSpreadEditor");
	}

	public void setPriceSource(PriceSource priceSource)
	{
		setToOneTarget("priceSource", priceSource, true);
	}

	public PriceSource getPriceSource()
	{
		return (PriceSource) readProperty("priceSource");
	}

	public void setTradingPeriod(TradingPeriod tradingPeriod)
	{
		setToOneTarget("tradingPeriod", tradingPeriod, true);
	}

	public TradingPeriod getTradingPeriod()
	{
		return (TradingPeriod) readProperty("tradingPeriod");
	}

	public void setTradingPeriod1(TradingPeriod tradingPeriod1)
	{
		setToOneTarget("tradingPeriod1", tradingPeriod1, true);
	}

	public TradingPeriod getTradingPeriod1()
	{
		return (TradingPeriod) readProperty("tradingPeriod1");
	}

}
