package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Specification;

/**
 * Class _InvBuildDrawSpec was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InvBuildDrawSpec extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String INV_B_D_NUM_PK_COLUMN = "inv_b_d_num";
	public static final String INV_NUM_PK_COLUMN = "inv_num";
	public static final String SPEC_CODE_PK_COLUMN = "spec_code";

	public static final Property<Double> SPEC_ACTUAL_VALUE = new Property<Double>("specActualValue");
	public static final Property<String> SPEC_ACTUAL_VALUE_TEXT = new Property<String>("specActualValueText");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Specification> SPECIFICATION = new Property<Specification>("specification");

	public void setSpecActualValue(Double specActualValue)
	{
		writeProperty("specActualValue", specActualValue);
	}

	public Double getSpecActualValue()
	{
		return (Double) readProperty("specActualValue");
	}

	public void setSpecActualValueText(String specActualValueText)
	{
		writeProperty("specActualValueText", specActualValueText);
	}

	public String getSpecActualValueText()
	{
		return (String) readProperty("specActualValueText");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setSpecification(Specification specification)
	{
		setToOneTarget("specification", specification, true);
	}

	public Specification getSpecification()
	{
		return (Specification) readProperty("specification");
	}

}
