package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.InvActualFifo;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Inventory;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _InvActual was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InvActual extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<Date> ACTUAL_DATE = new Property<Date>("actualDate");
	public static final Property<Double> ACTUAL_QTY = new Property<Double>("actualQty");
	public static final Property<Double> ADJUSTMENT_QTY = new Property<Double>("adjustmentQty");
	public static final Property<Short> AI_EST_ACTUAL_NUM = new Property<Short>("aiEstActualNum");
	public static final Property<Short> ALLOC_ITEM_NUM = new Property<Short>("allocItemNum");
	public static final Property<Integer> ALLOC_NUM = new Property<Integer>("allocNum");
	public static final Property<Double> AVG_PRICE = new Property<Double>("avgPrice");
	public static final Property<String> BUILD_DRAW_IND = new Property<String>("buildDrawInd");
	public static final Property<Integer> FIELD1 = new Property<Integer>("field1");
	public static final Property<Double> FIELD2 = new Property<Double>("field2");
	public static final Property<String> FIELD3 = new Property<String>("field3");
	public static final Property<Date> FIELD4 = new Property<Date>("field4");
	public static final Property<Double> FIFOED_QTY = new Property<Double>("fifoedQty");
	public static final Property<Integer> INV_BDNUM = new Property<Integer>("invBDNum");
	public static final Property<Integer> INV_FIFO_NUM = new Property<Integer>("invFifoNum");
	public static final Property<BigDecimal> NEG_ADJ_QTY = new Property<BigDecimal>("negAdjQty");
	public static final Property<Double> OPEN_QTY = new Property<Double>("openQty");
	public static final Property<BigDecimal> POS_ADJ_QTY = new Property<BigDecimal>("posAdjQty");
	public static final Property<Double> REAL_AVG_PRICE = new Property<Double>("realAvgPrice");
	public static final Property<Double> SEC_ACTUAL_QTY = new Property<Double>("secActualQty");
	public static final Property<Double> SEC_ADJUSTMENT_QTY = new Property<Double>("secAdjustmentQty");
	public static final Property<Double> SEC_FIFOED_QTY = new Property<Double>("secFifoedQty");
	public static final Property<Double> SEC_OPEN_QTY = new Property<Double>("secOpenQty");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Double> UNREAL_AVG_PRICE = new Property<Double>("unrealAvgPrice");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<List<InvActualFifo>> INV_ACTUAL_FIFOES = new Property<List<InvActualFifo>>("invActualFifoes");
	public static final Property<List<InvActualFifo>> INV_ACTUAL_FIFOES1 = new Property<List<InvActualFifo>>("invActualFifoes1");
	public static final Property<Inventory> INVENTORY = new Property<Inventory>("inventory");
	public static final Property<Uom> UOM = new Property<Uom>("uom");
	public static final Property<Uom> UOM1 = new Property<Uom>("uom1");
	public static final Property<Uom> UOM2 = new Property<Uom>("uom2");

	public void setActualDate(Date actualDate)
	{
		writeProperty("actualDate", actualDate);
	}

	public Date getActualDate()
	{
		return (Date) readProperty("actualDate");
	}

	public void setActualQty(Double actualQty)
	{
		writeProperty("actualQty", actualQty);
	}

	public Double getActualQty()
	{
		return (Double) readProperty("actualQty");
	}

	public void setAdjustmentQty(Double adjustmentQty)
	{
		writeProperty("adjustmentQty", adjustmentQty);
	}

	public Double getAdjustmentQty()
	{
		return (Double) readProperty("adjustmentQty");
	}

	public void setAiEstActualNum(Short aiEstActualNum)
	{
		writeProperty("aiEstActualNum", aiEstActualNum);
	}

	public Short getAiEstActualNum()
	{
		return (Short) readProperty("aiEstActualNum");
	}

	public void setAllocItemNum(Short allocItemNum)
	{
		writeProperty("allocItemNum", allocItemNum);
	}

	public Short getAllocItemNum()
	{
		return (Short) readProperty("allocItemNum");
	}

	public void setAllocNum(Integer allocNum)
	{
		writeProperty("allocNum", allocNum);
	}

	public Integer getAllocNum()
	{
		return (Integer) readProperty("allocNum");
	}

	public void setAvgPrice(Double avgPrice)
	{
		writeProperty("avgPrice", avgPrice);
	}

	public Double getAvgPrice()
	{
		return (Double) readProperty("avgPrice");
	}

	public void setBuildDrawInd(String buildDrawInd)
	{
		writeProperty("buildDrawInd", buildDrawInd);
	}

	public String getBuildDrawInd()
	{
		return (String) readProperty("buildDrawInd");
	}

	public void setField1(Integer field1)
	{
		writeProperty("field1", field1);
	}

	public Integer getField1()
	{
		return (Integer) readProperty("field1");
	}

	public void setField2(Double field2)
	{
		writeProperty("field2", field2);
	}

	public Double getField2()
	{
		return (Double) readProperty("field2");
	}

	public void setField3(String field3)
	{
		writeProperty("field3", field3);
	}

	public String getField3()
	{
		return (String) readProperty("field3");
	}

	public void setField4(Date field4)
	{
		writeProperty("field4", field4);
	}

	public Date getField4()
	{
		return (Date) readProperty("field4");
	}

	public void setFifoedQty(Double fifoedQty)
	{
		writeProperty("fifoedQty", fifoedQty);
	}

	public Double getFifoedQty()
	{
		return (Double) readProperty("fifoedQty");
	}

	public void setInvBDNum(Integer invBDNum)
	{
		writeProperty("invBDNum", invBDNum);
	}

	public Integer getInvBDNum()
	{
		return (Integer) readProperty("invBDNum");
	}

	public void setInvFifoNum(Integer invFifoNum)
	{
		writeProperty("invFifoNum", invFifoNum);
	}

	public Integer getInvFifoNum()
	{
		return (Integer) readProperty("invFifoNum");
	}

	public void setNegAdjQty(BigDecimal negAdjQty)
	{
		writeProperty("negAdjQty", negAdjQty);
	}

	public BigDecimal getNegAdjQty()
	{
		return (BigDecimal) readProperty("negAdjQty");
	}

	public void setOpenQty(Double openQty)
	{
		writeProperty("openQty", openQty);
	}

	public Double getOpenQty()
	{
		return (Double) readProperty("openQty");
	}

	public void setPosAdjQty(BigDecimal posAdjQty)
	{
		writeProperty("posAdjQty", posAdjQty);
	}

	public BigDecimal getPosAdjQty()
	{
		return (BigDecimal) readProperty("posAdjQty");
	}

	public void setRealAvgPrice(Double realAvgPrice)
	{
		writeProperty("realAvgPrice", realAvgPrice);
	}

	public Double getRealAvgPrice()
	{
		return (Double) readProperty("realAvgPrice");
	}

	public void setSecActualQty(Double secActualQty)
	{
		writeProperty("secActualQty", secActualQty);
	}

	public Double getSecActualQty()
	{
		return (Double) readProperty("secActualQty");
	}

	public void setSecAdjustmentQty(Double secAdjustmentQty)
	{
		writeProperty("secAdjustmentQty", secAdjustmentQty);
	}

	public Double getSecAdjustmentQty()
	{
		return (Double) readProperty("secAdjustmentQty");
	}

	public void setSecFifoedQty(Double secFifoedQty)
	{
		writeProperty("secFifoedQty", secFifoedQty);
	}

	public Double getSecFifoedQty()
	{
		return (Double) readProperty("secFifoedQty");
	}

	public void setSecOpenQty(Double secOpenQty)
	{
		writeProperty("secOpenQty", secOpenQty);
	}

	public Double getSecOpenQty()
	{
		return (Double) readProperty("secOpenQty");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setUnrealAvgPrice(Double unrealAvgPrice)
	{
		writeProperty("unrealAvgPrice", unrealAvgPrice);
	}

	public Double getUnrealAvgPrice()
	{
		return (Double) readProperty("unrealAvgPrice");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void addToInvActualFifoes(InvActualFifo obj)
	{
		addToManyTarget("invActualFifoes", obj, true);
	}

	public void removeFromInvActualFifoes(InvActualFifo obj)
	{
		removeToManyTarget("invActualFifoes", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<InvActualFifo> getInvActualFifoes()
	{
		return (List<InvActualFifo>) readProperty("invActualFifoes");
	}

	public void addToInvActualFifoes1(InvActualFifo obj)
	{
		addToManyTarget("invActualFifoes1", obj, true);
	}

	public void removeFromInvActualFifoes1(InvActualFifo obj)
	{
		removeToManyTarget("invActualFifoes1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<InvActualFifo> getInvActualFifoes1()
	{
		return (List<InvActualFifo>) readProperty("invActualFifoes1");
	}

	public void setInventory(Inventory inventory)
	{
		setToOneTarget("inventory", inventory, true);
	}

	public Inventory getInventory()
	{
		return (Inventory) readProperty("inventory");
	}

	public void setUom(Uom uom)
	{
		setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) readProperty("uom");
	}

	public void setUom1(Uom uom1)
	{
		setToOneTarget("uom1", uom1, true);
	}

	public Uom getUom1()
	{
		return (Uom) readProperty("uom1");
	}

	public void setUom2(Uom uom2)
	{
		setToOneTarget("uom2", uom2, true);
	}

	public Uom getUom2()
	{
		return (Uom) readProperty("uom2");
	}

}
