package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CollateralType;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsUser;
import com.tc.app.exchangemonitor.model.cayenne.persistent.LcStatus;
import com.tc.app.exchangemonitor.model.cayenne.persistent.LcType;
import com.tc.app.exchangemonitor.model.cayenne.persistent.LcUsage;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Location;

/**
 * Class _Lc was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Lc extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String LC_NUM_PK_COLUMN = "lc_num";

	public static final Property<String> EXTERNAL_REF_KEY = new Property<>("externalRefKey");
	public static final Property<Integer> GUARANTOR_ACCT_NUM = new Property<>("guarantorAcctNum");
	public static final Property<Date> LC_CONFIRM_DATE = new Property<>("lcConfirmDate");
	public static final Property<String> LC_CONFIRM_REQD_IND = new Property<>("lcConfirmReqdInd");
	public static final Property<String> LC_CUSTOM_COLUMN1 = new Property<>("lcCustomColumn1");
	public static final Property<String> LC_CUSTOM_COLUMN2 = new Property<>("lcCustomColumn2");
	public static final Property<String> LC_DISPUTE_IND = new Property<>("lcDisputeInd");
	public static final Property<String> LC_DISPUTE_STATUS = new Property<>("lcDisputeStatus");
	public static final Property<Short> LC_EVERGREEN_EXT_DAYS = new Property<>("lcEvergreenExtDays");
	public static final Property<Short> LC_EVERGREEN_ROLL_DAYS = new Property<>("lcEvergreenRollDays");
	public static final Property<String> LC_EVERGREEN_STATUS = new Property<>("lcEvergreenStatus");
	public static final Property<Date> LC_EXP_DATE = new Property<>("lcExpDate");
	public static final Property<Short> LC_EXP_DAYS = new Property<>("lcExpDays");
	public static final Property<String> LC_EXP_DAYS_OPER = new Property<>("lcExpDaysOper");
	public static final Property<String> LC_EXP_EVENT = new Property<>("lcExpEvent");
	public static final Property<String> LC_EXP_IMP_IND = new Property<>("lcExpImpInd");
	public static final Property<String> LC_FINAL_IND = new Property<>("lcFinalInd");
	public static final Property<Date> LC_ISSUE_DATE = new Property<>("lcIssueDate");
	public static final Property<String> LC_LOI_PRESENTED_IND = new Property<>("lcLoiPresentedInd");
	public static final Property<String> LC_NEGOTIATE_CLAUSE = new Property<>("lcNegotiateClause");
	public static final Property<String> LC_NETTING_IND = new Property<>("lcNettingInd");
	public static final Property<String> LC_PRIORITY = new Property<>("lcPriority");
	public static final Property<Date> LC_REQUEST_DATE = new Property<>("lcRequestDate");
	public static final Property<String> LC_SHORT_CMNT = new Property<>("lcShortCmnt");
	public static final Property<String> LC_STALE_DOC_ALLOW_IND = new Property<>("lcStaleDocAllowInd");
	public static final Property<Short> LC_STALE_DOC_DAYS = new Property<>("lcStaleDocDays");
	public static final Property<String> LC_TEMPLATE_IND = new Property<>("lcTemplateInd");
	public static final Property<String> LC_TEMPLATE_NAME = new Property<>("lcTemplateName");
	public static final Property<String> LC_TRANSACT_OR_BLANKET = new Property<>("lcTransactOrBlanket");
	public static final Property<String> OTHER_LCS_REL_IND = new Property<>("otherLcsRelInd");
	public static final Property<String> PCG_TYPE_CODE = new Property<>("pcgTypeCode");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<Account> ACCOUNT = new Property<>("account");
	public static final Property<Account> ACCOUNT1 = new Property<>("account1");
	public static final Property<Account> ACCOUNT2 = new Property<>("account2");
	public static final Property<Account> ACCOUNT3 = new Property<>("account3");
	public static final Property<Account> ACCOUNT4 = new Property<>("account4");
	public static final Property<Account> ACCOUNT5 = new Property<>("account5");
	public static final Property<CollateralType> COLLATERAL_TYPE = new Property<>("collateralType");
	public static final Property<IctsUser> ICTS_USER = new Property<>("ictsUser");
	public static final Property<IctsUser> ICTS_USER1 = new Property<>("ictsUser1");
	public static final Property<LcStatus> LC_STATUS = new Property<>("lcStatus");
	public static final Property<LcType> LC_TYPE = new Property<>("lcType");
	public static final Property<LcUsage> LC_USAGE = new Property<>("lcUsage");
	public static final Property<Location> LOCATION = new Property<>("location");

	public void setExternalRefKey(final String externalRefKey)
	{
		this.writeProperty("externalRefKey", externalRefKey);
	}

	public String getExternalRefKey()
	{
		return (String) this.readProperty("externalRefKey");
	}

	public void setGuarantorAcctNum(final Integer guarantorAcctNum)
	{
		this.writeProperty("guarantorAcctNum", guarantorAcctNum);
	}

	public Integer getGuarantorAcctNum()
	{
		return (Integer) this.readProperty("guarantorAcctNum");
	}

	public void setLcConfirmDate(final Date lcConfirmDate)
	{
		this.writeProperty("lcConfirmDate", lcConfirmDate);
	}

	public Date getLcConfirmDate()
	{
		return (Date) this.readProperty("lcConfirmDate");
	}

	public void setLcConfirmReqdInd(final String lcConfirmReqdInd)
	{
		this.writeProperty("lcConfirmReqdInd", lcConfirmReqdInd);
	}

	public String getLcConfirmReqdInd()
	{
		return (String) this.readProperty("lcConfirmReqdInd");
	}

	public void setLcCustomColumn1(final String lcCustomColumn1)
	{
		this.writeProperty("lcCustomColumn1", lcCustomColumn1);
	}

	public String getLcCustomColumn1()
	{
		return (String) this.readProperty("lcCustomColumn1");
	}

	public void setLcCustomColumn2(final String lcCustomColumn2)
	{
		this.writeProperty("lcCustomColumn2", lcCustomColumn2);
	}

	public String getLcCustomColumn2()
	{
		return (String) this.readProperty("lcCustomColumn2");
	}

	public void setLcDisputeInd(final String lcDisputeInd)
	{
		this.writeProperty("lcDisputeInd", lcDisputeInd);
	}

	public String getLcDisputeInd()
	{
		return (String) this.readProperty("lcDisputeInd");
	}

	public void setLcDisputeStatus(final String lcDisputeStatus)
	{
		this.writeProperty("lcDisputeStatus", lcDisputeStatus);
	}

	public String getLcDisputeStatus()
	{
		return (String) this.readProperty("lcDisputeStatus");
	}

	public void setLcEvergreenExtDays(final Short lcEvergreenExtDays)
	{
		this.writeProperty("lcEvergreenExtDays", lcEvergreenExtDays);
	}

	public Short getLcEvergreenExtDays()
	{
		return (Short) this.readProperty("lcEvergreenExtDays");
	}

	public void setLcEvergreenRollDays(final Short lcEvergreenRollDays)
	{
		this.writeProperty("lcEvergreenRollDays", lcEvergreenRollDays);
	}

	public Short getLcEvergreenRollDays()
	{
		return (Short) this.readProperty("lcEvergreenRollDays");
	}

	public void setLcEvergreenStatus(final String lcEvergreenStatus)
	{
		this.writeProperty("lcEvergreenStatus", lcEvergreenStatus);
	}

	public String getLcEvergreenStatus()
	{
		return (String) this.readProperty("lcEvergreenStatus");
	}

	public void setLcExpDate(final Date lcExpDate)
	{
		this.writeProperty("lcExpDate", lcExpDate);
	}

	public Date getLcExpDate()
	{
		return (Date) this.readProperty("lcExpDate");
	}

	public void setLcExpDays(final Short lcExpDays)
	{
		this.writeProperty("lcExpDays", lcExpDays);
	}

	public Short getLcExpDays()
	{
		return (Short) this.readProperty("lcExpDays");
	}

	public void setLcExpDaysOper(final String lcExpDaysOper)
	{
		this.writeProperty("lcExpDaysOper", lcExpDaysOper);
	}

	public String getLcExpDaysOper()
	{
		return (String) this.readProperty("lcExpDaysOper");
	}

	public void setLcExpEvent(final String lcExpEvent)
	{
		this.writeProperty("lcExpEvent", lcExpEvent);
	}

	public String getLcExpEvent()
	{
		return (String) this.readProperty("lcExpEvent");
	}

	public void setLcExpImpInd(final String lcExpImpInd)
	{
		this.writeProperty("lcExpImpInd", lcExpImpInd);
	}

	public String getLcExpImpInd()
	{
		return (String) this.readProperty("lcExpImpInd");
	}

	public void setLcFinalInd(final String lcFinalInd)
	{
		this.writeProperty("lcFinalInd", lcFinalInd);
	}

	public String getLcFinalInd()
	{
		return (String) this.readProperty("lcFinalInd");
	}

	public void setLcIssueDate(final Date lcIssueDate)
	{
		this.writeProperty("lcIssueDate", lcIssueDate);
	}

	public Date getLcIssueDate()
	{
		return (Date) this.readProperty("lcIssueDate");
	}

	public void setLcLoiPresentedInd(final String lcLoiPresentedInd)
	{
		this.writeProperty("lcLoiPresentedInd", lcLoiPresentedInd);
	}

	public String getLcLoiPresentedInd()
	{
		return (String) this.readProperty("lcLoiPresentedInd");
	}

	public void setLcNegotiateClause(final String lcNegotiateClause)
	{
		this.writeProperty("lcNegotiateClause", lcNegotiateClause);
	}

	public String getLcNegotiateClause()
	{
		return (String) this.readProperty("lcNegotiateClause");
	}

	public void setLcNettingInd(final String lcNettingInd)
	{
		this.writeProperty("lcNettingInd", lcNettingInd);
	}

	public String getLcNettingInd()
	{
		return (String) this.readProperty("lcNettingInd");
	}

	public void setLcPriority(final String lcPriority)
	{
		this.writeProperty("lcPriority", lcPriority);
	}

	public String getLcPriority()
	{
		return (String) this.readProperty("lcPriority");
	}

	public void setLcRequestDate(final Date lcRequestDate)
	{
		this.writeProperty("lcRequestDate", lcRequestDate);
	}

	public Date getLcRequestDate()
	{
		return (Date) this.readProperty("lcRequestDate");
	}

	public void setLcShortCmnt(final String lcShortCmnt)
	{
		this.writeProperty("lcShortCmnt", lcShortCmnt);
	}

	public String getLcShortCmnt()
	{
		return (String) this.readProperty("lcShortCmnt");
	}

	public void setLcStaleDocAllowInd(final String lcStaleDocAllowInd)
	{
		this.writeProperty("lcStaleDocAllowInd", lcStaleDocAllowInd);
	}

	public String getLcStaleDocAllowInd()
	{
		return (String) this.readProperty("lcStaleDocAllowInd");
	}

	public void setLcStaleDocDays(final Short lcStaleDocDays)
	{
		this.writeProperty("lcStaleDocDays", lcStaleDocDays);
	}

	public Short getLcStaleDocDays()
	{
		return (Short) this.readProperty("lcStaleDocDays");
	}

	public void setLcTemplateInd(final String lcTemplateInd)
	{
		this.writeProperty("lcTemplateInd", lcTemplateInd);
	}

	public String getLcTemplateInd()
	{
		return (String) this.readProperty("lcTemplateInd");
	}

	public void setLcTemplateName(final String lcTemplateName)
	{
		this.writeProperty("lcTemplateName", lcTemplateName);
	}

	public String getLcTemplateName()
	{
		return (String) this.readProperty("lcTemplateName");
	}

	public void setLcTransactOrBlanket(final String lcTransactOrBlanket)
	{
		this.writeProperty("lcTransactOrBlanket", lcTransactOrBlanket);
	}

	public String getLcTransactOrBlanket()
	{
		return (String) this.readProperty("lcTransactOrBlanket");
	}

	public void setOtherLcsRelInd(final String otherLcsRelInd)
	{
		this.writeProperty("otherLcsRelInd", otherLcsRelInd);
	}

	public String getOtherLcsRelInd()
	{
		return (String) this.readProperty("otherLcsRelInd");
	}

	public void setPcgTypeCode(final String pcgTypeCode)
	{
		this.writeProperty("pcgTypeCode", pcgTypeCode);
	}

	public String getPcgTypeCode()
	{
		return (String) this.readProperty("pcgTypeCode");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setAccount(final Account account)
	{
		this.setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) this.readProperty("account");
	}

	public void setAccount1(final Account account1)
	{
		this.setToOneTarget("account1", account1, true);
	}

	public Account getAccount1()
	{
		return (Account) this.readProperty("account1");
	}

	public void setAccount2(final Account account2)
	{
		this.setToOneTarget("account2", account2, true);
	}

	public Account getAccount2()
	{
		return (Account) this.readProperty("account2");
	}

	public void setAccount3(final Account account3)
	{
		this.setToOneTarget("account3", account3, true);
	}

	public Account getAccount3()
	{
		return (Account) this.readProperty("account3");
	}

	public void setAccount4(final Account account4)
	{
		this.setToOneTarget("account4", account4, true);
	}

	public Account getAccount4()
	{
		return (Account) this.readProperty("account4");
	}

	public void setAccount5(final Account account5)
	{
		this.setToOneTarget("account5", account5, true);
	}

	public Account getAccount5()
	{
		return (Account) this.readProperty("account5");
	}

	public void setCollateralType(final CollateralType collateralType)
	{
		this.setToOneTarget("collateralType", collateralType, true);
	}

	public CollateralType getCollateralType()
	{
		return (CollateralType) this.readProperty("collateralType");
	}

	public void setIctsUser(final IctsUser ictsUser)
	{
		this.setToOneTarget("ictsUser", ictsUser, true);
	}

	public IctsUser getIctsUser()
	{
		return (IctsUser) this.readProperty("ictsUser");
	}

	public void setIctsUser1(final IctsUser ictsUser1)
	{
		this.setToOneTarget("ictsUser1", ictsUser1, true);
	}

	public IctsUser getIctsUser1()
	{
		return (IctsUser) this.readProperty("ictsUser1");
	}

	public void setLcStatus(final LcStatus lcStatus)
	{
		this.setToOneTarget("lcStatus", lcStatus, true);
	}

	public LcStatus getLcStatus()
	{
		return (LcStatus) this.readProperty("lcStatus");
	}

	public void setLcType(final LcType lcType)
	{
		this.setToOneTarget("lcType", lcType, true);
	}

	public LcType getLcType()
	{
		return (LcType) this.readProperty("lcType");
	}

	public void setLcUsage(final LcUsage lcUsage)
	{
		this.setToOneTarget("lcUsage", lcUsage, true);
	}

	public LcUsage getLcUsage()
	{
		return (LcUsage) this.readProperty("lcUsage");
	}

	public void setLocation(final Location location)
	{
		this.setToOneTarget("location", location, true);
	}

	public Location getLocation()
	{
		return (Location) this.readProperty("location");
	}

}
