package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Lc;
import com.tc.app.exchangemonitor.model.cayenne.persistent.LcStatusHistory;

/**
 * Class _LcStatus was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LcStatus extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String LC_STATUS_CODE_PK_COLUMN = "lc_status_code";

	public static final Property<String> LC_STATUS_DESC = new Property<String>("lcStatusDesc");
	public static final Property<String> LC_STATUS_SHORT_NAME = new Property<String>("lcStatusShortName");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<List<LcStatusHistory>> LC_STATUS_HISTORIES = new Property<List<LcStatusHistory>>("lcStatusHistories");
	public static final Property<List<Lc>> LCS = new Property<List<Lc>>("lcs");

	public void setLcStatusDesc(String lcStatusDesc)
	{
		writeProperty("lcStatusDesc", lcStatusDesc);
	}

	public String getLcStatusDesc()
	{
		return (String) readProperty("lcStatusDesc");
	}

	public void setLcStatusShortName(String lcStatusShortName)
	{
		writeProperty("lcStatusShortName", lcStatusShortName);
	}

	public String getLcStatusShortName()
	{
		return (String) readProperty("lcStatusShortName");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void addToLcStatusHistories(LcStatusHistory obj)
	{
		addToManyTarget("lcStatusHistories", obj, true);
	}

	public void removeFromLcStatusHistories(LcStatusHistory obj)
	{
		removeToManyTarget("lcStatusHistories", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<LcStatusHistory> getLcStatusHistories()
	{
		return (List<LcStatusHistory>) readProperty("lcStatusHistories");
	}

	public void addToLcs(Lc obj)
	{
		addToManyTarget("lcs", obj, true);
	}

	public void removeFromLcs(Lc obj)
	{
		removeToManyTarget("lcs", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<Lc> getLcs()
	{
		return (List<Lc>) readProperty("lcs");
	}

}
