package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Location;
import com.tc.app.exchangemonitor.model.cayenne.persistent.VesselCardsAvailablePort;

/**
 * Class _LocationData was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LocationData extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_LOCT_KEY_PK_COLUMN = "fldchrLoctKey";

	public static final Property<String> FLDCHR_MINUS = new Property<>("fldchrMinus");
	public static final Property<String> FLDCHR_PLUS = new Property<>("fldchrPlus");
	public static final Property<String> FLDCHR_USER_NAME = new Property<>("fldchrUserName");
	public static final Property<BigDecimal> FLDDBL_AVERAGE_LURATE = new Property<>("flddblAverageLURate");
	public static final Property<BigDecimal> FLDDEC_NO_OPERATION_CHARGES = new Property<>("flddecNoOperationCharges");
	public static final Property<BigDecimal> FLDINT_HOUR = new Property<>("fldintHour");
	public static final Property<Date> FLDSDT_TIME_STAMP = new Property<>("fldsdtTimeStamp");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<Account> ACCOUNT = new Property<>("account");
	public static final Property<Location> LOCATION = new Property<>("location");
	public static final Property<List<VesselCardsAvailablePort>> VESSEL_CARDS_AVAILABLE_PORTS = new Property<>("vesselCardsAvailablePorts");

	public void setFldchrMinus(final String fldchrMinus)
	{
		this.writeProperty("fldchrMinus", fldchrMinus);
	}

	public String getFldchrMinus()
	{
		return (String) this.readProperty("fldchrMinus");
	}

	public void setFldchrPlus(final String fldchrPlus)
	{
		this.writeProperty("fldchrPlus", fldchrPlus);
	}

	public String getFldchrPlus()
	{
		return (String) this.readProperty("fldchrPlus");
	}

	public void setFldchrUserName(final String fldchrUserName)
	{
		this.writeProperty("fldchrUserName", fldchrUserName);
	}

	public String getFldchrUserName()
	{
		return (String) this.readProperty("fldchrUserName");
	}

	public void setFlddblAverageLURate(final BigDecimal flddblAverageLURate)
	{
		this.writeProperty("flddblAverageLURate", flddblAverageLURate);
	}

	public BigDecimal getFlddblAverageLURate()
	{
		return (BigDecimal) this.readProperty("flddblAverageLURate");
	}

	public void setFlddecNoOperationCharges(final BigDecimal flddecNoOperationCharges)
	{
		this.writeProperty("flddecNoOperationCharges", flddecNoOperationCharges);
	}

	public BigDecimal getFlddecNoOperationCharges()
	{
		return (BigDecimal) this.readProperty("flddecNoOperationCharges");
	}

	public void setFldintHour(final BigDecimal fldintHour)
	{
		this.writeProperty("fldintHour", fldintHour);
	}

	public BigDecimal getFldintHour()
	{
		return (BigDecimal) this.readProperty("fldintHour");
	}

	public void setFldsdtTimeStamp(final Date fldsdtTimeStamp)
	{
		this.writeProperty("fldsdtTimeStamp", fldsdtTimeStamp);
	}

	public Date getFldsdtTimeStamp()
	{
		return (Date) this.readProperty("fldsdtTimeStamp");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setAccount(final Account account)
	{
		this.setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) this.readProperty("account");
	}

	public void setLocation(final Location location)
	{
		this.setToOneTarget("location", location, true);
	}

	public Location getLocation()
	{
		return (Location) this.readProperty("location");
	}

	public void addToVesselCardsAvailablePorts(final VesselCardsAvailablePort obj)
	{
		this.addToManyTarget("vesselCardsAvailablePorts", obj, true);
	}

	public void removeFromVesselCardsAvailablePorts(final VesselCardsAvailablePort obj)
	{
		this.removeToManyTarget("vesselCardsAvailablePorts", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<VesselCardsAvailablePort> getVesselCardsAvailablePorts()
	{
		return (List<VesselCardsAvailablePort>) this.readProperty("vesselCardsAvailablePorts");
	}

}
