package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _LocationStorageDuties was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LocationStorageDuties extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_DUTY_CODE_PK_COLUMN = "fldchrDutyCode";

	public static final Property<String> FLDVCH_DUTY_DESC = new Property<String>("fldvchDutyDesc");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setFldvchDutyDesc(String fldvchDutyDesc)
	{
		writeProperty("fldvchDutyDesc", fldvchDutyDesc);
	}

	public String getFldvchDutyDesc()
	{
		return (String) readProperty("fldvchDutyDesc");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
