package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.AiEstActualVat;
import com.tc.app.exchangemonitor.model.cayenne.persistent.AllocationItemVat;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Country;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsUser;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Location;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Mot;
import com.tc.app.exchangemonitor.model.cayenne.persistent.State;

/**
 * Class _LocationExtInfo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LocationExtInfo extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String LOC_CODE_PK_COLUMN = "loc_code";

	public static final Property<String> BONDED_WAREHOUSE_LOC_IND = new Property<>("bondedWarehouseLocInd");
	public static final Property<String> CITY_CODE = new Property<>("cityCode");
	public static final Property<String> COUNTY_CODE = new Property<>("countyCode");
	public static final Property<String> EXCISE_WAREHOUSE_LOC_IND = new Property<>("exciseWarehouseLocInd");
	public static final Property<String> FACILITY_GOVT_CODE = new Property<>("facilityGovtCode");
	public static final Property<String> FACILITY_LEGAL_DESC = new Property<>("facilityLegalDesc");
	public static final Property<String> FACILITY_LSD_CODE = new Property<>("facilityLsdCode");
	public static final Property<String> OPER_GOVT_CODE = new Property<>("operGovtCode");
	public static final Property<String> OPER_LEGAL_DESC = new Property<>("operLegalDesc");
	public static final Property<String> POSTAL_CODE = new Property<>("postalCode");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<Account> ACCOUNT = new Property<>("account");
	public static final Property<IctsUser> ACCOUNTANT = new Property<>("accountant");
	public static final Property<List<AiEstActualVat>> AI_EST_ACTUAL_VATS = new Property<>("aiEstActualVats");
	public static final Property<List<AllocationItemVat>> ALLOCATION_ITEM_VATS = new Property<>("allocationItemVats");
	public static final Property<Country> COUNTRY = new Property<>("country");
	public static final Property<Location> LOCATION = new Property<>("location");
	public static final Property<Mot> MOT = new Property<>("mot");
	public static final Property<IctsUser> SCHEDULER = new Property<>("scheduler");
	public static final Property<State> STATE = new Property<>("state");
	public static final Property<IctsUser> TRADER = new Property<>("trader");

	public void setBondedWarehouseLocInd(final String bondedWarehouseLocInd)
	{
		this.writeProperty("bondedWarehouseLocInd", bondedWarehouseLocInd);
	}

	public String getBondedWarehouseLocInd()
	{
		return (String) this.readProperty("bondedWarehouseLocInd");
	}

	public void setCityCode(final String cityCode)
	{
		this.writeProperty("cityCode", cityCode);
	}

	public String getCityCode()
	{
		return (String) this.readProperty("cityCode");
	}

	public void setCountyCode(final String countyCode)
	{
		this.writeProperty("countyCode", countyCode);
	}

	public String getCountyCode()
	{
		return (String) this.readProperty("countyCode");
	}

	public void setExciseWarehouseLocInd(final String exciseWarehouseLocInd)
	{
		this.writeProperty("exciseWarehouseLocInd", exciseWarehouseLocInd);
	}

	public String getExciseWarehouseLocInd()
	{
		return (String) this.readProperty("exciseWarehouseLocInd");
	}

	public void setFacilityGovtCode(final String facilityGovtCode)
	{
		this.writeProperty("facilityGovtCode", facilityGovtCode);
	}

	public String getFacilityGovtCode()
	{
		return (String) this.readProperty("facilityGovtCode");
	}

	public void setFacilityLegalDesc(final String facilityLegalDesc)
	{
		this.writeProperty("facilityLegalDesc", facilityLegalDesc);
	}

	public String getFacilityLegalDesc()
	{
		return (String) this.readProperty("facilityLegalDesc");
	}

	public void setFacilityLsdCode(final String facilityLsdCode)
	{
		this.writeProperty("facilityLsdCode", facilityLsdCode);
	}

	public String getFacilityLsdCode()
	{
		return (String) this.readProperty("facilityLsdCode");
	}

	public void setOperGovtCode(final String operGovtCode)
	{
		this.writeProperty("operGovtCode", operGovtCode);
	}

	public String getOperGovtCode()
	{
		return (String) this.readProperty("operGovtCode");
	}

	public void setOperLegalDesc(final String operLegalDesc)
	{
		this.writeProperty("operLegalDesc", operLegalDesc);
	}

	public String getOperLegalDesc()
	{
		return (String) this.readProperty("operLegalDesc");
	}

	public void setPostalCode(final String postalCode)
	{
		this.writeProperty("postalCode", postalCode);
	}

	public String getPostalCode()
	{
		return (String) this.readProperty("postalCode");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setAccount(final Account account)
	{
		this.setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) this.readProperty("account");
	}

	public void setAccountant(final IctsUser accountant)
	{
		this.setToOneTarget("accountant", accountant, true);
	}

	public IctsUser getAccountant()
	{
		return (IctsUser) this.readProperty("accountant");
	}

	public void addToAiEstActualVats(final AiEstActualVat obj)
	{
		this.addToManyTarget("aiEstActualVats", obj, true);
	}

	public void removeFromAiEstActualVats(final AiEstActualVat obj)
	{
		this.removeToManyTarget("aiEstActualVats", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AiEstActualVat> getAiEstActualVats()
	{
		return (List<AiEstActualVat>) this.readProperty("aiEstActualVats");
	}

	public void addToAllocationItemVats(final AllocationItemVat obj)
	{
		this.addToManyTarget("allocationItemVats", obj, true);
	}

	public void removeFromAllocationItemVats(final AllocationItemVat obj)
	{
		this.removeToManyTarget("allocationItemVats", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AllocationItemVat> getAllocationItemVats()
	{
		return (List<AllocationItemVat>) this.readProperty("allocationItemVats");
	}

	public void setCountry(final Country country)
	{
		this.setToOneTarget("country", country, true);
	}

	public Country getCountry()
	{
		return (Country) this.readProperty("country");
	}

	public void setLocation(final Location location)
	{
		this.setToOneTarget("location", location, true);
	}

	public Location getLocation()
	{
		return (Location) this.readProperty("location");
	}

	public void setMot(final Mot mot)
	{
		this.setToOneTarget("mot", mot, true);
	}

	public Mot getMot()
	{
		return (Mot) this.readProperty("mot");
	}

	public void setScheduler(final IctsUser scheduler)
	{
		this.setToOneTarget("scheduler", scheduler, true);
	}

	public IctsUser getScheduler()
	{
		return (IctsUser) this.readProperty("scheduler");
	}

	public void setState(final State state)
	{
		this.setToOneTarget("state", state, true);
	}

	public State getState()
	{
		return (State) this.readProperty("state");
	}

	public void setTrader(final IctsUser trader)
	{
		this.setToOneTarget("trader", trader, true);
	}

	public IctsUser getTrader()
	{
		return (IctsUser) this.readProperty("trader");
	}

}
