package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Ba;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Loc;

/**
 * Class _LocHist was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LocHist extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String EFF_DT_PK_COLUMN = "eff_dt";
	public static final String LOC_ID_PK_COLUMN = "loc_id";

	public static final Property<Integer> CRUDE_SP_NO = new Property<Integer>("crudeSpNo");
	public static final Property<Integer> DISTR_ARM_NO = new Property<Integer>("distrArmNo");
	public static final Property<Date> EXPR_DT = new Property<Date>("exprDt");
	public static final Property<String> LOC_ABBR = new Property<String>("locAbbr");
	public static final Property<String> LOC_NM = new Property<String>("locNm");
	public static final Property<Integer> LOC_TYPE_GRP_ID = new Property<Integer>("locTypeGrpId");
	public static final Property<Integer> MKT_GRP_NO = new Property<Integer>("mktGrpNo");
	public static final Property<Integer> MKT_RGN_ID = new Property<Integer>("mktRgnId");
	public static final Property<Date> MOD_TS = new Property<Date>("modTs");
	public static final Property<String> MOD_USER_CD = new Property<String>("modUserCd");
	public static final Property<Integer> PRC_RGN_ID = new Property<Integer>("prcRgnId");
	public static final Property<Integer> TRAD_FCST_GRP_NO = new Property<Integer>("tradFcstGrpNo");
	public static final Property<Loc> LOC = new Property<Loc>("loc");
	public static final Property<Ba> OWN_BA = new Property<Ba>("ownBa");

	public void setCrudeSpNo(Integer crudeSpNo)
	{
		writeProperty("crudeSpNo", crudeSpNo);
	}

	public Integer getCrudeSpNo()
	{
		return (Integer) readProperty("crudeSpNo");
	}

	public void setDistrArmNo(Integer distrArmNo)
	{
		writeProperty("distrArmNo", distrArmNo);
	}

	public Integer getDistrArmNo()
	{
		return (Integer) readProperty("distrArmNo");
	}

	public void setExprDt(Date exprDt)
	{
		writeProperty("exprDt", exprDt);
	}

	public Date getExprDt()
	{
		return (Date) readProperty("exprDt");
	}

	public void setLocAbbr(String locAbbr)
	{
		writeProperty("locAbbr", locAbbr);
	}

	public String getLocAbbr()
	{
		return (String) readProperty("locAbbr");
	}

	public void setLocNm(String locNm)
	{
		writeProperty("locNm", locNm);
	}

	public String getLocNm()
	{
		return (String) readProperty("locNm");
	}

	public void setLocTypeGrpId(Integer locTypeGrpId)
	{
		writeProperty("locTypeGrpId", locTypeGrpId);
	}

	public Integer getLocTypeGrpId()
	{
		return (Integer) readProperty("locTypeGrpId");
	}

	public void setMktGrpNo(Integer mktGrpNo)
	{
		writeProperty("mktGrpNo", mktGrpNo);
	}

	public Integer getMktGrpNo()
	{
		return (Integer) readProperty("mktGrpNo");
	}

	public void setMktRgnId(Integer mktRgnId)
	{
		writeProperty("mktRgnId", mktRgnId);
	}

	public Integer getMktRgnId()
	{
		return (Integer) readProperty("mktRgnId");
	}

	public void setModTs(Date modTs)
	{
		writeProperty("modTs", modTs);
	}

	public Date getModTs()
	{
		return (Date) readProperty("modTs");
	}

	public void setModUserCd(String modUserCd)
	{
		writeProperty("modUserCd", modUserCd);
	}

	public String getModUserCd()
	{
		return (String) readProperty("modUserCd");
	}

	public void setPrcRgnId(Integer prcRgnId)
	{
		writeProperty("prcRgnId", prcRgnId);
	}

	public Integer getPrcRgnId()
	{
		return (Integer) readProperty("prcRgnId");
	}

	public void setTradFcstGrpNo(Integer tradFcstGrpNo)
	{
		writeProperty("tradFcstGrpNo", tradFcstGrpNo);
	}

	public Integer getTradFcstGrpNo()
	{
		return (Integer) readProperty("tradFcstGrpNo");
	}

	public void setLoc(Loc loc)
	{
		setToOneTarget("loc", loc, true);
	}

	public Loc getLoc()
	{
		return (Loc) readProperty("loc");
	}

	public void setOwnBa(Ba ownBa)
	{
		setToOneTarget("ownBa", ownBa, true);
	}

	public Ba getOwnBa()
	{
		return (Ba) readProperty("ownBa");
	}

}
