package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Market;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _MarketPricingCosts was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MarketPricingCosts extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String MKT_CODE_PK_COLUMN = "mkt_code";

	public static final Property<Double> COST_AMT = new Property<Double>("costAmt");
	public static final Property<Date> COST_DATE = new Property<Date>("costDate");
	public static final Property<String> COST_NAME = new Property<String>("costName");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<Market> MARKET = new Property<Market>("market");
	public static final Property<Uom> UOM = new Property<Uom>("uom");

	public void setCostAmt(Double costAmt)
	{
		writeProperty("costAmt", costAmt);
	}

	public Double getCostAmt()
	{
		return (Double) readProperty("costAmt");
	}

	public void setCostDate(Date costDate)
	{
		writeProperty("costDate", costDate);
	}

	public Date getCostDate()
	{
		return (Date) readProperty("costDate");
	}

	public void setCostName(String costName)
	{
		writeProperty("costName", costName);
	}

	public String getCostName()
	{
		return (String) readProperty("costName");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setMarket(Market market)
	{
		setToOneTarget("market", market, true);
	}

	public Market getMarket()
	{
		return (Market) readProperty("market");
	}

	public void setUom(Uom uom)
	{
		setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) readProperty("uom");
	}

}
