package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _McaStatus was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _McaStatus extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String MCA_STATUS_CODE_PK_COLUMN = "mca_status_code";

	public static final Property<String> MCA_STATUS_DESC = new Property<String>("mcaStatusDesc");
	public static final Property<String> MCA_STATUS_SHORT_NAME = new Property<String>("mcaStatusShortName");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setMcaStatusDesc(String mcaStatusDesc)
	{
		writeProperty("mcaStatusDesc", mcaStatusDesc);
	}

	public String getMcaStatusDesc()
	{
		return (String) readProperty("mcaStatusDesc");
	}

	public void setMcaStatusShortName(String mcaStatusShortName)
	{
		writeProperty("mcaStatusShortName", mcaStatusShortName);
	}

	public String getMcaStatusShortName()
	{
		return (String) readProperty("mcaStatusShortName");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
