package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _McaInvoiceTerms was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _McaInvoiceTerms extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String INVOICE_NUM_PK_COLUMN = "invoice_num";

	public static final Property<String> COLL_PARTY_TYPE = new Property<String>("collPartyType");
	public static final Property<String> CONTACT_NAME = new Property<String>("contactName");
	public static final Property<String> CONTACT_PHONE_NUM = new Property<String>("contactPhoneNum");
	public static final Property<String> CONTACT_TELEX_NUM = new Property<String>("contactTelexNum");
	public static final Property<Date> CUTOFF_DATE = new Property<Date>("cutoffDate");
	public static final Property<String> EMAIL = new Property<String>("email");
	public static final Property<String> ENABLE_EMAIL = new Property<String>("enableEmail");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setCollPartyType(String collPartyType)
	{
		writeProperty("collPartyType", collPartyType);
	}

	public String getCollPartyType()
	{
		return (String) readProperty("collPartyType");
	}

	public void setContactName(String contactName)
	{
		writeProperty("contactName", contactName);
	}

	public String getContactName()
	{
		return (String) readProperty("contactName");
	}

	public void setContactPhoneNum(String contactPhoneNum)
	{
		writeProperty("contactPhoneNum", contactPhoneNum);
	}

	public String getContactPhoneNum()
	{
		return (String) readProperty("contactPhoneNum");
	}

	public void setContactTelexNum(String contactTelexNum)
	{
		writeProperty("contactTelexNum", contactTelexNum);
	}

	public String getContactTelexNum()
	{
		return (String) readProperty("contactTelexNum");
	}

	public void setCutoffDate(Date cutoffDate)
	{
		writeProperty("cutoffDate", cutoffDate);
	}

	public Date getCutoffDate()
	{
		return (Date) readProperty("cutoffDate");
	}

	public void setEmail(String email)
	{
		writeProperty("email", email);
	}

	public String getEmail()
	{
		return (String) readProperty("email");
	}

	public void setEnableEmail(String enableEmail)
	{
		writeProperty("enableEmail", enableEmail);
	}

	public String getEnableEmail()
	{
		return (String) readProperty("enableEmail");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
