package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.AcctBookcompRestrict;
import com.tc.app.exchangemonitor.model.cayenne.persistent.BusCostOrderGroup;
import com.tc.app.exchangemonitor.model.cayenne.persistent.OrderTypeGroup;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Tax;

/**
 * Class _OrderTypeGrpDesc was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _OrderTypeGrpDesc extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ORDER_TYPE_GROUP_PK_COLUMN = "order_type_group";

	public static final Property<String> ORDER_TYPE_GROUP_DESC = new Property<String>("orderTypeGroupDesc");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<List<AcctBookcompRestrict>> ACCT_BOOKCOMP_RESTRICTS = new Property<List<AcctBookcompRestrict>>("acctBookcompRestricts");
	public static final Property<List<BusCostOrderGroup>> BUS_COST_ORDER_GROUPS = new Property<List<BusCostOrderGroup>>("busCostOrderGroups");
	public static final Property<List<OrderTypeGroup>> ORDER_TYPE_GROUPS = new Property<List<OrderTypeGroup>>("orderTypeGroups");
	public static final Property<List<Tax>> TAXES = new Property<List<Tax>>("taxes");

	public void setOrderTypeGroupDesc(String orderTypeGroupDesc)
	{
		writeProperty("orderTypeGroupDesc", orderTypeGroupDesc);
	}

	public String getOrderTypeGroupDesc()
	{
		return (String) readProperty("orderTypeGroupDesc");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void addToAcctBookcompRestricts(AcctBookcompRestrict obj)
	{
		addToManyTarget("acctBookcompRestricts", obj, true);
	}

	public void removeFromAcctBookcompRestricts(AcctBookcompRestrict obj)
	{
		removeToManyTarget("acctBookcompRestricts", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AcctBookcompRestrict> getAcctBookcompRestricts()
	{
		return (List<AcctBookcompRestrict>) readProperty("acctBookcompRestricts");
	}

	public void addToBusCostOrderGroups(BusCostOrderGroup obj)
	{
		addToManyTarget("busCostOrderGroups", obj, true);
	}

	public void removeFromBusCostOrderGroups(BusCostOrderGroup obj)
	{
		removeToManyTarget("busCostOrderGroups", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<BusCostOrderGroup> getBusCostOrderGroups()
	{
		return (List<BusCostOrderGroup>) readProperty("busCostOrderGroups");
	}

	public void addToOrderTypeGroups(OrderTypeGroup obj)
	{
		addToManyTarget("orderTypeGroups", obj, true);
	}

	public void removeFromOrderTypeGroups(OrderTypeGroup obj)
	{
		removeToManyTarget("orderTypeGroups", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<OrderTypeGroup> getOrderTypeGroups()
	{
		return (List<OrderTypeGroup>) readProperty("orderTypeGroups");
	}

	public void addToTaxes(Tax obj)
	{
		addToManyTarget("taxes", obj, true);
	}

	public void removeFromTaxes(Tax obj)
	{
		removeToManyTarget("taxes", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<Tax> getTaxes()
	{
		return (List<Tax>) readProperty("taxes");
	}

}
