package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsUser;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Location;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _ParentGuarantee was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ParentGuarantee extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String PG_NUM_PK_COLUMN = "pg_num";

	public static final Property<Double> PG_AMOUNT_COVERED = new Property<>("pgAmountCovered");
	public static final Property<String> PG_BUS_COVERED_CODE = new Property<>("pgBusCoveredCode");
	public static final Property<String> PG_COUNTER_REF_CODE = new Property<>("pgCounterRefCode");
	public static final Property<Date> PG_EXPIRATION_DATE = new Property<>("pgExpirationDate");
	public static final Property<String> PG_IN_OUT_IND = new Property<>("pgInOutInd");
	public static final Property<Date> PG_ISSUE_DATE = new Property<>("pgIssueDate");
	public static final Property<Date> PG_NOTIFY_DAYS = new Property<>("pgNotifyDays");
	public static final Property<String> PG_SUBS_COVERED_IND = new Property<>("pgSubsCoveredInd");
	public static final Property<Integer> PG_TRADE_NUM = new Property<>("pgTradeNum");
	public static final Property<Double> PG_VOLUME_LIMIT = new Property<>("pgVolumeLimit");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<Account> ACCOUNT = new Property<>("account");
	public static final Property<Account> ACCOUNT1 = new Property<>("account1");
	public static final Property<Commodity> COMMODITY = new Property<>("commodity");
	public static final Property<Commodity> COMMODITY1 = new Property<>("commodity1");
	public static final Property<IctsUser> ICTS_USER = new Property<>("ictsUser");
	public static final Property<IctsUser> ICTS_USER1 = new Property<>("ictsUser1");
	public static final Property<Location> LOCATION = new Property<>("location");
	public static final Property<Uom> UOM = new Property<>("uom");

	public void setPgAmountCovered(final Double pgAmountCovered)
	{
		this.writeProperty("pgAmountCovered", pgAmountCovered);
	}

	public Double getPgAmountCovered()
	{
		return (Double) this.readProperty("pgAmountCovered");
	}

	public void setPgBusCoveredCode(final String pgBusCoveredCode)
	{
		this.writeProperty("pgBusCoveredCode", pgBusCoveredCode);
	}

	public String getPgBusCoveredCode()
	{
		return (String) this.readProperty("pgBusCoveredCode");
	}

	public void setPgCounterRefCode(final String pgCounterRefCode)
	{
		this.writeProperty("pgCounterRefCode", pgCounterRefCode);
	}

	public String getPgCounterRefCode()
	{
		return (String) this.readProperty("pgCounterRefCode");
	}

	public void setPgExpirationDate(final Date pgExpirationDate)
	{
		this.writeProperty("pgExpirationDate", pgExpirationDate);
	}

	public Date getPgExpirationDate()
	{
		return (Date) this.readProperty("pgExpirationDate");
	}

	public void setPgInOutInd(final String pgInOutInd)
	{
		this.writeProperty("pgInOutInd", pgInOutInd);
	}

	public String getPgInOutInd()
	{
		return (String) this.readProperty("pgInOutInd");
	}

	public void setPgIssueDate(final Date pgIssueDate)
	{
		this.writeProperty("pgIssueDate", pgIssueDate);
	}

	public Date getPgIssueDate()
	{
		return (Date) this.readProperty("pgIssueDate");
	}

	public void setPgNotifyDays(final Date pgNotifyDays)
	{
		this.writeProperty("pgNotifyDays", pgNotifyDays);
	}

	public Date getPgNotifyDays()
	{
		return (Date) this.readProperty("pgNotifyDays");
	}

	public void setPgSubsCoveredInd(final String pgSubsCoveredInd)
	{
		this.writeProperty("pgSubsCoveredInd", pgSubsCoveredInd);
	}

	public String getPgSubsCoveredInd()
	{
		return (String) this.readProperty("pgSubsCoveredInd");
	}

	public void setPgTradeNum(final Integer pgTradeNum)
	{
		this.writeProperty("pgTradeNum", pgTradeNum);
	}

	public Integer getPgTradeNum()
	{
		return (Integer) this.readProperty("pgTradeNum");
	}

	public void setPgVolumeLimit(final Double pgVolumeLimit)
	{
		this.writeProperty("pgVolumeLimit", pgVolumeLimit);
	}

	public Double getPgVolumeLimit()
	{
		return (Double) this.readProperty("pgVolumeLimit");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setAccount(final Account account)
	{
		this.setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) this.readProperty("account");
	}

	public void setAccount1(final Account account1)
	{
		this.setToOneTarget("account1", account1, true);
	}

	public Account getAccount1()
	{
		return (Account) this.readProperty("account1");
	}

	public void setCommodity(final Commodity commodity)
	{
		this.setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) this.readProperty("commodity");
	}

	public void setCommodity1(final Commodity commodity1)
	{
		this.setToOneTarget("commodity1", commodity1, true);
	}

	public Commodity getCommodity1()
	{
		return (Commodity) this.readProperty("commodity1");
	}

	public void setIctsUser(final IctsUser ictsUser)
	{
		this.setToOneTarget("ictsUser", ictsUser, true);
	}

	public IctsUser getIctsUser()
	{
		return (IctsUser) this.readProperty("ictsUser");
	}

	public void setIctsUser1(final IctsUser ictsUser1)
	{
		this.setToOneTarget("ictsUser1", ictsUser1, true);
	}

	public IctsUser getIctsUser1()
	{
		return (IctsUser) this.readProperty("ictsUser1");
	}

	public void setLocation(final Location location)
	{
		this.setToOneTarget("location", location, true);
	}

	public Location getLocation()
	{
		return (Location) this.readProperty("location");
	}

	public void setUom(final Uom uom)
	{
		this.setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) this.readProperty("uom");
	}

}
