package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _PassControlInfo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PassControlInfo extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String PASS_CONTROL_ID_PK_COLUMN = "pass_control_id";

	public static final Property<String> PASS_CONTROL_VAL1 = new Property<String>("passControlVal1");
	public static final Property<String> PASS_CONTROL_VAL2 = new Property<String>("passControlVal2");
	public static final Property<String> PASS_CONTROL_VAL3 = new Property<String>("passControlVal3");
	public static final Property<String> PASS_CONTROL_VAL4 = new Property<String>("passControlVal4");
	public static final Property<String> PASS_CONTROL_VAL5 = new Property<String>("passControlVal5");
	public static final Property<String> PASS_CONTROL_VAL6 = new Property<String>("passControlVal6");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setPassControlVal1(String passControlVal1)
	{
		writeProperty("passControlVal1", passControlVal1);
	}

	public String getPassControlVal1()
	{
		return (String) readProperty("passControlVal1");
	}

	public void setPassControlVal2(String passControlVal2)
	{
		writeProperty("passControlVal2", passControlVal2);
	}

	public String getPassControlVal2()
	{
		return (String) readProperty("passControlVal2");
	}

	public void setPassControlVal3(String passControlVal3)
	{
		writeProperty("passControlVal3", passControlVal3);
	}

	public String getPassControlVal3()
	{
		return (String) readProperty("passControlVal3");
	}

	public void setPassControlVal4(String passControlVal4)
	{
		writeProperty("passControlVal4", passControlVal4);
	}

	public String getPassControlVal4()
	{
		return (String) readProperty("passControlVal4");
	}

	public void setPassControlVal5(String passControlVal5)
	{
		writeProperty("passControlVal5", passControlVal5);
	}

	public String getPassControlVal5()
	{
		return (String) readProperty("passControlVal5");
	}

	public void setPassControlVal6(String passControlVal6)
	{
		writeProperty("passControlVal6", passControlVal6);
	}

	public String getPassControlVal6()
	{
		return (String) readProperty("passControlVal6");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
