package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Location;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Mot;

/**
 * Class _Path was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Path extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> DEFAULT_PATH_IND = new Property<>("defaultPathInd");
	public static final Property<String> PATH_NAME = new Property<>("pathName");
	public static final Property<Date> TOT_TRANSIT_TIME = new Property<>("totTransitTime");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<Location> LOCATION = new Property<>("location");
	public static final Property<Location> LOCATION1 = new Property<>("location1");
	public static final Property<Mot> MOT = new Property<>("mot");

	public void setDefaultPathInd(final String defaultPathInd)
	{
		this.writeProperty("defaultPathInd", defaultPathInd);
	}

	public String getDefaultPathInd()
	{
		return (String) this.readProperty("defaultPathInd");
	}

	public void setPathName(final String pathName)
	{
		this.writeProperty("pathName", pathName);
	}

	public String getPathName()
	{
		return (String) this.readProperty("pathName");
	}

	public void setTotTransitTime(final Date totTransitTime)
	{
		this.writeProperty("totTransitTime", totTransitTime);
	}

	public Date getTotTransitTime()
	{
		return (Date) this.readProperty("totTransitTime");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setLocation(final Location location)
	{
		this.setToOneTarget("location", location, true);
	}

	public Location getLocation()
	{
		return (Location) this.readProperty("location");
	}

	public void setLocation1(final Location location1)
	{
		this.setToOneTarget("location1", location1, true);
	}

	public Location getLocation1()
	{
		return (Location) this.readProperty("location1");
	}

	public void setMot(final Mot mot)
	{
		this.setToOneTarget("mot", mot, true);
	}

	public Mot getMot()
	{
		return (Mot) this.readProperty("mot");
	}

}
