package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsUser;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Pipeline;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PlContractExclusions;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PlContractLaytimes;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PlContractLosses;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PlContractTariffAdj;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PlContractTariffs;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PlContractTerminals;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PlContractViscosities;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PlTransfer;
import com.tc.app.exchangemonitor.model.cayenne.persistent.WorkArea;

/**
 * Class _PlContract was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PlContract extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_CONTR_ID_PK_COLUMN = "fldchrContrId";
	public static final String FLDCHR_CONTR_YEAR_PK_COLUMN = "fldchrContrYear";

	public static final Property<String> FLDCHR_APIVRTON_FEE_UMCODE = new Property<String>("fldchrAPIVrtonFeeUMCode");
	public static final Property<String> FLDCHR_API_FEE_TOGGLE_FLAG = new Property<String>("fldchrApiFeeToggleFlag");
	public static final Property<String> FLDCHR_BSW_FEE_TOGGLE_FLAG = new Property<String>("fldchrBswFeeToggleFlag");
	public static final Property<String> FLDCHR_CHART_MODE_FLAG = new Property<String>("fldchrChartModeFlag");
	public static final Property<String> FLDCHR_CONFIRMED_FLAG = new Property<String>("fldchrConfirmedFlag");
	public static final Property<String> FLDCHR_CONTR_DURATION_UMFLAG = new Property<String>("fldchrContrDurationUMFlag");
	public static final Property<String> FLDCHR_CONTR_NUM = new Property<String>("fldchrContrNum");
	public static final Property<String> FLDCHR_CONTR_POSITION = new Property<String>("fldchrContrPosition");
	public static final Property<String> FLDCHR_CONTR_STATUS = new Property<String>("fldchrContrStatus");
	public static final Property<String> FLDCHR_DEAL_STATUS_FLAG = new Property<String>("fldchrDealStatusFlag");
	public static final Property<String> FLDCHR_DEBALLAST_FEE_TOGGLE_FLAG = new Property<String>("fldchrDeballastFeeToggleFlag");
	public static final Property<String> FLDCHR_DEBALLAST_FEE_UMCODE = new Property<String>("fldchrDeballastFeeUMCode");
	public static final Property<String> FLDCHR_EXCLUSIONS_TOGGLE_FLAG = new Property<String>("fldchrExclusionsToggleFlag");
	public static final Property<String> FLDCHR_GARBAGE_FEE_TOGGLE_FLAG = new Property<String>("fldchrGarbageFeeToggleFlag");
	public static final Property<String> FLDCHR_INHOUSE_FLAG = new Property<String>("fldchrInhouseFlag");
	public static final Property<String> FLDCHR_LOSSES_TOGGLE_FLAG = new Property<String>("fldchrLossesToggleFlag");
	public static final Property<String> FLDCHR_LTIM_TOGGLE_FLAG = new Property<String>("fldchrLtimToggleFlag");
	public static final Property<String> FLDCHR_OCCPY_TOGGLE_FLAG = new Property<String>("fldchrOccpyToggleFlag");
	public static final Property<String> FLDCHR_PLIFT_FEE_UMCODE = new Property<String>("fldchrPliftFeeUMCode");
	public static final Property<String> FLDCHR_PRELIFTING_FEE_TOGGLE_FLAG = new Property<String>("fldchrPreliftingFeeToggleFlag");
	public static final Property<String> FLDCHR_RENEWAL_OPTION_FLAG = new Property<String>("fldchrRenewalOptionFlag");
	public static final Property<String> FLDCHR_STORAGE_FEE_ALLOW_UMCODE = new Property<String>("fldchrStorageFeeAllowUMCode");
	public static final Property<String> FLDCHR_STORAGE_FEE_AMOUNT_UMCODE = new Property<String>("fldchrStorageFeeAmountUMCode");
	public static final Property<String> FLDCHR_STORAGE_FEE_TOGGLE_FLAG = new Property<String>("fldchrStorageFeeToggleFlag");
	public static final Property<String> FLDCHR_TARIFF_ADJ_TOGGLE_FLAG = new Property<String>("fldchrTariffAdjToggleFlag");
	public static final Property<String> FLDCHR_TARIFF_TOGGLE_FLAG = new Property<String>("fldchrTariffToggleFlag");
	public static final Property<String> FLDCHR_TOPP_EXTRA_FEE_UMCODE = new Property<String>("fldchrToppExtraFeeUMCode");
	public static final Property<String> FLDCHR_TOPP_MAX_ALLOW_UMCODE = new Property<String>("fldchrToppMaxAllowUMCode");
	public static final Property<String> FLDCHR_TOPPING_FEE_TOGGLE_FLAG = new Property<String>("fldchrToppingFeeToggleFlag");
	public static final Property<String> FLDCHR_VISCOSITY_TOGGLE_FLAG = new Property<String>("fldchrViscosityToggleFlag");
	public static final Property<BigDecimal> FLDDEC_APIVRTON_ALLOW = new Property<BigDecimal>("flddecAPIVrtonAllow");
	public static final Property<BigDecimal> FLDDEC_APIVRTON_FEE = new Property<BigDecimal>("flddecAPIVrtonFee");
	public static final Property<BigDecimal> FLDDEC_APIVRTON_STEP = new Property<BigDecimal>("flddecAPIVrtonStep");
	public static final Property<BigDecimal> FLDDEC_BSWADJ_FACTOR = new Property<BigDecimal>("flddecBSWAdjFactor");
	public static final Property<BigDecimal> FLDDEC_BSWALLOW = new Property<BigDecimal>("flddecBSWAllow");
	public static final Property<BigDecimal> FLDDEC_CONTR_LOSS = new Property<BigDecimal>("flddecContrLoss");
	public static final Property<BigDecimal> FLDDEC_DEBALLAST_DIRTY_WATER_PCTG = new Property<BigDecimal>("flddecDeballastDirtyWaterPctg");
	public static final Property<BigDecimal> FLDDEC_DEBALLAST_FEE = new Property<BigDecimal>("flddecDeballastFee");
	public static final Property<BigDecimal> FLDDEC_GARBAGE_FEE = new Property<BigDecimal>("flddecGarbageFee");
	public static final Property<BigDecimal> FLDDEC_GARBAGE_FEE_ESTM = new Property<BigDecimal>("flddecGarbageFeeEstm");
	public static final Property<BigDecimal> FLDDEC_PLIFT_FEE = new Property<BigDecimal>("flddecPliftFee");
	public static final Property<BigDecimal> FLDDEC_STORAGE_FEE_ALLOW_MIN_QTY = new Property<BigDecimal>("flddecStorageFeeAllowMinQty");
	public static final Property<BigDecimal> FLDDEC_STORAGE_FEE_AMOUNT = new Property<BigDecimal>("flddecStorageFeeAmount");
	public static final Property<BigDecimal> FLDDEC_TOPP_EXTRA_FEE = new Property<BigDecimal>("flddecToppExtraFee");
	public static final Property<BigDecimal> FLDDEC_TOPP_MAX_ALLOW = new Property<BigDecimal>("flddecToppMaxAllow");
	public static final Property<Integer> FLDINT_BOOKC_ACCT_NUM = new Property<Integer>("fldintBookcAcctNum");
	public static final Property<Integer> FLDINT_CONTACT_ACCT_NUM = new Property<Integer>("fldintContactAcctNum");
	public static final Property<Integer> FLDINT_CPART_ACCT_NUM = new Property<Integer>("fldintCpartAcctNum");
	public static final Property<Integer> FLDINT_STORAGE_FEE_ALLOW_DAYS = new Property<Integer>("fldintStorageFeeAllowDays");
	public static final Property<Integer> FLDINT_STORAGE_FEE_DAYS = new Property<Integer>("fldintStorageFeeDays");
	public static final Property<Date> FLDSDT_CONTR_DATE = new Property<Date>("fldsdtContrDate");
	public static final Property<Date> FLDSDT_CONTR_END_DATE = new Property<Date>("fldsdtContrEndDate");
	public static final Property<Date> FLDSDT_CONTR_NEGOTIATION_DATE = new Property<Date>("fldsdtContrNegotiationDate");
	public static final Property<Date> FLDSDT_CONTR_START_DATE = new Property<Date>("fldsdtContrStartDate");
	public static final Property<Short> FLDSMI_CONTR_DURATION = new Property<Short>("fldsmiContrDuration");
	public static final Property<String> FLDVCH_CONTR_FORM = new Property<String>("fldvchContrForm");
	public static final Property<String> FLDVCH_CPART_CONTR_NUM = new Property<String>("fldvchCpartContrNum");
	public static final Property<String> FLDVCH_RENEWAL_OPTION = new Property<String>("fldvchRenewalOption");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<Commodity> COMMODITY1 = new Property<Commodity>("commodity1");
	public static final Property<Commodity> COMMODITY2 = new Property<Commodity>("commodity2");
	public static final Property<Commodity> COMMODITY3 = new Property<Commodity>("commodity3");
	public static final Property<Commodity> COMMODITY4 = new Property<Commodity>("commodity4");
	public static final Property<Commodity> COMMODITY5 = new Property<Commodity>("commodity5");
	public static final Property<IctsUser> ICTS_USER = new Property<IctsUser>("ictsUser");
	public static final Property<IctsUser> ICTS_USER1 = new Property<IctsUser>("ictsUser1");
	public static final Property<Pipeline> PIPELINE = new Property<Pipeline>("pipeline");
	public static final Property<List<PlContractExclusions>> PL_CONTRACT_EXCLUSIONSS = new Property<List<PlContractExclusions>>("plContractExclusionss");
	public static final Property<List<PlContractLaytimes>> PL_CONTRACT_LAYTIMESES = new Property<List<PlContractLaytimes>>("plContractLaytimeses");
	public static final Property<List<PlContractLosses>> PL_CONTRACT_LOSSESES = new Property<List<PlContractLosses>>("plContractLosseses");
	public static final Property<List<PlContractTariffAdj>> PL_CONTRACT_TARIFF_ADJS = new Property<List<PlContractTariffAdj>>("plContractTariffAdjs");
	public static final Property<List<PlContractTariffs>> PL_CONTRACT_TARIFFSS = new Property<List<PlContractTariffs>>("plContractTariffss");
	public static final Property<List<PlContractTerminals>> PL_CONTRACT_TERMINALSS = new Property<List<PlContractTerminals>>("plContractTerminalss");
	public static final Property<List<PlContractViscosities>> PL_CONTRACT_VISCOSITIESES = new Property<List<PlContractViscosities>>("plContractViscositieses");
	public static final Property<List<PlTransfer>> PL_TRANSFERS = new Property<List<PlTransfer>>("plTransfers");
	public static final Property<WorkArea> WORK_AREA = new Property<WorkArea>("workArea");

	public void setFldchrAPIVrtonFeeUMCode(String fldchrAPIVrtonFeeUMCode)
	{
		writeProperty("fldchrAPIVrtonFeeUMCode", fldchrAPIVrtonFeeUMCode);
	}

	public String getFldchrAPIVrtonFeeUMCode()
	{
		return (String) readProperty("fldchrAPIVrtonFeeUMCode");
	}

	public void setFldchrApiFeeToggleFlag(String fldchrApiFeeToggleFlag)
	{
		writeProperty("fldchrApiFeeToggleFlag", fldchrApiFeeToggleFlag);
	}

	public String getFldchrApiFeeToggleFlag()
	{
		return (String) readProperty("fldchrApiFeeToggleFlag");
	}

	public void setFldchrBswFeeToggleFlag(String fldchrBswFeeToggleFlag)
	{
		writeProperty("fldchrBswFeeToggleFlag", fldchrBswFeeToggleFlag);
	}

	public String getFldchrBswFeeToggleFlag()
	{
		return (String) readProperty("fldchrBswFeeToggleFlag");
	}

	public void setFldchrChartModeFlag(String fldchrChartModeFlag)
	{
		writeProperty("fldchrChartModeFlag", fldchrChartModeFlag);
	}

	public String getFldchrChartModeFlag()
	{
		return (String) readProperty("fldchrChartModeFlag");
	}

	public void setFldchrConfirmedFlag(String fldchrConfirmedFlag)
	{
		writeProperty("fldchrConfirmedFlag", fldchrConfirmedFlag);
	}

	public String getFldchrConfirmedFlag()
	{
		return (String) readProperty("fldchrConfirmedFlag");
	}

	public void setFldchrContrDurationUMFlag(String fldchrContrDurationUMFlag)
	{
		writeProperty("fldchrContrDurationUMFlag", fldchrContrDurationUMFlag);
	}

	public String getFldchrContrDurationUMFlag()
	{
		return (String) readProperty("fldchrContrDurationUMFlag");
	}

	public void setFldchrContrNum(String fldchrContrNum)
	{
		writeProperty("fldchrContrNum", fldchrContrNum);
	}

	public String getFldchrContrNum()
	{
		return (String) readProperty("fldchrContrNum");
	}

	public void setFldchrContrPosition(String fldchrContrPosition)
	{
		writeProperty("fldchrContrPosition", fldchrContrPosition);
	}

	public String getFldchrContrPosition()
	{
		return (String) readProperty("fldchrContrPosition");
	}

	public void setFldchrContrStatus(String fldchrContrStatus)
	{
		writeProperty("fldchrContrStatus", fldchrContrStatus);
	}

	public String getFldchrContrStatus()
	{
		return (String) readProperty("fldchrContrStatus");
	}

	public void setFldchrDealStatusFlag(String fldchrDealStatusFlag)
	{
		writeProperty("fldchrDealStatusFlag", fldchrDealStatusFlag);
	}

	public String getFldchrDealStatusFlag()
	{
		return (String) readProperty("fldchrDealStatusFlag");
	}

	public void setFldchrDeballastFeeToggleFlag(String fldchrDeballastFeeToggleFlag)
	{
		writeProperty("fldchrDeballastFeeToggleFlag", fldchrDeballastFeeToggleFlag);
	}

	public String getFldchrDeballastFeeToggleFlag()
	{
		return (String) readProperty("fldchrDeballastFeeToggleFlag");
	}

	public void setFldchrDeballastFeeUMCode(String fldchrDeballastFeeUMCode)
	{
		writeProperty("fldchrDeballastFeeUMCode", fldchrDeballastFeeUMCode);
	}

	public String getFldchrDeballastFeeUMCode()
	{
		return (String) readProperty("fldchrDeballastFeeUMCode");
	}

	public void setFldchrExclusionsToggleFlag(String fldchrExclusionsToggleFlag)
	{
		writeProperty("fldchrExclusionsToggleFlag", fldchrExclusionsToggleFlag);
	}

	public String getFldchrExclusionsToggleFlag()
	{
		return (String) readProperty("fldchrExclusionsToggleFlag");
	}

	public void setFldchrGarbageFeeToggleFlag(String fldchrGarbageFeeToggleFlag)
	{
		writeProperty("fldchrGarbageFeeToggleFlag", fldchrGarbageFeeToggleFlag);
	}

	public String getFldchrGarbageFeeToggleFlag()
	{
		return (String) readProperty("fldchrGarbageFeeToggleFlag");
	}

	public void setFldchrInhouseFlag(String fldchrInhouseFlag)
	{
		writeProperty("fldchrInhouseFlag", fldchrInhouseFlag);
	}

	public String getFldchrInhouseFlag()
	{
		return (String) readProperty("fldchrInhouseFlag");
	}

	public void setFldchrLossesToggleFlag(String fldchrLossesToggleFlag)
	{
		writeProperty("fldchrLossesToggleFlag", fldchrLossesToggleFlag);
	}

	public String getFldchrLossesToggleFlag()
	{
		return (String) readProperty("fldchrLossesToggleFlag");
	}

	public void setFldchrLtimToggleFlag(String fldchrLtimToggleFlag)
	{
		writeProperty("fldchrLtimToggleFlag", fldchrLtimToggleFlag);
	}

	public String getFldchrLtimToggleFlag()
	{
		return (String) readProperty("fldchrLtimToggleFlag");
	}

	public void setFldchrOccpyToggleFlag(String fldchrOccpyToggleFlag)
	{
		writeProperty("fldchrOccpyToggleFlag", fldchrOccpyToggleFlag);
	}

	public String getFldchrOccpyToggleFlag()
	{
		return (String) readProperty("fldchrOccpyToggleFlag");
	}

	public void setFldchrPliftFeeUMCode(String fldchrPliftFeeUMCode)
	{
		writeProperty("fldchrPliftFeeUMCode", fldchrPliftFeeUMCode);
	}

	public String getFldchrPliftFeeUMCode()
	{
		return (String) readProperty("fldchrPliftFeeUMCode");
	}

	public void setFldchrPreliftingFeeToggleFlag(String fldchrPreliftingFeeToggleFlag)
	{
		writeProperty("fldchrPreliftingFeeToggleFlag", fldchrPreliftingFeeToggleFlag);
	}

	public String getFldchrPreliftingFeeToggleFlag()
	{
		return (String) readProperty("fldchrPreliftingFeeToggleFlag");
	}

	public void setFldchrRenewalOptionFlag(String fldchrRenewalOptionFlag)
	{
		writeProperty("fldchrRenewalOptionFlag", fldchrRenewalOptionFlag);
	}

	public String getFldchrRenewalOptionFlag()
	{
		return (String) readProperty("fldchrRenewalOptionFlag");
	}

	public void setFldchrStorageFeeAllowUMCode(String fldchrStorageFeeAllowUMCode)
	{
		writeProperty("fldchrStorageFeeAllowUMCode", fldchrStorageFeeAllowUMCode);
	}

	public String getFldchrStorageFeeAllowUMCode()
	{
		return (String) readProperty("fldchrStorageFeeAllowUMCode");
	}

	public void setFldchrStorageFeeAmountUMCode(String fldchrStorageFeeAmountUMCode)
	{
		writeProperty("fldchrStorageFeeAmountUMCode", fldchrStorageFeeAmountUMCode);
	}

	public String getFldchrStorageFeeAmountUMCode()
	{
		return (String) readProperty("fldchrStorageFeeAmountUMCode");
	}

	public void setFldchrStorageFeeToggleFlag(String fldchrStorageFeeToggleFlag)
	{
		writeProperty("fldchrStorageFeeToggleFlag", fldchrStorageFeeToggleFlag);
	}

	public String getFldchrStorageFeeToggleFlag()
	{
		return (String) readProperty("fldchrStorageFeeToggleFlag");
	}

	public void setFldchrTariffAdjToggleFlag(String fldchrTariffAdjToggleFlag)
	{
		writeProperty("fldchrTariffAdjToggleFlag", fldchrTariffAdjToggleFlag);
	}

	public String getFldchrTariffAdjToggleFlag()
	{
		return (String) readProperty("fldchrTariffAdjToggleFlag");
	}

	public void setFldchrTariffToggleFlag(String fldchrTariffToggleFlag)
	{
		writeProperty("fldchrTariffToggleFlag", fldchrTariffToggleFlag);
	}

	public String getFldchrTariffToggleFlag()
	{
		return (String) readProperty("fldchrTariffToggleFlag");
	}

	public void setFldchrToppExtraFeeUMCode(String fldchrToppExtraFeeUMCode)
	{
		writeProperty("fldchrToppExtraFeeUMCode", fldchrToppExtraFeeUMCode);
	}

	public String getFldchrToppExtraFeeUMCode()
	{
		return (String) readProperty("fldchrToppExtraFeeUMCode");
	}

	public void setFldchrToppMaxAllowUMCode(String fldchrToppMaxAllowUMCode)
	{
		writeProperty("fldchrToppMaxAllowUMCode", fldchrToppMaxAllowUMCode);
	}

	public String getFldchrToppMaxAllowUMCode()
	{
		return (String) readProperty("fldchrToppMaxAllowUMCode");
	}

	public void setFldchrToppingFeeToggleFlag(String fldchrToppingFeeToggleFlag)
	{
		writeProperty("fldchrToppingFeeToggleFlag", fldchrToppingFeeToggleFlag);
	}

	public String getFldchrToppingFeeToggleFlag()
	{
		return (String) readProperty("fldchrToppingFeeToggleFlag");
	}

	public void setFldchrViscosityToggleFlag(String fldchrViscosityToggleFlag)
	{
		writeProperty("fldchrViscosityToggleFlag", fldchrViscosityToggleFlag);
	}

	public String getFldchrViscosityToggleFlag()
	{
		return (String) readProperty("fldchrViscosityToggleFlag");
	}

	public void setFlddecAPIVrtonAllow(BigDecimal flddecAPIVrtonAllow)
	{
		writeProperty("flddecAPIVrtonAllow", flddecAPIVrtonAllow);
	}

	public BigDecimal getFlddecAPIVrtonAllow()
	{
		return (BigDecimal) readProperty("flddecAPIVrtonAllow");
	}

	public void setFlddecAPIVrtonFee(BigDecimal flddecAPIVrtonFee)
	{
		writeProperty("flddecAPIVrtonFee", flddecAPIVrtonFee);
	}

	public BigDecimal getFlddecAPIVrtonFee()
	{
		return (BigDecimal) readProperty("flddecAPIVrtonFee");
	}

	public void setFlddecAPIVrtonStep(BigDecimal flddecAPIVrtonStep)
	{
		writeProperty("flddecAPIVrtonStep", flddecAPIVrtonStep);
	}

	public BigDecimal getFlddecAPIVrtonStep()
	{
		return (BigDecimal) readProperty("flddecAPIVrtonStep");
	}

	public void setFlddecBSWAdjFactor(BigDecimal flddecBSWAdjFactor)
	{
		writeProperty("flddecBSWAdjFactor", flddecBSWAdjFactor);
	}

	public BigDecimal getFlddecBSWAdjFactor()
	{
		return (BigDecimal) readProperty("flddecBSWAdjFactor");
	}

	public void setFlddecBSWAllow(BigDecimal flddecBSWAllow)
	{
		writeProperty("flddecBSWAllow", flddecBSWAllow);
	}

	public BigDecimal getFlddecBSWAllow()
	{
		return (BigDecimal) readProperty("flddecBSWAllow");
	}

	public void setFlddecContrLoss(BigDecimal flddecContrLoss)
	{
		writeProperty("flddecContrLoss", flddecContrLoss);
	}

	public BigDecimal getFlddecContrLoss()
	{
		return (BigDecimal) readProperty("flddecContrLoss");
	}

	public void setFlddecDeballastDirtyWaterPctg(BigDecimal flddecDeballastDirtyWaterPctg)
	{
		writeProperty("flddecDeballastDirtyWaterPctg", flddecDeballastDirtyWaterPctg);
	}

	public BigDecimal getFlddecDeballastDirtyWaterPctg()
	{
		return (BigDecimal) readProperty("flddecDeballastDirtyWaterPctg");
	}

	public void setFlddecDeballastFee(BigDecimal flddecDeballastFee)
	{
		writeProperty("flddecDeballastFee", flddecDeballastFee);
	}

	public BigDecimal getFlddecDeballastFee()
	{
		return (BigDecimal) readProperty("flddecDeballastFee");
	}

	public void setFlddecGarbageFee(BigDecimal flddecGarbageFee)
	{
		writeProperty("flddecGarbageFee", flddecGarbageFee);
	}

	public BigDecimal getFlddecGarbageFee()
	{
		return (BigDecimal) readProperty("flddecGarbageFee");
	}

	public void setFlddecGarbageFeeEstm(BigDecimal flddecGarbageFeeEstm)
	{
		writeProperty("flddecGarbageFeeEstm", flddecGarbageFeeEstm);
	}

	public BigDecimal getFlddecGarbageFeeEstm()
	{
		return (BigDecimal) readProperty("flddecGarbageFeeEstm");
	}

	public void setFlddecPliftFee(BigDecimal flddecPliftFee)
	{
		writeProperty("flddecPliftFee", flddecPliftFee);
	}

	public BigDecimal getFlddecPliftFee()
	{
		return (BigDecimal) readProperty("flddecPliftFee");
	}

	public void setFlddecStorageFeeAllowMinQty(BigDecimal flddecStorageFeeAllowMinQty)
	{
		writeProperty("flddecStorageFeeAllowMinQty", flddecStorageFeeAllowMinQty);
	}

	public BigDecimal getFlddecStorageFeeAllowMinQty()
	{
		return (BigDecimal) readProperty("flddecStorageFeeAllowMinQty");
	}

	public void setFlddecStorageFeeAmount(BigDecimal flddecStorageFeeAmount)
	{
		writeProperty("flddecStorageFeeAmount", flddecStorageFeeAmount);
	}

	public BigDecimal getFlddecStorageFeeAmount()
	{
		return (BigDecimal) readProperty("flddecStorageFeeAmount");
	}

	public void setFlddecToppExtraFee(BigDecimal flddecToppExtraFee)
	{
		writeProperty("flddecToppExtraFee", flddecToppExtraFee);
	}

	public BigDecimal getFlddecToppExtraFee()
	{
		return (BigDecimal) readProperty("flddecToppExtraFee");
	}

	public void setFlddecToppMaxAllow(BigDecimal flddecToppMaxAllow)
	{
		writeProperty("flddecToppMaxAllow", flddecToppMaxAllow);
	}

	public BigDecimal getFlddecToppMaxAllow()
	{
		return (BigDecimal) readProperty("flddecToppMaxAllow");
	}

	public void setFldintBookcAcctNum(Integer fldintBookcAcctNum)
	{
		writeProperty("fldintBookcAcctNum", fldintBookcAcctNum);
	}

	public Integer getFldintBookcAcctNum()
	{
		return (Integer) readProperty("fldintBookcAcctNum");
	}

	public void setFldintContactAcctNum(Integer fldintContactAcctNum)
	{
		writeProperty("fldintContactAcctNum", fldintContactAcctNum);
	}

	public Integer getFldintContactAcctNum()
	{
		return (Integer) readProperty("fldintContactAcctNum");
	}

	public void setFldintCpartAcctNum(Integer fldintCpartAcctNum)
	{
		writeProperty("fldintCpartAcctNum", fldintCpartAcctNum);
	}

	public Integer getFldintCpartAcctNum()
	{
		return (Integer) readProperty("fldintCpartAcctNum");
	}

	public void setFldintStorageFeeAllowDays(Integer fldintStorageFeeAllowDays)
	{
		writeProperty("fldintStorageFeeAllowDays", fldintStorageFeeAllowDays);
	}

	public Integer getFldintStorageFeeAllowDays()
	{
		return (Integer) readProperty("fldintStorageFeeAllowDays");
	}

	public void setFldintStorageFeeDays(Integer fldintStorageFeeDays)
	{
		writeProperty("fldintStorageFeeDays", fldintStorageFeeDays);
	}

	public Integer getFldintStorageFeeDays()
	{
		return (Integer) readProperty("fldintStorageFeeDays");
	}

	public void setFldsdtContrDate(Date fldsdtContrDate)
	{
		writeProperty("fldsdtContrDate", fldsdtContrDate);
	}

	public Date getFldsdtContrDate()
	{
		return (Date) readProperty("fldsdtContrDate");
	}

	public void setFldsdtContrEndDate(Date fldsdtContrEndDate)
	{
		writeProperty("fldsdtContrEndDate", fldsdtContrEndDate);
	}

	public Date getFldsdtContrEndDate()
	{
		return (Date) readProperty("fldsdtContrEndDate");
	}

	public void setFldsdtContrNegotiationDate(Date fldsdtContrNegotiationDate)
	{
		writeProperty("fldsdtContrNegotiationDate", fldsdtContrNegotiationDate);
	}

	public Date getFldsdtContrNegotiationDate()
	{
		return (Date) readProperty("fldsdtContrNegotiationDate");
	}

	public void setFldsdtContrStartDate(Date fldsdtContrStartDate)
	{
		writeProperty("fldsdtContrStartDate", fldsdtContrStartDate);
	}

	public Date getFldsdtContrStartDate()
	{
		return (Date) readProperty("fldsdtContrStartDate");
	}

	public void setFldsmiContrDuration(Short fldsmiContrDuration)
	{
		writeProperty("fldsmiContrDuration", fldsmiContrDuration);
	}

	public Short getFldsmiContrDuration()
	{
		return (Short) readProperty("fldsmiContrDuration");
	}

	public void setFldvchContrForm(String fldvchContrForm)
	{
		writeProperty("fldvchContrForm", fldvchContrForm);
	}

	public String getFldvchContrForm()
	{
		return (String) readProperty("fldvchContrForm");
	}

	public void setFldvchCpartContrNum(String fldvchCpartContrNum)
	{
		writeProperty("fldvchCpartContrNum", fldvchCpartContrNum);
	}

	public String getFldvchCpartContrNum()
	{
		return (String) readProperty("fldvchCpartContrNum");
	}

	public void setFldvchRenewalOption(String fldvchRenewalOption)
	{
		writeProperty("fldvchRenewalOption", fldvchRenewalOption);
	}

	public String getFldvchRenewalOption()
	{
		return (String) readProperty("fldvchRenewalOption");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setCommodity1(Commodity commodity1)
	{
		setToOneTarget("commodity1", commodity1, true);
	}

	public Commodity getCommodity1()
	{
		return (Commodity) readProperty("commodity1");
	}

	public void setCommodity2(Commodity commodity2)
	{
		setToOneTarget("commodity2", commodity2, true);
	}

	public Commodity getCommodity2()
	{
		return (Commodity) readProperty("commodity2");
	}

	public void setCommodity3(Commodity commodity3)
	{
		setToOneTarget("commodity3", commodity3, true);
	}

	public Commodity getCommodity3()
	{
		return (Commodity) readProperty("commodity3");
	}

	public void setCommodity4(Commodity commodity4)
	{
		setToOneTarget("commodity4", commodity4, true);
	}

	public Commodity getCommodity4()
	{
		return (Commodity) readProperty("commodity4");
	}

	public void setCommodity5(Commodity commodity5)
	{
		setToOneTarget("commodity5", commodity5, true);
	}

	public Commodity getCommodity5()
	{
		return (Commodity) readProperty("commodity5");
	}

	public void setIctsUser(IctsUser ictsUser)
	{
		setToOneTarget("ictsUser", ictsUser, true);
	}

	public IctsUser getIctsUser()
	{
		return (IctsUser) readProperty("ictsUser");
	}

	public void setIctsUser1(IctsUser ictsUser1)
	{
		setToOneTarget("ictsUser1", ictsUser1, true);
	}

	public IctsUser getIctsUser1()
	{
		return (IctsUser) readProperty("ictsUser1");
	}

	public void setPipeline(Pipeline pipeline)
	{
		setToOneTarget("pipeline", pipeline, true);
	}

	public Pipeline getPipeline()
	{
		return (Pipeline) readProperty("pipeline");
	}

	public void addToPlContractExclusionss(PlContractExclusions obj)
	{
		addToManyTarget("plContractExclusionss", obj, true);
	}

	public void removeFromPlContractExclusionss(PlContractExclusions obj)
	{
		removeToManyTarget("plContractExclusionss", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<PlContractExclusions> getPlContractExclusionss()
	{
		return (List<PlContractExclusions>) readProperty("plContractExclusionss");
	}

	public void addToPlContractLaytimeses(PlContractLaytimes obj)
	{
		addToManyTarget("plContractLaytimeses", obj, true);
	}

	public void removeFromPlContractLaytimeses(PlContractLaytimes obj)
	{
		removeToManyTarget("plContractLaytimeses", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<PlContractLaytimes> getPlContractLaytimeses()
	{
		return (List<PlContractLaytimes>) readProperty("plContractLaytimeses");
	}

	public void addToPlContractLosseses(PlContractLosses obj)
	{
		addToManyTarget("plContractLosseses", obj, true);
	}

	public void removeFromPlContractLosseses(PlContractLosses obj)
	{
		removeToManyTarget("plContractLosseses", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<PlContractLosses> getPlContractLosseses()
	{
		return (List<PlContractLosses>) readProperty("plContractLosseses");
	}

	public void addToPlContractTariffAdjs(PlContractTariffAdj obj)
	{
		addToManyTarget("plContractTariffAdjs", obj, true);
	}

	public void removeFromPlContractTariffAdjs(PlContractTariffAdj obj)
	{
		removeToManyTarget("plContractTariffAdjs", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<PlContractTariffAdj> getPlContractTariffAdjs()
	{
		return (List<PlContractTariffAdj>) readProperty("plContractTariffAdjs");
	}

	public void addToPlContractTariffss(PlContractTariffs obj)
	{
		addToManyTarget("plContractTariffss", obj, true);
	}

	public void removeFromPlContractTariffss(PlContractTariffs obj)
	{
		removeToManyTarget("plContractTariffss", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<PlContractTariffs> getPlContractTariffss()
	{
		return (List<PlContractTariffs>) readProperty("plContractTariffss");
	}

	public void addToPlContractTerminalss(PlContractTerminals obj)
	{
		addToManyTarget("plContractTerminalss", obj, true);
	}

	public void removeFromPlContractTerminalss(PlContractTerminals obj)
	{
		removeToManyTarget("plContractTerminalss", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<PlContractTerminals> getPlContractTerminalss()
	{
		return (List<PlContractTerminals>) readProperty("plContractTerminalss");
	}

	public void addToPlContractViscositieses(PlContractViscosities obj)
	{
		addToManyTarget("plContractViscositieses", obj, true);
	}

	public void removeFromPlContractViscositieses(PlContractViscosities obj)
	{
		removeToManyTarget("plContractViscositieses", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<PlContractViscosities> getPlContractViscositieses()
	{
		return (List<PlContractViscosities>) readProperty("plContractViscositieses");
	}

	public void addToPlTransfers(PlTransfer obj)
	{
		addToManyTarget("plTransfers", obj, true);
	}

	public void removeFromPlTransfers(PlTransfer obj)
	{
		removeToManyTarget("plTransfers", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<PlTransfer> getPlTransfers()
	{
		return (List<PlTransfer>) readProperty("plTransfers");
	}

	public void setWorkArea(WorkArea workArea)
	{
		setToOneTarget("workArea", workArea, true);
	}

	public WorkArea getWorkArea()
	{
		return (WorkArea) readProperty("workArea");
	}

}
