package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PlContract;

/**
 * Class _PlContractTariffs was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PlContractTariffs extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_REC_ID_PK_COLUMN = "fldchrRecId";

	public static final Property<String> FLDCHR_HI_LIMIT_HANDLING_FLAG = new Property<String>("fldchrHiLimitHandlingFlag");
	public static final Property<String> FLDCHR_LIMIT_UMCODE = new Property<String>("fldchrLimitUMCode");
	public static final Property<String> FLDCHR_LO_LIMIT_HANDLING_FLAG = new Property<String>("fldchrLoLimitHandlingFlag");
	public static final Property<String> FLDCHR_PLTRML_KEY = new Property<String>("fldchrPLTrmlKey");
	public static final Property<String> FLDCHR_TARIFF_UMCODE = new Property<String>("fldchrTariffUMCode");
	public static final Property<BigDecimal> FLDDEC_TARIFF = new Property<BigDecimal>("flddecTariff");
	public static final Property<Integer> FLDINT_HI_LIMIT = new Property<Integer>("fldintHiLimit");
	public static final Property<Integer> FLDINT_LO_LIMIT = new Property<Integer>("fldintLoLimit");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<Commodity> COMMODITY1 = new Property<Commodity>("commodity1");
	public static final Property<Commodity> COMMODITY2 = new Property<Commodity>("commodity2");
	public static final Property<PlContract> PL_CONTRACT = new Property<PlContract>("plContract");

	public void setFldchrHiLimitHandlingFlag(String fldchrHiLimitHandlingFlag)
	{
		writeProperty("fldchrHiLimitHandlingFlag", fldchrHiLimitHandlingFlag);
	}

	public String getFldchrHiLimitHandlingFlag()
	{
		return (String) readProperty("fldchrHiLimitHandlingFlag");
	}

	public void setFldchrLimitUMCode(String fldchrLimitUMCode)
	{
		writeProperty("fldchrLimitUMCode", fldchrLimitUMCode);
	}

	public String getFldchrLimitUMCode()
	{
		return (String) readProperty("fldchrLimitUMCode");
	}

	public void setFldchrLoLimitHandlingFlag(String fldchrLoLimitHandlingFlag)
	{
		writeProperty("fldchrLoLimitHandlingFlag", fldchrLoLimitHandlingFlag);
	}

	public String getFldchrLoLimitHandlingFlag()
	{
		return (String) readProperty("fldchrLoLimitHandlingFlag");
	}

	public void setFldchrPLTrmlKey(String fldchrPLTrmlKey)
	{
		writeProperty("fldchrPLTrmlKey", fldchrPLTrmlKey);
	}

	public String getFldchrPLTrmlKey()
	{
		return (String) readProperty("fldchrPLTrmlKey");
	}

	public void setFldchrTariffUMCode(String fldchrTariffUMCode)
	{
		writeProperty("fldchrTariffUMCode", fldchrTariffUMCode);
	}

	public String getFldchrTariffUMCode()
	{
		return (String) readProperty("fldchrTariffUMCode");
	}

	public void setFlddecTariff(BigDecimal flddecTariff)
	{
		writeProperty("flddecTariff", flddecTariff);
	}

	public BigDecimal getFlddecTariff()
	{
		return (BigDecimal) readProperty("flddecTariff");
	}

	public void setFldintHiLimit(Integer fldintHiLimit)
	{
		writeProperty("fldintHiLimit", fldintHiLimit);
	}

	public Integer getFldintHiLimit()
	{
		return (Integer) readProperty("fldintHiLimit");
	}

	public void setFldintLoLimit(Integer fldintLoLimit)
	{
		writeProperty("fldintLoLimit", fldintLoLimit);
	}

	public Integer getFldintLoLimit()
	{
		return (Integer) readProperty("fldintLoLimit");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setCommodity1(Commodity commodity1)
	{
		setToOneTarget("commodity1", commodity1, true);
	}

	public Commodity getCommodity1()
	{
		return (Commodity) readProperty("commodity1");
	}

	public void setCommodity2(Commodity commodity2)
	{
		setToOneTarget("commodity2", commodity2, true);
	}

	public Commodity getCommodity2()
	{
		return (Commodity) readProperty("commodity2");
	}

	public void setPlContract(PlContract plContract)
	{
		setToOneTarget("plContract", plContract, true);
	}

	public PlContract getPlContract()
	{
		return (PlContract) readProperty("plContract");
	}

}
