package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PlContract;

/**
 * Class _PlContractLosses was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PlContractLosses extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_REC_ID_PK_COLUMN = "fldchrRecId";

	public static final Property<BigDecimal> FLDDEC_CONTR_LOSS = new Property<BigDecimal>("flddecContrLoss");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<Commodity> COMMODITY1 = new Property<Commodity>("commodity1");
	public static final Property<PlContract> PL_CONTRACT = new Property<PlContract>("plContract");

	public void setFlddecContrLoss(BigDecimal flddecContrLoss)
	{
		writeProperty("flddecContrLoss", flddecContrLoss);
	}

	public BigDecimal getFlddecContrLoss()
	{
		return (BigDecimal) readProperty("flddecContrLoss");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setCommodity1(Commodity commodity1)
	{
		setToOneTarget("commodity1", commodity1, true);
	}

	public Commodity getCommodity1()
	{
		return (Commodity) readProperty("commodity1");
	}

	public void setPlContract(PlContract plContract)
	{
		setToOneTarget("plContract", plContract, true);
	}

	public PlContract getPlContract()
	{
		return (PlContract) readProperty("plContract");
	}

}
