package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _PortfolioEodIcon was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PortfolioEodIcon extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String PORT_NUM_PK_COLUMN = "port_num";

	public static final Property<byte[]> ICON = new Property<byte[]>("icon");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setIcon(byte[] icon)
	{
		writeProperty("icon", icon);
	}

	public byte[] getIcon()
	{
		return (byte[]) readProperty("icon");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
