package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _PostedPriceDetail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PostedPriceDetail extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Double> ADJ_PRICE = new Property<Double>("adjPrice");
	public static final Property<BigDecimal> ADJUSTMENT = new Property<BigDecimal>("adjustment");
	public static final Property<String> COMMODITY = new Property<String>("commodity");
	public static final Property<Date> EFFECT_DATE = new Property<Date>("effectDate");
	public static final Property<String> GRAVITY_TABLE = new Property<String>("gravityTable");
	public static final Property<String> MARKET = new Property<String>("market");
	public static final Property<Double> POSTED_GRAVITY = new Property<Double>("postedGravity");
	public static final Property<Double> POSTED_PRICE = new Property<Double>("postedPrice");
	public static final Property<String> SOURCE = new Property<String>("source");

	public void setAdjPrice(Double adjPrice)
	{
		writeProperty("adjPrice", adjPrice);
	}

	public Double getAdjPrice()
	{
		return (Double) readProperty("adjPrice");
	}

	public void setAdjustment(BigDecimal adjustment)
	{
		writeProperty("adjustment", adjustment);
	}

	public BigDecimal getAdjustment()
	{
		return (BigDecimal) readProperty("adjustment");
	}

	public void setCommodity(String commodity)
	{
		writeProperty("commodity", commodity);
	}

	public String getCommodity()
	{
		return (String) readProperty("commodity");
	}

	public void setEffectDate(Date effectDate)
	{
		writeProperty("effectDate", effectDate);
	}

	public Date getEffectDate()
	{
		return (Date) readProperty("effectDate");
	}

	public void setGravityTable(String gravityTable)
	{
		writeProperty("gravityTable", gravityTable);
	}

	public String getGravityTable()
	{
		return (String) readProperty("gravityTable");
	}

	public void setMarket(String market)
	{
		writeProperty("market", market);
	}

	public String getMarket()
	{
		return (String) readProperty("market");
	}

	public void setPostedGravity(Double postedGravity)
	{
		writeProperty("postedGravity", postedGravity);
	}

	public Double getPostedGravity()
	{
		return (Double) readProperty("postedGravity");
	}

	public void setPostedPrice(Double postedPrice)
	{
		writeProperty("postedPrice", postedPrice);
	}

	public Double getPostedPrice()
	{
		return (Double) readProperty("postedPrice");
	}

	public void setSource(String source)
	{
		writeProperty("source", source);
	}

	public String getSource()
	{
		return (String) readProperty("source");
	}

}
