package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Location;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _RailcarPtpRate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RailcarPtpRate extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String DESTIN_LOC_CODE_PK_COLUMN = "destin_loc_code";
	public static final String ORDER_NUM_PK_COLUMN = "order_num";
	public static final String ORIGIN_LOC_CODE_PK_COLUMN = "origin_loc_code";
	public static final String TRADE_NUM_PK_COLUMN = "trade_num";

	public static final Property<Double> RATE_AMOUNT = new Property<>("rateAmount");
	public static final Property<String> REC_DEL_IND_FOR_COST = new Property<>("recDelIndForCost");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<Commodity> COMMODITY = new Property<>("commodity");
	public static final Property<Location> LOCATION = new Property<>("location");
	public static final Property<Location> LOCATION1 = new Property<>("location1");
	public static final Property<Uom> UOM = new Property<>("uom");

	public void setRateAmount(final Double rateAmount)
	{
		this.writeProperty("rateAmount", rateAmount);
	}

	public Double getRateAmount()
	{
		return (Double) this.readProperty("rateAmount");
	}

	public void setRecDelIndForCost(final String recDelIndForCost)
	{
		this.writeProperty("recDelIndForCost", recDelIndForCost);
	}

	public String getRecDelIndForCost()
	{
		return (String) this.readProperty("recDelIndForCost");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setCommodity(final Commodity commodity)
	{
		this.setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) this.readProperty("commodity");
	}

	public void setLocation(final Location location)
	{
		this.setToOneTarget("location", location, true);
	}

	public Location getLocation()
	{
		return (Location) this.readProperty("location");
	}

	public void setLocation1(final Location location1)
	{
		this.setToOneTarget("location1", location1, true);
	}

	public Location getLocation1()
	{
		return (Location) this.readProperty("location1");
	}

	public void setUom(final Uom uom)
	{
		this.setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) this.readProperty("uom");
	}

}
