package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.ReportExcelConfig;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ReportNameLinks;
import com.tc.app.exchangemonitor.model.cayenne.persistent.WorkArea;

/**
 * Class _Report was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Report extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDINT_REPORT_ID_PK_COLUMN = "fldintReportId";

	public static final Property<String> FLDCHR_REPORT_ID = new Property<String>("fldchrReportId");
	public static final Property<String> FLDVCH_REPORT_DESC = new Property<String>("fldvchReportDesc");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<List<ReportExcelConfig>> REPORT_EXCEL_CONFIGS = new Property<List<ReportExcelConfig>>("reportExcelConfigs");
	public static final Property<List<ReportNameLinks>> REPORT_NAME_LINKSS = new Property<List<ReportNameLinks>>("reportNameLinkss");
	public static final Property<WorkArea> WORK_AREA = new Property<WorkArea>("workArea");

	public void setFldchrReportId(String fldchrReportId)
	{
		writeProperty("fldchrReportId", fldchrReportId);
	}

	public String getFldchrReportId()
	{
		return (String) readProperty("fldchrReportId");
	}

	public void setFldvchReportDesc(String fldvchReportDesc)
	{
		writeProperty("fldvchReportDesc", fldvchReportDesc);
	}

	public String getFldvchReportDesc()
	{
		return (String) readProperty("fldvchReportDesc");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void addToReportExcelConfigs(ReportExcelConfig obj)
	{
		addToManyTarget("reportExcelConfigs", obj, true);
	}

	public void removeFromReportExcelConfigs(ReportExcelConfig obj)
	{
		removeToManyTarget("reportExcelConfigs", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ReportExcelConfig> getReportExcelConfigs()
	{
		return (List<ReportExcelConfig>) readProperty("reportExcelConfigs");
	}

	public void addToReportNameLinkss(ReportNameLinks obj)
	{
		addToManyTarget("reportNameLinkss", obj, true);
	}

	public void removeFromReportNameLinkss(ReportNameLinks obj)
	{
		removeToManyTarget("reportNameLinkss", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ReportNameLinks> getReportNameLinkss()
	{
		return (List<ReportNameLinks>) readProperty("reportNameLinkss");
	}

	public void setWorkArea(WorkArea workArea)
	{
		setToOneTarget("workArea", workArea, true);
	}

	public WorkArea getWorkArea()
	{
		return (WorkArea) readProperty("workArea");
	}

}
