package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.ReportLinksPcka;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ReportParamsPcka;
import com.tc.app.exchangemonitor.model.cayenne.persistent.WorkArea;

/**
 * Class _ReportPcka was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ReportPcka extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDINT_REPORT_PCKA_REC_ID_PK_COLUMN = "fldintReportPckaRecId";

	public static final Property<String> FLDCHR_CONTEXT_ID = new Property<String>("fldchrContextId");
	public static final Property<String> FLDCHR_ENABLE_EXCEL = new Property<String>("fldchrEnableExcel");
	public static final Property<String> FLDCHR_ENABLE_PRINT = new Property<String>("fldchrEnablePrint");
	public static final Property<String> FLDCHR_ENABLE_REPORT = new Property<String>("fldchrEnableReport");
	public static final Property<String> FLDVCH_REPORT_DESC = new Property<String>("fldvchReportDesc");
	public static final Property<List<ReportLinksPcka>> REPORT_LINKS_PCKAS = new Property<List<ReportLinksPcka>>("reportLinksPckas");
	public static final Property<List<ReportParamsPcka>> REPORT_PARAMS_PCKAS = new Property<List<ReportParamsPcka>>("reportParamsPckas");
	public static final Property<WorkArea> WORK_AREA = new Property<WorkArea>("workArea");

	public void setFldchrContextId(String fldchrContextId)
	{
		writeProperty("fldchrContextId", fldchrContextId);
	}

	public String getFldchrContextId()
	{
		return (String) readProperty("fldchrContextId");
	}

	public void setFldchrEnableExcel(String fldchrEnableExcel)
	{
		writeProperty("fldchrEnableExcel", fldchrEnableExcel);
	}

	public String getFldchrEnableExcel()
	{
		return (String) readProperty("fldchrEnableExcel");
	}

	public void setFldchrEnablePrint(String fldchrEnablePrint)
	{
		writeProperty("fldchrEnablePrint", fldchrEnablePrint);
	}

	public String getFldchrEnablePrint()
	{
		return (String) readProperty("fldchrEnablePrint");
	}

	public void setFldchrEnableReport(String fldchrEnableReport)
	{
		writeProperty("fldchrEnableReport", fldchrEnableReport);
	}

	public String getFldchrEnableReport()
	{
		return (String) readProperty("fldchrEnableReport");
	}

	public void setFldvchReportDesc(String fldvchReportDesc)
	{
		writeProperty("fldvchReportDesc", fldvchReportDesc);
	}

	public String getFldvchReportDesc()
	{
		return (String) readProperty("fldvchReportDesc");
	}

	public void addToReportLinksPckas(ReportLinksPcka obj)
	{
		addToManyTarget("reportLinksPckas", obj, true);
	}

	public void removeFromReportLinksPckas(ReportLinksPcka obj)
	{
		removeToManyTarget("reportLinksPckas", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ReportLinksPcka> getReportLinksPckas()
	{
		return (List<ReportLinksPcka>) readProperty("reportLinksPckas");
	}

	public void addToReportParamsPckas(ReportParamsPcka obj)
	{
		addToManyTarget("reportParamsPckas", obj, true);
	}

	public void removeFromReportParamsPckas(ReportParamsPcka obj)
	{
		removeToManyTarget("reportParamsPckas", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ReportParamsPcka> getReportParamsPckas()
	{
		return (List<ReportParamsPcka>) readProperty("reportParamsPckas");
	}

	public void setWorkArea(WorkArea workArea)
	{
		setToOneTarget("workArea", workArea, true);
	}

	public WorkArea getWorkArea()
	{
		return (WorkArea) readProperty("workArea");
	}

}
