package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.ReportExcelPckb;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ReportPckb;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ReportSubPckb;

/**
 * Class _ReportLinksPckb was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ReportLinksPckb extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDINT_REPORT_LINKS_PCKB_REC_ID_PK_COLUMN = "fldintReportLinksPckbRecId";

	public static final Property<String> FLDCHR_PRINT_LAY_OUT = new Property<String>("fldchrPrintLayOut");
	public static final Property<String> FLDCHR_REPORT_DESCR = new Property<String>("fldchrReportDescr");
	public static final Property<String> FLDCHR_REPORT_NAME = new Property<String>("fldchrReportName");
	public static final Property<String> FLDCHR_SUB_REPORT_FLAG = new Property<String>("fldchrSubReportFlag");
	public static final Property<ReportPckb> FLDINT_REPORT_PCKB_REC = new Property<ReportPckb>("fldintReportPckbRec");
	public static final Property<List<ReportExcelPckb>> REPORT_EXCEL_PCKBS = new Property<List<ReportExcelPckb>>("reportExcelPckbs");
	public static final Property<List<ReportSubPckb>> REPORT_SUB_PCKBS = new Property<List<ReportSubPckb>>("reportSubPckbs");

	public void setFldchrPrintLayOut(String fldchrPrintLayOut)
	{
		writeProperty("fldchrPrintLayOut", fldchrPrintLayOut);
	}

	public String getFldchrPrintLayOut()
	{
		return (String) readProperty("fldchrPrintLayOut");
	}

	public void setFldchrReportDescr(String fldchrReportDescr)
	{
		writeProperty("fldchrReportDescr", fldchrReportDescr);
	}

	public String getFldchrReportDescr()
	{
		return (String) readProperty("fldchrReportDescr");
	}

	public void setFldchrReportName(String fldchrReportName)
	{
		writeProperty("fldchrReportName", fldchrReportName);
	}

	public String getFldchrReportName()
	{
		return (String) readProperty("fldchrReportName");
	}

	public void setFldchrSubReportFlag(String fldchrSubReportFlag)
	{
		writeProperty("fldchrSubReportFlag", fldchrSubReportFlag);
	}

	public String getFldchrSubReportFlag()
	{
		return (String) readProperty("fldchrSubReportFlag");
	}

	public void setFldintReportPckbRec(ReportPckb fldintReportPckbRec)
	{
		setToOneTarget("fldintReportPckbRec", fldintReportPckbRec, true);
	}

	public ReportPckb getFldintReportPckbRec()
	{
		return (ReportPckb) readProperty("fldintReportPckbRec");
	}

	public void addToReportExcelPckbs(ReportExcelPckb obj)
	{
		addToManyTarget("reportExcelPckbs", obj, true);
	}

	public void removeFromReportExcelPckbs(ReportExcelPckb obj)
	{
		removeToManyTarget("reportExcelPckbs", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ReportExcelPckb> getReportExcelPckbs()
	{
		return (List<ReportExcelPckb>) readProperty("reportExcelPckbs");
	}

	public void addToReportSubPckbs(ReportSubPckb obj)
	{
		addToManyTarget("reportSubPckbs", obj, true);
	}

	public void removeFromReportSubPckbs(ReportSubPckb obj)
	{
		removeToManyTarget("reportSubPckbs", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ReportSubPckb> getReportSubPckbs()
	{
		return (List<ReportSubPckb>) readProperty("reportSubPckbs");
	}

}
