package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _ReportContextLinks was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ReportContextLinks extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_CONTEXT_ID_PK_COLUMN = "fldchrContextId";
	public static final String FLDINT_REPORT_ID_PK_COLUMN = "fldintReportId";

	public static final Property<String> FLDCHR_EXCEL_REPORT_NAME = new Property<String>("fldchrExcelReportName");
	public static final Property<String> FLDCHR_FLAG_EXPORT_EXCEL = new Property<String>("fldchrFlagExportExcel");
	public static final Property<String> FLDCHR_REC_ID = new Property<String>("fldchrRecId");
	public static final Property<String> FLDCHR_REPORT_ID = new Property<String>("fldchrReportId");
	public static final Property<String> FLDCHR_REPORT_NAME = new Property<String>("fldchrReportName");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setFldchrExcelReportName(String fldchrExcelReportName)
	{
		writeProperty("fldchrExcelReportName", fldchrExcelReportName);
	}

	public String getFldchrExcelReportName()
	{
		return (String) readProperty("fldchrExcelReportName");
	}

	public void setFldchrFlagExportExcel(String fldchrFlagExportExcel)
	{
		writeProperty("fldchrFlagExportExcel", fldchrFlagExportExcel);
	}

	public String getFldchrFlagExportExcel()
	{
		return (String) readProperty("fldchrFlagExportExcel");
	}

	public void setFldchrRecId(String fldchrRecId)
	{
		writeProperty("fldchrRecId", fldchrRecId);
	}

	public String getFldchrRecId()
	{
		return (String) readProperty("fldchrRecId");
	}

	public void setFldchrReportId(String fldchrReportId)
	{
		writeProperty("fldchrReportId", fldchrReportId);
	}

	public String getFldchrReportId()
	{
		return (String) readProperty("fldchrReportId");
	}

	public void setFldchrReportName(String fldchrReportName)
	{
		writeProperty("fldchrReportName", fldchrReportName);
	}

	public String getFldchrReportName()
	{
		return (String) readProperty("fldchrReportName");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
