package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.RiskmgrWinDef;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _RiskmgrWinPivotDef was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RiskmgrWinPivotDef extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> ASOF_DATE = new Property<String>("asofDate");
	public static final Property<Short> NUM_OF_DECIMALS = new Property<Short>("numOfDecimals");
	public static final Property<Integer> PIV_DEF_ID = new Property<Integer>("pivDefId");
	public static final Property<String> PIVOT_LAYOUT = new Property<String>("pivotLayout");
	public static final Property<String> PRIMARY_UOM = new Property<String>("primaryUom");
	public static final Property<String> SHOW_FUTURE_EQUIV = new Property<String>("showFutureEquiv");
	public static final Property<String> SHOW_ZERO = new Property<String>("showZero");
	public static final Property<Integer> TAB_INDEX = new Property<Integer>("tabIndex");
	public static final Property<String> TAB_NAME = new Property<String>("tabName");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<RiskmgrWinDef> OWNER_WIN = new Property<RiskmgrWinDef>("ownerWin");
	public static final Property<Uom> UOM1 = new Property<Uom>("uom1");

	public void setAsofDate(String asofDate)
	{
		writeProperty("asofDate", asofDate);
	}

	public String getAsofDate()
	{
		return (String) readProperty("asofDate");
	}

	public void setNumOfDecimals(Short numOfDecimals)
	{
		writeProperty("numOfDecimals", numOfDecimals);
	}

	public Short getNumOfDecimals()
	{
		return (Short) readProperty("numOfDecimals");
	}

	public void setPivDefId(Integer pivDefId)
	{
		writeProperty("pivDefId", pivDefId);
	}

	public Integer getPivDefId()
	{
		return (Integer) readProperty("pivDefId");
	}

	public void setPivotLayout(String pivotLayout)
	{
		writeProperty("pivotLayout", pivotLayout);
	}

	public String getPivotLayout()
	{
		return (String) readProperty("pivotLayout");
	}

	public void setPrimaryUom(String primaryUom)
	{
		writeProperty("primaryUom", primaryUom);
	}

	public String getPrimaryUom()
	{
		return (String) readProperty("primaryUom");
	}

	public void setShowFutureEquiv(String showFutureEquiv)
	{
		writeProperty("showFutureEquiv", showFutureEquiv);
	}

	public String getShowFutureEquiv()
	{
		return (String) readProperty("showFutureEquiv");
	}

	public void setShowZero(String showZero)
	{
		writeProperty("showZero", showZero);
	}

	public String getShowZero()
	{
		return (String) readProperty("showZero");
	}

	public void setTabIndex(Integer tabIndex)
	{
		writeProperty("tabIndex", tabIndex);
	}

	public Integer getTabIndex()
	{
		return (Integer) readProperty("tabIndex");
	}

	public void setTabName(String tabName)
	{
		writeProperty("tabName", tabName);
	}

	public String getTabName()
	{
		return (String) readProperty("tabName");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setOwnerWin(RiskmgrWinDef ownerWin)
	{
		setToOneTarget("ownerWin", ownerWin, true);
	}

	public RiskmgrWinDef getOwnerWin()
	{
		return (RiskmgrWinDef) readProperty("ownerWin");
	}

	public void setUom1(Uom uom1)
	{
		setToOneTarget("uom1", uom1, true);
	}

	public Uom getUom1()
	{
		return (Uom) readProperty("uom1");
	}

}
