package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Route was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Route extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> FROM_LOC_CODE = new Property<String>("fromLocCode");
	public static final Property<String> ROUTE_NAME = new Property<String>("routeName");
	public static final Property<String> TO_LOC_CODE = new Property<String>("toLocCode");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setFromLocCode(String fromLocCode)
	{
		writeProperty("fromLocCode", fromLocCode);
	}

	public String getFromLocCode()
	{
		return (String) readProperty("fromLocCode");
	}

	public void setRouteName(String routeName)
	{
		writeProperty("routeName", routeName);
	}

	public String getRouteName()
	{
		return (String) readProperty("routeName");
	}

	public void setToLocCode(String toLocCode)
	{
		writeProperty("toLocCode", toLocCode);
	}

	public String getToLocCode()
	{
		return (String) readProperty("toLocCode");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
