package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.AllocationItem;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Market;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Portfolio;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TradeItem;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _ScenarioItem was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ScenarioItem extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> ACCT_REF_NUM = new Property<String>("acctRefNum");
	public static final Property<String> BUY_SELL_IND = new Property<String>("buySellInd");
	public static final Property<Date> DEL_END_DATE = new Property<Date>("delEndDate");
	public static final Property<Date> DEL_START_DATE = new Property<Date>("delStartDate");
	public static final Property<BigDecimal> DIFFERENTIAL = new Property<BigDecimal>("differential");
	public static final Property<String> DISCH_PORT_LOC_CODE = new Property<String>("dischPortLocCode");
	public static final Property<String> LOAD_PORT_LOC_CODE = new Property<String>("loadPortLocCode");
	public static final Property<String> MOT_CODE = new Property<String>("motCode");
	public static final Property<Integer> OPP_PORT_NUM = new Property<Integer>("oppPortNum");
	public static final Property<String> PRICE_CURR_CODE = new Property<String>("priceCurrCode");
	public static final Property<Date> PRICE_END_DATE = new Property<Date>("priceEndDate");
	public static final Property<Date> PRICE_START_DATE = new Property<Date>("priceStartDate");
	public static final Property<BigDecimal> QTY = new Property<BigDecimal>("qty");
	public static final Property<BigDecimal> QTY_PERCENT = new Property<BigDecimal>("qtyPercent");
	public static final Property<String> QTY_PERIODICITY = new Property<String>("qtyPeriodicity");
	public static final Property<String> QUOTE = new Property<String>("quote");
	public static final Property<Integer> REF_SUB_ALLOC_NUM = new Property<Integer>("refSubAllocNum");
	public static final Property<String> RISK_PERIOD = new Property<String>("riskPeriod");
	public static final Property<Integer> SCENARIO_ID = new Property<Integer>("scenarioId");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Account> ACCOUNT = new Property<Account>("account");
	public static final Property<Account> ACCOUNT1 = new Property<Account>("account1");
	public static final Property<AllocationItem> ALLOCATION_ITEM = new Property<AllocationItem>("allocationItem");
	public static final Property<AllocationItem> ALLOCATION_ITEM1 = new Property<AllocationItem>("allocationItem1");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<Market> MARKET = new Property<Market>("market");
	public static final Property<Portfolio> PORTFOLIO = new Property<Portfolio>("portfolio");
	public static final Property<TradeItem> TRADE_ITEM = new Property<TradeItem>("tradeItem");
	public static final Property<TradeItem> TRADE_ITEM1 = new Property<TradeItem>("tradeItem1");
	public static final Property<TradeItem> TRADE_ITEM2 = new Property<TradeItem>("tradeItem2");
	public static final Property<Uom> UOM = new Property<Uom>("uom");
	public static final Property<Uom> UOM1 = new Property<Uom>("uom1");

	public void setAcctRefNum(String acctRefNum)
	{
		writeProperty("acctRefNum", acctRefNum);
	}

	public String getAcctRefNum()
	{
		return (String) readProperty("acctRefNum");
	}

	public void setBuySellInd(String buySellInd)
	{
		writeProperty("buySellInd", buySellInd);
	}

	public String getBuySellInd()
	{
		return (String) readProperty("buySellInd");
	}

	public void setDelEndDate(Date delEndDate)
	{
		writeProperty("delEndDate", delEndDate);
	}

	public Date getDelEndDate()
	{
		return (Date) readProperty("delEndDate");
	}

	public void setDelStartDate(Date delStartDate)
	{
		writeProperty("delStartDate", delStartDate);
	}

	public Date getDelStartDate()
	{
		return (Date) readProperty("delStartDate");
	}

	public void setDifferential(BigDecimal differential)
	{
		writeProperty("differential", differential);
	}

	public BigDecimal getDifferential()
	{
		return (BigDecimal) readProperty("differential");
	}

	public void setDischPortLocCode(String dischPortLocCode)
	{
		writeProperty("dischPortLocCode", dischPortLocCode);
	}

	public String getDischPortLocCode()
	{
		return (String) readProperty("dischPortLocCode");
	}

	public void setLoadPortLocCode(String loadPortLocCode)
	{
		writeProperty("loadPortLocCode", loadPortLocCode);
	}

	public String getLoadPortLocCode()
	{
		return (String) readProperty("loadPortLocCode");
	}

	public void setMotCode(String motCode)
	{
		writeProperty("motCode", motCode);
	}

	public String getMotCode()
	{
		return (String) readProperty("motCode");
	}

	public void setOppPortNum(Integer oppPortNum)
	{
		writeProperty("oppPortNum", oppPortNum);
	}

	public Integer getOppPortNum()
	{
		return (Integer) readProperty("oppPortNum");
	}

	public void setPriceCurrCode(String priceCurrCode)
	{
		writeProperty("priceCurrCode", priceCurrCode);
	}

	public String getPriceCurrCode()
	{
		return (String) readProperty("priceCurrCode");
	}

	public void setPriceEndDate(Date priceEndDate)
	{
		writeProperty("priceEndDate", priceEndDate);
	}

	public Date getPriceEndDate()
	{
		return (Date) readProperty("priceEndDate");
	}

	public void setPriceStartDate(Date priceStartDate)
	{
		writeProperty("priceStartDate", priceStartDate);
	}

	public Date getPriceStartDate()
	{
		return (Date) readProperty("priceStartDate");
	}

	public void setQty(BigDecimal qty)
	{
		writeProperty("qty", qty);
	}

	public BigDecimal getQty()
	{
		return (BigDecimal) readProperty("qty");
	}

	public void setQtyPercent(BigDecimal qtyPercent)
	{
		writeProperty("qtyPercent", qtyPercent);
	}

	public BigDecimal getQtyPercent()
	{
		return (BigDecimal) readProperty("qtyPercent");
	}

	public void setQtyPeriodicity(String qtyPeriodicity)
	{
		writeProperty("qtyPeriodicity", qtyPeriodicity);
	}

	public String getQtyPeriodicity()
	{
		return (String) readProperty("qtyPeriodicity");
	}

	public void setQuote(String quote)
	{
		writeProperty("quote", quote);
	}

	public String getQuote()
	{
		return (String) readProperty("quote");
	}

	public void setRefSubAllocNum(Integer refSubAllocNum)
	{
		writeProperty("refSubAllocNum", refSubAllocNum);
	}

	public Integer getRefSubAllocNum()
	{
		return (Integer) readProperty("refSubAllocNum");
	}

	public void setRiskPeriod(String riskPeriod)
	{
		writeProperty("riskPeriod", riskPeriod);
	}

	public String getRiskPeriod()
	{
		return (String) readProperty("riskPeriod");
	}

	public void setScenarioId(Integer scenarioId)
	{
		writeProperty("scenarioId", scenarioId);
	}

	public Integer getScenarioId()
	{
		return (Integer) readProperty("scenarioId");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setAccount(Account account)
	{
		setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) readProperty("account");
	}

	public void setAccount1(Account account1)
	{
		setToOneTarget("account1", account1, true);
	}

	public Account getAccount1()
	{
		return (Account) readProperty("account1");
	}

	public void setAllocationItem(AllocationItem allocationItem)
	{
		setToOneTarget("allocationItem", allocationItem, true);
	}

	public AllocationItem getAllocationItem()
	{
		return (AllocationItem) readProperty("allocationItem");
	}

	public void setAllocationItem1(AllocationItem allocationItem1)
	{
		setToOneTarget("allocationItem1", allocationItem1, true);
	}

	public AllocationItem getAllocationItem1()
	{
		return (AllocationItem) readProperty("allocationItem1");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setMarket(Market market)
	{
		setToOneTarget("market", market, true);
	}

	public Market getMarket()
	{
		return (Market) readProperty("market");
	}

	public void setPortfolio(Portfolio portfolio)
	{
		setToOneTarget("portfolio", portfolio, true);
	}

	public Portfolio getPortfolio()
	{
		return (Portfolio) readProperty("portfolio");
	}

	public void setTradeItem(TradeItem tradeItem)
	{
		setToOneTarget("tradeItem", tradeItem, true);
	}

	public TradeItem getTradeItem()
	{
		return (TradeItem) readProperty("tradeItem");
	}

	public void setTradeItem1(TradeItem tradeItem1)
	{
		setToOneTarget("tradeItem1", tradeItem1, true);
	}

	public TradeItem getTradeItem1()
	{
		return (TradeItem) readProperty("tradeItem1");
	}

	public void setTradeItem2(TradeItem tradeItem2)
	{
		setToOneTarget("tradeItem2", tradeItem2, true);
	}

	public TradeItem getTradeItem2()
	{
		return (TradeItem) readProperty("tradeItem2");
	}

	public void setUom(Uom uom)
	{
		setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) readProperty("uom");
	}

	public void setUom1(Uom uom1)
	{
		setToOneTarget("uom1", uom1, true);
	}

	public Uom getUom1()
	{
		return (Uom) readProperty("uom1");
	}

}
