package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _ShipDataConsumptions was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ShipDataConsumptions extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_CMDTY_CODE_PK_COLUMN = "fldchrCmdtyCode";
	public static final String FLDCHR_LLOYDS_REF_NUM_PK_COLUMN = "fldchrLloydsRefNum";

	public static final Property<String> FLDCHR_REC_ID = new Property<String>("fldchrRecId");
	public static final Property<String> FLDCHR_USER_NAME = new Property<String>("fldchrUserName");
	public static final Property<BigDecimal> FLDDEC_CSPT_HEAT = new Property<BigDecimal>("flddecCsptHeat");
	public static final Property<BigDecimal> FLDDEC_CSPT_IGS = new Property<BigDecimal>("flddecCsptIGS");
	public static final Property<BigDecimal> FLDDEC_CSPT_IDLE = new Property<BigDecimal>("flddecCsptIdle");
	public static final Property<BigDecimal> FLDDEC_CSPT_NAVG = new Property<BigDecimal>("flddecCsptNavg");
	public static final Property<BigDecimal> FLDDEC_CSPT_PUMP = new Property<BigDecimal>("flddecCsptPump");
	public static final Property<Date> FLDSDT_TIME_STAMP = new Property<Date>("fldsdtTimeStamp");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Uom> UOM = new Property<Uom>("uom");

	public void setFldchrRecId(String fldchrRecId)
	{
		writeProperty("fldchrRecId", fldchrRecId);
	}

	public String getFldchrRecId()
	{
		return (String) readProperty("fldchrRecId");
	}

	public void setFldchrUserName(String fldchrUserName)
	{
		writeProperty("fldchrUserName", fldchrUserName);
	}

	public String getFldchrUserName()
	{
		return (String) readProperty("fldchrUserName");
	}

	public void setFlddecCsptHeat(BigDecimal flddecCsptHeat)
	{
		writeProperty("flddecCsptHeat", flddecCsptHeat);
	}

	public BigDecimal getFlddecCsptHeat()
	{
		return (BigDecimal) readProperty("flddecCsptHeat");
	}

	public void setFlddecCsptIGS(BigDecimal flddecCsptIGS)
	{
		writeProperty("flddecCsptIGS", flddecCsptIGS);
	}

	public BigDecimal getFlddecCsptIGS()
	{
		return (BigDecimal) readProperty("flddecCsptIGS");
	}

	public void setFlddecCsptIdle(BigDecimal flddecCsptIdle)
	{
		writeProperty("flddecCsptIdle", flddecCsptIdle);
	}

	public BigDecimal getFlddecCsptIdle()
	{
		return (BigDecimal) readProperty("flddecCsptIdle");
	}

	public void setFlddecCsptNavg(BigDecimal flddecCsptNavg)
	{
		writeProperty("flddecCsptNavg", flddecCsptNavg);
	}

	public BigDecimal getFlddecCsptNavg()
	{
		return (BigDecimal) readProperty("flddecCsptNavg");
	}

	public void setFlddecCsptPump(BigDecimal flddecCsptPump)
	{
		writeProperty("flddecCsptPump", flddecCsptPump);
	}

	public BigDecimal getFlddecCsptPump()
	{
		return (BigDecimal) readProperty("flddecCsptPump");
	}

	public void setFldsdtTimeStamp(Date fldsdtTimeStamp)
	{
		writeProperty("fldsdtTimeStamp", fldsdtTimeStamp);
	}

	public Date getFldsdtTimeStamp()
	{
		return (Date) readProperty("fldsdtTimeStamp");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setUom(Uom uom)
	{
		setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) readProperty("uom");
	}

}
