package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.ShipintVoyPort;

/**
 * Class _ShipintVoyPortDraft was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ShipintVoyPortDraft extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> DRAFT_POSITION = new Property<String>("draftPosition");
	public static final Property<String> DRAFT_TYPE = new Property<String>("draftType");
	public static final Property<String> DRAFT_UOM = new Property<String>("draftUom");
	public static final Property<Double> DRAFT_VALUE = new Property<Double>("draftValue");
	public static final Property<ShipintVoyPort> VOY_PORT = new Property<ShipintVoyPort>("voyPort");

	public void setDraftPosition(String draftPosition)
	{
		writeProperty("draftPosition", draftPosition);
	}

	public String getDraftPosition()
	{
		return (String) readProperty("draftPosition");
	}

	public void setDraftType(String draftType)
	{
		writeProperty("draftType", draftType);
	}

	public String getDraftType()
	{
		return (String) readProperty("draftType");
	}

	public void setDraftUom(String draftUom)
	{
		writeProperty("draftUom", draftUom);
	}

	public String getDraftUom()
	{
		return (String) readProperty("draftUom");
	}

	public void setDraftValue(Double draftValue)
	{
		writeProperty("draftValue", draftValue);
	}

	public Double getDraftValue()
	{
		return (Double) readProperty("draftValue");
	}

	public void setVoyPort(ShipintVoyPort voyPort)
	{
		setToOneTarget("voyPort", voyPort, true);
	}

	public ShipintVoyPort getVoyPort()
	{
		return (ShipintVoyPort) readProperty("voyPort");
	}

}
