package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.AgNominationLineItem;
import com.tc.app.exchangemonitor.model.cayenne.persistent.AgScheduleLineItem;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Comment;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsUser;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Location;
import com.tc.app.exchangemonitor.model.cayenne.persistent.MotType;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PaymentTerm;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PmTypeBRecord;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ShipmentChain;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ShipmentStatus;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _Shipment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Shipment extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<Integer> ALLOC_NUM = new Property<>("allocNum");
	public static final Property<BigDecimal> BALANCE_QTY = new Property<>("balanceQty");
	public static final Property<BigDecimal> CAPACITY = new Property<>("capacity");
	public static final Property<Integer> CONTRACT_NUM = new Property<>("contractNum");
	public static final Property<Integer> CONTRACT_ORDER_NUM = new Property<>("contractOrderNum");
	public static final Property<Date> CREATION_DATE = new Property<>("creationDate");
	public static final Property<String> DEST_FACILITY_CODE = new Property<>("destFacilityCode");
	public static final Property<Integer> DEST_TANK_NUM = new Property<>("destTankNum");
	public static final Property<Date> END_DATE = new Property<>("endDate");
	public static final Property<String> FEED_INTERFACE = new Property<>("feedInterface");
	public static final Property<BigDecimal> FREIGHT_RATE = new Property<>("freightRate");
	public static final Property<Date> LAST_UPDATE_DATE = new Property<>("lastUpdateDate");
	public static final Property<String> LOAD_FACILITY_CODE = new Property<>("loadFacilityCode");
	public static final Property<Integer> LOAD_TANK_NUM = new Property<>("loadTankNum");
	public static final Property<Boolean> MANUAL_TRANSPORT_PARCELS = new Property<>("manualTransportParcels");
	public static final Property<Integer> PIPELINE_CYCLE_NUM = new Property<>("pipelineCycleNum");
	public static final Property<Integer> PRIMARY_SHIPMENT_NUM = new Property<>("primaryShipmentNum");
	public static final Property<String> REFERENCE = new Property<>("reference");
	public static final Property<String> SAP_SHIPMENT_NUM = new Property<>("sapShipmentNum");
	public static final Property<BigDecimal> SHIP_QTY = new Property<>("shipQty");
	public static final Property<Date> START_DATE = new Property<>("startDate");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<String> TRANSPORT_REFERENCE = new Property<>("transportReference");
	public static final Property<List<AgNominationLineItem>> AG_NOMINATION_LINE_ITEMS = new Property<>("agNominationLineItems");
	public static final Property<List<AgScheduleLineItem>> AG_SCHEDULE_LINE_ITEMS = new Property<>("agScheduleLineItems");
	public static final Property<Comment> COMMENT = new Property<>("comment");
	public static final Property<Commodity> COMMODITY = new Property<>("commodity");
	public static final Property<Commodity> COMMODITY1 = new Property<>("commodity1");
	public static final Property<IctsUser> ICTS_USER = new Property<>("ictsUser");
	public static final Property<IctsUser> ICTS_USER1 = new Property<>("ictsUser1");
	public static final Property<Location> LOCATION = new Property<>("location");
	public static final Property<Location> LOCATION1 = new Property<>("location1");
	public static final Property<MotType> MOT_TYPE = new Property<>("motType");
	public static final Property<PaymentTerm> PAYMENT_TERM = new Property<>("paymentTerm");
	public static final Property<List<PmTypeBRecord>> PM_TYPE_BRECORDS = new Property<>("pmTypeBRecords");
	public static final Property<List<ShipmentChain>> SHIPMENT_CHAINS = new Property<>("shipmentChains");
	public static final Property<List<ShipmentChain>> SHIPMENT_CHAINS1 = new Property<>("shipmentChains1");
	public static final Property<ShipmentStatus> SHIPMENT_STATUS = new Property<>("shipmentStatus");
	public static final Property<Account> TRANSPORT_OPERATOR = new Property<>("transportOperator");
	public static final Property<Account> TRANSPORT_OWNER = new Property<>("transportOwner");
	public static final Property<Uom> UOM = new Property<>("uom");
	public static final Property<Uom> UOM1 = new Property<>("uom1");
	public static final Property<Uom> UOM2 = new Property<>("uom2");

	public void setAllocNum(final Integer allocNum)
	{
		this.writeProperty("allocNum", allocNum);
	}

	public Integer getAllocNum()
	{
		return (Integer) this.readProperty("allocNum");
	}

	public void setBalanceQty(final BigDecimal balanceQty)
	{
		this.writeProperty("balanceQty", balanceQty);
	}

	public BigDecimal getBalanceQty()
	{
		return (BigDecimal) this.readProperty("balanceQty");
	}

	public void setCapacity(final BigDecimal capacity)
	{
		this.writeProperty("capacity", capacity);
	}

	public BigDecimal getCapacity()
	{
		return (BigDecimal) this.readProperty("capacity");
	}

	public void setContractNum(final Integer contractNum)
	{
		this.writeProperty("contractNum", contractNum);
	}

	public Integer getContractNum()
	{
		return (Integer) this.readProperty("contractNum");
	}

	public void setContractOrderNum(final Integer contractOrderNum)
	{
		this.writeProperty("contractOrderNum", contractOrderNum);
	}

	public Integer getContractOrderNum()
	{
		return (Integer) this.readProperty("contractOrderNum");
	}

	public void setCreationDate(final Date creationDate)
	{
		this.writeProperty("creationDate", creationDate);
	}

	public Date getCreationDate()
	{
		return (Date) this.readProperty("creationDate");
	}

	public void setDestFacilityCode(final String destFacilityCode)
	{
		this.writeProperty("destFacilityCode", destFacilityCode);
	}

	public String getDestFacilityCode()
	{
		return (String) this.readProperty("destFacilityCode");
	}

	public void setDestTankNum(final Integer destTankNum)
	{
		this.writeProperty("destTankNum", destTankNum);
	}

	public Integer getDestTankNum()
	{
		return (Integer) this.readProperty("destTankNum");
	}

	public void setEndDate(final Date endDate)
	{
		this.writeProperty("endDate", endDate);
	}

	public Date getEndDate()
	{
		return (Date) this.readProperty("endDate");
	}

	public void setFeedInterface(final String feedInterface)
	{
		this.writeProperty("feedInterface", feedInterface);
	}

	public String getFeedInterface()
	{
		return (String) this.readProperty("feedInterface");
	}

	public void setFreightRate(final BigDecimal freightRate)
	{
		this.writeProperty("freightRate", freightRate);
	}

	public BigDecimal getFreightRate()
	{
		return (BigDecimal) this.readProperty("freightRate");
	}

	public void setLastUpdateDate(final Date lastUpdateDate)
	{
		this.writeProperty("lastUpdateDate", lastUpdateDate);
	}

	public Date getLastUpdateDate()
	{
		return (Date) this.readProperty("lastUpdateDate");
	}

	public void setLoadFacilityCode(final String loadFacilityCode)
	{
		this.writeProperty("loadFacilityCode", loadFacilityCode);
	}

	public String getLoadFacilityCode()
	{
		return (String) this.readProperty("loadFacilityCode");
	}

	public void setLoadTankNum(final Integer loadTankNum)
	{
		this.writeProperty("loadTankNum", loadTankNum);
	}

	public Integer getLoadTankNum()
	{
		return (Integer) this.readProperty("loadTankNum");
	}

	public void setManualTransportParcels(final Boolean manualTransportParcels)
	{
		this.writeProperty("manualTransportParcels", manualTransportParcels);
	}

	public Boolean getManualTransportParcels()
	{
		return (Boolean) this.readProperty("manualTransportParcels");
	}

	public void setPipelineCycleNum(final Integer pipelineCycleNum)
	{
		this.writeProperty("pipelineCycleNum", pipelineCycleNum);
	}

	public Integer getPipelineCycleNum()
	{
		return (Integer) this.readProperty("pipelineCycleNum");
	}

	public void setPrimaryShipmentNum(final Integer primaryShipmentNum)
	{
		this.writeProperty("primaryShipmentNum", primaryShipmentNum);
	}

	public Integer getPrimaryShipmentNum()
	{
		return (Integer) this.readProperty("primaryShipmentNum");
	}

	public void setReference(final String reference)
	{
		this.writeProperty("reference", reference);
	}

	public String getReference()
	{
		return (String) this.readProperty("reference");
	}

	public void setSapShipmentNum(final String sapShipmentNum)
	{
		this.writeProperty("sapShipmentNum", sapShipmentNum);
	}

	public String getSapShipmentNum()
	{
		return (String) this.readProperty("sapShipmentNum");
	}

	public void setShipQty(final BigDecimal shipQty)
	{
		this.writeProperty("shipQty", shipQty);
	}

	public BigDecimal getShipQty()
	{
		return (BigDecimal) this.readProperty("shipQty");
	}

	public void setStartDate(final Date startDate)
	{
		this.writeProperty("startDate", startDate);
	}

	public Date getStartDate()
	{
		return (Date) this.readProperty("startDate");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setTransportReference(final String transportReference)
	{
		this.writeProperty("transportReference", transportReference);
	}

	public String getTransportReference()
	{
		return (String) this.readProperty("transportReference");
	}

	public void addToAgNominationLineItems(final AgNominationLineItem obj)
	{
		this.addToManyTarget("agNominationLineItems", obj, true);
	}

	public void removeFromAgNominationLineItems(final AgNominationLineItem obj)
	{
		this.removeToManyTarget("agNominationLineItems", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AgNominationLineItem> getAgNominationLineItems()
	{
		return (List<AgNominationLineItem>) this.readProperty("agNominationLineItems");
	}

	public void addToAgScheduleLineItems(final AgScheduleLineItem obj)
	{
		this.addToManyTarget("agScheduleLineItems", obj, true);
	}

	public void removeFromAgScheduleLineItems(final AgScheduleLineItem obj)
	{
		this.removeToManyTarget("agScheduleLineItems", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AgScheduleLineItem> getAgScheduleLineItems()
	{
		return (List<AgScheduleLineItem>) this.readProperty("agScheduleLineItems");
	}

	public void setComment(final Comment comment)
	{
		this.setToOneTarget("comment", comment, true);
	}

	public Comment getComment()
	{
		return (Comment) this.readProperty("comment");
	}

	public void setCommodity(final Commodity commodity)
	{
		this.setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) this.readProperty("commodity");
	}

	public void setCommodity1(final Commodity commodity1)
	{
		this.setToOneTarget("commodity1", commodity1, true);
	}

	public Commodity getCommodity1()
	{
		return (Commodity) this.readProperty("commodity1");
	}

	public void setIctsUser(final IctsUser ictsUser)
	{
		this.setToOneTarget("ictsUser", ictsUser, true);
	}

	public IctsUser getIctsUser()
	{
		return (IctsUser) this.readProperty("ictsUser");
	}

	public void setIctsUser1(final IctsUser ictsUser1)
	{
		this.setToOneTarget("ictsUser1", ictsUser1, true);
	}

	public IctsUser getIctsUser1()
	{
		return (IctsUser) this.readProperty("ictsUser1");
	}

	public void setLocation(final Location location)
	{
		this.setToOneTarget("location", location, true);
	}

	public Location getLocation()
	{
		return (Location) this.readProperty("location");
	}

	public void setLocation1(final Location location1)
	{
		this.setToOneTarget("location1", location1, true);
	}

	public Location getLocation1()
	{
		return (Location) this.readProperty("location1");
	}

	public void setMotType(final MotType motType)
	{
		this.setToOneTarget("motType", motType, true);
	}

	public MotType getMotType()
	{
		return (MotType) this.readProperty("motType");
	}

	public void setPaymentTerm(final PaymentTerm paymentTerm)
	{
		this.setToOneTarget("paymentTerm", paymentTerm, true);
	}

	public PaymentTerm getPaymentTerm()
	{
		return (PaymentTerm) this.readProperty("paymentTerm");
	}

	public void addToPmTypeBRecords(final PmTypeBRecord obj)
	{
		this.addToManyTarget("pmTypeBRecords", obj, true);
	}

	public void removeFromPmTypeBRecords(final PmTypeBRecord obj)
	{
		this.removeToManyTarget("pmTypeBRecords", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<PmTypeBRecord> getPmTypeBRecords()
	{
		return (List<PmTypeBRecord>) this.readProperty("pmTypeBRecords");
	}

	public void addToShipmentChains(final ShipmentChain obj)
	{
		this.addToManyTarget("shipmentChains", obj, true);
	}

	public void removeFromShipmentChains(final ShipmentChain obj)
	{
		this.removeToManyTarget("shipmentChains", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ShipmentChain> getShipmentChains()
	{
		return (List<ShipmentChain>) this.readProperty("shipmentChains");
	}

	public void addToShipmentChains1(final ShipmentChain obj)
	{
		this.addToManyTarget("shipmentChains1", obj, true);
	}

	public void removeFromShipmentChains1(final ShipmentChain obj)
	{
		this.removeToManyTarget("shipmentChains1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ShipmentChain> getShipmentChains1()
	{
		return (List<ShipmentChain>) this.readProperty("shipmentChains1");
	}

	public void setShipmentStatus(final ShipmentStatus shipmentStatus)
	{
		this.setToOneTarget("shipmentStatus", shipmentStatus, true);
	}

	public ShipmentStatus getShipmentStatus()
	{
		return (ShipmentStatus) this.readProperty("shipmentStatus");
	}

	public void setTransportOperator(final Account transportOperator)
	{
		this.setToOneTarget("transportOperator", transportOperator, true);
	}

	public Account getTransportOperator()
	{
		return (Account) this.readProperty("transportOperator");
	}

	public void setTransportOwner(final Account transportOwner)
	{
		this.setToOneTarget("transportOwner", transportOwner, true);
	}

	public Account getTransportOwner()
	{
		return (Account) this.readProperty("transportOwner");
	}

	public void setUom(final Uom uom)
	{
		this.setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) this.readProperty("uom");
	}

	public void setUom1(final Uom uom1)
	{
		this.setToOneTarget("uom1", uom1, true);
	}

	public Uom getUom1()
	{
		return (Uom) this.readProperty("uom1");
	}

	public void setUom2(final Uom uom2)
	{
		this.setToOneTarget("uom2", uom2, true);
	}

	public Uom getUom2()
	{
		return (Uom) this.readProperty("uom2");
	}

}
