package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.AiEstActualSpec;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CommoditySpecification;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CommoditySpecificationOption;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Specification;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TradeItemSpec;

/**
 * Class _SpecificationOption was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SpecificationOption extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String SPEC_CODE_PK_COLUMN = "spec_code";
	public static final String SPEC_OPTION_PK_COLUMN = "spec_option";

	public static final Property<String> SPEC_OPTION_DESC = new Property<String>("specOptionDesc");
	public static final Property<String> SPEC_OPTION_STATUS = new Property<String>("specOptionStatus");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<List<AiEstActualSpec>> AI_EST_ACTUAL_SPECS = new Property<List<AiEstActualSpec>>("aiEstActualSpecs");
	public static final Property<List<AiEstActualSpec>> AI_EST_ACTUAL_SPECS1 = new Property<List<AiEstActualSpec>>("aiEstActualSpecs1");
	public static final Property<List<AiEstActualSpec>> AI_EST_ACTUAL_SPECS2 = new Property<List<AiEstActualSpec>>("aiEstActualSpecs2");
	public static final Property<List<CommoditySpecificationOption>> COMMODITY_SPECIFICATION_OPTIONS = new Property<List<CommoditySpecificationOption>>("commoditySpecificationOptions");
	public static final Property<List<CommoditySpecificationOption>> COMMODITY_SPECIFICATION_OPTIONS1 = new Property<List<CommoditySpecificationOption>>("commoditySpecificationOptions1");
	public static final Property<List<CommoditySpecification>> COMMODITY_SPECIFICATIONS = new Property<List<CommoditySpecification>>("commoditySpecifications");
	public static final Property<List<CommoditySpecification>> COMMODITY_SPECIFICATIONS1 = new Property<List<CommoditySpecification>>("commoditySpecifications1");
	public static final Property<Specification> SPECIFICATION = new Property<Specification>("specification");
	public static final Property<List<TradeItemSpec>> TRADE_ITEM_SPECS = new Property<List<TradeItemSpec>>("tradeItemSpecs");
	public static final Property<List<TradeItemSpec>> TRADE_ITEM_SPECS1 = new Property<List<TradeItemSpec>>("tradeItemSpecs1");
	public static final Property<List<TradeItemSpec>> TRADE_ITEM_SPECS2 = new Property<List<TradeItemSpec>>("tradeItemSpecs2");

	public void setSpecOptionDesc(String specOptionDesc)
	{
		writeProperty("specOptionDesc", specOptionDesc);
	}

	public String getSpecOptionDesc()
	{
		return (String) readProperty("specOptionDesc");
	}

	public void setSpecOptionStatus(String specOptionStatus)
	{
		writeProperty("specOptionStatus", specOptionStatus);
	}

	public String getSpecOptionStatus()
	{
		return (String) readProperty("specOptionStatus");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void addToAiEstActualSpecs(AiEstActualSpec obj)
	{
		addToManyTarget("aiEstActualSpecs", obj, true);
	}

	public void removeFromAiEstActualSpecs(AiEstActualSpec obj)
	{
		removeToManyTarget("aiEstActualSpecs", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AiEstActualSpec> getAiEstActualSpecs()
	{
		return (List<AiEstActualSpec>) readProperty("aiEstActualSpecs");
	}

	public void addToAiEstActualSpecs1(AiEstActualSpec obj)
	{
		addToManyTarget("aiEstActualSpecs1", obj, true);
	}

	public void removeFromAiEstActualSpecs1(AiEstActualSpec obj)
	{
		removeToManyTarget("aiEstActualSpecs1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AiEstActualSpec> getAiEstActualSpecs1()
	{
		return (List<AiEstActualSpec>) readProperty("aiEstActualSpecs1");
	}

	public void addToAiEstActualSpecs2(AiEstActualSpec obj)
	{
		addToManyTarget("aiEstActualSpecs2", obj, true);
	}

	public void removeFromAiEstActualSpecs2(AiEstActualSpec obj)
	{
		removeToManyTarget("aiEstActualSpecs2", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AiEstActualSpec> getAiEstActualSpecs2()
	{
		return (List<AiEstActualSpec>) readProperty("aiEstActualSpecs2");
	}

	public void addToCommoditySpecificationOptions(CommoditySpecificationOption obj)
	{
		addToManyTarget("commoditySpecificationOptions", obj, true);
	}

	public void removeFromCommoditySpecificationOptions(CommoditySpecificationOption obj)
	{
		removeToManyTarget("commoditySpecificationOptions", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<CommoditySpecificationOption> getCommoditySpecificationOptions()
	{
		return (List<CommoditySpecificationOption>) readProperty("commoditySpecificationOptions");
	}

	public void addToCommoditySpecificationOptions1(CommoditySpecificationOption obj)
	{
		addToManyTarget("commoditySpecificationOptions1", obj, true);
	}

	public void removeFromCommoditySpecificationOptions1(CommoditySpecificationOption obj)
	{
		removeToManyTarget("commoditySpecificationOptions1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<CommoditySpecificationOption> getCommoditySpecificationOptions1()
	{
		return (List<CommoditySpecificationOption>) readProperty("commoditySpecificationOptions1");
	}

	public void addToCommoditySpecifications(CommoditySpecification obj)
	{
		addToManyTarget("commoditySpecifications", obj, true);
	}

	public void removeFromCommoditySpecifications(CommoditySpecification obj)
	{
		removeToManyTarget("commoditySpecifications", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<CommoditySpecification> getCommoditySpecifications()
	{
		return (List<CommoditySpecification>) readProperty("commoditySpecifications");
	}

	public void addToCommoditySpecifications1(CommoditySpecification obj)
	{
		addToManyTarget("commoditySpecifications1", obj, true);
	}

	public void removeFromCommoditySpecifications1(CommoditySpecification obj)
	{
		removeToManyTarget("commoditySpecifications1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<CommoditySpecification> getCommoditySpecifications1()
	{
		return (List<CommoditySpecification>) readProperty("commoditySpecifications1");
	}

	public void setSpecification(Specification specification)
	{
		setToOneTarget("specification", specification, true);
	}

	public Specification getSpecification()
	{
		return (Specification) readProperty("specification");
	}

	public void addToTradeItemSpecs(TradeItemSpec obj)
	{
		addToManyTarget("tradeItemSpecs", obj, true);
	}

	public void removeFromTradeItemSpecs(TradeItemSpec obj)
	{
		removeToManyTarget("tradeItemSpecs", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<TradeItemSpec> getTradeItemSpecs()
	{
		return (List<TradeItemSpec>) readProperty("tradeItemSpecs");
	}

	public void addToTradeItemSpecs1(TradeItemSpec obj)
	{
		addToManyTarget("tradeItemSpecs1", obj, true);
	}

	public void removeFromTradeItemSpecs1(TradeItemSpec obj)
	{
		removeToManyTarget("tradeItemSpecs1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<TradeItemSpec> getTradeItemSpecs1()
	{
		return (List<TradeItemSpec>) readProperty("tradeItemSpecs1");
	}

	public void addToTradeItemSpecs2(TradeItemSpec obj)
	{
		addToManyTarget("tradeItemSpecs2", obj, true);
	}

	public void removeFromTradeItemSpecs2(TradeItemSpec obj)
	{
		removeToManyTarget("tradeItemSpecs2", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<TradeItemSpec> getTradeItemSpecs2()
	{
		return (List<TradeItemSpec>) readProperty("tradeItemSpecs2");
	}

}
