package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.ContrStatusKstContrStatus;

/**
 * Class _SrceContrStatus was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SrceContrStatus extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String SRCE_CONTR_STATUS_ID_PK_COLUMN = "srce_contr_status_id";

	public static final Property<Date> CRE_TS = new Property<Date>("creTs");
	public static final Property<String> EXTN_SYS_CD = new Property<String>("extnSysCd");
	public static final Property<Date> INACTV_DT = new Property<Date>("inactvDt");
	public static final Property<Date> MOD_TS = new Property<Date>("modTs");
	public static final Property<String> MOD_USER_CD = new Property<String>("modUserCd");
	public static final Property<String> SRCE_CONTR_STATUS_CD = new Property<String>("srceContrStatusCd");
	public static final Property<List<ContrStatusKstContrStatus>> CONTR_STATUS_KST_CONTR_STATUSES = new Property<List<ContrStatusKstContrStatus>>("contrStatusKstContrStatuses");

	public void setCreTs(Date creTs)
	{
		writeProperty("creTs", creTs);
	}

	public Date getCreTs()
	{
		return (Date) readProperty("creTs");
	}

	public void setExtnSysCd(String extnSysCd)
	{
		writeProperty("extnSysCd", extnSysCd);
	}

	public String getExtnSysCd()
	{
		return (String) readProperty("extnSysCd");
	}

	public void setInactvDt(Date inactvDt)
	{
		writeProperty("inactvDt", inactvDt);
	}

	public Date getInactvDt()
	{
		return (Date) readProperty("inactvDt");
	}

	public void setModTs(Date modTs)
	{
		writeProperty("modTs", modTs);
	}

	public Date getModTs()
	{
		return (Date) readProperty("modTs");
	}

	public void setModUserCd(String modUserCd)
	{
		writeProperty("modUserCd", modUserCd);
	}

	public String getModUserCd()
	{
		return (String) readProperty("modUserCd");
	}

	public void setSrceContrStatusCd(String srceContrStatusCd)
	{
		writeProperty("srceContrStatusCd", srceContrStatusCd);
	}

	public String getSrceContrStatusCd()
	{
		return (String) readProperty("srceContrStatusCd");
	}

	public void addToContrStatusKstContrStatuses(ContrStatusKstContrStatus obj)
	{
		addToManyTarget("contrStatusKstContrStatuses", obj, true);
	}

	public void removeFromContrStatusKstContrStatuses(ContrStatusKstContrStatus obj)
	{
		removeToManyTarget("contrStatusKstContrStatuses", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ContrStatusKstContrStatus> getContrStatusKstContrStatuses()
	{
		return (List<ContrStatusKstContrStatus>) readProperty("contrStatusKstContrStatuses");
	}

}
