package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _TblGroupsConfig1 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TblGroupsConfig1 extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Integer> COL1 = new Property<Integer>("col1");
	public static final Property<Integer> COL2 = new Property<Integer>("col2");
	public static final Property<String> CONFIG_NAME = new Property<String>("configName");
	public static final Property<String> CONFIG_TYPE = new Property<String>("configType");
	public static final Property<String> GROUP_NAME = new Property<String>("groupName");
	public static final Property<Integer> ORDEN = new Property<Integer>("orden");
	public static final Property<Integer> ROW1 = new Property<Integer>("row1");
	public static final Property<Integer> ROW2 = new Property<Integer>("row2");

	public void setCol1(Integer col1)
	{
		writeProperty("col1", col1);
	}

	public Integer getCol1()
	{
		return (Integer) readProperty("col1");
	}

	public void setCol2(Integer col2)
	{
		writeProperty("col2", col2);
	}

	public Integer getCol2()
	{
		return (Integer) readProperty("col2");
	}

	public void setConfigName(String configName)
	{
		writeProperty("configName", configName);
	}

	public String getConfigName()
	{
		return (String) readProperty("configName");
	}

	public void setConfigType(String configType)
	{
		writeProperty("configType", configType);
	}

	public String getConfigType()
	{
		return (String) readProperty("configType");
	}

	public void setGroupName(String groupName)
	{
		writeProperty("groupName", groupName);
	}

	public String getGroupName()
	{
		return (String) readProperty("groupName");
	}

	public void setOrden(Integer orden)
	{
		writeProperty("orden", orden);
	}

	public Integer getOrden()
	{
		return (Integer) readProperty("orden");
	}

	public void setRow1(Integer row1)
	{
		writeProperty("row1", row1);
	}

	public Integer getRow1()
	{
		return (Integer) readProperty("row1");
	}

	public void setRow2(Integer row2)
	{
		writeProperty("row2", row2);
	}

	public Integer getRow2()
	{
		return (Integer) readProperty("row2");
	}

}
