package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _TempValueAdjustDetail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TempValueAdjustDetail extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> ACCT_NAME = new Property<String>("acctName");
	public static final Property<Integer> ACCT_NUM = new Property<Integer>("acctNum");
	public static final Property<String> CMDTY_CODE = new Property<String>("cmdtyCode");
	public static final Property<String> CMDTY_NAME = new Property<String>("cmdtyName");
	public static final Property<Date> DATE_FROM = new Property<Date>("dateFrom");
	public static final Property<Date> DATE_TO = new Property<Date>("dateTo");
	public static final Property<Double> DELTA = new Property<Double>("delta");
	public static final Property<String> LOC_CODE = new Property<String>("locCode");
	public static final Property<String> LOC_NAME = new Property<String>("locName");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setAcctName(String acctName)
	{
		writeProperty("acctName", acctName);
	}

	public String getAcctName()
	{
		return (String) readProperty("acctName");
	}

	public void setAcctNum(Integer acctNum)
	{
		writeProperty("acctNum", acctNum);
	}

	public Integer getAcctNum()
	{
		return (Integer) readProperty("acctNum");
	}

	public void setCmdtyCode(String cmdtyCode)
	{
		writeProperty("cmdtyCode", cmdtyCode);
	}

	public String getCmdtyCode()
	{
		return (String) readProperty("cmdtyCode");
	}

	public void setCmdtyName(String cmdtyName)
	{
		writeProperty("cmdtyName", cmdtyName);
	}

	public String getCmdtyName()
	{
		return (String) readProperty("cmdtyName");
	}

	public void setDateFrom(Date dateFrom)
	{
		writeProperty("dateFrom", dateFrom);
	}

	public Date getDateFrom()
	{
		return (Date) readProperty("dateFrom");
	}

	public void setDateTo(Date dateTo)
	{
		writeProperty("dateTo", dateTo);
	}

	public Date getDateTo()
	{
		return (Date) readProperty("dateTo");
	}

	public void setDelta(Double delta)
	{
		writeProperty("delta", delta);
	}

	public Double getDelta()
	{
		return (Double) readProperty("delta");
	}

	public void setLocCode(String locCode)
	{
		writeProperty("locCode", locCode);
	}

	public String getLocCode()
	{
		return (String) readProperty("locCode");
	}

	public void setLocName(String locName)
	{
		writeProperty("locName", locName);
	}

	public String getLocName()
	{
		return (String) readProperty("locName");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
