package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _TidMtmVolatility was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TidMtmVolatility extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String DIST_NUM_PK_COLUMN = "dist_num";
	public static final String MTM_PL_ASOF_DATE_PK_COLUMN = "mtm_pl_asof_date";
	public static final String VOL_NUM_PK_COLUMN = "vol_num";

	public static final Property<BigDecimal> SKEW_PRICE = new Property<BigDecimal>("skewPrice");
	public static final Property<BigDecimal> STRIKE_PRICE = new Property<BigDecimal>("strikePrice");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<String> USE_OPTION_SKEW = new Property<String>("useOptionSkew");
	public static final Property<BigDecimal> VOLATILITY = new Property<BigDecimal>("volatility");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<Uom> UOM = new Property<Uom>("uom");

	public void setSkewPrice(BigDecimal skewPrice)
	{
		writeProperty("skewPrice", skewPrice);
	}

	public BigDecimal getSkewPrice()
	{
		return (BigDecimal) readProperty("skewPrice");
	}

	public void setStrikePrice(BigDecimal strikePrice)
	{
		writeProperty("strikePrice", strikePrice);
	}

	public BigDecimal getStrikePrice()
	{
		return (BigDecimal) readProperty("strikePrice");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setUseOptionSkew(String useOptionSkew)
	{
		writeProperty("useOptionSkew", useOptionSkew);
	}

	public String getUseOptionSkew()
	{
		return (String) readProperty("useOptionSkew");
	}

	public void setVolatility(BigDecimal volatility)
	{
		writeProperty("volatility", volatility);
	}

	public BigDecimal getVolatility()
	{
		return (BigDecimal) readProperty("volatility");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setUom(Uom uom)
	{
		setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) readProperty("uom");
	}

}
