package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.TiInboundDataXml;

/**
 * Class _TiExchBal was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TiExchBal extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<BigDecimal> CALC_CLOSING_BAL = new Property<BigDecimal>("calcClosingBal");
	public static final Property<Date> ETL_TIMESTAMP = new Property<Date>("etlTimestamp");
	public static final Property<String> EXCHANGE_AGREEMENT_NUM = new Property<String>("exchangeAgreementNum");
	public static final Property<BigDecimal> MANUAL_OPENING_BAL = new Property<BigDecimal>("manualOpeningBal");
	public static final Property<String> MATERIAL = new Property<String>("material");
	public static final Property<Date> MONTH_YEAR = new Property<Date>("monthYear");
	public static final Property<String> STATUS = new Property<String>("status");
	public static final Property<BigDecimal> SYSTEM_CALC_BAL = new Property<BigDecimal>("systemCalcBal");
	public static final Property<String> UOM = new Property<String>("uom");
	public static final Property<TiInboundDataXml> INBOUND_DATA_O = new Property<TiInboundDataXml>("inboundDataO");

	public void setCalcClosingBal(BigDecimal calcClosingBal)
	{
		writeProperty("calcClosingBal", calcClosingBal);
	}

	public BigDecimal getCalcClosingBal()
	{
		return (BigDecimal) readProperty("calcClosingBal");
	}

	public void setEtlTimestamp(Date etlTimestamp)
	{
		writeProperty("etlTimestamp", etlTimestamp);
	}

	public Date getEtlTimestamp()
	{
		return (Date) readProperty("etlTimestamp");
	}

	public void setExchangeAgreementNum(String exchangeAgreementNum)
	{
		writeProperty("exchangeAgreementNum", exchangeAgreementNum);
	}

	public String getExchangeAgreementNum()
	{
		return (String) readProperty("exchangeAgreementNum");
	}

	public void setManualOpeningBal(BigDecimal manualOpeningBal)
	{
		writeProperty("manualOpeningBal", manualOpeningBal);
	}

	public BigDecimal getManualOpeningBal()
	{
		return (BigDecimal) readProperty("manualOpeningBal");
	}

	public void setMaterial(String material)
	{
		writeProperty("material", material);
	}

	public String getMaterial()
	{
		return (String) readProperty("material");
	}

	public void setMonthYear(Date monthYear)
	{
		writeProperty("monthYear", monthYear);
	}

	public Date getMonthYear()
	{
		return (Date) readProperty("monthYear");
	}

	public void setStatus(String status)
	{
		writeProperty("status", status);
	}

	public String getStatus()
	{
		return (String) readProperty("status");
	}

	public void setSystemCalcBal(BigDecimal systemCalcBal)
	{
		writeProperty("systemCalcBal", systemCalcBal);
	}

	public BigDecimal getSystemCalcBal()
	{
		return (BigDecimal) readProperty("systemCalcBal");
	}

	public void setUom(String uom)
	{
		writeProperty("uom", uom);
	}

	public String getUom()
	{
		return (String) readProperty("uom");
	}

	public void setInboundDataO(TiInboundDataXml inboundDataO)
	{
		setToOneTarget("inboundDataO", inboundDataO, true);
	}

	public TiInboundDataXml getInboundDataO()
	{
		return (TiInboundDataXml) readProperty("inboundDataO");
	}

}
