package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsUser;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Market;
import com.tc.app.exchangemonitor.model.cayenne.persistent.OrderType;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _TiMarkToMarket was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TiMarkToMarket extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ITEM_NUM_PK_COLUMN = "item_num";
	public static final String MTM_PL_ASOF_DATE_PK_COLUMN = "mtm_pl_asof_date";
	public static final String ORDER_NUM_PK_COLUMN = "order_num";
	public static final String TRADE_NUM_PK_COLUMN = "trade_num";

	public static final Property<Integer> ACCT_NUM = new Property<Integer>("acctNum");
	public static final Property<Date> CONTR_DATE = new Property<Date>("contrDate");
	public static final Property<BigDecimal> CONTR_QTY = new Property<BigDecimal>("contrQty");
	public static final Property<String> CONTR_QTY_PERIODICITY = new Property<String>("contrQtyPeriodicity");
	public static final Property<Date> CREATION_DATE = new Property<Date>("creationDate");
	public static final Property<Date> LAST_TRADE_DATE = new Property<Date>("lastTradeDate");
	public static final Property<BigDecimal> OPEN_QTY = new Property<BigDecimal>("openQty");
	public static final Property<String> P_SIND = new Property<String>("pSInd");
	public static final Property<Integer> REAL_PORT_NUM = new Property<Integer>("realPortNum");
	public static final Property<String> TRADING_PRD = new Property<String>("tradingPrd");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Account> ACCOUNT = new Property<Account>("account");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<IctsUser> ICTS_USER = new Property<IctsUser>("ictsUser");
	public static final Property<Market> MARKET = new Property<Market>("market");
	public static final Property<OrderType> ORDER_TYPE = new Property<OrderType>("orderType");
	public static final Property<Uom> UOM = new Property<Uom>("uom");

	public void setAcctNum(Integer acctNum)
	{
		writeProperty("acctNum", acctNum);
	}

	public Integer getAcctNum()
	{
		return (Integer) readProperty("acctNum");
	}

	public void setContrDate(Date contrDate)
	{
		writeProperty("contrDate", contrDate);
	}

	public Date getContrDate()
	{
		return (Date) readProperty("contrDate");
	}

	public void setContrQty(BigDecimal contrQty)
	{
		writeProperty("contrQty", contrQty);
	}

	public BigDecimal getContrQty()
	{
		return (BigDecimal) readProperty("contrQty");
	}

	public void setContrQtyPeriodicity(String contrQtyPeriodicity)
	{
		writeProperty("contrQtyPeriodicity", contrQtyPeriodicity);
	}

	public String getContrQtyPeriodicity()
	{
		return (String) readProperty("contrQtyPeriodicity");
	}

	public void setCreationDate(Date creationDate)
	{
		writeProperty("creationDate", creationDate);
	}

	public Date getCreationDate()
	{
		return (Date) readProperty("creationDate");
	}

	public void setLastTradeDate(Date lastTradeDate)
	{
		writeProperty("lastTradeDate", lastTradeDate);
	}

	public Date getLastTradeDate()
	{
		return (Date) readProperty("lastTradeDate");
	}

	public void setOpenQty(BigDecimal openQty)
	{
		writeProperty("openQty", openQty);
	}

	public BigDecimal getOpenQty()
	{
		return (BigDecimal) readProperty("openQty");
	}

	public void setPSInd(String pSInd)
	{
		writeProperty("pSInd", pSInd);
	}

	public String getPSInd()
	{
		return (String) readProperty("pSInd");
	}

	public void setRealPortNum(Integer realPortNum)
	{
		writeProperty("realPortNum", realPortNum);
	}

	public Integer getRealPortNum()
	{
		return (Integer) readProperty("realPortNum");
	}

	public void setTradingPrd(String tradingPrd)
	{
		writeProperty("tradingPrd", tradingPrd);
	}

	public String getTradingPrd()
	{
		return (String) readProperty("tradingPrd");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setAccount(Account account)
	{
		setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) readProperty("account");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setIctsUser(IctsUser ictsUser)
	{
		setToOneTarget("ictsUser", ictsUser, true);
	}

	public IctsUser getIctsUser()
	{
		return (IctsUser) readProperty("ictsUser");
	}

	public void setMarket(Market market)
	{
		setToOneTarget("market", market, true);
	}

	public Market getMarket()
	{
		return (Market) readProperty("market");
	}

	public void setOrderType(OrderType orderType)
	{
		setToOneTarget("orderType", orderType, true);
	}

	public OrderType getOrderType()
	{
		return (OrderType) readProperty("orderType");
	}

	public void setUom(Uom uom)
	{
		setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) readProperty("uom");
	}

}
