package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.TiBulkIgnore;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TiInboundDataXml;

/**
 * Class _TiPsmvFeed was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TiPsmvFeed extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> COMP_MATERIAL1 = new Property<String>("compMaterial1");
	public static final Property<BigDecimal> COMP_MATERIAL1QTY = new Property<BigDecimal>("compMaterial1Qty");
	public static final Property<String> COMP_MATERIAL2 = new Property<String>("compMaterial2");
	public static final Property<BigDecimal> COMP_MATERIAL2QTY = new Property<BigDecimal>("compMaterial2Qty");
	public static final Property<String> COMP_MATERIAL3 = new Property<String>("compMaterial3");
	public static final Property<BigDecimal> COMP_MATERIAL3QTY = new Property<BigDecimal>("compMaterial3Qty");
	public static final Property<String> COMP_MATERIAL4 = new Property<String>("compMaterial4");
	public static final Property<BigDecimal> COMP_MATERIAL4QTY = new Property<BigDecimal>("compMaterial4Qty");
	public static final Property<String> CONTRACT_ITEM = new Property<String>("contractItem");
	public static final Property<String> CONTRACT_NUMBER = new Property<String>("contractNumber");
	public static final Property<Date> CREATE_DATE = new Property<Date>("createDate");
	public static final Property<Date> DELIVERY_DATE = new Property<Date>("deliveryDate");
	public static final Property<Date> DOCUMENT_DATE = new Property<Date>("documentDate");
	public static final Property<String> DOCUMENT_INDICATOR = new Property<String>("documentIndicator");
	public static final Property<Date> ETL_TIMESTAMP = new Property<Date>("etlTimestamp");
	public static final Property<String> IN_TRANSIT_PLANT = new Property<String>("inTransitPlant");
	public static final Property<String> IS_NEW_NOMIN_KEY = new Property<String>("isNewNominKey");
	public static final Property<String> ISSUE_LOCATION = new Property<String>("issueLocation");
	public static final Property<String> MATERIAL = new Property<String>("material");
	public static final Property<String> MATERIAL_DOC_ITEM = new Property<String>("materialDocItem");
	public static final Property<String> MATERIAL_DOC_NUMBER = new Property<String>("materialDocNumber");
	public static final Property<Integer> MATERIAL_DOC_YEAR = new Property<Integer>("materialDocYear");
	public static final Property<String> MOT = new Property<String>("mot");
	public static final Property<String> MOVEMENT_TYPE = new Property<String>("movementType");
	public static final Property<String> MOVEMENT_VOLUME_TYPE = new Property<String>("movementVolumeType");
	public static final Property<String> NOMIN_KEY = new Property<String>("nominKey");
	public static final Property<String> NOMIN_KEY_ITEM = new Property<String>("nominKeyItem");
	public static final Property<Date> POSTING_DATE = new Property<Date>("postingDate");
	public static final Property<String> PW_ISSUE_LOCATION = new Property<String>("pwIssueLocation");
	public static final Property<String> PW_MATERIAL = new Property<String>("pwMaterial");
	public static final Property<String> PW_RECEIVE_LOCATION = new Property<String>("pwReceiveLocation");
	public static final Property<String> RECEIVE_LOCATION = new Property<String>("receiveLocation");
	public static final Property<String> REFERENCE_DOCUMENT_TYPE = new Property<String>("referenceDocumentType");
	public static final Property<String> REVERSAL_MATERIAL_DOC_ITEM = new Property<String>("reversalMaterialDocItem");
	public static final Property<String> REVERSAL_MATERIAL_DOC_NUMBER = new Property<String>("reversalMaterialDocNumber");
	public static final Property<Integer> REVERSAL_MATERIAL_DOC_YEAR = new Property<Integer>("reversalMaterialDocYear");
	public static final Property<String> SCHEDULE_TYPE = new Property<String>("scheduleType");
	public static final Property<String> STATUS = new Property<String>("status");
	public static final Property<String> UOM = new Property<String>("uom");
	public static final Property<BigDecimal> VOLUME = new Property<BigDecimal>("volume");
	public static final Property<TiInboundDataXml> INBOUND_DATA_O = new Property<TiInboundDataXml>("inboundDataO");
	public static final Property<List<TiBulkIgnore>> TI_BULK_IGNORES = new Property<List<TiBulkIgnore>>("tiBulkIgnores");

	public void setCompMaterial1(String compMaterial1)
	{
		writeProperty("compMaterial1", compMaterial1);
	}

	public String getCompMaterial1()
	{
		return (String) readProperty("compMaterial1");
	}

	public void setCompMaterial1Qty(BigDecimal compMaterial1Qty)
	{
		writeProperty("compMaterial1Qty", compMaterial1Qty);
	}

	public BigDecimal getCompMaterial1Qty()
	{
		return (BigDecimal) readProperty("compMaterial1Qty");
	}

	public void setCompMaterial2(String compMaterial2)
	{
		writeProperty("compMaterial2", compMaterial2);
	}

	public String getCompMaterial2()
	{
		return (String) readProperty("compMaterial2");
	}

	public void setCompMaterial2Qty(BigDecimal compMaterial2Qty)
	{
		writeProperty("compMaterial2Qty", compMaterial2Qty);
	}

	public BigDecimal getCompMaterial2Qty()
	{
		return (BigDecimal) readProperty("compMaterial2Qty");
	}

	public void setCompMaterial3(String compMaterial3)
	{
		writeProperty("compMaterial3", compMaterial3);
	}

	public String getCompMaterial3()
	{
		return (String) readProperty("compMaterial3");
	}

	public void setCompMaterial3Qty(BigDecimal compMaterial3Qty)
	{
		writeProperty("compMaterial3Qty", compMaterial3Qty);
	}

	public BigDecimal getCompMaterial3Qty()
	{
		return (BigDecimal) readProperty("compMaterial3Qty");
	}

	public void setCompMaterial4(String compMaterial4)
	{
		writeProperty("compMaterial4", compMaterial4);
	}

	public String getCompMaterial4()
	{
		return (String) readProperty("compMaterial4");
	}

	public void setCompMaterial4Qty(BigDecimal compMaterial4Qty)
	{
		writeProperty("compMaterial4Qty", compMaterial4Qty);
	}

	public BigDecimal getCompMaterial4Qty()
	{
		return (BigDecimal) readProperty("compMaterial4Qty");
	}

	public void setContractItem(String contractItem)
	{
		writeProperty("contractItem", contractItem);
	}

	public String getContractItem()
	{
		return (String) readProperty("contractItem");
	}

	public void setContractNumber(String contractNumber)
	{
		writeProperty("contractNumber", contractNumber);
	}

	public String getContractNumber()
	{
		return (String) readProperty("contractNumber");
	}

	public void setCreateDate(Date createDate)
	{
		writeProperty("createDate", createDate);
	}

	public Date getCreateDate()
	{
		return (Date) readProperty("createDate");
	}

	public void setDeliveryDate(Date deliveryDate)
	{
		writeProperty("deliveryDate", deliveryDate);
	}

	public Date getDeliveryDate()
	{
		return (Date) readProperty("deliveryDate");
	}

	public void setDocumentDate(Date documentDate)
	{
		writeProperty("documentDate", documentDate);
	}

	public Date getDocumentDate()
	{
		return (Date) readProperty("documentDate");
	}

	public void setDocumentIndicator(String documentIndicator)
	{
		writeProperty("documentIndicator", documentIndicator);
	}

	public String getDocumentIndicator()
	{
		return (String) readProperty("documentIndicator");
	}

	public void setEtlTimestamp(Date etlTimestamp)
	{
		writeProperty("etlTimestamp", etlTimestamp);
	}

	public Date getEtlTimestamp()
	{
		return (Date) readProperty("etlTimestamp");
	}

	public void setInTransitPlant(String inTransitPlant)
	{
		writeProperty("inTransitPlant", inTransitPlant);
	}

	public String getInTransitPlant()
	{
		return (String) readProperty("inTransitPlant");
	}

	public void setIsNewNominKey(String isNewNominKey)
	{
		writeProperty("isNewNominKey", isNewNominKey);
	}

	public String getIsNewNominKey()
	{
		return (String) readProperty("isNewNominKey");
	}

	public void setIssueLocation(String issueLocation)
	{
		writeProperty("issueLocation", issueLocation);
	}

	public String getIssueLocation()
	{
		return (String) readProperty("issueLocation");
	}

	public void setMaterial(String material)
	{
		writeProperty("material", material);
	}

	public String getMaterial()
	{
		return (String) readProperty("material");
	}

	public void setMaterialDocItem(String materialDocItem)
	{
		writeProperty("materialDocItem", materialDocItem);
	}

	public String getMaterialDocItem()
	{
		return (String) readProperty("materialDocItem");
	}

	public void setMaterialDocNumber(String materialDocNumber)
	{
		writeProperty("materialDocNumber", materialDocNumber);
	}

	public String getMaterialDocNumber()
	{
		return (String) readProperty("materialDocNumber");
	}

	public void setMaterialDocYear(Integer materialDocYear)
	{
		writeProperty("materialDocYear", materialDocYear);
	}

	public Integer getMaterialDocYear()
	{
		return (Integer) readProperty("materialDocYear");
	}

	public void setMot(String mot)
	{
		writeProperty("mot", mot);
	}

	public String getMot()
	{
		return (String) readProperty("mot");
	}

	public void setMovementType(String movementType)
	{
		writeProperty("movementType", movementType);
	}

	public String getMovementType()
	{
		return (String) readProperty("movementType");
	}

	public void setMovementVolumeType(String movementVolumeType)
	{
		writeProperty("movementVolumeType", movementVolumeType);
	}

	public String getMovementVolumeType()
	{
		return (String) readProperty("movementVolumeType");
	}

	public void setNominKey(String nominKey)
	{
		writeProperty("nominKey", nominKey);
	}

	public String getNominKey()
	{
		return (String) readProperty("nominKey");
	}

	public void setNominKeyItem(String nominKeyItem)
	{
		writeProperty("nominKeyItem", nominKeyItem);
	}

	public String getNominKeyItem()
	{
		return (String) readProperty("nominKeyItem");
	}

	public void setPostingDate(Date postingDate)
	{
		writeProperty("postingDate", postingDate);
	}

	public Date getPostingDate()
	{
		return (Date) readProperty("postingDate");
	}

	public void setPwIssueLocation(String pwIssueLocation)
	{
		writeProperty("pwIssueLocation", pwIssueLocation);
	}

	public String getPwIssueLocation()
	{
		return (String) readProperty("pwIssueLocation");
	}

	public void setPwMaterial(String pwMaterial)
	{
		writeProperty("pwMaterial", pwMaterial);
	}

	public String getPwMaterial()
	{
		return (String) readProperty("pwMaterial");
	}

	public void setPwReceiveLocation(String pwReceiveLocation)
	{
		writeProperty("pwReceiveLocation", pwReceiveLocation);
	}

	public String getPwReceiveLocation()
	{
		return (String) readProperty("pwReceiveLocation");
	}

	public void setReceiveLocation(String receiveLocation)
	{
		writeProperty("receiveLocation", receiveLocation);
	}

	public String getReceiveLocation()
	{
		return (String) readProperty("receiveLocation");
	}

	public void setReferenceDocumentType(String referenceDocumentType)
	{
		writeProperty("referenceDocumentType", referenceDocumentType);
	}

	public String getReferenceDocumentType()
	{
		return (String) readProperty("referenceDocumentType");
	}

	public void setReversalMaterialDocItem(String reversalMaterialDocItem)
	{
		writeProperty("reversalMaterialDocItem", reversalMaterialDocItem);
	}

	public String getReversalMaterialDocItem()
	{
		return (String) readProperty("reversalMaterialDocItem");
	}

	public void setReversalMaterialDocNumber(String reversalMaterialDocNumber)
	{
		writeProperty("reversalMaterialDocNumber", reversalMaterialDocNumber);
	}

	public String getReversalMaterialDocNumber()
	{
		return (String) readProperty("reversalMaterialDocNumber");
	}

	public void setReversalMaterialDocYear(Integer reversalMaterialDocYear)
	{
		writeProperty("reversalMaterialDocYear", reversalMaterialDocYear);
	}

	public Integer getReversalMaterialDocYear()
	{
		return (Integer) readProperty("reversalMaterialDocYear");
	}

	public void setScheduleType(String scheduleType)
	{
		writeProperty("scheduleType", scheduleType);
	}

	public String getScheduleType()
	{
		return (String) readProperty("scheduleType");
	}

	public void setStatus(String status)
	{
		writeProperty("status", status);
	}

	public String getStatus()
	{
		return (String) readProperty("status");
	}

	public void setUom(String uom)
	{
		writeProperty("uom", uom);
	}

	public String getUom()
	{
		return (String) readProperty("uom");
	}

	public void setVolume(BigDecimal volume)
	{
		writeProperty("volume", volume);
	}

	public BigDecimal getVolume()
	{
		return (BigDecimal) readProperty("volume");
	}

	public void setInboundDataO(TiInboundDataXml inboundDataO)
	{
		setToOneTarget("inboundDataO", inboundDataO, true);
	}

	public TiInboundDataXml getInboundDataO()
	{
		return (TiInboundDataXml) readProperty("inboundDataO");
	}

	public void addToTiBulkIgnores(TiBulkIgnore obj)
	{
		addToManyTarget("tiBulkIgnores", obj, true);
	}

	public void removeFromTiBulkIgnores(TiBulkIgnore obj)
	{
		removeToManyTarget("tiBulkIgnores", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<TiBulkIgnore> getTiBulkIgnores()
	{
		return (List<TiBulkIgnore>) readProperty("tiBulkIgnores");
	}

}
