package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.TiInboundDataXml;

/**
 * Class _TiRateTable was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TiRateTable extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> ALTERNATE_LOCATION = new Property<String>("alternateLocation");
	public static final Property<String> BASE_LOCATION = new Property<String>("baseLocation");
	public static final Property<String> CHANGE_INDICATOR = new Property<String>("changeIndicator");
	public static final Property<Date> ETL_TIMESTAMP = new Property<Date>("etlTimestamp");
	public static final Property<String> PRICE_QUOTATION_CURR = new Property<String>("priceQuotationCurr");
	public static final Property<String> PRICE_QUOTATION_UOM = new Property<String>("priceQuotationUom");
	public static final Property<Date> QUOTATION_DATE = new Property<Date>("quotationDate");
	public static final Property<String> QUOTATION_NUMBER = new Property<String>("quotationNumber");
	public static final Property<BigDecimal> QUOTATION_PRICE = new Property<BigDecimal>("quotationPrice");
	public static final Property<String> QUOTATION_PRICE_UNIT = new Property<String>("quotationPriceUnit");
	public static final Property<String> STATUS = new Property<String>("status");
	public static final Property<TiInboundDataXml> INBOUND_DATA_O = new Property<TiInboundDataXml>("inboundDataO");

	public void setAlternateLocation(String alternateLocation)
	{
		writeProperty("alternateLocation", alternateLocation);
	}

	public String getAlternateLocation()
	{
		return (String) readProperty("alternateLocation");
	}

	public void setBaseLocation(String baseLocation)
	{
		writeProperty("baseLocation", baseLocation);
	}

	public String getBaseLocation()
	{
		return (String) readProperty("baseLocation");
	}

	public void setChangeIndicator(String changeIndicator)
	{
		writeProperty("changeIndicator", changeIndicator);
	}

	public String getChangeIndicator()
	{
		return (String) readProperty("changeIndicator");
	}

	public void setEtlTimestamp(Date etlTimestamp)
	{
		writeProperty("etlTimestamp", etlTimestamp);
	}

	public Date getEtlTimestamp()
	{
		return (Date) readProperty("etlTimestamp");
	}

	public void setPriceQuotationCurr(String priceQuotationCurr)
	{
		writeProperty("priceQuotationCurr", priceQuotationCurr);
	}

	public String getPriceQuotationCurr()
	{
		return (String) readProperty("priceQuotationCurr");
	}

	public void setPriceQuotationUom(String priceQuotationUom)
	{
		writeProperty("priceQuotationUom", priceQuotationUom);
	}

	public String getPriceQuotationUom()
	{
		return (String) readProperty("priceQuotationUom");
	}

	public void setQuotationDate(Date quotationDate)
	{
		writeProperty("quotationDate", quotationDate);
	}

	public Date getQuotationDate()
	{
		return (Date) readProperty("quotationDate");
	}

	public void setQuotationNumber(String quotationNumber)
	{
		writeProperty("quotationNumber", quotationNumber);
	}

	public String getQuotationNumber()
	{
		return (String) readProperty("quotationNumber");
	}

	public void setQuotationPrice(BigDecimal quotationPrice)
	{
		writeProperty("quotationPrice", quotationPrice);
	}

	public BigDecimal getQuotationPrice()
	{
		return (BigDecimal) readProperty("quotationPrice");
	}

	public void setQuotationPriceUnit(String quotationPriceUnit)
	{
		writeProperty("quotationPriceUnit", quotationPriceUnit);
	}

	public String getQuotationPriceUnit()
	{
		return (String) readProperty("quotationPriceUnit");
	}

	public void setStatus(String status)
	{
		writeProperty("status", status);
	}

	public String getStatus()
	{
		return (String) readProperty("status");
	}

	public void setInboundDataO(TiInboundDataXml inboundDataO)
	{
		setToOneTarget("inboundDataO", inboundDataO, true);
	}

	public TiInboundDataXml getInboundDataO()
	{
		return (TiInboundDataXml) readProperty("inboundDataO");
	}

}
