package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.TiInboundDataXml;

/**
 * Class _TiSopTradePlan was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TiSopTradePlan extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> BUY_SELL = new Property<String>("buySell");
	public static final Property<String> DEAL_TYPE = new Property<String>("dealType");
	public static final Property<String> DISTRIBUTIVE_AREA = new Property<String>("distributiveArea");
	public static final Property<Date> ETL_TIMESTAMP = new Property<Date>("etlTimestamp");
	public static final Property<String> LOCATION = new Property<String>("location");
	public static final Property<String> MATERIAL = new Property<String>("material");
	public static final Property<Date> PLAN_END_DATE = new Property<Date>("planEndDate");
	public static final Property<Integer> PLAN_ID = new Property<Integer>("planId");
	public static final Property<Date> PLAN_START_DATE = new Property<Date>("planStartDate");
	public static final Property<BigDecimal> QUANTITY = new Property<BigDecimal>("quantity");
	public static final Property<Date> START_DATE = new Property<Date>("startDate");
	public static final Property<String> STATUS = new Property<String>("status");
	public static final Property<String> UOM = new Property<String>("uom");
	public static final Property<TiInboundDataXml> INBOUND_DATA_O = new Property<TiInboundDataXml>("inboundDataO");

	public void setBuySell(String buySell)
	{
		writeProperty("buySell", buySell);
	}

	public String getBuySell()
	{
		return (String) readProperty("buySell");
	}

	public void setDealType(String dealType)
	{
		writeProperty("dealType", dealType);
	}

	public String getDealType()
	{
		return (String) readProperty("dealType");
	}

	public void setDistributiveArea(String distributiveArea)
	{
		writeProperty("distributiveArea", distributiveArea);
	}

	public String getDistributiveArea()
	{
		return (String) readProperty("distributiveArea");
	}

	public void setEtlTimestamp(Date etlTimestamp)
	{
		writeProperty("etlTimestamp", etlTimestamp);
	}

	public Date getEtlTimestamp()
	{
		return (Date) readProperty("etlTimestamp");
	}

	public void setLocation(String location)
	{
		writeProperty("location", location);
	}

	public String getLocation()
	{
		return (String) readProperty("location");
	}

	public void setMaterial(String material)
	{
		writeProperty("material", material);
	}

	public String getMaterial()
	{
		return (String) readProperty("material");
	}

	public void setPlanEndDate(Date planEndDate)
	{
		writeProperty("planEndDate", planEndDate);
	}

	public Date getPlanEndDate()
	{
		return (Date) readProperty("planEndDate");
	}

	public void setPlanId(Integer planId)
	{
		writeProperty("planId", planId);
	}

	public Integer getPlanId()
	{
		return (Integer) readProperty("planId");
	}

	public void setPlanStartDate(Date planStartDate)
	{
		writeProperty("planStartDate", planStartDate);
	}

	public Date getPlanStartDate()
	{
		return (Date) readProperty("planStartDate");
	}

	public void setQuantity(BigDecimal quantity)
	{
		writeProperty("quantity", quantity);
	}

	public BigDecimal getQuantity()
	{
		return (BigDecimal) readProperty("quantity");
	}

	public void setStartDate(Date startDate)
	{
		writeProperty("startDate", startDate);
	}

	public Date getStartDate()
	{
		return (Date) readProperty("startDate");
	}

	public void setStatus(String status)
	{
		writeProperty("status", status);
	}

	public String getStatus()
	{
		return (String) readProperty("status");
	}

	public void setUom(String uom)
	{
		writeProperty("uom", uom);
	}

	public String getUom()
	{
		return (String) readProperty("uom");
	}

	public void setInboundDataO(TiInboundDataXml inboundDataO)
	{
		setToOneTarget("inboundDataO", inboundDataO, true);
	}

	public TiInboundDataXml getInboundDataO()
	{
		return (TiInboundDataXml) readProperty("inboundDataO");
	}

}
