package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CreditTerm;
import com.tc.app.exchangemonitor.model.cayenne.persistent.DeliveryTerm;
import com.tc.app.exchangemonitor.model.cayenne.persistent.HandlingType;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Location;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PaymentTerm;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TimeZone;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _TradeItemBunker was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TradeItemBunker extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ITEM_NUM_PK_COLUMN = "item_num";
	public static final String ORDER_NUM_PK_COLUMN = "order_num";
	public static final String TRADE_NUM_PK_COLUMN = "trade_num";

	public static final Property<Date> CURR_EXCH_DATE = new Property<>("currExchDate");
	public static final Property<Date> DEL_DATE = new Property<>("delDate");
	public static final Property<String> DELIVERY_MOT = new Property<>("deliveryMot");
	public static final Property<Date> ETA_DATE = new Property<>("etaDate");
	public static final Property<BigDecimal> MAX_QTY = new Property<>("maxQty");
	public static final Property<String> MAX_QTY_UOM_CODE = new Property<>("maxQtyUomCode");
	public static final Property<BigDecimal> MIN_QTY = new Property<>("minQty");
	public static final Property<String> MIN_QTY_UOM_CODE = new Property<>("minQtyUomCode");
	public static final Property<String> MOT_CODE = new Property<>("motCode");
	public static final Property<Date> PRICING_EXP_DATE = new Property<>("pricingExpDate");
	public static final Property<String> TOL_OPT = new Property<>("tolOpt");
	public static final Property<BigDecimal> TOL_QTY = new Property<>("tolQty");
	public static final Property<String> TOL_QTY_UOM_CODE = new Property<>("tolQtyUomCode");
	public static final Property<String> TOL_SIGN = new Property<>("tolSign");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<Double> TRANSP_PRICE_AMT = new Property<>("transpPriceAmt");
	public static final Property<Account> ACCOUNT = new Property<>("account");
	public static final Property<Account> ACCOUNT1 = new Property<>("account1");
	public static final Property<Commodity> COMMODITY = new Property<>("commodity");
	public static final Property<CreditTerm> CREDIT_TERM = new Property<>("creditTerm");
	public static final Property<DeliveryTerm> DELIVERY_TERM = new Property<>("deliveryTerm");
	public static final Property<HandlingType> HANDLING_TYPE = new Property<>("handlingType");
	public static final Property<Location> LOCATION = new Property<>("location");
	public static final Property<Location> LOCATION1 = new Property<>("location1");
	public static final Property<PaymentTerm> PAYMENT_TERM = new Property<>("paymentTerm");
	public static final Property<TimeZone> TIME_ZONE = new Property<>("timeZone");
	public static final Property<Uom> UOM = new Property<>("uom");

	public void setCurrExchDate(final Date currExchDate)
	{
		this.writeProperty("currExchDate", currExchDate);
	}

	public Date getCurrExchDate()
	{
		return (Date) this.readProperty("currExchDate");
	}

	public void setDelDate(final Date delDate)
	{
		this.writeProperty("delDate", delDate);
	}

	public Date getDelDate()
	{
		return (Date) this.readProperty("delDate");
	}

	public void setDeliveryMot(final String deliveryMot)
	{
		this.writeProperty("deliveryMot", deliveryMot);
	}

	public String getDeliveryMot()
	{
		return (String) this.readProperty("deliveryMot");
	}

	public void setEtaDate(final Date etaDate)
	{
		this.writeProperty("etaDate", etaDate);
	}

	public Date getEtaDate()
	{
		return (Date) this.readProperty("etaDate");
	}

	public void setMaxQty(final BigDecimal maxQty)
	{
		this.writeProperty("maxQty", maxQty);
	}

	public BigDecimal getMaxQty()
	{
		return (BigDecimal) this.readProperty("maxQty");
	}

	public void setMaxQtyUomCode(final String maxQtyUomCode)
	{
		this.writeProperty("maxQtyUomCode", maxQtyUomCode);
	}

	public String getMaxQtyUomCode()
	{
		return (String) this.readProperty("maxQtyUomCode");
	}

	public void setMinQty(final BigDecimal minQty)
	{
		this.writeProperty("minQty", minQty);
	}

	public BigDecimal getMinQty()
	{
		return (BigDecimal) this.readProperty("minQty");
	}

	public void setMinQtyUomCode(final String minQtyUomCode)
	{
		this.writeProperty("minQtyUomCode", minQtyUomCode);
	}

	public String getMinQtyUomCode()
	{
		return (String) this.readProperty("minQtyUomCode");
	}

	public void setMotCode(final String motCode)
	{
		this.writeProperty("motCode", motCode);
	}

	public String getMotCode()
	{
		return (String) this.readProperty("motCode");
	}

	public void setPricingExpDate(final Date pricingExpDate)
	{
		this.writeProperty("pricingExpDate", pricingExpDate);
	}

	public Date getPricingExpDate()
	{
		return (Date) this.readProperty("pricingExpDate");
	}

	public void setTolOpt(final String tolOpt)
	{
		this.writeProperty("tolOpt", tolOpt);
	}

	public String getTolOpt()
	{
		return (String) this.readProperty("tolOpt");
	}

	public void setTolQty(final BigDecimal tolQty)
	{
		this.writeProperty("tolQty", tolQty);
	}

	public BigDecimal getTolQty()
	{
		return (BigDecimal) this.readProperty("tolQty");
	}

	public void setTolQtyUomCode(final String tolQtyUomCode)
	{
		this.writeProperty("tolQtyUomCode", tolQtyUomCode);
	}

	public String getTolQtyUomCode()
	{
		return (String) this.readProperty("tolQtyUomCode");
	}

	public void setTolSign(final String tolSign)
	{
		this.writeProperty("tolSign", tolSign);
	}

	public String getTolSign()
	{
		return (String) this.readProperty("tolSign");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setTranspPriceAmt(final Double transpPriceAmt)
	{
		this.writeProperty("transpPriceAmt", transpPriceAmt);
	}

	public Double getTranspPriceAmt()
	{
		return (Double) this.readProperty("transpPriceAmt");
	}

	public void setAccount(final Account account)
	{
		this.setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) this.readProperty("account");
	}

	public void setAccount1(final Account account1)
	{
		this.setToOneTarget("account1", account1, true);
	}

	public Account getAccount1()
	{
		return (Account) this.readProperty("account1");
	}

	public void setCommodity(final Commodity commodity)
	{
		this.setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) this.readProperty("commodity");
	}

	public void setCreditTerm(final CreditTerm creditTerm)
	{
		this.setToOneTarget("creditTerm", creditTerm, true);
	}

	public CreditTerm getCreditTerm()
	{
		return (CreditTerm) this.readProperty("creditTerm");
	}

	public void setDeliveryTerm(final DeliveryTerm deliveryTerm)
	{
		this.setToOneTarget("deliveryTerm", deliveryTerm, true);
	}

	public DeliveryTerm getDeliveryTerm()
	{
		return (DeliveryTerm) this.readProperty("deliveryTerm");
	}

	public void setHandlingType(final HandlingType handlingType)
	{
		this.setToOneTarget("handlingType", handlingType, true);
	}

	public HandlingType getHandlingType()
	{
		return (HandlingType) this.readProperty("handlingType");
	}

	public void setLocation(final Location location)
	{
		this.setToOneTarget("location", location, true);
	}

	public Location getLocation()
	{
		return (Location) this.readProperty("location");
	}

	public void setLocation1(final Location location1)
	{
		this.setToOneTarget("location1", location1, true);
	}

	public Location getLocation1()
	{
		return (Location) this.readProperty("location1");
	}

	public void setPaymentTerm(final PaymentTerm paymentTerm)
	{
		this.setToOneTarget("paymentTerm", paymentTerm, true);
	}

	public PaymentTerm getPaymentTerm()
	{
		return (PaymentTerm) this.readProperty("paymentTerm");
	}

	public void setTimeZone(final TimeZone timeZone)
	{
		this.setToOneTarget("timeZone", timeZone, true);
	}

	public TimeZone getTimeZone()
	{
		return (TimeZone) this.readProperty("timeZone");
	}

	public void setUom(final Uom uom)
	{
		this.setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) this.readProperty("uom");
	}

}
