package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.AccountAgreement;
import com.tc.app.exchangemonitor.model.cayenne.persistent.AccountContact;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Country;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ExceptionsAdditions;
import com.tc.app.exchangemonitor.model.cayenne.persistent.FinancialReconcil;
import com.tc.app.exchangemonitor.model.cayenne.persistent.FxCostDrawDownHist;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Gtc;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsUser;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Location;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Market;
import com.tc.app.exchangemonitor.model.cayenne.persistent.RcAssignTrade;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ScenarioItem;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _TradeItem was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TradeItem extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ITEM_NUM_PK_COLUMN = "item_num";
	public static final String ORDER_NUM_PK_COLUMN = "order_num";
	public static final String TRADE_NUM_PK_COLUMN = "trade_num";

	public static final Property<String> ACCUM_PERIODICITY = new Property<>("accumPeriodicity");
	public static final Property<String> ACTIVE_STATUS_IND = new Property<>("activeStatusInd");
	public static final Property<Double> ADDL_COST_SUM = new Property<>("addlCostSum");
	public static final Property<Date> AMEND_CREATION_DATE = new Property<>("amendCreationDate");
	public static final Property<Date> AMEND_EFFECT_END_DATE = new Property<>("amendEffectEndDate");
	public static final Property<Date> AMEND_EFFECT_START_DATE = new Property<>("amendEffectStartDate");
	public static final Property<Short> AMEND_NUM = new Property<>("amendNum");
	public static final Property<Double> AVG_PRICE = new Property<>("avgPrice");
	public static final Property<String> B2B_TRADE_ITEM = new Property<>("b2bTradeItem");
	public static final Property<String> BILLING_TYPE = new Property<>("billingType");
	public static final Property<Double> BRKR_COMM_AMT = new Property<>("brkrCommAmt");
	public static final Property<String> BRKR_REF_NUM = new Property<>("brkrRefNum");
	public static final Property<String> CALENDAR_CODE = new Property<>("calendarCode");
	public static final Property<Integer> CMNT_NUM = new Property<>("cmntNum");
	public static final Property<Double> CONTR_MTM_PL = new Property<>("contrMtmPl");
	public static final Property<Double> CONTR_QTY = new Property<>("contrQty");
	public static final Property<String> CONTR_QTY_PERIODICITY = new Property<>("contrQtyPeriodicity");
	public static final Property<String> ESTIMATE_IND = new Property<>("estimateInd");
	public static final Property<Date> FORMULA_DECLAR_DATE = new Property<>("formulaDeclarDate");
	public static final Property<String> FORMULA_IND = new Property<>("formulaInd");
	public static final Property<String> HEDGE_MULTI_DIV_IND = new Property<>("hedgeMultiDivInd");
	public static final Property<String> HEDGE_POS_IND = new Property<>("hedgePosInd");
	public static final Property<Double> HEDGE_RATE = new Property<>("hedgeRate");
	public static final Property<String> IDMS_ACCT_ALLOC = new Property<>("idmsAcctAlloc");
	public static final Property<String> IDMS_BB_REF_NUM = new Property<>("idmsBbRefNum");
	public static final Property<String> IDMS_CONTR_NUM = new Property<>("idmsContrNum");
	public static final Property<String> IDMS_PROFIT_CENTER = new Property<>("idmsProfitCenter");
	public static final Property<Boolean> INCLUDES_EXCISE_TAX_IND = new Property<>("includesExciseTaxInd");
	public static final Property<Boolean> INCLUDES_FUEL_TAX_IND = new Property<>("includesFuelTaxInd");
	public static final Property<Short> INTERNAL_PARENT_ITEM_NUM = new Property<>("internalParentItemNum");
	public static final Property<Short> INTERNAL_PARENT_ORDER_NUM = new Property<>("internalParentOrderNum");
	public static final Property<Integer> INTERNAL_PARENT_TRADE_NUM = new Property<>("internalParentTradeNum");
	public static final Property<String> IS_CLEARED_IND = new Property<>("isClearedInd");
	public static final Property<String> IS_LC_ASSIGNED = new Property<>("isLcAssigned");
	public static final Property<String> IS_RC_ASSIGNED = new Property<>("isRcAssigned");
	public static final Property<String> ITEM_CONFIRM_IND = new Property<>("itemConfirmInd");
	public static final Property<String> ITEM_STATUS_CODE = new Property<>("itemStatusCode");
	public static final Property<String> ITEM_TYPE = new Property<>("itemType");
	public static final Property<BigDecimal> MARKET_VALUE = new Property<>("marketValue");
	public static final Property<Short> MAX_ACCUM_NUM = new Property<>("maxAccumNum");
	public static final Property<Double> MTM_PL = new Property<>("mtmPl");
	public static final Property<Date> MTM_PL_AS_OF_DATE = new Property<>("mtmPlAsOfDate");
	public static final Property<Double> OPEN_QTY = new Property<>("openQty");
	public static final Property<String> OPEN_QTY_UOM_CODE = new Property<>("openQtyUomCode");
	public static final Property<String> P_SIND = new Property<>("pSInd");
	public static final Property<Short> PARENT_ITEM_NUM = new Property<>("parentItemNum");
	public static final Property<String> POOLING_PORT_IND = new Property<>("poolingPortInd");
	public static final Property<Integer> POOLING_PORT_NUM = new Property<>("poolingPortNum");
	public static final Property<String> POOLING_TYPE = new Property<>("poolingType");
	public static final Property<String> PURCHASING_GROUP = new Property<>("purchasingGroup");
	public static final Property<Integer> QUOTE_ID = new Property<>("quoteId");
	public static final Property<Integer> REAL_PORT_NUM = new Property<>("realPortNum");
	public static final Property<Integer> REAL_QUOTE_PERIOD_ID = new Property<>("realQuotePeriodId");
	public static final Property<Integer> RECAP_ITEM_NUM = new Property<>("recapItemNum");
	public static final Property<String> RIN_IND = new Property<>("rinInd");
	public static final Property<String> SAP_ORDER_NUM = new Property<>("sapOrderNum");
	public static final Property<Short> SCHED_STATUS = new Property<>("schedStatus");
	public static final Property<String> STRIP_ITEM_STATUS = new Property<>("stripItemStatus");
	public static final Property<Short> SUMMARY_ITEM_NUM = new Property<>("summaryItemNum");
	public static final Property<BigDecimal> TOTAL_COMMITTED_QTY = new Property<>("totalCommittedQty");
	public static final Property<Double> TOTAL_PRICED_QTY = new Property<>("totalPricedQty");
	public static final Property<Double> TOTAL_SCH_QTY = new Property<>("totalSchQty");
	public static final Property<String> TRADE_MODIFIED_IND = new Property<>("tradeModifiedInd");
	public static final Property<String> TRADING_PRD = new Property<>("tradingPrd");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<Double> UOM_CONV_RATE = new Property<>("uomConvRate");
	public static final Property<String> USE_MKT_FORMULA_FOR_PL = new Property<>("useMktFormulaForPl");
	public static final Property<Account> ACCOUNT = new Property<>("account");
	public static final Property<Account> ACCOUNT1 = new Property<>("account1");
	public static final Property<Account> ACCOUNT2 = new Property<>("account2");
	public static final Property<Account> ACCOUNT3 = new Property<>("account3");
	public static final Property<Account> ACCOUNT4 = new Property<>("account4");
	public static final Property<AccountAgreement> ACCOUNT_AGREEMENT = new Property<>("accountAgreement");
	public static final Property<AccountContact> ACCOUNT_CONTACT = new Property<>("accountContact");
	public static final Property<AccountContact> ACCOUNT_CONTACT1 = new Property<>("accountContact1");
	public static final Property<Commodity> COMMODITY = new Property<>("commodity");
	public static final Property<Commodity> COMMODITY1 = new Property<>("commodity1");
	public static final Property<Commodity> COMMODITY2 = new Property<>("commodity2");
	public static final Property<Commodity> COMMODITY3 = new Property<>("commodity3");
	public static final Property<Commodity> COMMODITY4 = new Property<>("commodity4");
	public static final Property<Country> COUNTRY = new Property<>("country");
	public static final Property<ExceptionsAdditions> EXCEPTIONS_ADDITIONS = new Property<>("exceptionsAdditions");
	public static final Property<List<FinancialReconcil>> FINANCIAL_RECONCILS = new Property<>("financialReconcils");
	public static final Property<List<FinancialReconcil>> FINANCIAL_RECONCILS1 = new Property<>("financialReconcils1");
	public static final Property<List<FinancialReconcil>> FINANCIAL_RECONCILS2 = new Property<>("financialReconcils2");
	public static final Property<List<FxCostDrawDownHist>> FX_COST_DRAW_DOWN_HISTS = new Property<>("fxCostDrawDownHists");
	public static final Property<List<FxCostDrawDownHist>> FX_COST_DRAW_DOWN_HISTS1 = new Property<>("fxCostDrawDownHists1");
	public static final Property<List<FxCostDrawDownHist>> FX_COST_DRAW_DOWN_HISTS2 = new Property<>("fxCostDrawDownHists2");
	public static final Property<Gtc> GTC = new Property<>("gtc");
	public static final Property<IctsUser> ICTS_USER = new Property<>("ictsUser");
	public static final Property<Location> LOCATION = new Property<>("location");
	public static final Property<Location> LOCATION1 = new Property<>("location1");
	public static final Property<Market> MARKET = new Property<>("market");
	public static final Property<Market> MARKET1 = new Property<>("market1");
	public static final Property<List<RcAssignTrade>> RC_ASSIGN_TRADES = new Property<>("rcAssignTrades");
	public static final Property<List<RcAssignTrade>> RC_ASSIGN_TRADES1 = new Property<>("rcAssignTrades1");
	public static final Property<List<RcAssignTrade>> RC_ASSIGN_TRADES2 = new Property<>("rcAssignTrades2");
	public static final Property<List<ScenarioItem>> SCENARIO_ITEMS = new Property<>("scenarioItems");
	public static final Property<List<ScenarioItem>> SCENARIO_ITEMS1 = new Property<>("scenarioItems1");
	public static final Property<List<ScenarioItem>> SCENARIO_ITEMS2 = new Property<>("scenarioItems2");
	public static final Property<Uom> UOM = new Property<>("uom");
	public static final Property<Uom> UOM1 = new Property<>("uom1");
	public static final Property<Uom> UOM2 = new Property<>("uom2");
	public static final Property<Uom> UOM3 = new Property<>("uom3");
	public static final Property<Uom> UOM4 = new Property<>("uom4");
	public static final Property<Uom> UOM5 = new Property<>("uom5");

	public void setAccumPeriodicity(final String accumPeriodicity)
	{
		this.writeProperty("accumPeriodicity", accumPeriodicity);
	}

	public String getAccumPeriodicity()
	{
		return (String) this.readProperty("accumPeriodicity");
	}

	public void setActiveStatusInd(final String activeStatusInd)
	{
		this.writeProperty("activeStatusInd", activeStatusInd);
	}

	public String getActiveStatusInd()
	{
		return (String) this.readProperty("activeStatusInd");
	}

	public void setAddlCostSum(final Double addlCostSum)
	{
		this.writeProperty("addlCostSum", addlCostSum);
	}

	public Double getAddlCostSum()
	{
		return (Double) this.readProperty("addlCostSum");
	}

	public void setAmendCreationDate(final Date amendCreationDate)
	{
		this.writeProperty("amendCreationDate", amendCreationDate);
	}

	public Date getAmendCreationDate()
	{
		return (Date) this.readProperty("amendCreationDate");
	}

	public void setAmendEffectEndDate(final Date amendEffectEndDate)
	{
		this.writeProperty("amendEffectEndDate", amendEffectEndDate);
	}

	public Date getAmendEffectEndDate()
	{
		return (Date) this.readProperty("amendEffectEndDate");
	}

	public void setAmendEffectStartDate(final Date amendEffectStartDate)
	{
		this.writeProperty("amendEffectStartDate", amendEffectStartDate);
	}

	public Date getAmendEffectStartDate()
	{
		return (Date) this.readProperty("amendEffectStartDate");
	}

	public void setAmendNum(final Short amendNum)
	{
		this.writeProperty("amendNum", amendNum);
	}

	public Short getAmendNum()
	{
		return (Short) this.readProperty("amendNum");
	}

	public void setAvgPrice(final Double avgPrice)
	{
		this.writeProperty("avgPrice", avgPrice);
	}

	public Double getAvgPrice()
	{
		return (Double) this.readProperty("avgPrice");
	}

	public void setB2bTradeItem(final String b2bTradeItem)
	{
		this.writeProperty("b2bTradeItem", b2bTradeItem);
	}

	public String getB2bTradeItem()
	{
		return (String) this.readProperty("b2bTradeItem");
	}

	public void setBillingType(final String billingType)
	{
		this.writeProperty("billingType", billingType);
	}

	public String getBillingType()
	{
		return (String) this.readProperty("billingType");
	}

	public void setBrkrCommAmt(final Double brkrCommAmt)
	{
		this.writeProperty("brkrCommAmt", brkrCommAmt);
	}

	public Double getBrkrCommAmt()
	{
		return (Double) this.readProperty("brkrCommAmt");
	}

	public void setBrkrRefNum(final String brkrRefNum)
	{
		this.writeProperty("brkrRefNum", brkrRefNum);
	}

	public String getBrkrRefNum()
	{
		return (String) this.readProperty("brkrRefNum");
	}

	public void setCalendarCode(final String calendarCode)
	{
		this.writeProperty("calendarCode", calendarCode);
	}

	public String getCalendarCode()
	{
		return (String) this.readProperty("calendarCode");
	}

	public void setCmntNum(final Integer cmntNum)
	{
		this.writeProperty("cmntNum", cmntNum);
	}

	public Integer getCmntNum()
	{
		return (Integer) this.readProperty("cmntNum");
	}

	public void setContrMtmPl(final Double contrMtmPl)
	{
		this.writeProperty("contrMtmPl", contrMtmPl);
	}

	public Double getContrMtmPl()
	{
		return (Double) this.readProperty("contrMtmPl");
	}

	public void setContrQty(final Double contrQty)
	{
		this.writeProperty("contrQty", contrQty);
	}

	public Double getContrQty()
	{
		return (Double) this.readProperty("contrQty");
	}

	public void setContrQtyPeriodicity(final String contrQtyPeriodicity)
	{
		this.writeProperty("contrQtyPeriodicity", contrQtyPeriodicity);
	}

	public String getContrQtyPeriodicity()
	{
		return (String) this.readProperty("contrQtyPeriodicity");
	}

	public void setEstimateInd(final String estimateInd)
	{
		this.writeProperty("estimateInd", estimateInd);
	}

	public String getEstimateInd()
	{
		return (String) this.readProperty("estimateInd");
	}

	public void setFormulaDeclarDate(final Date formulaDeclarDate)
	{
		this.writeProperty("formulaDeclarDate", formulaDeclarDate);
	}

	public Date getFormulaDeclarDate()
	{
		return (Date) this.readProperty("formulaDeclarDate");
	}

	public void setFormulaInd(final String formulaInd)
	{
		this.writeProperty("formulaInd", formulaInd);
	}

	public String getFormulaInd()
	{
		return (String) this.readProperty("formulaInd");
	}

	public void setHedgeMultiDivInd(final String hedgeMultiDivInd)
	{
		this.writeProperty("hedgeMultiDivInd", hedgeMultiDivInd);
	}

	public String getHedgeMultiDivInd()
	{
		return (String) this.readProperty("hedgeMultiDivInd");
	}

	public void setHedgePosInd(final String hedgePosInd)
	{
		this.writeProperty("hedgePosInd", hedgePosInd);
	}

	public String getHedgePosInd()
	{
		return (String) this.readProperty("hedgePosInd");
	}

	public void setHedgeRate(final Double hedgeRate)
	{
		this.writeProperty("hedgeRate", hedgeRate);
	}

	public Double getHedgeRate()
	{
		return (Double) this.readProperty("hedgeRate");
	}

	public void setIdmsAcctAlloc(final String idmsAcctAlloc)
	{
		this.writeProperty("idmsAcctAlloc", idmsAcctAlloc);
	}

	public String getIdmsAcctAlloc()
	{
		return (String) this.readProperty("idmsAcctAlloc");
	}

	public void setIdmsBbRefNum(final String idmsBbRefNum)
	{
		this.writeProperty("idmsBbRefNum", idmsBbRefNum);
	}

	public String getIdmsBbRefNum()
	{
		return (String) this.readProperty("idmsBbRefNum");
	}

	public void setIdmsContrNum(final String idmsContrNum)
	{
		this.writeProperty("idmsContrNum", idmsContrNum);
	}

	public String getIdmsContrNum()
	{
		return (String) this.readProperty("idmsContrNum");
	}

	public void setIdmsProfitCenter(final String idmsProfitCenter)
	{
		this.writeProperty("idmsProfitCenter", idmsProfitCenter);
	}

	public String getIdmsProfitCenter()
	{
		return (String) this.readProperty("idmsProfitCenter");
	}

	public void setIncludesExciseTaxInd(final Boolean includesExciseTaxInd)
	{
		this.writeProperty("includesExciseTaxInd", includesExciseTaxInd);
	}

	public Boolean getIncludesExciseTaxInd()
	{
		return (Boolean) this.readProperty("includesExciseTaxInd");
	}

	public void setIncludesFuelTaxInd(final Boolean includesFuelTaxInd)
	{
		this.writeProperty("includesFuelTaxInd", includesFuelTaxInd);
	}

	public Boolean getIncludesFuelTaxInd()
	{
		return (Boolean) this.readProperty("includesFuelTaxInd");
	}

	public void setInternalParentItemNum(final Short internalParentItemNum)
	{
		this.writeProperty("internalParentItemNum", internalParentItemNum);
	}

	public Short getInternalParentItemNum()
	{
		return (Short) this.readProperty("internalParentItemNum");
	}

	public void setInternalParentOrderNum(final Short internalParentOrderNum)
	{
		this.writeProperty("internalParentOrderNum", internalParentOrderNum);
	}

	public Short getInternalParentOrderNum()
	{
		return (Short) this.readProperty("internalParentOrderNum");
	}

	public void setInternalParentTradeNum(final Integer internalParentTradeNum)
	{
		this.writeProperty("internalParentTradeNum", internalParentTradeNum);
	}

	public Integer getInternalParentTradeNum()
	{
		return (Integer) this.readProperty("internalParentTradeNum");
	}

	public void setIsClearedInd(final String isClearedInd)
	{
		this.writeProperty("isClearedInd", isClearedInd);
	}

	public String getIsClearedInd()
	{
		return (String) this.readProperty("isClearedInd");
	}

	public void setIsLcAssigned(final String isLcAssigned)
	{
		this.writeProperty("isLcAssigned", isLcAssigned);
	}

	public String getIsLcAssigned()
	{
		return (String) this.readProperty("isLcAssigned");
	}

	public void setIsRcAssigned(final String isRcAssigned)
	{
		this.writeProperty("isRcAssigned", isRcAssigned);
	}

	public String getIsRcAssigned()
	{
		return (String) this.readProperty("isRcAssigned");
	}

	public void setItemConfirmInd(final String itemConfirmInd)
	{
		this.writeProperty("itemConfirmInd", itemConfirmInd);
	}

	public String getItemConfirmInd()
	{
		return (String) this.readProperty("itemConfirmInd");
	}

	public void setItemStatusCode(final String itemStatusCode)
	{
		this.writeProperty("itemStatusCode", itemStatusCode);
	}

	public String getItemStatusCode()
	{
		return (String) this.readProperty("itemStatusCode");
	}

	public void setItemType(final String itemType)
	{
		this.writeProperty("itemType", itemType);
	}

	public String getItemType()
	{
		return (String) this.readProperty("itemType");
	}

	public void setMarketValue(final BigDecimal marketValue)
	{
		this.writeProperty("marketValue", marketValue);
	}

	public BigDecimal getMarketValue()
	{
		return (BigDecimal) this.readProperty("marketValue");
	}

	public void setMaxAccumNum(final Short maxAccumNum)
	{
		this.writeProperty("maxAccumNum", maxAccumNum);
	}

	public Short getMaxAccumNum()
	{
		return (Short) this.readProperty("maxAccumNum");
	}

	public void setMtmPl(final Double mtmPl)
	{
		this.writeProperty("mtmPl", mtmPl);
	}

	public Double getMtmPl()
	{
		return (Double) this.readProperty("mtmPl");
	}

	public void setMtmPlAsOfDate(final Date mtmPlAsOfDate)
	{
		this.writeProperty("mtmPlAsOfDate", mtmPlAsOfDate);
	}

	public Date getMtmPlAsOfDate()
	{
		return (Date) this.readProperty("mtmPlAsOfDate");
	}

	public void setOpenQty(final Double openQty)
	{
		this.writeProperty("openQty", openQty);
	}

	public Double getOpenQty()
	{
		return (Double) this.readProperty("openQty");
	}

	public void setOpenQtyUomCode(final String openQtyUomCode)
	{
		this.writeProperty("openQtyUomCode", openQtyUomCode);
	}

	public String getOpenQtyUomCode()
	{
		return (String) this.readProperty("openQtyUomCode");
	}

	public void setPSInd(final String pSInd)
	{
		this.writeProperty("pSInd", pSInd);
	}

	public String getPSInd()
	{
		return (String) this.readProperty("pSInd");
	}

	public void setParentItemNum(final Short parentItemNum)
	{
		this.writeProperty("parentItemNum", parentItemNum);
	}

	public Short getParentItemNum()
	{
		return (Short) this.readProperty("parentItemNum");
	}

	public void setPoolingPortInd(final String poolingPortInd)
	{
		this.writeProperty("poolingPortInd", poolingPortInd);
	}

	public String getPoolingPortInd()
	{
		return (String) this.readProperty("poolingPortInd");
	}

	public void setPoolingPortNum(final Integer poolingPortNum)
	{
		this.writeProperty("poolingPortNum", poolingPortNum);
	}

	public Integer getPoolingPortNum()
	{
		return (Integer) this.readProperty("poolingPortNum");
	}

	public void setPoolingType(final String poolingType)
	{
		this.writeProperty("poolingType", poolingType);
	}

	public String getPoolingType()
	{
		return (String) this.readProperty("poolingType");
	}

	public void setPurchasingGroup(final String purchasingGroup)
	{
		this.writeProperty("purchasingGroup", purchasingGroup);
	}

	public String getPurchasingGroup()
	{
		return (String) this.readProperty("purchasingGroup");
	}

	public void setQuoteId(final Integer quoteId)
	{
		this.writeProperty("quoteId", quoteId);
	}

	public Integer getQuoteId()
	{
		return (Integer) this.readProperty("quoteId");
	}

	public void setRealPortNum(final Integer realPortNum)
	{
		this.writeProperty("realPortNum", realPortNum);
	}

	public Integer getRealPortNum()
	{
		return (Integer) this.readProperty("realPortNum");
	}

	public void setRealQuotePeriodId(final Integer realQuotePeriodId)
	{
		this.writeProperty("realQuotePeriodId", realQuotePeriodId);
	}

	public Integer getRealQuotePeriodId()
	{
		return (Integer) this.readProperty("realQuotePeriodId");
	}

	public void setRecapItemNum(final Integer recapItemNum)
	{
		this.writeProperty("recapItemNum", recapItemNum);
	}

	public Integer getRecapItemNum()
	{
		return (Integer) this.readProperty("recapItemNum");
	}

	public void setRinInd(final String rinInd)
	{
		this.writeProperty("rinInd", rinInd);
	}

	public String getRinInd()
	{
		return (String) this.readProperty("rinInd");
	}

	public void setSapOrderNum(final String sapOrderNum)
	{
		this.writeProperty("sapOrderNum", sapOrderNum);
	}

	public String getSapOrderNum()
	{
		return (String) this.readProperty("sapOrderNum");
	}

	public void setSchedStatus(final Short schedStatus)
	{
		this.writeProperty("schedStatus", schedStatus);
	}

	public Short getSchedStatus()
	{
		return (Short) this.readProperty("schedStatus");
	}

	public void setStripItemStatus(final String stripItemStatus)
	{
		this.writeProperty("stripItemStatus", stripItemStatus);
	}

	public String getStripItemStatus()
	{
		return (String) this.readProperty("stripItemStatus");
	}

	public void setSummaryItemNum(final Short summaryItemNum)
	{
		this.writeProperty("summaryItemNum", summaryItemNum);
	}

	public Short getSummaryItemNum()
	{
		return (Short) this.readProperty("summaryItemNum");
	}

	public void setTotalCommittedQty(final BigDecimal totalCommittedQty)
	{
		this.writeProperty("totalCommittedQty", totalCommittedQty);
	}

	public BigDecimal getTotalCommittedQty()
	{
		return (BigDecimal) this.readProperty("totalCommittedQty");
	}

	public void setTotalPricedQty(final Double totalPricedQty)
	{
		this.writeProperty("totalPricedQty", totalPricedQty);
	}

	public Double getTotalPricedQty()
	{
		return (Double) this.readProperty("totalPricedQty");
	}

	public void setTotalSchQty(final Double totalSchQty)
	{
		this.writeProperty("totalSchQty", totalSchQty);
	}

	public Double getTotalSchQty()
	{
		return (Double) this.readProperty("totalSchQty");
	}

	public void setTradeModifiedInd(final String tradeModifiedInd)
	{
		this.writeProperty("tradeModifiedInd", tradeModifiedInd);
	}

	public String getTradeModifiedInd()
	{
		return (String) this.readProperty("tradeModifiedInd");
	}

	public void setTradingPrd(final String tradingPrd)
	{
		this.writeProperty("tradingPrd", tradingPrd);
	}

	public String getTradingPrd()
	{
		return (String) this.readProperty("tradingPrd");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setUomConvRate(final Double uomConvRate)
	{
		this.writeProperty("uomConvRate", uomConvRate);
	}

	public Double getUomConvRate()
	{
		return (Double) this.readProperty("uomConvRate");
	}

	public void setUseMktFormulaForPl(final String useMktFormulaForPl)
	{
		this.writeProperty("useMktFormulaForPl", useMktFormulaForPl);
	}

	public String getUseMktFormulaForPl()
	{
		return (String) this.readProperty("useMktFormulaForPl");
	}

	public void setAccount(final Account account)
	{
		this.setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) this.readProperty("account");
	}

	public void setAccount1(final Account account1)
	{
		this.setToOneTarget("account1", account1, true);
	}

	public Account getAccount1()
	{
		return (Account) this.readProperty("account1");
	}

	public void setAccount2(final Account account2)
	{
		this.setToOneTarget("account2", account2, true);
	}

	public Account getAccount2()
	{
		return (Account) this.readProperty("account2");
	}

	public void setAccount3(final Account account3)
	{
		this.setToOneTarget("account3", account3, true);
	}

	public Account getAccount3()
	{
		return (Account) this.readProperty("account3");
	}

	public void setAccount4(final Account account4)
	{
		this.setToOneTarget("account4", account4, true);
	}

	public Account getAccount4()
	{
		return (Account) this.readProperty("account4");
	}

	public void setAccountAgreement(final AccountAgreement accountAgreement)
	{
		this.setToOneTarget("accountAgreement", accountAgreement, true);
	}

	public AccountAgreement getAccountAgreement()
	{
		return (AccountAgreement) this.readProperty("accountAgreement");
	}

	public void setAccountContact(final AccountContact accountContact)
	{
		this.setToOneTarget("accountContact", accountContact, true);
	}

	public AccountContact getAccountContact()
	{
		return (AccountContact) this.readProperty("accountContact");
	}

	public void setAccountContact1(final AccountContact accountContact1)
	{
		this.setToOneTarget("accountContact1", accountContact1, true);
	}

	public AccountContact getAccountContact1()
	{
		return (AccountContact) this.readProperty("accountContact1");
	}

	public void setCommodity(final Commodity commodity)
	{
		this.setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) this.readProperty("commodity");
	}

	public void setCommodity1(final Commodity commodity1)
	{
		this.setToOneTarget("commodity1", commodity1, true);
	}

	public Commodity getCommodity1()
	{
		return (Commodity) this.readProperty("commodity1");
	}

	public void setCommodity2(final Commodity commodity2)
	{
		this.setToOneTarget("commodity2", commodity2, true);
	}

	public Commodity getCommodity2()
	{
		return (Commodity) this.readProperty("commodity2");
	}

	public void setCommodity3(final Commodity commodity3)
	{
		this.setToOneTarget("commodity3", commodity3, true);
	}

	public Commodity getCommodity3()
	{
		return (Commodity) this.readProperty("commodity3");
	}

	public void setCommodity4(final Commodity commodity4)
	{
		this.setToOneTarget("commodity4", commodity4, true);
	}

	public Commodity getCommodity4()
	{
		return (Commodity) this.readProperty("commodity4");
	}

	public void setCountry(final Country country)
	{
		this.setToOneTarget("country", country, true);
	}

	public Country getCountry()
	{
		return (Country) this.readProperty("country");
	}

	public void setExceptionsAdditions(final ExceptionsAdditions exceptionsAdditions)
	{
		this.setToOneTarget("exceptionsAdditions", exceptionsAdditions, true);
	}

	public ExceptionsAdditions getExceptionsAdditions()
	{
		return (ExceptionsAdditions) this.readProperty("exceptionsAdditions");
	}

	public void addToFinancialReconcils(final FinancialReconcil obj)
	{
		this.addToManyTarget("financialReconcils", obj, true);
	}

	public void removeFromFinancialReconcils(final FinancialReconcil obj)
	{
		this.removeToManyTarget("financialReconcils", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FinancialReconcil> getFinancialReconcils()
	{
		return (List<FinancialReconcil>) this.readProperty("financialReconcils");
	}

	public void addToFinancialReconcils1(final FinancialReconcil obj)
	{
		this.addToManyTarget("financialReconcils1", obj, true);
	}

	public void removeFromFinancialReconcils1(final FinancialReconcil obj)
	{
		this.removeToManyTarget("financialReconcils1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FinancialReconcil> getFinancialReconcils1()
	{
		return (List<FinancialReconcil>) this.readProperty("financialReconcils1");
	}

	public void addToFinancialReconcils2(final FinancialReconcil obj)
	{
		this.addToManyTarget("financialReconcils2", obj, true);
	}

	public void removeFromFinancialReconcils2(final FinancialReconcil obj)
	{
		this.removeToManyTarget("financialReconcils2", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FinancialReconcil> getFinancialReconcils2()
	{
		return (List<FinancialReconcil>) this.readProperty("financialReconcils2");
	}

	public void addToFxCostDrawDownHists(final FxCostDrawDownHist obj)
	{
		this.addToManyTarget("fxCostDrawDownHists", obj, true);
	}

	public void removeFromFxCostDrawDownHists(final FxCostDrawDownHist obj)
	{
		this.removeToManyTarget("fxCostDrawDownHists", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FxCostDrawDownHist> getFxCostDrawDownHists()
	{
		return (List<FxCostDrawDownHist>) this.readProperty("fxCostDrawDownHists");
	}

	public void addToFxCostDrawDownHists1(final FxCostDrawDownHist obj)
	{
		this.addToManyTarget("fxCostDrawDownHists1", obj, true);
	}

	public void removeFromFxCostDrawDownHists1(final FxCostDrawDownHist obj)
	{
		this.removeToManyTarget("fxCostDrawDownHists1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FxCostDrawDownHist> getFxCostDrawDownHists1()
	{
		return (List<FxCostDrawDownHist>) this.readProperty("fxCostDrawDownHists1");
	}

	public void addToFxCostDrawDownHists2(final FxCostDrawDownHist obj)
	{
		this.addToManyTarget("fxCostDrawDownHists2", obj, true);
	}

	public void removeFromFxCostDrawDownHists2(final FxCostDrawDownHist obj)
	{
		this.removeToManyTarget("fxCostDrawDownHists2", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<FxCostDrawDownHist> getFxCostDrawDownHists2()
	{
		return (List<FxCostDrawDownHist>) this.readProperty("fxCostDrawDownHists2");
	}

	public void setGtc(final Gtc gtc)
	{
		this.setToOneTarget("gtc", gtc, true);
	}

	public Gtc getGtc()
	{
		return (Gtc) this.readProperty("gtc");
	}

	public void setIctsUser(final IctsUser ictsUser)
	{
		this.setToOneTarget("ictsUser", ictsUser, true);
	}

	public IctsUser getIctsUser()
	{
		return (IctsUser) this.readProperty("ictsUser");
	}

	public void setLocation(final Location location)
	{
		this.setToOneTarget("location", location, true);
	}

	public Location getLocation()
	{
		return (Location) this.readProperty("location");
	}

	public void setLocation1(final Location location1)
	{
		this.setToOneTarget("location1", location1, true);
	}

	public Location getLocation1()
	{
		return (Location) this.readProperty("location1");
	}

	public void setMarket(final Market market)
	{
		this.setToOneTarget("market", market, true);
	}

	public Market getMarket()
	{
		return (Market) this.readProperty("market");
	}

	public void setMarket1(final Market market1)
	{
		this.setToOneTarget("market1", market1, true);
	}

	public Market getMarket1()
	{
		return (Market) this.readProperty("market1");
	}

	public void addToRcAssignTrades(final RcAssignTrade obj)
	{
		this.addToManyTarget("rcAssignTrades", obj, true);
	}

	public void removeFromRcAssignTrades(final RcAssignTrade obj)
	{
		this.removeToManyTarget("rcAssignTrades", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<RcAssignTrade> getRcAssignTrades()
	{
		return (List<RcAssignTrade>) this.readProperty("rcAssignTrades");
	}

	public void addToRcAssignTrades1(final RcAssignTrade obj)
	{
		this.addToManyTarget("rcAssignTrades1", obj, true);
	}

	public void removeFromRcAssignTrades1(final RcAssignTrade obj)
	{
		this.removeToManyTarget("rcAssignTrades1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<RcAssignTrade> getRcAssignTrades1()
	{
		return (List<RcAssignTrade>) this.readProperty("rcAssignTrades1");
	}

	public void addToRcAssignTrades2(final RcAssignTrade obj)
	{
		this.addToManyTarget("rcAssignTrades2", obj, true);
	}

	public void removeFromRcAssignTrades2(final RcAssignTrade obj)
	{
		this.removeToManyTarget("rcAssignTrades2", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<RcAssignTrade> getRcAssignTrades2()
	{
		return (List<RcAssignTrade>) this.readProperty("rcAssignTrades2");
	}

	public void addToScenarioItems(final ScenarioItem obj)
	{
		this.addToManyTarget("scenarioItems", obj, true);
	}

	public void removeFromScenarioItems(final ScenarioItem obj)
	{
		this.removeToManyTarget("scenarioItems", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ScenarioItem> getScenarioItems()
	{
		return (List<ScenarioItem>) this.readProperty("scenarioItems");
	}

	public void addToScenarioItems1(final ScenarioItem obj)
	{
		this.addToManyTarget("scenarioItems1", obj, true);
	}

	public void removeFromScenarioItems1(final ScenarioItem obj)
	{
		this.removeToManyTarget("scenarioItems1", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ScenarioItem> getScenarioItems1()
	{
		return (List<ScenarioItem>) this.readProperty("scenarioItems1");
	}

	public void addToScenarioItems2(final ScenarioItem obj)
	{
		this.addToManyTarget("scenarioItems2", obj, true);
	}

	public void removeFromScenarioItems2(final ScenarioItem obj)
	{
		this.removeToManyTarget("scenarioItems2", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ScenarioItem> getScenarioItems2()
	{
		return (List<ScenarioItem>) this.readProperty("scenarioItems2");
	}

	public void setUom(final Uom uom)
	{
		this.setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) this.readProperty("uom");
	}

	public void setUom1(final Uom uom1)
	{
		this.setToOneTarget("uom1", uom1, true);
	}

	public Uom getUom1()
	{
		return (Uom) this.readProperty("uom1");
	}

	public void setUom2(final Uom uom2)
	{
		this.setToOneTarget("uom2", uom2, true);
	}

	public Uom getUom2()
	{
		return (Uom) this.readProperty("uom2");
	}

	public void setUom3(final Uom uom3)
	{
		this.setToOneTarget("uom3", uom3, true);
	}

	public Uom getUom3()
	{
		return (Uom) this.readProperty("uom3");
	}

	public void setUom4(final Uom uom4)
	{
		this.setToOneTarget("uom4", uom4, true);
	}

	public Uom getUom4()
	{
		return (Uom) this.readProperty("uom4");
	}

	public void setUom5(final Uom uom5)
	{
		this.setToOneTarget("uom5", uom5, true);
	}

	public Uom getUom5()
	{
		return (Uom) this.readProperty("uom5");
	}

}
