package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.CreditTerm;
import com.tc.app.exchangemonitor.model.cayenne.persistent.DeliveryTerm;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Facility;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsUser;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Location;
import com.tc.app.exchangemonitor.model.cayenne.persistent.LocationTankInfo;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PaymentTerm;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PipelineCycle;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _TradeItemWetPhy was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TradeItemWetPhy extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ITEM_NUM_PK_COLUMN = "item_num";
	public static final String ORDER_NUM_PK_COLUMN = "order_num";
	public static final String TRADE_NUM_PK_COLUMN = "trade_num";

	public static final Property<String> B2B_SALE_IND = new Property<>("b2bSaleInd");
	public static final Property<String> COST_ADJ_QTY1 = new Property<>("costAdjQty1");
	public static final Property<String> COST_ADJ_QTY2 = new Property<>("costAdjQty2");
	public static final Property<Date> CREDIT_APPROVAL_DATE = new Property<>("creditApprovalDate");
	public static final Property<String> DECLAR_DATE_TYPE = new Property<>("declarDateType");
	public static final Property<Short> DECLAR_REL_DAYS = new Property<>("declarRelDays");
	public static final Property<String> DEL_DATE_BASIS = new Property<>("delDateBasis");
	public static final Property<String> DEL_DATE_EST_IND = new Property<>("delDateEstInd");
	public static final Property<Date> DEL_DATE_FROM = new Property<>("delDateFrom");
	public static final Property<Date> DEL_DATE_TO = new Property<>("delDateTo");
	public static final Property<String> DEL_LOC_TYPE = new Property<>("delLocType");
	public static final Property<String> DENSITY_IND = new Property<>("densityInd");
	public static final Property<Short> DEST_ITEM_NUM = new Property<>("destItemNum");
	public static final Property<Short> DEST_ORDER_NUM = new Property<>("destOrderNum");
	public static final Property<Integer> DEST_TRADE_NUM = new Property<>("destTradeNum");
	public static final Property<BigDecimal> ESTIMATE_QTY = new Property<>("estimateQty");
	public static final Property<Double> FLOAT_VAL = new Property<>("floatVal");
	public static final Property<String> HEAT_ADJ_IND = new Property<>("heatAdjInd");
	public static final Property<Integer> IMP_REC_REASON_OID = new Property<>("impRecReasonOid");
	public static final Property<Integer> INT_VAL = new Property<>("intVal");
	public static final Property<String> ITEM_PETROEX_NUM = new Property<>("itemPetroexNum");
	public static final Property<Integer> LEASE_NUM = new Property<>("leaseNum");
	public static final Property<Integer> LEASE_VER_NUM = new Property<>("leaseVerNum");
	public static final Property<Double> MAX_QTY = new Property<>("maxQty");
	public static final Property<Double> MIN_QTY = new Property<>("minQty");
	public static final Property<Double> MIN_SHIP_QTY = new Property<>("minShipQty");
	public static final Property<String> MOT_CODE = new Property<>("motCode");
	public static final Property<String> PARCEL_NUM = new Property<>("parcelNum");
	public static final Property<Date> PARTIAL_DEADLINE_DATE = new Property<>("partialDeadlineDate");
	public static final Property<Double> PARTIAL_RES_INC_AMT = new Property<>("partialResIncAmt");
	public static final Property<Integer> PAY_DAYS = new Property<>("payDays");
	public static final Property<Integer> PP_QTY_ADJ_RULE_NUM = new Property<>("ppQtyAdjRuleNum");
	public static final Property<Date> PRELIM_DUE_DATE = new Property<>("prelimDueDate");
	public static final Property<BigDecimal> PRELIM_PERCENTAGE = new Property<>("prelimPercentage");
	public static final Property<BigDecimal> PRELIM_PRICE = new Property<>("prelimPrice");
	public static final Property<String> PRELIM_PRICE_TYPE = new Property<>("prelimPriceType");
	public static final Property<String> PRELIM_QTY_BASE = new Property<>("prelimQtyBase");
	public static final Property<String> PROC_DEAL_DELIVERY_TYPE = new Property<>("procDealDeliveryType");
	public static final Property<String> PROC_DEAL_EVENT_NAME = new Property<>("procDealEventName");
	public static final Property<Short> PROC_DEAL_EVENT_SPEC = new Property<>("procDealEventSpec");
	public static final Property<Short> PROC_DEAL_LIFTING_DAYS = new Property<>("procDealLiftingDays");
	public static final Property<String> STR_VAL = new Property<>("strVal");
	public static final Property<String> TAKEN_TO_SCH_POS_IND = new Property<>("takenToSchPosInd");
	public static final Property<String> TAX_QUALIFICATION_CODE = new Property<>("taxQualificationCode");
	public static final Property<Short> TIMING_CYCLE_YEAR = new Property<>("timingCycleYear");
	public static final Property<String> TITLE_TRANSFER_DOC = new Property<>("titleTransferDoc");
	public static final Property<String> TOL_OPT = new Property<>("tolOpt");
	public static final Property<Double> TOL_QTY = new Property<>("tolQty");
	public static final Property<String> TOL_SIGN = new Property<>("tolSign");
	public static final Property<Short> TOTAL_SHIP_NUM = new Property<>("totalShipNum");
	public static final Property<String> TRADE_EXP_REC_IND = new Property<>("tradeExpRecInd");
	public static final Property<String> TRADE_IMP_REC_IND = new Property<>("tradeImpRecInd");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<String> TRANSPORTATION = new Property<>("transportation");
	public static final Property<CreditTerm> CREDIT_TERM = new Property<>("creditTerm");
	public static final Property<DeliveryTerm> DELIVERY_TERM = new Property<>("deliveryTerm");
	public static final Property<Facility> FACILITY = new Property<>("facility");
	public static final Property<IctsUser> ICTS_USER = new Property<>("ictsUser");
	public static final Property<IctsUser> ICTS_USER1 = new Property<>("ictsUser1");
	public static final Property<Location> LOCATION = new Property<>("location");
	public static final Property<LocationTankInfo> LOCATION_TANK_INFO = new Property<>("locationTankInfo");
	public static final Property<PaymentTerm> PAYMENT_TERM = new Property<>("paymentTerm");
	public static final Property<PaymentTerm> PAYMENT_TERM1 = new Property<>("paymentTerm1");
	public static final Property<PipelineCycle> PIPELINE_CYCLE = new Property<>("pipelineCycle");
	public static final Property<Uom> UOM = new Property<>("uom");
	public static final Property<Uom> UOM1 = new Property<>("uom1");
	public static final Property<Uom> UOM2 = new Property<>("uom2");
	public static final Property<Uom> UOM3 = new Property<>("uom3");

	public void setB2bSaleInd(final String b2bSaleInd)
	{
		this.writeProperty("b2bSaleInd", b2bSaleInd);
	}

	public String getB2bSaleInd()
	{
		return (String) this.readProperty("b2bSaleInd");
	}

	public void setCostAdjQty1(final String costAdjQty1)
	{
		this.writeProperty("costAdjQty1", costAdjQty1);
	}

	public String getCostAdjQty1()
	{
		return (String) this.readProperty("costAdjQty1");
	}

	public void setCostAdjQty2(final String costAdjQty2)
	{
		this.writeProperty("costAdjQty2", costAdjQty2);
	}

	public String getCostAdjQty2()
	{
		return (String) this.readProperty("costAdjQty2");
	}

	public void setCreditApprovalDate(final Date creditApprovalDate)
	{
		this.writeProperty("creditApprovalDate", creditApprovalDate);
	}

	public Date getCreditApprovalDate()
	{
		return (Date) this.readProperty("creditApprovalDate");
	}

	public void setDeclarDateType(final String declarDateType)
	{
		this.writeProperty("declarDateType", declarDateType);
	}

	public String getDeclarDateType()
	{
		return (String) this.readProperty("declarDateType");
	}

	public void setDeclarRelDays(final Short declarRelDays)
	{
		this.writeProperty("declarRelDays", declarRelDays);
	}

	public Short getDeclarRelDays()
	{
		return (Short) this.readProperty("declarRelDays");
	}

	public void setDelDateBasis(final String delDateBasis)
	{
		this.writeProperty("delDateBasis", delDateBasis);
	}

	public String getDelDateBasis()
	{
		return (String) this.readProperty("delDateBasis");
	}

	public void setDelDateEstInd(final String delDateEstInd)
	{
		this.writeProperty("delDateEstInd", delDateEstInd);
	}

	public String getDelDateEstInd()
	{
		return (String) this.readProperty("delDateEstInd");
	}

	public void setDelDateFrom(final Date delDateFrom)
	{
		this.writeProperty("delDateFrom", delDateFrom);
	}

	public Date getDelDateFrom()
	{
		return (Date) this.readProperty("delDateFrom");
	}

	public void setDelDateTo(final Date delDateTo)
	{
		this.writeProperty("delDateTo", delDateTo);
	}

	public Date getDelDateTo()
	{
		return (Date) this.readProperty("delDateTo");
	}

	public void setDelLocType(final String delLocType)
	{
		this.writeProperty("delLocType", delLocType);
	}

	public String getDelLocType()
	{
		return (String) this.readProperty("delLocType");
	}

	public void setDensityInd(final String densityInd)
	{
		this.writeProperty("densityInd", densityInd);
	}

	public String getDensityInd()
	{
		return (String) this.readProperty("densityInd");
	}

	public void setDestItemNum(final Short destItemNum)
	{
		this.writeProperty("destItemNum", destItemNum);
	}

	public Short getDestItemNum()
	{
		return (Short) this.readProperty("destItemNum");
	}

	public void setDestOrderNum(final Short destOrderNum)
	{
		this.writeProperty("destOrderNum", destOrderNum);
	}

	public Short getDestOrderNum()
	{
		return (Short) this.readProperty("destOrderNum");
	}

	public void setDestTradeNum(final Integer destTradeNum)
	{
		this.writeProperty("destTradeNum", destTradeNum);
	}

	public Integer getDestTradeNum()
	{
		return (Integer) this.readProperty("destTradeNum");
	}

	public void setEstimateQty(final BigDecimal estimateQty)
	{
		this.writeProperty("estimateQty", estimateQty);
	}

	public BigDecimal getEstimateQty()
	{
		return (BigDecimal) this.readProperty("estimateQty");
	}

	public void setFloatVal(final Double floatVal)
	{
		this.writeProperty("floatVal", floatVal);
	}

	public Double getFloatVal()
	{
		return (Double) this.readProperty("floatVal");
	}

	public void setHeatAdjInd(final String heatAdjInd)
	{
		this.writeProperty("heatAdjInd", heatAdjInd);
	}

	public String getHeatAdjInd()
	{
		return (String) this.readProperty("heatAdjInd");
	}

	public void setImpRecReasonOid(final Integer impRecReasonOid)
	{
		this.writeProperty("impRecReasonOid", impRecReasonOid);
	}

	public Integer getImpRecReasonOid()
	{
		return (Integer) this.readProperty("impRecReasonOid");
	}

	public void setIntVal(final Integer intVal)
	{
		this.writeProperty("intVal", intVal);
	}

	public Integer getIntVal()
	{
		return (Integer) this.readProperty("intVal");
	}

	public void setItemPetroexNum(final String itemPetroexNum)
	{
		this.writeProperty("itemPetroexNum", itemPetroexNum);
	}

	public String getItemPetroexNum()
	{
		return (String) this.readProperty("itemPetroexNum");
	}

	public void setLeaseNum(final Integer leaseNum)
	{
		this.writeProperty("leaseNum", leaseNum);
	}

	public Integer getLeaseNum()
	{
		return (Integer) this.readProperty("leaseNum");
	}

	public void setLeaseVerNum(final Integer leaseVerNum)
	{
		this.writeProperty("leaseVerNum", leaseVerNum);
	}

	public Integer getLeaseVerNum()
	{
		return (Integer) this.readProperty("leaseVerNum");
	}

	public void setMaxQty(final Double maxQty)
	{
		this.writeProperty("maxQty", maxQty);
	}

	public Double getMaxQty()
	{
		return (Double) this.readProperty("maxQty");
	}

	public void setMinQty(final Double minQty)
	{
		this.writeProperty("minQty", minQty);
	}

	public Double getMinQty()
	{
		return (Double) this.readProperty("minQty");
	}

	public void setMinShipQty(final Double minShipQty)
	{
		this.writeProperty("minShipQty", minShipQty);
	}

	public Double getMinShipQty()
	{
		return (Double) this.readProperty("minShipQty");
	}

	public void setMotCode(final String motCode)
	{
		this.writeProperty("motCode", motCode);
	}

	public String getMotCode()
	{
		return (String) this.readProperty("motCode");
	}

	public void setParcelNum(final String parcelNum)
	{
		this.writeProperty("parcelNum", parcelNum);
	}

	public String getParcelNum()
	{
		return (String) this.readProperty("parcelNum");
	}

	public void setPartialDeadlineDate(final Date partialDeadlineDate)
	{
		this.writeProperty("partialDeadlineDate", partialDeadlineDate);
	}

	public Date getPartialDeadlineDate()
	{
		return (Date) this.readProperty("partialDeadlineDate");
	}

	public void setPartialResIncAmt(final Double partialResIncAmt)
	{
		this.writeProperty("partialResIncAmt", partialResIncAmt);
	}

	public Double getPartialResIncAmt()
	{
		return (Double) this.readProperty("partialResIncAmt");
	}

	public void setPayDays(final Integer payDays)
	{
		this.writeProperty("payDays", payDays);
	}

	public Integer getPayDays()
	{
		return (Integer) this.readProperty("payDays");
	}

	public void setPpQtyAdjRuleNum(final Integer ppQtyAdjRuleNum)
	{
		this.writeProperty("ppQtyAdjRuleNum", ppQtyAdjRuleNum);
	}

	public Integer getPpQtyAdjRuleNum()
	{
		return (Integer) this.readProperty("ppQtyAdjRuleNum");
	}

	public void setPrelimDueDate(final Date prelimDueDate)
	{
		this.writeProperty("prelimDueDate", prelimDueDate);
	}

	public Date getPrelimDueDate()
	{
		return (Date) this.readProperty("prelimDueDate");
	}

	public void setPrelimPercentage(final BigDecimal prelimPercentage)
	{
		this.writeProperty("prelimPercentage", prelimPercentage);
	}

	public BigDecimal getPrelimPercentage()
	{
		return (BigDecimal) this.readProperty("prelimPercentage");
	}

	public void setPrelimPrice(final BigDecimal prelimPrice)
	{
		this.writeProperty("prelimPrice", prelimPrice);
	}

	public BigDecimal getPrelimPrice()
	{
		return (BigDecimal) this.readProperty("prelimPrice");
	}

	public void setPrelimPriceType(final String prelimPriceType)
	{
		this.writeProperty("prelimPriceType", prelimPriceType);
	}

	public String getPrelimPriceType()
	{
		return (String) this.readProperty("prelimPriceType");
	}

	public void setPrelimQtyBase(final String prelimQtyBase)
	{
		this.writeProperty("prelimQtyBase", prelimQtyBase);
	}

	public String getPrelimQtyBase()
	{
		return (String) this.readProperty("prelimQtyBase");
	}

	public void setProcDealDeliveryType(final String procDealDeliveryType)
	{
		this.writeProperty("procDealDeliveryType", procDealDeliveryType);
	}

	public String getProcDealDeliveryType()
	{
		return (String) this.readProperty("procDealDeliveryType");
	}

	public void setProcDealEventName(final String procDealEventName)
	{
		this.writeProperty("procDealEventName", procDealEventName);
	}

	public String getProcDealEventName()
	{
		return (String) this.readProperty("procDealEventName");
	}

	public void setProcDealEventSpec(final Short procDealEventSpec)
	{
		this.writeProperty("procDealEventSpec", procDealEventSpec);
	}

	public Short getProcDealEventSpec()
	{
		return (Short) this.readProperty("procDealEventSpec");
	}

	public void setProcDealLiftingDays(final Short procDealLiftingDays)
	{
		this.writeProperty("procDealLiftingDays", procDealLiftingDays);
	}

	public Short getProcDealLiftingDays()
	{
		return (Short) this.readProperty("procDealLiftingDays");
	}

	public void setStrVal(final String strVal)
	{
		this.writeProperty("strVal", strVal);
	}

	public String getStrVal()
	{
		return (String) this.readProperty("strVal");
	}

	public void setTakenToSchPosInd(final String takenToSchPosInd)
	{
		this.writeProperty("takenToSchPosInd", takenToSchPosInd);
	}

	public String getTakenToSchPosInd()
	{
		return (String) this.readProperty("takenToSchPosInd");
	}

	public void setTaxQualificationCode(final String taxQualificationCode)
	{
		this.writeProperty("taxQualificationCode", taxQualificationCode);
	}

	public String getTaxQualificationCode()
	{
		return (String) this.readProperty("taxQualificationCode");
	}

	public void setTimingCycleYear(final Short timingCycleYear)
	{
		this.writeProperty("timingCycleYear", timingCycleYear);
	}

	public Short getTimingCycleYear()
	{
		return (Short) this.readProperty("timingCycleYear");
	}

	public void setTitleTransferDoc(final String titleTransferDoc)
	{
		this.writeProperty("titleTransferDoc", titleTransferDoc);
	}

	public String getTitleTransferDoc()
	{
		return (String) this.readProperty("titleTransferDoc");
	}

	public void setTolOpt(final String tolOpt)
	{
		this.writeProperty("tolOpt", tolOpt);
	}

	public String getTolOpt()
	{
		return (String) this.readProperty("tolOpt");
	}

	public void setTolQty(final Double tolQty)
	{
		this.writeProperty("tolQty", tolQty);
	}

	public Double getTolQty()
	{
		return (Double) this.readProperty("tolQty");
	}

	public void setTolSign(final String tolSign)
	{
		this.writeProperty("tolSign", tolSign);
	}

	public String getTolSign()
	{
		return (String) this.readProperty("tolSign");
	}

	public void setTotalShipNum(final Short totalShipNum)
	{
		this.writeProperty("totalShipNum", totalShipNum);
	}

	public Short getTotalShipNum()
	{
		return (Short) this.readProperty("totalShipNum");
	}

	public void setTradeExpRecInd(final String tradeExpRecInd)
	{
		this.writeProperty("tradeExpRecInd", tradeExpRecInd);
	}

	public String getTradeExpRecInd()
	{
		return (String) this.readProperty("tradeExpRecInd");
	}

	public void setTradeImpRecInd(final String tradeImpRecInd)
	{
		this.writeProperty("tradeImpRecInd", tradeImpRecInd);
	}

	public String getTradeImpRecInd()
	{
		return (String) this.readProperty("tradeImpRecInd");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setTransportation(final String transportation)
	{
		this.writeProperty("transportation", transportation);
	}

	public String getTransportation()
	{
		return (String) this.readProperty("transportation");
	}

	public void setCreditTerm(final CreditTerm creditTerm)
	{
		this.setToOneTarget("creditTerm", creditTerm, true);
	}

	public CreditTerm getCreditTerm()
	{
		return (CreditTerm) this.readProperty("creditTerm");
	}

	public void setDeliveryTerm(final DeliveryTerm deliveryTerm)
	{
		this.setToOneTarget("deliveryTerm", deliveryTerm, true);
	}

	public DeliveryTerm getDeliveryTerm()
	{
		return (DeliveryTerm) this.readProperty("deliveryTerm");
	}

	public void setFacility(final Facility facility)
	{
		this.setToOneTarget("facility", facility, true);
	}

	public Facility getFacility()
	{
		return (Facility) this.readProperty("facility");
	}

	public void setIctsUser(final IctsUser ictsUser)
	{
		this.setToOneTarget("ictsUser", ictsUser, true);
	}

	public IctsUser getIctsUser()
	{
		return (IctsUser) this.readProperty("ictsUser");
	}

	public void setIctsUser1(final IctsUser ictsUser1)
	{
		this.setToOneTarget("ictsUser1", ictsUser1, true);
	}

	public IctsUser getIctsUser1()
	{
		return (IctsUser) this.readProperty("ictsUser1");
	}

	public void setLocation(final Location location)
	{
		this.setToOneTarget("location", location, true);
	}

	public Location getLocation()
	{
		return (Location) this.readProperty("location");
	}

	public void setLocationTankInfo(final LocationTankInfo locationTankInfo)
	{
		this.setToOneTarget("locationTankInfo", locationTankInfo, true);
	}

	public LocationTankInfo getLocationTankInfo()
	{
		return (LocationTankInfo) this.readProperty("locationTankInfo");
	}

	public void setPaymentTerm(final PaymentTerm paymentTerm)
	{
		this.setToOneTarget("paymentTerm", paymentTerm, true);
	}

	public PaymentTerm getPaymentTerm()
	{
		return (PaymentTerm) this.readProperty("paymentTerm");
	}

	public void setPaymentTerm1(final PaymentTerm paymentTerm1)
	{
		this.setToOneTarget("paymentTerm1", paymentTerm1, true);
	}

	public PaymentTerm getPaymentTerm1()
	{
		return (PaymentTerm) this.readProperty("paymentTerm1");
	}

	public void setPipelineCycle(final PipelineCycle pipelineCycle)
	{
		this.setToOneTarget("pipelineCycle", pipelineCycle, true);
	}

	public PipelineCycle getPipelineCycle()
	{
		return (PipelineCycle) this.readProperty("pipelineCycle");
	}

	public void setUom(final Uom uom)
	{
		this.setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) this.readProperty("uom");
	}

	public void setUom1(final Uom uom1)
	{
		this.setToOneTarget("uom1", uom1, true);
	}

	public Uom getUom1()
	{
		return (Uom) this.readProperty("uom1");
	}

	public void setUom2(final Uom uom2)
	{
		this.setToOneTarget("uom2", uom2, true);
	}

	public Uom getUom2()
	{
		return (Uom) this.readProperty("uom2");
	}

	public void setUom3(final Uom uom3)
	{
		this.setToOneTarget("uom3", uom3, true);
	}

	public Uom getUom3()
	{
		return (Uom) this.readProperty("uom3");
	}

}
