package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.AliasSource;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PriceSource;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TradingPeriod;

/**
 * Class _TradingPeriodAlias was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TradingPeriodAlias extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ALIAS_HIGH_LOW_IND_PK_COLUMN = "alias_high_low_ind";
	public static final String ALIAS_SOURCE_CODE_PK_COLUMN = "alias_source_code";
	public static final String COMMKT_KEY_PK_COLUMN = "commkt_key";
	public static final String PRICE_SOURCE_CODE_PK_COLUMN = "price_source_code";
	public static final String TRADING_PRD_PK_COLUMN = "trading_prd";
	public static final String TRADING_PRD_ALIAS_NAME_PK_COLUMN = "trading_prd_alias_name";

	public static final Property<String> ALIAS_FORMAT_CODE = new Property<String>("aliasFormatCode");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<AliasSource> ALIAS_SOURCE = new Property<AliasSource>("aliasSource");
	public static final Property<PriceSource> PRICE_SOURCE = new Property<PriceSource>("priceSource");
	public static final Property<TradingPeriod> TRADING_PERIOD = new Property<TradingPeriod>("tradingPeriod");
	public static final Property<TradingPeriod> TRADING_PERIOD1 = new Property<TradingPeriod>("tradingPeriod1");

	public void setAliasFormatCode(String aliasFormatCode)
	{
		writeProperty("aliasFormatCode", aliasFormatCode);
	}

	public String getAliasFormatCode()
	{
		return (String) readProperty("aliasFormatCode");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setAliasSource(AliasSource aliasSource)
	{
		setToOneTarget("aliasSource", aliasSource, true);
	}

	public AliasSource getAliasSource()
	{
		return (AliasSource) readProperty("aliasSource");
	}

	public void setPriceSource(PriceSource priceSource)
	{
		setToOneTarget("priceSource", priceSource, true);
	}

	public PriceSource getPriceSource()
	{
		return (PriceSource) readProperty("priceSource");
	}

	public void setTradingPeriod(TradingPeriod tradingPeriod)
	{
		setToOneTarget("tradingPeriod", tradingPeriod, true);
	}

	public TradingPeriod getTradingPeriod()
	{
		return (TradingPeriod) readProperty("tradingPeriod");
	}

	public void setTradingPeriod1(TradingPeriod tradingPeriod1)
	{
		setToOneTarget("tradingPeriod1", tradingPeriod1, true);
	}

	public TradingPeriod getTradingPeriod1()
	{
		return (TradingPeriod) readProperty("tradingPeriod1");
	}

}
