package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.AccountContact;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ContractStatus;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CreditTerm;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsProduct;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsUser;
import com.tc.app.exchangemonitor.model.cayenne.persistent.ReleaseDocument;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TradeFeed;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TradeStatus;

/**
 * Class _Trade was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Trade extends CayenneDataObject
{
	private static final long serialVersionUID = 1L;

	public static final String TRADE_NUM_PK_COLUMN = "trade_num";

	public static final Property<String> ACCT_REF_NUM = new Property<>("acctRefNum");
	public static final Property<String> ACCT_SHORT_NAME = new Property<>("acctShortName");
	public static final Property<String> CARGO_ID_NUMBER = new Property<>("cargoIdNumber");
	public static final Property<Date> CONCLUDED_DATE = new Property<>("concludedDate");
	public static final Property<String> CONCLUSION_TYPE = new Property<>("conclusionType");
	public static final Property<String> CONTR_ANLY_INIT = new Property<>("contrAnlyInit");
	public static final Property<String> CONTR_APPROV_TYPE = new Property<>("contrApprovType");
	public static final Property<String> CONTR_CNFRM_METHOD = new Property<>("contrCnfrmMethod");
	public static final Property<Date> CONTR_DATE = new Property<>("contrDate");
	public static final Property<String> CONTR_EXCH_METHOD = new Property<>("contrExchMethod");
	public static final Property<String> CONTR_TLX_HOLD_IND = new Property<>("contrTlxHoldInd");
	public static final Property<String> COPY_TYPE = new Property<>("copyType");
	public static final Property<String> CP_GOV_CONTR_IND = new Property<>("cpGovContrInd");
	public static final Property<Date> CREATION_DATE = new Property<>("creationDate");
	public static final Property<Date> CREDIT_RES_EXP_DATE = new Property<>("creditResExpDate");
	public static final Property<String> CREDIT_STATUS = new Property<>("creditStatus");
	public static final Property<String> ECONFIRM_STATUS = new Property<>("econfirmStatus");
	public static final Property<String> EXTERNAL_TRADE_TYPE = new Property<>("externalTradeType");
	public static final Property<String> INHOUSE_IND = new Property<>("inhouseInd");
	public static final Property<String> INTERNAL_AGREEMENT_IND = new Property<>("internalAgreementInd");
	public static final Property<Integer> INTERNAL_PARENT_TRADE_NUM = new Property<>("internalParentTradeNum");
	public static final Property<String> INV_PRICING_TYPE = new Property<>("invPricingType");
	public static final Property<String> INVENTORY_TYPE = new Property<>("inventoryType");
	public static final Property<String> INVOICE_CAP_TYPE = new Property<>("invoiceCapType");
	public static final Property<String> IS_LONG_TERM_IND = new Property<>("isLongTermInd");
	public static final Property<Short> MAX_ORDER_NUM = new Property<>("maxOrderNum");
	public static final Property<String> NO_DEL_DRAW_PRICE_IND = new Property<>("noDelDrawPriceInd");
	public static final Property<Integer> NO_OF_FORWARD_MONTHS = new Property<>("noOfForwardMonths");
	public static final Property<Integer> PORT_NUM = new Property<>("portNum");
	public static final Property<String> SPECIAL_CONTRACT_NUM = new Property<>("specialContractNum");
	public static final Property<Date> TRADE_MOD_DATE = new Property<>("tradeModDate");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<Boolean> USE_MTM = new Property<>("useMtm");
	public static final Property<Account> ACCOUNT = new Property<>("account");
	public static final Property<AccountContact> ACCOUNT_CONTACT = new Property<>("accountContact");
	public static final Property<AccountContact> ACCOUNT_CONTACT1 = new Property<>("accountContact1");
	public static final Property<ContractStatus> CONTRACT_STATUS = new Property<>("contractStatus");
	public static final Property<CreditTerm> CREDIT_TERM = new Property<>("creditTerm");
	public static final Property<IctsUser> ICTS_USER = new Property<>("ictsUser");
	public static final Property<IctsUser> ICTS_USER1 = new Property<>("ictsUser1");
	public static final Property<IctsUser> ICTS_USER2 = new Property<>("ictsUser2");
	public static final Property<IctsUser> ICTS_USER3 = new Property<>("ictsUser3");
	public static final Property<IctsProduct> PRODUCT = new Property<>("product");
	public static final Property<List<ReleaseDocument>> RELEASE_DOCUMENTS = new Property<>("releaseDocuments");
	public static final Property<List<TradeFeed>> TRADE_FEEDS = new Property<>("tradeFeeds");
	public static final Property<TradeStatus> TRADE_STATUS = new Property<>("tradeStatus");

	public void setAcctRefNum(final String acctRefNum)
	{
		this.writeProperty("acctRefNum", acctRefNum);
	}

	public String getAcctRefNum()
	{
		return (String) this.readProperty("acctRefNum");
	}

	public void setAcctShortName(final String acctShortName)
	{
		this.writeProperty("acctShortName", acctShortName);
	}

	public String getAcctShortName()
	{
		return (String) this.readProperty("acctShortName");
	}

	public void setCargoIdNumber(final String cargoIdNumber)
	{
		this.writeProperty("cargoIdNumber", cargoIdNumber);
	}

	public String getCargoIdNumber()
	{
		return (String) this.readProperty("cargoIdNumber");
	}

	public void setConcludedDate(final Date concludedDate)
	{
		this.writeProperty("concludedDate", concludedDate);
	}

	public Date getConcludedDate()
	{
		return (Date) this.readProperty("concludedDate");
	}

	public void setConclusionType(final String conclusionType)
	{
		this.writeProperty("conclusionType", conclusionType);
	}

	public String getConclusionType()
	{
		return (String) this.readProperty("conclusionType");
	}

	public void setContrAnlyInit(final String contrAnlyInit)
	{
		this.writeProperty("contrAnlyInit", contrAnlyInit);
	}

	public String getContrAnlyInit()
	{
		return (String) this.readProperty("contrAnlyInit");
	}

	public void setContrApprovType(final String contrApprovType)
	{
		this.writeProperty("contrApprovType", contrApprovType);
	}

	public String getContrApprovType()
	{
		return (String) this.readProperty("contrApprovType");
	}

	public void setContrCnfrmMethod(final String contrCnfrmMethod)
	{
		this.writeProperty("contrCnfrmMethod", contrCnfrmMethod);
	}

	public String getContrCnfrmMethod()
	{
		return (String) this.readProperty("contrCnfrmMethod");
	}

	public void setContrDate(final Date contrDate)
	{
		this.writeProperty("contrDate", contrDate);
	}

	public Date getContrDate()
	{
		return (Date) this.readProperty("contrDate");
	}

	public void setContrExchMethod(final String contrExchMethod)
	{
		this.writeProperty("contrExchMethod", contrExchMethod);
	}

	public String getContrExchMethod()
	{
		return (String) this.readProperty("contrExchMethod");
	}

	public void setContrTlxHoldInd(final String contrTlxHoldInd)
	{
		this.writeProperty("contrTlxHoldInd", contrTlxHoldInd);
	}

	public String getContrTlxHoldInd()
	{
		return (String) this.readProperty("contrTlxHoldInd");
	}

	public void setCopyType(final String copyType)
	{
		this.writeProperty("copyType", copyType);
	}

	public String getCopyType()
	{
		return (String) this.readProperty("copyType");
	}

	public void setCpGovContrInd(final String cpGovContrInd)
	{
		this.writeProperty("cpGovContrInd", cpGovContrInd);
	}

	public String getCpGovContrInd()
	{
		return (String) this.readProperty("cpGovContrInd");
	}

	public void setCreationDate(final Date creationDate)
	{
		this.writeProperty("creationDate", creationDate);
	}

	public Date getCreationDate()
	{
		return (Date) this.readProperty("creationDate");
	}

	public void setCreditResExpDate(final Date creditResExpDate)
	{
		this.writeProperty("creditResExpDate", creditResExpDate);
	}

	public Date getCreditResExpDate()
	{
		return (Date) this.readProperty("creditResExpDate");
	}

	public void setCreditStatus(final String creditStatus)
	{
		this.writeProperty("creditStatus", creditStatus);
	}

	public String getCreditStatus()
	{
		return (String) this.readProperty("creditStatus");
	}

	public void setEconfirmStatus(final String econfirmStatus)
	{
		this.writeProperty("econfirmStatus", econfirmStatus);
	}

	public String getEconfirmStatus()
	{
		return (String) this.readProperty("econfirmStatus");
	}

	public void setExternalTradeType(final String externalTradeType)
	{
		this.writeProperty("externalTradeType", externalTradeType);
	}

	public String getExternalTradeType()
	{
		return (String) this.readProperty("externalTradeType");
	}

	public void setInhouseInd(final String inhouseInd)
	{
		this.writeProperty("inhouseInd", inhouseInd);
	}

	public String getInhouseInd()
	{
		return (String) this.readProperty("inhouseInd");
	}

	public void setInternalAgreementInd(final String internalAgreementInd)
	{
		this.writeProperty("internalAgreementInd", internalAgreementInd);
	}

	public String getInternalAgreementInd()
	{
		return (String) this.readProperty("internalAgreementInd");
	}

	public void setInternalParentTradeNum(final Integer internalParentTradeNum)
	{
		this.writeProperty("internalParentTradeNum", internalParentTradeNum);
	}

	public Integer getInternalParentTradeNum()
	{
		return (Integer) this.readProperty("internalParentTradeNum");
	}

	public void setInvPricingType(final String invPricingType)
	{
		this.writeProperty("invPricingType", invPricingType);
	}

	public String getInvPricingType()
	{
		return (String) this.readProperty("invPricingType");
	}

	public void setInventoryType(final String inventoryType)
	{
		this.writeProperty("inventoryType", inventoryType);
	}

	public String getInventoryType()
	{
		return (String) this.readProperty("inventoryType");
	}

	public void setInvoiceCapType(final String invoiceCapType)
	{
		this.writeProperty("invoiceCapType", invoiceCapType);
	}

	public String getInvoiceCapType()
	{
		return (String) this.readProperty("invoiceCapType");
	}

	public void setIsLongTermInd(final String isLongTermInd)
	{
		this.writeProperty("isLongTermInd", isLongTermInd);
	}

	public String getIsLongTermInd()
	{
		return (String) this.readProperty("isLongTermInd");
	}

	public void setMaxOrderNum(final Short maxOrderNum)
	{
		this.writeProperty("maxOrderNum", maxOrderNum);
	}

	public Short getMaxOrderNum()
	{
		return (Short) this.readProperty("maxOrderNum");
	}

	public void setNoDelDrawPriceInd(final String noDelDrawPriceInd)
	{
		this.writeProperty("noDelDrawPriceInd", noDelDrawPriceInd);
	}

	public String getNoDelDrawPriceInd()
	{
		return (String) this.readProperty("noDelDrawPriceInd");
	}

	public void setNoOfForwardMonths(final Integer noOfForwardMonths)
	{
		this.writeProperty("noOfForwardMonths", noOfForwardMonths);
	}

	public Integer getNoOfForwardMonths()
	{
		return (Integer) this.readProperty("noOfForwardMonths");
	}

	public void setPortNum(final Integer portNum)
	{
		this.writeProperty("portNum", portNum);
	}

	public Integer getPortNum()
	{
		return (Integer) this.readProperty("portNum");
	}

	public void setSpecialContractNum(final String specialContractNum)
	{
		this.writeProperty("specialContractNum", specialContractNum);
	}

	public String getSpecialContractNum()
	{
		return (String) this.readProperty("specialContractNum");
	}

	public void setTradeModDate(final Date tradeModDate)
	{
		this.writeProperty("tradeModDate", tradeModDate);
	}

	public Date getTradeModDate()
	{
		return (Date) this.readProperty("tradeModDate");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setUseMtm(final Boolean useMtm)
	{
		this.writeProperty("useMtm", useMtm);
	}

	public Boolean getUseMtm()
	{
		return (Boolean) this.readProperty("useMtm");
	}

	public void setAccount(final Account account)
	{
		this.setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) this.readProperty("account");
	}

	public void setAccountContact(final AccountContact accountContact)
	{
		this.setToOneTarget("accountContact", accountContact, true);
	}

	public AccountContact getAccountContact()
	{
		return (AccountContact) this.readProperty("accountContact");
	}

	public void setAccountContact1(final AccountContact accountContact1)
	{
		this.setToOneTarget("accountContact1", accountContact1, true);
	}

	public AccountContact getAccountContact1()
	{
		return (AccountContact) this.readProperty("accountContact1");
	}

	public void setContractStatus(final ContractStatus contractStatus)
	{
		this.setToOneTarget("contractStatus", contractStatus, true);
	}

	public ContractStatus getContractStatus()
	{
		return (ContractStatus) this.readProperty("contractStatus");
	}

	public void setCreditTerm(final CreditTerm creditTerm)
	{
		this.setToOneTarget("creditTerm", creditTerm, true);
	}

	public CreditTerm getCreditTerm()
	{
		return (CreditTerm) this.readProperty("creditTerm");
	}

	public void setIctsUser(final IctsUser ictsUser)
	{
		this.setToOneTarget("ictsUser", ictsUser, true);
	}

	public IctsUser getIctsUser()
	{
		return (IctsUser) this.readProperty("ictsUser");
	}

	public void setIctsUser1(final IctsUser ictsUser1)
	{
		this.setToOneTarget("ictsUser1", ictsUser1, true);
	}

	public IctsUser getIctsUser1()
	{
		return (IctsUser) this.readProperty("ictsUser1");
	}

	public void setIctsUser2(final IctsUser ictsUser2)
	{
		this.setToOneTarget("ictsUser2", ictsUser2, true);
	}

	public IctsUser getIctsUser2()
	{
		return (IctsUser) this.readProperty("ictsUser2");
	}

	public void setIctsUser3(final IctsUser ictsUser3)
	{
		this.setToOneTarget("ictsUser3", ictsUser3, true);
	}

	public IctsUser getIctsUser3()
	{
		return (IctsUser) this.readProperty("ictsUser3");
	}

	public void setProduct(final IctsProduct product)
	{
		this.setToOneTarget("product", product, true);
	}

	public IctsProduct getProduct()
	{
		return (IctsProduct) this.readProperty("product");
	}

	public void addToReleaseDocuments(final ReleaseDocument obj)
	{
		this.addToManyTarget("releaseDocuments", obj, true);
	}

	public void removeFromReleaseDocuments(final ReleaseDocument obj)
	{
		this.removeToManyTarget("releaseDocuments", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<ReleaseDocument> getReleaseDocuments()
	{
		return (List<ReleaseDocument>) this.readProperty("releaseDocuments");
	}

	public void addToTradeFeeds(final TradeFeed obj)
	{
		this.addToManyTarget("tradeFeeds", obj, true);
	}

	public void removeFromTradeFeeds(final TradeFeed obj)
	{
		this.removeToManyTarget("tradeFeeds", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<TradeFeed> getTradeFeeds()
	{
		return (List<TradeFeed>) this.readProperty("tradeFeeds");
	}

	public void setTradeStatus(final TradeStatus tradeStatus)
	{
		this.setToOneTarget("tradeStatus", tradeStatus, true);
	}

	public TradeStatus getTradeStatus()
	{
		return (TradeStatus) this.readProperty("tradeStatus");
	}

}
