package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CreditTerm;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PaymentTerm;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TimeZone;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _TradeItemOtcOpt was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TradeItemOtcOpt extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ITEM_NUM_PK_COLUMN = "item_num";
	public static final String ORDER_NUM_PK_COLUMN = "order_num";
	public static final String TRADE_NUM_PK_COLUMN = "trade_num";

	public static final Property<String> APO_SPECIAL_COND_CODE = new Property<>("apoSpecialCondCode");
	public static final Property<String> DESIRED_OPT_EVAL_METHOD = new Property<>("desiredOptEvalMethod");
	public static final Property<String> DESIRED_OTC_OPT_CODE = new Property<>("desiredOtcOptCode");
	public static final Property<Date> EXP_DATE = new Property<>("expDate");
	public static final Property<String> LOOKBACK_COND_CODE = new Property<>("lookbackCondCode");
	public static final Property<Date> LOOKBACK_LAST_DATE = new Property<>("lookbackLastDate");
	public static final Property<String> OPT_TYPE = new Property<>("optType");
	public static final Property<Double> PREMIUM = new Property<>("premium");
	public static final Property<Date> PREMIUM_PAY_DATE = new Property<>("premiumPayDate");
	public static final Property<Date> PRICE_DATE_FROM = new Property<>("priceDateFrom");
	public static final Property<Date> PRICE_DATE_TO = new Property<>("priceDateTo");
	public static final Property<String> PUT_CALL_IND = new Property<>("putCallInd");
	public static final Property<String> SETTLEMENT_TYPE = new Property<>("settlementType");
	public static final Property<Date> STRIKE_EXCER_DATE = new Property<>("strikeExcerDate");
	public static final Property<Double> STRIKE_PRICE = new Property<>("strikePrice");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<Commodity> COMMODITY = new Property<>("commodity");
	public static final Property<Commodity> COMMODITY1 = new Property<>("commodity1");
	public static final Property<CreditTerm> CREDIT_TERM = new Property<>("creditTerm");
	public static final Property<PaymentTerm> PAYMENT_TERM = new Property<>("paymentTerm");
	public static final Property<TimeZone> TIME_ZONE = new Property<>("timeZone");
	public static final Property<Uom> UOM = new Property<>("uom");
	public static final Property<Uom> UOM1 = new Property<>("uom1");

	public void setApoSpecialCondCode(final String apoSpecialCondCode)
	{
		this.writeProperty("apoSpecialCondCode", apoSpecialCondCode);
	}

	public String getApoSpecialCondCode()
	{
		return (String) this.readProperty("apoSpecialCondCode");
	}

	public void setDesiredOptEvalMethod(final String desiredOptEvalMethod)
	{
		this.writeProperty("desiredOptEvalMethod", desiredOptEvalMethod);
	}

	public String getDesiredOptEvalMethod()
	{
		return (String) this.readProperty("desiredOptEvalMethod");
	}

	public void setDesiredOtcOptCode(final String desiredOtcOptCode)
	{
		this.writeProperty("desiredOtcOptCode", desiredOtcOptCode);
	}

	public String getDesiredOtcOptCode()
	{
		return (String) this.readProperty("desiredOtcOptCode");
	}

	public void setExpDate(final Date expDate)
	{
		this.writeProperty("expDate", expDate);
	}

	public Date getExpDate()
	{
		return (Date) this.readProperty("expDate");
	}

	public void setLookbackCondCode(final String lookbackCondCode)
	{
		this.writeProperty("lookbackCondCode", lookbackCondCode);
	}

	public String getLookbackCondCode()
	{
		return (String) this.readProperty("lookbackCondCode");
	}

	public void setLookbackLastDate(final Date lookbackLastDate)
	{
		this.writeProperty("lookbackLastDate", lookbackLastDate);
	}

	public Date getLookbackLastDate()
	{
		return (Date) this.readProperty("lookbackLastDate");
	}

	public void setOptType(final String optType)
	{
		this.writeProperty("optType", optType);
	}

	public String getOptType()
	{
		return (String) this.readProperty("optType");
	}

	public void setPremium(final Double premium)
	{
		this.writeProperty("premium", premium);
	}

	public Double getPremium()
	{
		return (Double) this.readProperty("premium");
	}

	public void setPremiumPayDate(final Date premiumPayDate)
	{
		this.writeProperty("premiumPayDate", premiumPayDate);
	}

	public Date getPremiumPayDate()
	{
		return (Date) this.readProperty("premiumPayDate");
	}

	public void setPriceDateFrom(final Date priceDateFrom)
	{
		this.writeProperty("priceDateFrom", priceDateFrom);
	}

	public Date getPriceDateFrom()
	{
		return (Date) this.readProperty("priceDateFrom");
	}

	public void setPriceDateTo(final Date priceDateTo)
	{
		this.writeProperty("priceDateTo", priceDateTo);
	}

	public Date getPriceDateTo()
	{
		return (Date) this.readProperty("priceDateTo");
	}

	public void setPutCallInd(final String putCallInd)
	{
		this.writeProperty("putCallInd", putCallInd);
	}

	public String getPutCallInd()
	{
		return (String) this.readProperty("putCallInd");
	}

	public void setSettlementType(final String settlementType)
	{
		this.writeProperty("settlementType", settlementType);
	}

	public String getSettlementType()
	{
		return (String) this.readProperty("settlementType");
	}

	public void setStrikeExcerDate(final Date strikeExcerDate)
	{
		this.writeProperty("strikeExcerDate", strikeExcerDate);
	}

	public Date getStrikeExcerDate()
	{
		return (Date) this.readProperty("strikeExcerDate");
	}

	public void setStrikePrice(final Double strikePrice)
	{
		this.writeProperty("strikePrice", strikePrice);
	}

	public Double getStrikePrice()
	{
		return (Double) this.readProperty("strikePrice");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setCommodity(final Commodity commodity)
	{
		this.setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) this.readProperty("commodity");
	}

	public void setCommodity1(final Commodity commodity1)
	{
		this.setToOneTarget("commodity1", commodity1, true);
	}

	public Commodity getCommodity1()
	{
		return (Commodity) this.readProperty("commodity1");
	}

	public void setCreditTerm(final CreditTerm creditTerm)
	{
		this.setToOneTarget("creditTerm", creditTerm, true);
	}

	public CreditTerm getCreditTerm()
	{
		return (CreditTerm) this.readProperty("creditTerm");
	}

	public void setPaymentTerm(final PaymentTerm paymentTerm)
	{
		this.setToOneTarget("paymentTerm", paymentTerm, true);
	}

	public PaymentTerm getPaymentTerm()
	{
		return (PaymentTerm) this.readProperty("paymentTerm");
	}

	public void setTimeZone(final TimeZone timeZone)
	{
		this.setToOneTarget("timeZone", timeZone, true);
	}

	public TimeZone getTimeZone()
	{
		return (TimeZone) this.readProperty("timeZone");
	}

	public void setUom(final Uom uom)
	{
		this.setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) this.readProperty("uom");
	}

	public void setUom1(final Uom uom1)
	{
		this.setToOneTarget("uom1", uom1, true);
	}

	public Uom getUom1()
	{
		return (Uom) this.readProperty("uom1");
	}

}
