package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Specification;
import com.tc.app.exchangemonitor.model.cayenne.persistent.TradingPeriod;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _TradeItemDist was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TradeItemDist extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String DIST_NUM_PK_COLUMN = "dist_num";

	public static final Property<Short> ACCUM_NUM = new Property<Short>("accumNum");
	public static final Property<Double> ADDL_COST_SUM = new Property<Double>("addlCostSum");
	public static final Property<Double> ALLOC_QTY = new Property<Double>("allocQty");
	public static final Property<Date> BUS_DATE = new Property<Date>("busDate");
	public static final Property<Double> CLOSED_PL = new Property<Double>("closedPl");
	public static final Property<Double> DELIVERED_QTY = new Property<Double>("deliveredQty");
	public static final Property<Double> DISCOUNT_QTY = new Property<Double>("discountQty");
	public static final Property<Double> DIST_QTY = new Property<Double>("distQty");
	public static final Property<String> DIST_TYPE = new Property<String>("distType");
	public static final Property<String> EQUIV_SOURCE_IND = new Property<String>("equivSourceInd");
	public static final Property<BigDecimal> ESTIMATE_QTY = new Property<BigDecimal>("estimateQty");
	public static final Property<Double> FLOAT_VALUE = new Property<Double>("floatValue");
	public static final Property<Integer> FORMULA_BODY_NUM = new Property<Integer>("formulaBodyNum");
	public static final Property<Integer> FORMULA_NUM = new Property<Integer>("formulaNum");
	public static final Property<Integer> INT_VALUE = new Property<Integer>("intValue");
	public static final Property<String> IS_EQUIV_IND = new Property<String>("isEquivInd");
	public static final Property<Short> ITEM_NUM = new Property<Short>("itemNum");
	public static final Property<Double> OPEN_PL = new Property<Double>("openPl");
	public static final Property<Short> ORDER_NUM = new Property<Short>("orderNum");
	public static final Property<String> P_SIND = new Property<String>("pSInd");
	public static final Property<Integer> PARCEL_NUM = new Property<Integer>("parcelNum");
	public static final Property<Integer> PARENT_DIST_NUM = new Property<Integer>("parentDistNum");
	public static final Property<Date> PL_ASOF_DATE = new Property<Date>("plAsofDate");
	public static final Property<Integer> POS_NUM = new Property<Integer>("posNum");
	public static final Property<Double> PRICE_CURR_CONV_RATE = new Property<Double>("priceCurrConvRate");
	public static final Property<Double> PRICE_UOM_CONV_RATE = new Property<Double>("priceUomConvRate");
	public static final Property<Double> PRICED_QTY = new Property<Double>("pricedQty");
	public static final Property<Short> QPP_NUM = new Property<Short>("qppNum");
	public static final Property<Double> QTY_UOM_CONV_RATE = new Property<Double>("qtyUomConvRate");
	public static final Property<Integer> REAL_PORT_NUM = new Property<Integer>("realPortNum");
	public static final Property<String> REAL_SYNTH_IND = new Property<String>("realSynthInd");
	public static final Property<Double> SEC_CONVERSION_FACTOR = new Property<Double>("secConversionFactor");
	public static final Property<Integer> SPREAD_POS_GROUP_NUM = new Property<Integer>("spreadPosGroupNum");
	public static final Property<String> STRING_VALUE = new Property<String>("stringValue");
	public static final Property<Integer> TRADE_NUM = new Property<Integer>("tradeNum");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<String> WHAT_IF_IND = new Property<String>("whatIfInd");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<Specification> SPECIFICATION = new Property<Specification>("specification");
	public static final Property<TradingPeriod> TRADING_PERIOD = new Property<TradingPeriod>("tradingPeriod");
	public static final Property<TradingPeriod> TRADING_PERIOD1 = new Property<TradingPeriod>("tradingPeriod1");
	public static final Property<Uom> UOM = new Property<Uom>("uom");
	public static final Property<Uom> UOM1 = new Property<Uom>("uom1");
	public static final Property<Uom> UOM2 = new Property<Uom>("uom2");
	public static final Property<Uom> UOM3 = new Property<Uom>("uom3");

	public void setAccumNum(Short accumNum)
	{
		writeProperty("accumNum", accumNum);
	}

	public Short getAccumNum()
	{
		return (Short) readProperty("accumNum");
	}

	public void setAddlCostSum(Double addlCostSum)
	{
		writeProperty("addlCostSum", addlCostSum);
	}

	public Double getAddlCostSum()
	{
		return (Double) readProperty("addlCostSum");
	}

	public void setAllocQty(Double allocQty)
	{
		writeProperty("allocQty", allocQty);
	}

	public Double getAllocQty()
	{
		return (Double) readProperty("allocQty");
	}

	public void setBusDate(Date busDate)
	{
		writeProperty("busDate", busDate);
	}

	public Date getBusDate()
	{
		return (Date) readProperty("busDate");
	}

	public void setClosedPl(Double closedPl)
	{
		writeProperty("closedPl", closedPl);
	}

	public Double getClosedPl()
	{
		return (Double) readProperty("closedPl");
	}

	public void setDeliveredQty(Double deliveredQty)
	{
		writeProperty("deliveredQty", deliveredQty);
	}

	public Double getDeliveredQty()
	{
		return (Double) readProperty("deliveredQty");
	}

	public void setDiscountQty(Double discountQty)
	{
		writeProperty("discountQty", discountQty);
	}

	public Double getDiscountQty()
	{
		return (Double) readProperty("discountQty");
	}

	public void setDistQty(Double distQty)
	{
		writeProperty("distQty", distQty);
	}

	public Double getDistQty()
	{
		return (Double) readProperty("distQty");
	}

	public void setDistType(String distType)
	{
		writeProperty("distType", distType);
	}

	public String getDistType()
	{
		return (String) readProperty("distType");
	}

	public void setEquivSourceInd(String equivSourceInd)
	{
		writeProperty("equivSourceInd", equivSourceInd);
	}

	public String getEquivSourceInd()
	{
		return (String) readProperty("equivSourceInd");
	}

	public void setEstimateQty(BigDecimal estimateQty)
	{
		writeProperty("estimateQty", estimateQty);
	}

	public BigDecimal getEstimateQty()
	{
		return (BigDecimal) readProperty("estimateQty");
	}

	public void setFloatValue(Double floatValue)
	{
		writeProperty("floatValue", floatValue);
	}

	public Double getFloatValue()
	{
		return (Double) readProperty("floatValue");
	}

	public void setFormulaBodyNum(Integer formulaBodyNum)
	{
		writeProperty("formulaBodyNum", formulaBodyNum);
	}

	public Integer getFormulaBodyNum()
	{
		return (Integer) readProperty("formulaBodyNum");
	}

	public void setFormulaNum(Integer formulaNum)
	{
		writeProperty("formulaNum", formulaNum);
	}

	public Integer getFormulaNum()
	{
		return (Integer) readProperty("formulaNum");
	}

	public void setIntValue(Integer intValue)
	{
		writeProperty("intValue", intValue);
	}

	public Integer getIntValue()
	{
		return (Integer) readProperty("intValue");
	}

	public void setIsEquivInd(String isEquivInd)
	{
		writeProperty("isEquivInd", isEquivInd);
	}

	public String getIsEquivInd()
	{
		return (String) readProperty("isEquivInd");
	}

	public void setItemNum(Short itemNum)
	{
		writeProperty("itemNum", itemNum);
	}

	public Short getItemNum()
	{
		return (Short) readProperty("itemNum");
	}

	public void setOpenPl(Double openPl)
	{
		writeProperty("openPl", openPl);
	}

	public Double getOpenPl()
	{
		return (Double) readProperty("openPl");
	}

	public void setOrderNum(Short orderNum)
	{
		writeProperty("orderNum", orderNum);
	}

	public Short getOrderNum()
	{
		return (Short) readProperty("orderNum");
	}

	public void setPSInd(String pSInd)
	{
		writeProperty("pSInd", pSInd);
	}

	public String getPSInd()
	{
		return (String) readProperty("pSInd");
	}

	public void setParcelNum(Integer parcelNum)
	{
		writeProperty("parcelNum", parcelNum);
	}

	public Integer getParcelNum()
	{
		return (Integer) readProperty("parcelNum");
	}

	public void setParentDistNum(Integer parentDistNum)
	{
		writeProperty("parentDistNum", parentDistNum);
	}

	public Integer getParentDistNum()
	{
		return (Integer) readProperty("parentDistNum");
	}

	public void setPlAsofDate(Date plAsofDate)
	{
		writeProperty("plAsofDate", plAsofDate);
	}

	public Date getPlAsofDate()
	{
		return (Date) readProperty("plAsofDate");
	}

	public void setPosNum(Integer posNum)
	{
		writeProperty("posNum", posNum);
	}

	public Integer getPosNum()
	{
		return (Integer) readProperty("posNum");
	}

	public void setPriceCurrConvRate(Double priceCurrConvRate)
	{
		writeProperty("priceCurrConvRate", priceCurrConvRate);
	}

	public Double getPriceCurrConvRate()
	{
		return (Double) readProperty("priceCurrConvRate");
	}

	public void setPriceUomConvRate(Double priceUomConvRate)
	{
		writeProperty("priceUomConvRate", priceUomConvRate);
	}

	public Double getPriceUomConvRate()
	{
		return (Double) readProperty("priceUomConvRate");
	}

	public void setPricedQty(Double pricedQty)
	{
		writeProperty("pricedQty", pricedQty);
	}

	public Double getPricedQty()
	{
		return (Double) readProperty("pricedQty");
	}

	public void setQppNum(Short qppNum)
	{
		writeProperty("qppNum", qppNum);
	}

	public Short getQppNum()
	{
		return (Short) readProperty("qppNum");
	}

	public void setQtyUomConvRate(Double qtyUomConvRate)
	{
		writeProperty("qtyUomConvRate", qtyUomConvRate);
	}

	public Double getQtyUomConvRate()
	{
		return (Double) readProperty("qtyUomConvRate");
	}

	public void setRealPortNum(Integer realPortNum)
	{
		writeProperty("realPortNum", realPortNum);
	}

	public Integer getRealPortNum()
	{
		return (Integer) readProperty("realPortNum");
	}

	public void setRealSynthInd(String realSynthInd)
	{
		writeProperty("realSynthInd", realSynthInd);
	}

	public String getRealSynthInd()
	{
		return (String) readProperty("realSynthInd");
	}

	public void setSecConversionFactor(Double secConversionFactor)
	{
		writeProperty("secConversionFactor", secConversionFactor);
	}

	public Double getSecConversionFactor()
	{
		return (Double) readProperty("secConversionFactor");
	}

	public void setSpreadPosGroupNum(Integer spreadPosGroupNum)
	{
		writeProperty("spreadPosGroupNum", spreadPosGroupNum);
	}

	public Integer getSpreadPosGroupNum()
	{
		return (Integer) readProperty("spreadPosGroupNum");
	}

	public void setStringValue(String stringValue)
	{
		writeProperty("stringValue", stringValue);
	}

	public String getStringValue()
	{
		return (String) readProperty("stringValue");
	}

	public void setTradeNum(Integer tradeNum)
	{
		writeProperty("tradeNum", tradeNum);
	}

	public Integer getTradeNum()
	{
		return (Integer) readProperty("tradeNum");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setWhatIfInd(String whatIfInd)
	{
		writeProperty("whatIfInd", whatIfInd);
	}

	public String getWhatIfInd()
	{
		return (String) readProperty("whatIfInd");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setSpecification(Specification specification)
	{
		setToOneTarget("specification", specification, true);
	}

	public Specification getSpecification()
	{
		return (Specification) readProperty("specification");
	}

	public void setTradingPeriod(TradingPeriod tradingPeriod)
	{
		setToOneTarget("tradingPeriod", tradingPeriod, true);
	}

	public TradingPeriod getTradingPeriod()
	{
		return (TradingPeriod) readProperty("tradingPeriod");
	}

	public void setTradingPeriod1(TradingPeriod tradingPeriod1)
	{
		setToOneTarget("tradingPeriod1", tradingPeriod1, true);
	}

	public TradingPeriod getTradingPeriod1()
	{
		return (TradingPeriod) readProperty("tradingPeriod1");
	}

	public void setUom(Uom uom)
	{
		setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) readProperty("uom");
	}

	public void setUom1(Uom uom1)
	{
		setToOneTarget("uom1", uom1, true);
	}

	public Uom getUom1()
	{
		return (Uom) readProperty("uom1");
	}

	public void setUom2(Uom uom2)
	{
		setToOneTarget("uom2", uom2, true);
	}

	public Uom getUom2()
	{
		return (Uom) readProperty("uom2");
	}

	public void setUom3(Uom uom3)
	{
		setToOneTarget("uom3", uom3, true);
	}

	public Uom getUom3()
	{
		return (Uom) readProperty("uom3");
	}

}
