package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsEntityName;
import com.tc.app.exchangemonitor.model.cayenne.persistent.UicReportType;
import com.tc.app.exchangemonitor.model.cayenne.persistent.UicRptCriteriaEntity;

/**
 * Class _UicRptCriteria was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _UicRptCriteria extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> CRITERIA_DESC = new Property<String>("criteriaDesc");
	public static final Property<String> DISPLAY_VALUE_SELECTOR = new Property<String>("displayValueSelector");
	public static final Property<String> REPORT_VALUE_SELECTOR = new Property<String>("reportValueSelector");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<IctsEntityName> DISPLAY_ENTITY = new Property<IctsEntityName>("displayEntity");
	public static final Property<UicReportType> REPORT_TYPE = new Property<UicReportType>("reportType");
	public static final Property<List<UicRptCriteriaEntity>> UIC_RPT_CRITERIA_ENTITIES = new Property<List<UicRptCriteriaEntity>>("uicRptCriteriaEntities");

	public void setCriteriaDesc(String criteriaDesc)
	{
		writeProperty("criteriaDesc", criteriaDesc);
	}

	public String getCriteriaDesc()
	{
		return (String) readProperty("criteriaDesc");
	}

	public void setDisplayValueSelector(String displayValueSelector)
	{
		writeProperty("displayValueSelector", displayValueSelector);
	}

	public String getDisplayValueSelector()
	{
		return (String) readProperty("displayValueSelector");
	}

	public void setReportValueSelector(String reportValueSelector)
	{
		writeProperty("reportValueSelector", reportValueSelector);
	}

	public String getReportValueSelector()
	{
		return (String) readProperty("reportValueSelector");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setDisplayEntity(IctsEntityName displayEntity)
	{
		setToOneTarget("displayEntity", displayEntity, true);
	}

	public IctsEntityName getDisplayEntity()
	{
		return (IctsEntityName) readProperty("displayEntity");
	}

	public void setReportType(UicReportType reportType)
	{
		setToOneTarget("reportType", reportType, true);
	}

	public UicReportType getReportType()
	{
		return (UicReportType) readProperty("reportType");
	}

	public void addToUicRptCriteriaEntities(UicRptCriteriaEntity obj)
	{
		addToManyTarget("uicRptCriteriaEntities", obj, true);
	}

	public void removeFromUicRptCriteriaEntities(UicRptCriteriaEntity obj)
	{
		removeToManyTarget("uicRptCriteriaEntities", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<UicRptCriteriaEntity> getUicRptCriteriaEntities()
	{
		return (List<UicRptCriteriaEntity>) readProperty("uicRptCriteriaEntities");
	}

}
