package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _VarLimit was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VarLimit extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<BigDecimal> CONFIDENCE_LEVEL = new Property<BigDecimal>("confidenceLevel");
	public static final Property<Integer> HORIZON = new Property<Integer>("horizon");
	public static final Property<Date> LAST_UPDATE_DATE = new Property<Date>("lastUpdateDate");
	public static final Property<String> LIMIT_TYPE = new Property<String>("limitType");
	public static final Property<String> PORT_NUM_LIST = new Property<String>("portNumList");
	public static final Property<String> USER_INIT = new Property<String>("userInit");
	public static final Property<Double> VAR_LIMIT = new Property<Double>("varLimit");
	public static final Property<String> VAR_LIMIT_CURR_CODE = new Property<String>("varLimitCurrCode");

	public void setConfidenceLevel(BigDecimal confidenceLevel)
	{
		writeProperty("confidenceLevel", confidenceLevel);
	}

	public BigDecimal getConfidenceLevel()
	{
		return (BigDecimal) readProperty("confidenceLevel");
	}

	public void setHorizon(Integer horizon)
	{
		writeProperty("horizon", horizon);
	}

	public Integer getHorizon()
	{
		return (Integer) readProperty("horizon");
	}

	public void setLastUpdateDate(Date lastUpdateDate)
	{
		writeProperty("lastUpdateDate", lastUpdateDate);
	}

	public Date getLastUpdateDate()
	{
		return (Date) readProperty("lastUpdateDate");
	}

	public void setLimitType(String limitType)
	{
		writeProperty("limitType", limitType);
	}

	public String getLimitType()
	{
		return (String) readProperty("limitType");
	}

	public void setPortNumList(String portNumList)
	{
		writeProperty("portNumList", portNumList);
	}

	public String getPortNumList()
	{
		return (String) readProperty("portNumList");
	}

	public void setUserInit(String userInit)
	{
		writeProperty("userInit", userInit);
	}

	public String getUserInit()
	{
		return (String) readProperty("userInit");
	}

	public void setVarLimit(Double varLimit)
	{
		writeProperty("varLimit", varLimit);
	}

	public Double getVarLimit()
	{
		return (Double) readProperty("varLimit");
	}

	public void setVarLimitCurrCode(String varLimitCurrCode)
	{
		writeProperty("varLimitCurrCode", varLimitCurrCode);
	}

	public String getVarLimitCurrCode()
	{
		return (String) readProperty("varLimitCurrCode");
	}

}
