package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.CommodityMarket;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PriceSource;

/**
 * Class _VarfeedBeta was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VarfeedBeta extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String COMMKT_KEY_PK_COLUMN = "commkt_key";
	public static final String PRICE_SOURCE_CODE_PK_COLUMN = "price_source_code";
	public static final String VAL_TYPE_PK_COLUMN = "val_type";

	public static final Property<BigDecimal> PRICE_BETA = new Property<BigDecimal>("priceBeta");
	public static final Property<String> RISK_FACTOR = new Property<String>("riskFactor");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<BigDecimal> VOL_BETA = new Property<BigDecimal>("volBeta");
	public static final Property<CommodityMarket> COMMODITY_MARKET = new Property<CommodityMarket>("commodityMarket");
	public static final Property<PriceSource> PRICE_SOURCE = new Property<PriceSource>("priceSource");

	public void setPriceBeta(BigDecimal priceBeta)
	{
		writeProperty("priceBeta", priceBeta);
	}

	public BigDecimal getPriceBeta()
	{
		return (BigDecimal) readProperty("priceBeta");
	}

	public void setRiskFactor(String riskFactor)
	{
		writeProperty("riskFactor", riskFactor);
	}

	public String getRiskFactor()
	{
		return (String) readProperty("riskFactor");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setVolBeta(BigDecimal volBeta)
	{
		writeProperty("volBeta", volBeta);
	}

	public BigDecimal getVolBeta()
	{
		return (BigDecimal) readProperty("volBeta");
	}

	public void setCommodityMarket(CommodityMarket commodityMarket)
	{
		setToOneTarget("commodityMarket", commodityMarket, true);
	}

	public CommodityMarket getCommodityMarket()
	{
		return (CommodityMarket) readProperty("commodityMarket");
	}

	public void setPriceSource(PriceSource priceSource)
	{
		setToOneTarget("priceSource", priceSource, true);
	}

	public PriceSource getPriceSource()
	{
		return (PriceSource) readProperty("priceSource");
	}

}
