package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.VarRun;

/**
 * Class _VarOutput was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VarOutput extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String OID_PK_COLUMN = "oid";

	public static final Property<String> BUCKET_TAG = new Property<String>("bucketTag");
	public static final Property<Integer> BUCKET_TYPE = new Property<Integer>("bucketType");
	public static final Property<BigDecimal> CONFIDENCE_LEVEL = new Property<BigDecimal>("confidenceLevel");
	public static final Property<BigDecimal> CVAR_AMOUNT = new Property<BigDecimal>("cvarAmount");
	public static final Property<String> PORT_RUN_LIST = new Property<String>("portRunList");
	public static final Property<BigDecimal> VAR_AMOUNT = new Property<BigDecimal>("varAmount");
	public static final Property<Date> VAR_PERIOD = new Property<Date>("varPeriod");
	public static final Property<VarRun> VAR_RUN = new Property<VarRun>("varRun");

	public void setBucketTag(String bucketTag)
	{
		writeProperty("bucketTag", bucketTag);
	}

	public String getBucketTag()
	{
		return (String) readProperty("bucketTag");
	}

	public void setBucketType(Integer bucketType)
	{
		writeProperty("bucketType", bucketType);
	}

	public Integer getBucketType()
	{
		return (Integer) readProperty("bucketType");
	}

	public void setConfidenceLevel(BigDecimal confidenceLevel)
	{
		writeProperty("confidenceLevel", confidenceLevel);
	}

	public BigDecimal getConfidenceLevel()
	{
		return (BigDecimal) readProperty("confidenceLevel");
	}

	public void setCvarAmount(BigDecimal cvarAmount)
	{
		writeProperty("cvarAmount", cvarAmount);
	}

	public BigDecimal getCvarAmount()
	{
		return (BigDecimal) readProperty("cvarAmount");
	}

	public void setPortRunList(String portRunList)
	{
		writeProperty("portRunList", portRunList);
	}

	public String getPortRunList()
	{
		return (String) readProperty("portRunList");
	}

	public void setVarAmount(BigDecimal varAmount)
	{
		writeProperty("varAmount", varAmount);
	}

	public BigDecimal getVarAmount()
	{
		return (BigDecimal) readProperty("varAmount");
	}

	public void setVarPeriod(Date varPeriod)
	{
		writeProperty("varPeriod", varPeriod);
	}

	public Date getVarPeriod()
	{
		return (Date) readProperty("varPeriod");
	}

	public void setVarRun(VarRun varRun)
	{
		setToOneTarget("varRun", varRun, true);
	}

	public VarRun getVarRun()
	{
		return (VarRun) readProperty("varRun");
	}

}
