package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.AiEstActualVat;
import com.tc.app.exchangemonitor.model.cayenne.persistent.AllocationItemVat;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Country;

/**
 * Class _VatDeclaration was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VatDeclaration extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String VAT_DECLARATION_ID_PK_COLUMN = "vat_declaration_id";

	public static final Property<String> DECLARATION = new Property<String>("declaration");
	public static final Property<String> DECLARATION_SHORT_NAME = new Property<String>("declarationShortName");
	public static final Property<Boolean> T1IND = new Property<Boolean>("t1Ind");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<List<AiEstActualVat>> AI_EST_ACTUAL_VATS = new Property<List<AiEstActualVat>>("aiEstActualVats");
	public static final Property<List<AllocationItemVat>> ALLOCATION_ITEM_VATS = new Property<List<AllocationItemVat>>("allocationItemVats");
	public static final Property<Country> COUNTRY = new Property<Country>("country");

	public void setDeclaration(String declaration)
	{
		writeProperty("declaration", declaration);
	}

	public String getDeclaration()
	{
		return (String) readProperty("declaration");
	}

	public void setDeclarationShortName(String declarationShortName)
	{
		writeProperty("declarationShortName", declarationShortName);
	}

	public String getDeclarationShortName()
	{
		return (String) readProperty("declarationShortName");
	}

	public void setT1Ind(Boolean t1Ind)
	{
		writeProperty("t1Ind", t1Ind);
	}

	public Boolean getT1Ind()
	{
		return (Boolean) readProperty("t1Ind");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void addToAiEstActualVats(AiEstActualVat obj)
	{
		addToManyTarget("aiEstActualVats", obj, true);
	}

	public void removeFromAiEstActualVats(AiEstActualVat obj)
	{
		removeToManyTarget("aiEstActualVats", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AiEstActualVat> getAiEstActualVats()
	{
		return (List<AiEstActualVat>) readProperty("aiEstActualVats");
	}

	public void addToAllocationItemVats(AllocationItemVat obj)
	{
		addToManyTarget("allocationItemVats", obj, true);
	}

	public void removeFromAllocationItemVats(AllocationItemVat obj)
	{
		removeToManyTarget("allocationItemVats", obj, true);
	}

	@SuppressWarnings("unchecked")
	public List<AllocationItemVat> getAllocationItemVats()
	{
		return (List<AllocationItemVat>) readProperty("allocationItemVats");
	}

	public void setCountry(Country country)
	{
		setToOneTarget("country", country, true);
	}

	public Country getCountry()
	{
		return (Country) readProperty("country");
	}

}
