package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _VCubePositionSnapshot was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VCubePositionSnapshot extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> BOOK = new Property<String>("book");
	public static final Property<Integer> BOOK_ENTITY_NUM = new Property<Integer>("bookEntityNum");
	public static final Property<String> CMDTY_CODE = new Property<String>("cmdtyCode");
	public static final Property<String> CMDTY_GROUP = new Property<String>("cmdtyGroup");
	public static final Property<String> CMDTY_SHORT_NAME = new Property<String>("cmdtyShortName");
	public static final Property<Integer> COMMKT_KEY = new Property<Integer>("commktKey");
	public static final Property<Date> CONTR_DATE = new Property<Date>("contrDate");
	public static final Property<String> CONTRACT_PSIND = new Property<String>("contractPSInd");
	public static final Property<Double> CONTRACT_QTY = new Property<Double>("contractQty");
	public static final Property<String> CONTRACT_QTY_UOM_CODE = new Property<String>("contractQtyUomCode");
	public static final Property<Integer> COUNTERPARTY = new Property<Integer>("counterparty");
	public static final Property<Integer> DIST_NUM = new Property<Integer>("distNum");
	public static final Property<String> GRID_POSITION_MONTH = new Property<String>("gridPositionMonth");
	public static final Property<String> GRID_POSITION_QTR = new Property<String>("gridPositionQtr");
	public static final Property<String> GRID_POSITION_YEAR = new Property<String>("gridPositionYear");
	public static final Property<String> INHOUSE_IND = new Property<String>("inhouseInd");
	public static final Property<String> IS_EQUIV_IND = new Property<String>("isEquivInd");
	public static final Property<String> IS_HEDGE_IND = new Property<String>("isHedgeInd");
	public static final Property<Date> LAST_ISSUE_DATE = new Property<Date>("lastIssueDate");
	public static final Property<Date> LAST_TRADE_DATE = new Property<Date>("lastTradeDate");
	public static final Property<String> MKT_CODE = new Property<String>("mktCode");
	public static final Property<String> MKT_SHORT_NAME = new Property<String>("mktShortName");
	public static final Property<String> MTM_PRICE_SOURCE_CODE = new Property<String>("mtmPriceSourceCode");
	public static final Property<String> ORDER_TYPE_CODE = new Property<String>("orderTypeCode");
	public static final Property<Integer> POS_NUM = new Property<Integer>("posNum");
	public static final Property<String> POS_QTY_UOM_CODE = new Property<String>("posQtyUomCode");
	public static final Property<String> POS_TYPE = new Property<String>("posType");
	public static final Property<String> POSITION_PSIND = new Property<String>("positionPSInd");
	public static final Property<String> POSTION_TYPE_DESC = new Property<String>("postionTypeDesc");
	public static final Property<Integer> PRICING_RISK_DATE = new Property<Integer>("pricingRiskDate");
	public static final Property<Double> PRIMARY_POS_QTY = new Property<Double>("primaryPosQty");
	public static final Property<Integer> PRODUCT = new Property<Integer>("product");
	public static final Property<String> PROFIT_CNTR = new Property<String>("profitCntr");
	public static final Property<Integer> REAL_PORT_NUM = new Property<Integer>("realPortNum");
	public static final Property<Double> SECONDARY_POS_QTY = new Property<Double>("secondaryPosQty");
	public static final Property<String> SECONDARY_QTY_UOM_CODE = new Property<String>("secondaryQtyUomCode");
	public static final Property<Date> TRADE_CREATION_DATE = new Property<Date>("tradeCreationDate");
	public static final Property<String> TRADE_KEY = new Property<String>("tradeKey");
	public static final Property<Date> TRADE_MOD_DATE = new Property<Date>("tradeModDate");
	public static final Property<Integer> TRADE_NUM = new Property<Integer>("tradeNum");
	public static final Property<String> TRADER_INIT = new Property<String>("traderInit");
	public static final Property<String> TRADING_ENTITY = new Property<String>("tradingEntity");
	public static final Property<String> TRADING_PRD = new Property<String>("tradingPrd");
	public static final Property<String> TRADING_PRD_DESC = new Property<String>("tradingPrdDesc");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setBook(String book)
	{
		writeProperty("book", book);
	}

	public String getBook()
	{
		return (String) readProperty("book");
	}

	public void setBookEntityNum(Integer bookEntityNum)
	{
		writeProperty("bookEntityNum", bookEntityNum);
	}

	public Integer getBookEntityNum()
	{
		return (Integer) readProperty("bookEntityNum");
	}

	public void setCmdtyCode(String cmdtyCode)
	{
		writeProperty("cmdtyCode", cmdtyCode);
	}

	public String getCmdtyCode()
	{
		return (String) readProperty("cmdtyCode");
	}

	public void setCmdtyGroup(String cmdtyGroup)
	{
		writeProperty("cmdtyGroup", cmdtyGroup);
	}

	public String getCmdtyGroup()
	{
		return (String) readProperty("cmdtyGroup");
	}

	public void setCmdtyShortName(String cmdtyShortName)
	{
		writeProperty("cmdtyShortName", cmdtyShortName);
	}

	public String getCmdtyShortName()
	{
		return (String) readProperty("cmdtyShortName");
	}

	public void setCommktKey(Integer commktKey)
	{
		writeProperty("commktKey", commktKey);
	}

	public Integer getCommktKey()
	{
		return (Integer) readProperty("commktKey");
	}

	public void setContrDate(Date contrDate)
	{
		writeProperty("contrDate", contrDate);
	}

	public Date getContrDate()
	{
		return (Date) readProperty("contrDate");
	}

	public void setContractPSInd(String contractPSInd)
	{
		writeProperty("contractPSInd", contractPSInd);
	}

	public String getContractPSInd()
	{
		return (String) readProperty("contractPSInd");
	}

	public void setContractQty(Double contractQty)
	{
		writeProperty("contractQty", contractQty);
	}

	public Double getContractQty()
	{
		return (Double) readProperty("contractQty");
	}

	public void setContractQtyUomCode(String contractQtyUomCode)
	{
		writeProperty("contractQtyUomCode", contractQtyUomCode);
	}

	public String getContractQtyUomCode()
	{
		return (String) readProperty("contractQtyUomCode");
	}

	public void setCounterparty(Integer counterparty)
	{
		writeProperty("counterparty", counterparty);
	}

	public Integer getCounterparty()
	{
		return (Integer) readProperty("counterparty");
	}

	public void setDistNum(Integer distNum)
	{
		writeProperty("distNum", distNum);
	}

	public Integer getDistNum()
	{
		return (Integer) readProperty("distNum");
	}

	public void setGridPositionMonth(String gridPositionMonth)
	{
		writeProperty("gridPositionMonth", gridPositionMonth);
	}

	public String getGridPositionMonth()
	{
		return (String) readProperty("gridPositionMonth");
	}

	public void setGridPositionQtr(String gridPositionQtr)
	{
		writeProperty("gridPositionQtr", gridPositionQtr);
	}

	public String getGridPositionQtr()
	{
		return (String) readProperty("gridPositionQtr");
	}

	public void setGridPositionYear(String gridPositionYear)
	{
		writeProperty("gridPositionYear", gridPositionYear);
	}

	public String getGridPositionYear()
	{
		return (String) readProperty("gridPositionYear");
	}

	public void setInhouseInd(String inhouseInd)
	{
		writeProperty("inhouseInd", inhouseInd);
	}

	public String getInhouseInd()
	{
		return (String) readProperty("inhouseInd");
	}

	public void setIsEquivInd(String isEquivInd)
	{
		writeProperty("isEquivInd", isEquivInd);
	}

	public String getIsEquivInd()
	{
		return (String) readProperty("isEquivInd");
	}

	public void setIsHedgeInd(String isHedgeInd)
	{
		writeProperty("isHedgeInd", isHedgeInd);
	}

	public String getIsHedgeInd()
	{
		return (String) readProperty("isHedgeInd");
	}

	public void setLastIssueDate(Date lastIssueDate)
	{
		writeProperty("lastIssueDate", lastIssueDate);
	}

	public Date getLastIssueDate()
	{
		return (Date) readProperty("lastIssueDate");
	}

	public void setLastTradeDate(Date lastTradeDate)
	{
		writeProperty("lastTradeDate", lastTradeDate);
	}

	public Date getLastTradeDate()
	{
		return (Date) readProperty("lastTradeDate");
	}

	public void setMktCode(String mktCode)
	{
		writeProperty("mktCode", mktCode);
	}

	public String getMktCode()
	{
		return (String) readProperty("mktCode");
	}

	public void setMktShortName(String mktShortName)
	{
		writeProperty("mktShortName", mktShortName);
	}

	public String getMktShortName()
	{
		return (String) readProperty("mktShortName");
	}

	public void setMtmPriceSourceCode(String mtmPriceSourceCode)
	{
		writeProperty("mtmPriceSourceCode", mtmPriceSourceCode);
	}

	public String getMtmPriceSourceCode()
	{
		return (String) readProperty("mtmPriceSourceCode");
	}

	public void setOrderTypeCode(String orderTypeCode)
	{
		writeProperty("orderTypeCode", orderTypeCode);
	}

	public String getOrderTypeCode()
	{
		return (String) readProperty("orderTypeCode");
	}

	public void setPosNum(Integer posNum)
	{
		writeProperty("posNum", posNum);
	}

	public Integer getPosNum()
	{
		return (Integer) readProperty("posNum");
	}

	public void setPosQtyUomCode(String posQtyUomCode)
	{
		writeProperty("posQtyUomCode", posQtyUomCode);
	}

	public String getPosQtyUomCode()
	{
		return (String) readProperty("posQtyUomCode");
	}

	public void setPosType(String posType)
	{
		writeProperty("posType", posType);
	}

	public String getPosType()
	{
		return (String) readProperty("posType");
	}

	public void setPositionPSInd(String positionPSInd)
	{
		writeProperty("positionPSInd", positionPSInd);
	}

	public String getPositionPSInd()
	{
		return (String) readProperty("positionPSInd");
	}

	public void setPostionTypeDesc(String postionTypeDesc)
	{
		writeProperty("postionTypeDesc", postionTypeDesc);
	}

	public String getPostionTypeDesc()
	{
		return (String) readProperty("postionTypeDesc");
	}

	public void setPricingRiskDate(Integer pricingRiskDate)
	{
		writeProperty("pricingRiskDate", pricingRiskDate);
	}

	public Integer getPricingRiskDate()
	{
		return (Integer) readProperty("pricingRiskDate");
	}

	public void setPrimaryPosQty(Double primaryPosQty)
	{
		writeProperty("primaryPosQty", primaryPosQty);
	}

	public Double getPrimaryPosQty()
	{
		return (Double) readProperty("primaryPosQty");
	}

	public void setProduct(Integer product)
	{
		writeProperty("product", product);
	}

	public Integer getProduct()
	{
		return (Integer) readProperty("product");
	}

	public void setProfitCntr(String profitCntr)
	{
		writeProperty("profitCntr", profitCntr);
	}

	public String getProfitCntr()
	{
		return (String) readProperty("profitCntr");
	}

	public void setRealPortNum(Integer realPortNum)
	{
		writeProperty("realPortNum", realPortNum);
	}

	public Integer getRealPortNum()
	{
		return (Integer) readProperty("realPortNum");
	}

	public void setSecondaryPosQty(Double secondaryPosQty)
	{
		writeProperty("secondaryPosQty", secondaryPosQty);
	}

	public Double getSecondaryPosQty()
	{
		return (Double) readProperty("secondaryPosQty");
	}

	public void setSecondaryQtyUomCode(String secondaryQtyUomCode)
	{
		writeProperty("secondaryQtyUomCode", secondaryQtyUomCode);
	}

	public String getSecondaryQtyUomCode()
	{
		return (String) readProperty("secondaryQtyUomCode");
	}

	public void setTradeCreationDate(Date tradeCreationDate)
	{
		writeProperty("tradeCreationDate", tradeCreationDate);
	}

	public Date getTradeCreationDate()
	{
		return (Date) readProperty("tradeCreationDate");
	}

	public void setTradeKey(String tradeKey)
	{
		writeProperty("tradeKey", tradeKey);
	}

	public String getTradeKey()
	{
		return (String) readProperty("tradeKey");
	}

	public void setTradeModDate(Date tradeModDate)
	{
		writeProperty("tradeModDate", tradeModDate);
	}

	public Date getTradeModDate()
	{
		return (Date) readProperty("tradeModDate");
	}

	public void setTradeNum(Integer tradeNum)
	{
		writeProperty("tradeNum", tradeNum);
	}

	public Integer getTradeNum()
	{
		return (Integer) readProperty("tradeNum");
	}

	public void setTraderInit(String traderInit)
	{
		writeProperty("traderInit", traderInit);
	}

	public String getTraderInit()
	{
		return (String) readProperty("traderInit");
	}

	public void setTradingEntity(String tradingEntity)
	{
		writeProperty("tradingEntity", tradingEntity);
	}

	public String getTradingEntity()
	{
		return (String) readProperty("tradingEntity");
	}

	public void setTradingPrd(String tradingPrd)
	{
		writeProperty("tradingPrd", tradingPrd);
	}

	public String getTradingPrd()
	{
		return (String) readProperty("tradingPrd");
	}

	public void setTradingPrdDesc(String tradingPrdDesc)
	{
		writeProperty("tradingPrdDesc", tradingPrdDesc);
	}

	public String getTradingPrdDesc()
	{
		return (String) readProperty("tradingPrdDesc");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
