package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _VFxCostDrawDownHistRev was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VFxCostDrawDownHistRev extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Integer> ASOF_TRANS_ID = new Property<Integer>("asofTransId");
	public static final Property<String> COST_CODE = new Property<String>("costCode");
	public static final Property<String> COST_TYPE_CODE = new Property<String>("costTypeCode");
	public static final Property<String> DRAW_DOWN_UP_IND = new Property<String>("drawDownUpInd");
	public static final Property<Integer> FROM_COST_NUM = new Property<Integer>("fromCostNum");
	public static final Property<Date> FROM_FX_PL_ASOF_DATE = new Property<Date>("fromFxPlAsofDate");
	public static final Property<Date> FX_PL_ROLL_DATE = new Property<Date>("fxPlRollDate");
	public static final Property<Short> ITEM_NUM = new Property<Short>("itemNum");
	public static final Property<Integer> OID = new Property<Integer>("oid");
	public static final Property<Short> ORDER_NUM = new Property<Short>("orderNum");
	public static final Property<String> PAY_REC_IND = new Property<String>("payRecInd");
	public static final Property<Integer> RESP_TRANS_ID = new Property<Integer>("respTransId");
	public static final Property<Integer> TO_COST_NUM = new Property<Integer>("toCostNum");
	public static final Property<Integer> TRADE_NUM = new Property<Integer>("tradeNum");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setAsofTransId(Integer asofTransId)
	{
		writeProperty("asofTransId", asofTransId);
	}

	public Integer getAsofTransId()
	{
		return (Integer) readProperty("asofTransId");
	}

	public void setCostCode(String costCode)
	{
		writeProperty("costCode", costCode);
	}

	public String getCostCode()
	{
		return (String) readProperty("costCode");
	}

	public void setCostTypeCode(String costTypeCode)
	{
		writeProperty("costTypeCode", costTypeCode);
	}

	public String getCostTypeCode()
	{
		return (String) readProperty("costTypeCode");
	}

	public void setDrawDownUpInd(String drawDownUpInd)
	{
		writeProperty("drawDownUpInd", drawDownUpInd);
	}

	public String getDrawDownUpInd()
	{
		return (String) readProperty("drawDownUpInd");
	}

	public void setFromCostNum(Integer fromCostNum)
	{
		writeProperty("fromCostNum", fromCostNum);
	}

	public Integer getFromCostNum()
	{
		return (Integer) readProperty("fromCostNum");
	}

	public void setFromFxPlAsofDate(Date fromFxPlAsofDate)
	{
		writeProperty("fromFxPlAsofDate", fromFxPlAsofDate);
	}

	public Date getFromFxPlAsofDate()
	{
		return (Date) readProperty("fromFxPlAsofDate");
	}

	public void setFxPlRollDate(Date fxPlRollDate)
	{
		writeProperty("fxPlRollDate", fxPlRollDate);
	}

	public Date getFxPlRollDate()
	{
		return (Date) readProperty("fxPlRollDate");
	}

	public void setItemNum(Short itemNum)
	{
		writeProperty("itemNum", itemNum);
	}

	public Short getItemNum()
	{
		return (Short) readProperty("itemNum");
	}

	public void setOid(Integer oid)
	{
		writeProperty("oid", oid);
	}

	public Integer getOid()
	{
		return (Integer) readProperty("oid");
	}

	public void setOrderNum(Short orderNum)
	{
		writeProperty("orderNum", orderNum);
	}

	public Short getOrderNum()
	{
		return (Short) readProperty("orderNum");
	}

	public void setPayRecInd(String payRecInd)
	{
		writeProperty("payRecInd", payRecInd);
	}

	public String getPayRecInd()
	{
		return (String) readProperty("payRecInd");
	}

	public void setRespTransId(Integer respTransId)
	{
		writeProperty("respTransId", respTransId);
	}

	public Integer getRespTransId()
	{
		return (Integer) readProperty("respTransId");
	}

	public void setToCostNum(Integer toCostNum)
	{
		writeProperty("toCostNum", toCostNum);
	}

	public Integer getToCostNum()
	{
		return (Integer) readProperty("toCostNum");
	}

	public void setTradeNum(Integer tradeNum)
	{
		writeProperty("tradeNum", tradeNum);
	}

	public Integer getTradeNum()
	{
		return (Integer) readProperty("tradeNum");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
