package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _ViewOpenClaimFinal was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ViewOpenClaimFinal extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> ACCT_SHORT_NAME = new Property<String>("acctShortName");
	public static final Property<Date> B_L_DATE = new Property<Date>("b_L_Date");
	public static final Property<Double> B_L_QUANTITY = new Property<Double>("b_L_Quantity");
	public static final Property<String> B_L_UOM = new Property<String>("b_l_uom");
	public static final Property<String> COMMODITY = new Property<String>("commodity");
	public static final Property<Integer> DEMURRAGE_KEY = new Property<Integer>("demurrageKey");
	public static final Property<BigDecimal> FINAL_HOURS = new Property<BigDecimal>("finalHours");
	public static final Property<String> OWNER = new Property<String>("owner");
	public static final Property<String> OWNER_TYPE = new Property<String>("ownerType");
	public static final Property<String> PORT_SHORT_NAME = new Property<String>("portShortName");
	public static final Property<String> STATUS = new Property<String>("status");
	public static final Property<Integer> TRADE_NUM = new Property<Integer>("tradeNum");
	public static final Property<String> VESSEL = new Property<String>("vessel");

	public void setAcctShortName(String acctShortName)
	{
		writeProperty("acctShortName", acctShortName);
	}

	public String getAcctShortName()
	{
		return (String) readProperty("acctShortName");
	}

	public void setB_L_Date(Date b_L_Date)
	{
		writeProperty("b_L_Date", b_L_Date);
	}

	public Date getB_L_Date()
	{
		return (Date) readProperty("b_L_Date");
	}

	public void setB_L_Quantity(Double b_L_Quantity)
	{
		writeProperty("b_L_Quantity", b_L_Quantity);
	}

	public Double getB_L_Quantity()
	{
		return (Double) readProperty("b_L_Quantity");
	}

	public void setB_l_uom(String b_l_uom)
	{
		writeProperty("b_l_uom", b_l_uom);
	}

	public String getB_l_uom()
	{
		return (String) readProperty("b_l_uom");
	}

	public void setCommodity(String commodity)
	{
		writeProperty("commodity", commodity);
	}

	public String getCommodity()
	{
		return (String) readProperty("commodity");
	}

	public void setDemurrageKey(Integer demurrageKey)
	{
		writeProperty("demurrageKey", demurrageKey);
	}

	public Integer getDemurrageKey()
	{
		return (Integer) readProperty("demurrageKey");
	}

	public void setFinalHours(BigDecimal finalHours)
	{
		writeProperty("finalHours", finalHours);
	}

	public BigDecimal getFinalHours()
	{
		return (BigDecimal) readProperty("finalHours");
	}

	public void setOwner(String owner)
	{
		writeProperty("owner", owner);
	}

	public String getOwner()
	{
		return (String) readProperty("owner");
	}

	public void setOwnerType(String ownerType)
	{
		writeProperty("ownerType", ownerType);
	}

	public String getOwnerType()
	{
		return (String) readProperty("ownerType");
	}

	public void setPortShortName(String portShortName)
	{
		writeProperty("portShortName", portShortName);
	}

	public String getPortShortName()
	{
		return (String) readProperty("portShortName");
	}

	public void setStatus(String status)
	{
		writeProperty("status", status);
	}

	public String getStatus()
	{
		return (String) readProperty("status");
	}

	public void setTradeNum(Integer tradeNum)
	{
		writeProperty("tradeNum", tradeNum);
	}

	public Integer getTradeNum()
	{
		return (Integer) readProperty("tradeNum");
	}

	public void setVessel(String vessel)
	{
		writeProperty("vessel", vessel);
	}

	public String getVessel()
	{
		return (String) readProperty("vessel");
	}

}
