package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _VieRPTCommodityMasterAPI was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VieRPTCommodityMasterAPI extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> CMDTY_CODE = new Property<String>("cmdtyCode");
	public static final Property<BigDecimal> CMDTY_SPEC_TYPICAL_VAL = new Property<BigDecimal>("cmdtySpecTypicalVal");

	public void setCmdtyCode(String cmdtyCode)
	{
		writeProperty("cmdtyCode", cmdtyCode);
	}

	public String getCmdtyCode()
	{
		return (String) readProperty("cmdtyCode");
	}

	public void setCmdtySpecTypicalVal(BigDecimal cmdtySpecTypicalVal)
	{
		writeProperty("cmdtySpecTypicalVal", cmdtySpecTypicalVal);
	}

	public BigDecimal getCmdtySpecTypicalVal()
	{
		return (BigDecimal) readProperty("cmdtySpecTypicalVal");
	}

}
