package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _VieOFFHIREPrevvoyage was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VieOFFHIREPrevvoyage extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Date> E_TANORDATE = new Property<Date>("eTANordate");
	public static final Property<Date> E_TSDATE = new Property<Date>("eTSdate");
	public static final Property<String> OPERATION = new Property<String>("operation");
	public static final Property<String> ROUTE = new Property<String>("route");
	public static final Property<String> TIME_CHARTER = new Property<String>("timeCharter");
	public static final Property<String> VESSEL_NAME = new Property<String>("vesselName");
	public static final Property<String> VOYAGE_KEY = new Property<String>("voyageKey");

	public void setETANordate(Date eTANordate)
	{
		writeProperty("eTANordate", eTANordate);
	}

	public Date getETANordate()
	{
		return (Date) readProperty("eTANordate");
	}

	public void setETSdate(Date eTSdate)
	{
		writeProperty("eTSdate", eTSdate);
	}

	public Date getETSdate()
	{
		return (Date) readProperty("eTSdate");
	}

	public void setOperation(String operation)
	{
		writeProperty("operation", operation);
	}

	public String getOperation()
	{
		return (String) readProperty("operation");
	}

	public void setRoute(String route)
	{
		writeProperty("route", route);
	}

	public String getRoute()
	{
		return (String) readProperty("route");
	}

	public void setTimeCharter(String timeCharter)
	{
		writeProperty("timeCharter", timeCharter);
	}

	public String getTimeCharter()
	{
		return (String) readProperty("timeCharter");
	}

	public void setVesselName(String vesselName)
	{
		writeProperty("vesselName", vesselName);
	}

	public String getVesselName()
	{
		return (String) readProperty("vesselName");
	}

	public void setVoyageKey(String voyageKey)
	{
		writeProperty("voyageKey", voyageKey);
	}

	public String getVoyageKey()
	{
		return (String) readProperty("voyageKey");
	}

}
