package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _VieRPTPrgPrd was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VieRPTPrgPrd extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> CMDTY_SHORT_NAME = new Property<String>("cmdtyShortName");
	public static final Property<String> FLDCHR_CARGO_MODE_FLAG = new Property<String>("fldchrCargoModeFlag");
	public static final Property<String> FLDCHR_INSPECTION_NOTE = new Property<String>("fldchrInspectionNote");
	public static final Property<String> FLDCHR_LOAD_INSPECTION_NOTE = new Property<String>("fldchrLoadInspectionNote");
	public static final Property<String> FLDCHR_LOAD_STORAGE_CODE = new Property<String>("fldchrLoadStorageCode");
	public static final Property<String> FLDCHR_NOTE = new Property<String>("fldchrNote");
	public static final Property<String> FLDCHR_REF_MONTH = new Property<String>("fldchrRefMonth");
	public static final Property<String> FLDCHR_REF_YEAR = new Property<String>("fldchrRefYear");
	public static final Property<String> FLDCHR_SENT_VOYAGE_FLAG = new Property<String>("fldchrSentVoyageFlag");
	public static final Property<String> FLDCHR_STORAGE_CODE = new Property<String>("fldchrStorageCode");
	public static final Property<BigDecimal> FLDDEC_QTY_TNE = new Property<BigDecimal>("flddecQtyTNE");
	public static final Property<Integer> FLDINT_INSP_COMP_ACCT_NUM = new Property<Integer>("fldintInspCompAcctNum");
	public static final Property<Integer> FLDINT_LOAD_INSP_COMP_ACCT_NUM = new Property<Integer>("fldintLoadInspCompAcctNum");
	public static final Property<Date> FLDSDT_ETA = new Property<Date>("fldsdtEta");
	public static final Property<Date> FLDSDT_LOAD_LCAN_END = new Property<Date>("fldsdtLoadLcanEnd");
	public static final Property<Date> FLDSDT_LOAD_LCAN_START = new Property<Date>("fldsdtLoadLcanStart");
	public static final Property<String> FLDVCH_CURR_VSL_NAME = new Property<String>("fldvchCurrVslName");
	public static final Property<String> FLDVCH_INSP_COMP_ACCT_NAME = new Property<String>("fldvchInspCompAcctName");
	public static final Property<String> FLDVCH_LOAD_INSP_COMP_ACCT_NAME = new Property<String>("fldvchLoadInspCompAcctName");

	public void setCmdtyShortName(String cmdtyShortName)
	{
		writeProperty("cmdtyShortName", cmdtyShortName);
	}

	public String getCmdtyShortName()
	{
		return (String) readProperty("cmdtyShortName");
	}

	public void setFldchrCargoModeFlag(String fldchrCargoModeFlag)
	{
		writeProperty("fldchrCargoModeFlag", fldchrCargoModeFlag);
	}

	public String getFldchrCargoModeFlag()
	{
		return (String) readProperty("fldchrCargoModeFlag");
	}

	public void setFldchrInspectionNote(String fldchrInspectionNote)
	{
		writeProperty("fldchrInspectionNote", fldchrInspectionNote);
	}

	public String getFldchrInspectionNote()
	{
		return (String) readProperty("fldchrInspectionNote");
	}

	public void setFldchrLoadInspectionNote(String fldchrLoadInspectionNote)
	{
		writeProperty("fldchrLoadInspectionNote", fldchrLoadInspectionNote);
	}

	public String getFldchrLoadInspectionNote()
	{
		return (String) readProperty("fldchrLoadInspectionNote");
	}

	public void setFldchrLoadStorageCode(String fldchrLoadStorageCode)
	{
		writeProperty("fldchrLoadStorageCode", fldchrLoadStorageCode);
	}

	public String getFldchrLoadStorageCode()
	{
		return (String) readProperty("fldchrLoadStorageCode");
	}

	public void setFldchrNote(String fldchrNote)
	{
		writeProperty("fldchrNote", fldchrNote);
	}

	public String getFldchrNote()
	{
		return (String) readProperty("fldchrNote");
	}

	public void setFldchrRefMonth(String fldchrRefMonth)
	{
		writeProperty("fldchrRefMonth", fldchrRefMonth);
	}

	public String getFldchrRefMonth()
	{
		return (String) readProperty("fldchrRefMonth");
	}

	public void setFldchrRefYear(String fldchrRefYear)
	{
		writeProperty("fldchrRefYear", fldchrRefYear);
	}

	public String getFldchrRefYear()
	{
		return (String) readProperty("fldchrRefYear");
	}

	public void setFldchrSentVoyageFlag(String fldchrSentVoyageFlag)
	{
		writeProperty("fldchrSentVoyageFlag", fldchrSentVoyageFlag);
	}

	public String getFldchrSentVoyageFlag()
	{
		return (String) readProperty("fldchrSentVoyageFlag");
	}

	public void setFldchrStorageCode(String fldchrStorageCode)
	{
		writeProperty("fldchrStorageCode", fldchrStorageCode);
	}

	public String getFldchrStorageCode()
	{
		return (String) readProperty("fldchrStorageCode");
	}

	public void setFlddecQtyTNE(BigDecimal flddecQtyTNE)
	{
		writeProperty("flddecQtyTNE", flddecQtyTNE);
	}

	public BigDecimal getFlddecQtyTNE()
	{
		return (BigDecimal) readProperty("flddecQtyTNE");
	}

	public void setFldintInspCompAcctNum(Integer fldintInspCompAcctNum)
	{
		writeProperty("fldintInspCompAcctNum", fldintInspCompAcctNum);
	}

	public Integer getFldintInspCompAcctNum()
	{
		return (Integer) readProperty("fldintInspCompAcctNum");
	}

	public void setFldintLoadInspCompAcctNum(Integer fldintLoadInspCompAcctNum)
	{
		writeProperty("fldintLoadInspCompAcctNum", fldintLoadInspCompAcctNum);
	}

	public Integer getFldintLoadInspCompAcctNum()
	{
		return (Integer) readProperty("fldintLoadInspCompAcctNum");
	}

	public void setFldsdtEta(Date fldsdtEta)
	{
		writeProperty("fldsdtEta", fldsdtEta);
	}

	public Date getFldsdtEta()
	{
		return (Date) readProperty("fldsdtEta");
	}

	public void setFldsdtLoadLcanEnd(Date fldsdtLoadLcanEnd)
	{
		writeProperty("fldsdtLoadLcanEnd", fldsdtLoadLcanEnd);
	}

	public Date getFldsdtLoadLcanEnd()
	{
		return (Date) readProperty("fldsdtLoadLcanEnd");
	}

	public void setFldsdtLoadLcanStart(Date fldsdtLoadLcanStart)
	{
		writeProperty("fldsdtLoadLcanStart", fldsdtLoadLcanStart);
	}

	public Date getFldsdtLoadLcanStart()
	{
		return (Date) readProperty("fldsdtLoadLcanStart");
	}

	public void setFldvchCurrVslName(String fldvchCurrVslName)
	{
		writeProperty("fldvchCurrVslName", fldvchCurrVslName);
	}

	public String getFldvchCurrVslName()
	{
		return (String) readProperty("fldvchCurrVslName");
	}

	public void setFldvchInspCompAcctName(String fldvchInspCompAcctName)
	{
		writeProperty("fldvchInspCompAcctName", fldvchInspCompAcctName);
	}

	public String getFldvchInspCompAcctName()
	{
		return (String) readProperty("fldvchInspCompAcctName");
	}

	public void setFldvchLoadInspCompAcctName(String fldvchLoadInspCompAcctName)
	{
		writeProperty("fldvchLoadInspCompAcctName", fldvchLoadInspCompAcctName);
	}

	public String getFldvchLoadInspCompAcctName()
	{
		return (String) readProperty("fldvchLoadInspCompAcctName");
	}

}
