package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Uom;

/**
 * Class _VoucherCost was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VoucherCost extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String COST_NUM_PK_COLUMN = "cost_num";
	public static final String VOUCHER_NUM_PK_COLUMN = "voucher_num";

	public static final Property<Integer> LINE_NUM = new Property<Integer>("lineNum");
	public static final Property<Double> PROV_AMT = new Property<Double>("provAmt");
	public static final Property<Double> PROV_PRICE = new Property<Double>("provPrice");
	public static final Property<Double> PROV_QTY = new Property<Double>("provQty");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<String> VOUCHER_COST_STATUS = new Property<String>("voucherCostStatus");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<Uom> UOM = new Property<Uom>("uom");

	public void setLineNum(Integer lineNum)
	{
		writeProperty("lineNum", lineNum);
	}

	public Integer getLineNum()
	{
		return (Integer) readProperty("lineNum");
	}

	public void setProvAmt(Double provAmt)
	{
		writeProperty("provAmt", provAmt);
	}

	public Double getProvAmt()
	{
		return (Double) readProperty("provAmt");
	}

	public void setProvPrice(Double provPrice)
	{
		writeProperty("provPrice", provPrice);
	}

	public Double getProvPrice()
	{
		return (Double) readProperty("provPrice");
	}

	public void setProvQty(Double provQty)
	{
		writeProperty("provQty", provQty);
	}

	public Double getProvQty()
	{
		return (Double) readProperty("provQty");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setVoucherCostStatus(String voucherCostStatus)
	{
		writeProperty("voucherCostStatus", voucherCostStatus);
	}

	public String getVoucherCostStatus()
	{
		return (String) readProperty("voucherCostStatus");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setUom(Uom uom)
	{
		setToOneTarget("uom", uom, true);
	}

	public Uom getUom()
	{
		return (Uom) readProperty("uom");
	}

}
