package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Account;
import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CreditTerm;
import com.tc.app.exchangemonitor.model.cayenne.persistent.IctsUser;
import com.tc.app.exchangemonitor.model.cayenne.persistent.AccountBankInfo;
import com.tc.app.exchangemonitor.model.cayenne.persistent.AccountInstruction;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PaymentMethod;
import com.tc.app.exchangemonitor.model.cayenne.persistent.PaymentTerm;

/**
 * Class _Voucher was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Voucher extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String VOUCHER_NUM_PK_COLUMN = "voucher_num";

	public static final Property<Date> CASH_DATE = new Property<>("cashDate");
	public static final Property<Integer> CMNT_NUM = new Property<>("cmntNum");
	public static final Property<Date> CUST_INV_RECV_DATE = new Property<>("custInvRecvDate");
	public static final Property<String> CUST_INV_TYPE_IND = new Property<>("custInvTypeInd");
	public static final Property<String> CUSTOM_VOUCHER_STRING = new Property<>("customVoucherString");
	public static final Property<String> EXTERNAL_REF_KEY = new Property<>("externalRefKey");
	public static final Property<String> INVOICE_EXCH_RATE_COMMENT = new Property<>("invoiceExchRateComment");
	public static final Property<Integer> MAX_LINE_NUM = new Property<>("maxLineNum");
	public static final Property<Integer> REF_VOUCHER_NUM = new Property<>("refVoucherNum");
	public static final Property<String> SAP_INVOICE_NUMBER = new Property<>("sapInvoiceNumber");
	public static final Property<String> SPECIAL_BANK_INSTR = new Property<>("specialBankInstr");
	public static final Property<Integer> TRANS_ID = new Property<>("transId");
	public static final Property<Double> VOCH_TOT_PAID_AMT = new Property<>("vochTotPaidAmt");
	public static final Property<String> VOUCHER_ACCT_NAME = new Property<>("voucherAcctName");
	public static final Property<Date> VOUCHER_APPROVAL_DATE = new Property<>("voucherApprovalDate");
	public static final Property<String> VOUCHER_ARAP_ACCT_CODE = new Property<>("voucherArapAcctCode");
	public static final Property<Date> VOUCHER_AUTH_DATE = new Property<>("voucherAuthDate");
	public static final Property<String> VOUCHER_AUTH_REQD_IND = new Property<>("voucherAuthReqdInd");
	public static final Property<String> VOUCHER_BOOK_COMP_NAME = new Property<>("voucherBookCompName");
	public static final Property<Date> VOUCHER_BOOK_DATE = new Property<>("voucherBookDate");
	public static final Property<Double> VOUCHER_BOOK_EXCH_RATE = new Property<>("voucherBookExchRate");
	public static final Property<Date> VOUCHER_BOOK_PRD_DATE = new Property<>("voucherBookPrdDate");
	public static final Property<String> VOUCHER_CAT_CODE = new Property<>("voucherCatCode");
	public static final Property<Date> VOUCHER_CREATION_DATE = new Property<>("voucherCreationDate");
	public static final Property<Double> VOUCHER_CUST_INV_AMT = new Property<>("voucherCustInvAmt");
	public static final Property<Date> VOUCHER_CUST_INV_DATE = new Property<>("voucherCustInvDate");
	public static final Property<String> VOUCHER_CUST_REF_NUM = new Property<>("voucherCustRefNum");
	public static final Property<Date> VOUCHER_DUE_DATE = new Property<>("voucherDueDate");
	public static final Property<Date> VOUCHER_EFF_DATE = new Property<>("voucherEffDate");
	public static final Property<Date> VOUCHER_EXPECTED_PAY_DATE = new Property<>("voucherExpectedPayDate");
	public static final Property<String> VOUCHER_HOLD_IND = new Property<>("voucherHoldInd");
	public static final Property<BigDecimal> VOUCHER_INV_EXCH_RATE = new Property<>("voucherInvExchRate");
	public static final Property<Integer> VOUCHER_LOI_NUM = new Property<>("voucherLoiNum");
	public static final Property<Date> VOUCHER_MOD_DATE = new Property<>("voucherModDate");
	public static final Property<Date> VOUCHER_PAID_DATE = new Property<>("voucherPaidDate");
	public static final Property<Short> VOUCHER_PAY_DAYS = new Property<>("voucherPayDays");
	public static final Property<String> VOUCHER_PAY_RECV_IND = new Property<>("voucherPayRecvInd");
	public static final Property<Date> VOUCHER_PRINT_DATE = new Property<>("voucherPrintDate");
	public static final Property<String> VOUCHER_REVERSAL_IND = new Property<>("voucherReversalInd");
	public static final Property<Date> VOUCHER_SEND_TO_ARAP_DATE = new Property<>("voucherSendToArapDate");
	public static final Property<Date> VOUCHER_SEND_TO_CUST_DATE = new Property<>("voucherSendToCustDate");
	public static final Property<String> VOUCHER_SHORT_CMNT = new Property<>("voucherShortCmnt");
	public static final Property<String> VOUCHER_STATUS = new Property<>("voucherStatus");
	public static final Property<Double> VOUCHER_TOT_AMT = new Property<>("voucherTotAmt");
	public static final Property<String> VOUCHER_TYPE_CODE = new Property<>("voucherTypeCode");
	public static final Property<Date> VOUCHER_WRITEOFF_DATE = new Property<>("voucherWriteoffDate");
	public static final Property<String> VOUCHER_XRATE_CONV_IND = new Property<>("voucherXrateConvInd");
	public static final Property<Account> ACCOUNT = new Property<>("account");
	public static final Property<Account> ACCOUNT1 = new Property<>("account1");
	public static final Property<AccountInstruction> ACCOUNT_INSTRUCTION = new Property<>("accountInstruction");
	public static final Property<AccountInstruction> ACCOUNT_INSTRUCTION1 = new Property<>("accountInstruction1");
	public static final Property<AccountBankInfo> BOOK_COMP_ACCT_BANK = new Property<>("bookCompAcctBank");
	public static final Property<Commodity> COMMODITY = new Property<>("commodity");
	public static final Property<Commodity> COMMODITY1 = new Property<>("commodity1");
	public static final Property<Commodity> COMMODITY2 = new Property<>("commodity2");
	public static final Property<Commodity> COMMODITY3 = new Property<>("commodity3");
	public static final Property<AccountBankInfo> CP_ACCT_BANK = new Property<>("cpAcctBank");
	public static final Property<CreditTerm> CREDIT_TERM = new Property<>("creditTerm");
	public static final Property<IctsUser> ICTS_USER = new Property<>("ictsUser");
	public static final Property<IctsUser> ICTS_USER1 = new Property<>("ictsUser1");
	public static final Property<IctsUser> ICTS_USER2 = new Property<>("ictsUser2");
	public static final Property<IctsUser> ICTS_USER3 = new Property<>("ictsUser3");
	public static final Property<IctsUser> ICTS_USER4 = new Property<>("ictsUser4");
	public static final Property<PaymentMethod> PAYMENT_METHOD = new Property<>("paymentMethod");
	public static final Property<PaymentTerm> PAYMENT_TERM = new Property<>("paymentTerm");
	public static final Property<AccountBankInfo> REVISED_BOOK_COMP_BANK = new Property<>("revisedBookCompBank");

	public void setCashDate(final Date cashDate)
	{
		this.writeProperty("cashDate", cashDate);
	}

	public Date getCashDate()
	{
		return (Date) this.readProperty("cashDate");
	}

	public void setCmntNum(final Integer cmntNum)
	{
		this.writeProperty("cmntNum", cmntNum);
	}

	public Integer getCmntNum()
	{
		return (Integer) this.readProperty("cmntNum");
	}

	public void setCustInvRecvDate(final Date custInvRecvDate)
	{
		this.writeProperty("custInvRecvDate", custInvRecvDate);
	}

	public Date getCustInvRecvDate()
	{
		return (Date) this.readProperty("custInvRecvDate");
	}

	public void setCustInvTypeInd(final String custInvTypeInd)
	{
		this.writeProperty("custInvTypeInd", custInvTypeInd);
	}

	public String getCustInvTypeInd()
	{
		return (String) this.readProperty("custInvTypeInd");
	}

	public void setCustomVoucherString(final String customVoucherString)
	{
		this.writeProperty("customVoucherString", customVoucherString);
	}

	public String getCustomVoucherString()
	{
		return (String) this.readProperty("customVoucherString");
	}

	public void setExternalRefKey(final String externalRefKey)
	{
		this.writeProperty("externalRefKey", externalRefKey);
	}

	public String getExternalRefKey()
	{
		return (String) this.readProperty("externalRefKey");
	}

	public void setInvoiceExchRateComment(final String invoiceExchRateComment)
	{
		this.writeProperty("invoiceExchRateComment", invoiceExchRateComment);
	}

	public String getInvoiceExchRateComment()
	{
		return (String) this.readProperty("invoiceExchRateComment");
	}

	public void setMaxLineNum(final Integer maxLineNum)
	{
		this.writeProperty("maxLineNum", maxLineNum);
	}

	public Integer getMaxLineNum()
	{
		return (Integer) this.readProperty("maxLineNum");
	}

	public void setRefVoucherNum(final Integer refVoucherNum)
	{
		this.writeProperty("refVoucherNum", refVoucherNum);
	}

	public Integer getRefVoucherNum()
	{
		return (Integer) this.readProperty("refVoucherNum");
	}

	public void setSapInvoiceNumber(final String sapInvoiceNumber)
	{
		this.writeProperty("sapInvoiceNumber", sapInvoiceNumber);
	}

	public String getSapInvoiceNumber()
	{
		return (String) this.readProperty("sapInvoiceNumber");
	}

	public void setSpecialBankInstr(final String specialBankInstr)
	{
		this.writeProperty("specialBankInstr", specialBankInstr);
	}

	public String getSpecialBankInstr()
	{
		return (String) this.readProperty("specialBankInstr");
	}

	public void setTransId(final Integer transId)
	{
		this.writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) this.readProperty("transId");
	}

	public void setVochTotPaidAmt(final Double vochTotPaidAmt)
	{
		this.writeProperty("vochTotPaidAmt", vochTotPaidAmt);
	}

	public Double getVochTotPaidAmt()
	{
		return (Double) this.readProperty("vochTotPaidAmt");
	}

	public void setVoucherAcctName(final String voucherAcctName)
	{
		this.writeProperty("voucherAcctName", voucherAcctName);
	}

	public String getVoucherAcctName()
	{
		return (String) this.readProperty("voucherAcctName");
	}

	public void setVoucherApprovalDate(final Date voucherApprovalDate)
	{
		this.writeProperty("voucherApprovalDate", voucherApprovalDate);
	}

	public Date getVoucherApprovalDate()
	{
		return (Date) this.readProperty("voucherApprovalDate");
	}

	public void setVoucherArapAcctCode(final String voucherArapAcctCode)
	{
		this.writeProperty("voucherArapAcctCode", voucherArapAcctCode);
	}

	public String getVoucherArapAcctCode()
	{
		return (String) this.readProperty("voucherArapAcctCode");
	}

	public void setVoucherAuthDate(final Date voucherAuthDate)
	{
		this.writeProperty("voucherAuthDate", voucherAuthDate);
	}

	public Date getVoucherAuthDate()
	{
		return (Date) this.readProperty("voucherAuthDate");
	}

	public void setVoucherAuthReqdInd(final String voucherAuthReqdInd)
	{
		this.writeProperty("voucherAuthReqdInd", voucherAuthReqdInd);
	}

	public String getVoucherAuthReqdInd()
	{
		return (String) this.readProperty("voucherAuthReqdInd");
	}

	public void setVoucherBookCompName(final String voucherBookCompName)
	{
		this.writeProperty("voucherBookCompName", voucherBookCompName);
	}

	public String getVoucherBookCompName()
	{
		return (String) this.readProperty("voucherBookCompName");
	}

	public void setVoucherBookDate(final Date voucherBookDate)
	{
		this.writeProperty("voucherBookDate", voucherBookDate);
	}

	public Date getVoucherBookDate()
	{
		return (Date) this.readProperty("voucherBookDate");
	}

	public void setVoucherBookExchRate(final Double voucherBookExchRate)
	{
		this.writeProperty("voucherBookExchRate", voucherBookExchRate);
	}

	public Double getVoucherBookExchRate()
	{
		return (Double) this.readProperty("voucherBookExchRate");
	}

	public void setVoucherBookPrdDate(final Date voucherBookPrdDate)
	{
		this.writeProperty("voucherBookPrdDate", voucherBookPrdDate);
	}

	public Date getVoucherBookPrdDate()
	{
		return (Date) this.readProperty("voucherBookPrdDate");
	}

	public void setVoucherCatCode(final String voucherCatCode)
	{
		this.writeProperty("voucherCatCode", voucherCatCode);
	}

	public String getVoucherCatCode()
	{
		return (String) this.readProperty("voucherCatCode");
	}

	public void setVoucherCreationDate(final Date voucherCreationDate)
	{
		this.writeProperty("voucherCreationDate", voucherCreationDate);
	}

	public Date getVoucherCreationDate()
	{
		return (Date) this.readProperty("voucherCreationDate");
	}

	public void setVoucherCustInvAmt(final Double voucherCustInvAmt)
	{
		this.writeProperty("voucherCustInvAmt", voucherCustInvAmt);
	}

	public Double getVoucherCustInvAmt()
	{
		return (Double) this.readProperty("voucherCustInvAmt");
	}

	public void setVoucherCustInvDate(final Date voucherCustInvDate)
	{
		this.writeProperty("voucherCustInvDate", voucherCustInvDate);
	}

	public Date getVoucherCustInvDate()
	{
		return (Date) this.readProperty("voucherCustInvDate");
	}

	public void setVoucherCustRefNum(final String voucherCustRefNum)
	{
		this.writeProperty("voucherCustRefNum", voucherCustRefNum);
	}

	public String getVoucherCustRefNum()
	{
		return (String) this.readProperty("voucherCustRefNum");
	}

	public void setVoucherDueDate(final Date voucherDueDate)
	{
		this.writeProperty("voucherDueDate", voucherDueDate);
	}

	public Date getVoucherDueDate()
	{
		return (Date) this.readProperty("voucherDueDate");
	}

	public void setVoucherEffDate(final Date voucherEffDate)
	{
		this.writeProperty("voucherEffDate", voucherEffDate);
	}

	public Date getVoucherEffDate()
	{
		return (Date) this.readProperty("voucherEffDate");
	}

	public void setVoucherExpectedPayDate(final Date voucherExpectedPayDate)
	{
		this.writeProperty("voucherExpectedPayDate", voucherExpectedPayDate);
	}

	public Date getVoucherExpectedPayDate()
	{
		return (Date) this.readProperty("voucherExpectedPayDate");
	}

	public void setVoucherHoldInd(final String voucherHoldInd)
	{
		this.writeProperty("voucherHoldInd", voucherHoldInd);
	}

	public String getVoucherHoldInd()
	{
		return (String) this.readProperty("voucherHoldInd");
	}

	public void setVoucherInvExchRate(final BigDecimal voucherInvExchRate)
	{
		this.writeProperty("voucherInvExchRate", voucherInvExchRate);
	}

	public BigDecimal getVoucherInvExchRate()
	{
		return (BigDecimal) this.readProperty("voucherInvExchRate");
	}

	public void setVoucherLoiNum(final Integer voucherLoiNum)
	{
		this.writeProperty("voucherLoiNum", voucherLoiNum);
	}

	public Integer getVoucherLoiNum()
	{
		return (Integer) this.readProperty("voucherLoiNum");
	}

	public void setVoucherModDate(final Date voucherModDate)
	{
		this.writeProperty("voucherModDate", voucherModDate);
	}

	public Date getVoucherModDate()
	{
		return (Date) this.readProperty("voucherModDate");
	}

	public void setVoucherPaidDate(final Date voucherPaidDate)
	{
		this.writeProperty("voucherPaidDate", voucherPaidDate);
	}

	public Date getVoucherPaidDate()
	{
		return (Date) this.readProperty("voucherPaidDate");
	}

	public void setVoucherPayDays(final Short voucherPayDays)
	{
		this.writeProperty("voucherPayDays", voucherPayDays);
	}

	public Short getVoucherPayDays()
	{
		return (Short) this.readProperty("voucherPayDays");
	}

	public void setVoucherPayRecvInd(final String voucherPayRecvInd)
	{
		this.writeProperty("voucherPayRecvInd", voucherPayRecvInd);
	}

	public String getVoucherPayRecvInd()
	{
		return (String) this.readProperty("voucherPayRecvInd");
	}

	public void setVoucherPrintDate(final Date voucherPrintDate)
	{
		this.writeProperty("voucherPrintDate", voucherPrintDate);
	}

	public Date getVoucherPrintDate()
	{
		return (Date) this.readProperty("voucherPrintDate");
	}

	public void setVoucherReversalInd(final String voucherReversalInd)
	{
		this.writeProperty("voucherReversalInd", voucherReversalInd);
	}

	public String getVoucherReversalInd()
	{
		return (String) this.readProperty("voucherReversalInd");
	}

	public void setVoucherSendToArapDate(final Date voucherSendToArapDate)
	{
		this.writeProperty("voucherSendToArapDate", voucherSendToArapDate);
	}

	public Date getVoucherSendToArapDate()
	{
		return (Date) this.readProperty("voucherSendToArapDate");
	}

	public void setVoucherSendToCustDate(final Date voucherSendToCustDate)
	{
		this.writeProperty("voucherSendToCustDate", voucherSendToCustDate);
	}

	public Date getVoucherSendToCustDate()
	{
		return (Date) this.readProperty("voucherSendToCustDate");
	}

	public void setVoucherShortCmnt(final String voucherShortCmnt)
	{
		this.writeProperty("voucherShortCmnt", voucherShortCmnt);
	}

	public String getVoucherShortCmnt()
	{
		return (String) this.readProperty("voucherShortCmnt");
	}

	public void setVoucherStatus(final String voucherStatus)
	{
		this.writeProperty("voucherStatus", voucherStatus);
	}

	public String getVoucherStatus()
	{
		return (String) this.readProperty("voucherStatus");
	}

	public void setVoucherTotAmt(final Double voucherTotAmt)
	{
		this.writeProperty("voucherTotAmt", voucherTotAmt);
	}

	public Double getVoucherTotAmt()
	{
		return (Double) this.readProperty("voucherTotAmt");
	}

	public void setVoucherTypeCode(final String voucherTypeCode)
	{
		this.writeProperty("voucherTypeCode", voucherTypeCode);
	}

	public String getVoucherTypeCode()
	{
		return (String) this.readProperty("voucherTypeCode");
	}

	public void setVoucherWriteoffDate(final Date voucherWriteoffDate)
	{
		this.writeProperty("voucherWriteoffDate", voucherWriteoffDate);
	}

	public Date getVoucherWriteoffDate()
	{
		return (Date) this.readProperty("voucherWriteoffDate");
	}

	public void setVoucherXrateConvInd(final String voucherXrateConvInd)
	{
		this.writeProperty("voucherXrateConvInd", voucherXrateConvInd);
	}

	public String getVoucherXrateConvInd()
	{
		return (String) this.readProperty("voucherXrateConvInd");
	}

	public void setAccount(final Account account)
	{
		this.setToOneTarget("account", account, true);
	}

	public Account getAccount()
	{
		return (Account) this.readProperty("account");
	}

	public void setAccount1(final Account account1)
	{
		this.setToOneTarget("account1", account1, true);
	}

	public Account getAccount1()
	{
		return (Account) this.readProperty("account1");
	}

	public void setAccountInstruction(final AccountInstruction accountInstruction)
	{
		this.setToOneTarget("accountInstruction", accountInstruction, true);
	}

	public AccountInstruction getAccountInstruction()
	{
		return (AccountInstruction) this.readProperty("accountInstruction");
	}

	public void setAccountInstruction1(final AccountInstruction accountInstruction1)
	{
		this.setToOneTarget("accountInstruction1", accountInstruction1, true);
	}

	public AccountInstruction getAccountInstruction1()
	{
		return (AccountInstruction) this.readProperty("accountInstruction1");
	}

	public void setBookCompAcctBank(final AccountBankInfo bookCompAcctBank)
	{
		this.setToOneTarget("bookCompAcctBank", bookCompAcctBank, true);
	}

	public AccountBankInfo getBookCompAcctBank()
	{
		return (AccountBankInfo) this.readProperty("bookCompAcctBank");
	}

	public void setCommodity(final Commodity commodity)
	{
		this.setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) this.readProperty("commodity");
	}

	public void setCommodity1(final Commodity commodity1)
	{
		this.setToOneTarget("commodity1", commodity1, true);
	}

	public Commodity getCommodity1()
	{
		return (Commodity) this.readProperty("commodity1");
	}

	public void setCommodity2(final Commodity commodity2)
	{
		this.setToOneTarget("commodity2", commodity2, true);
	}

	public Commodity getCommodity2()
	{
		return (Commodity) this.readProperty("commodity2");
	}

	public void setCommodity3(final Commodity commodity3)
	{
		this.setToOneTarget("commodity3", commodity3, true);
	}

	public Commodity getCommodity3()
	{
		return (Commodity) this.readProperty("commodity3");
	}

	public void setCpAcctBank(final AccountBankInfo cpAcctBank)
	{
		this.setToOneTarget("cpAcctBank", cpAcctBank, true);
	}

	public AccountBankInfo getCpAcctBank()
	{
		return (AccountBankInfo) this.readProperty("cpAcctBank");
	}

	public void setCreditTerm(final CreditTerm creditTerm)
	{
		this.setToOneTarget("creditTerm", creditTerm, true);
	}

	public CreditTerm getCreditTerm()
	{
		return (CreditTerm) this.readProperty("creditTerm");
	}

	public void setIctsUser(final IctsUser ictsUser)
	{
		this.setToOneTarget("ictsUser", ictsUser, true);
	}

	public IctsUser getIctsUser()
	{
		return (IctsUser) this.readProperty("ictsUser");
	}

	public void setIctsUser1(final IctsUser ictsUser1)
	{
		this.setToOneTarget("ictsUser1", ictsUser1, true);
	}

	public IctsUser getIctsUser1()
	{
		return (IctsUser) this.readProperty("ictsUser1");
	}

	public void setIctsUser2(final IctsUser ictsUser2)
	{
		this.setToOneTarget("ictsUser2", ictsUser2, true);
	}

	public IctsUser getIctsUser2()
	{
		return (IctsUser) this.readProperty("ictsUser2");
	}

	public void setIctsUser3(final IctsUser ictsUser3)
	{
		this.setToOneTarget("ictsUser3", ictsUser3, true);
	}

	public IctsUser getIctsUser3()
	{
		return (IctsUser) this.readProperty("ictsUser3");
	}

	public void setIctsUser4(final IctsUser ictsUser4)
	{
		this.setToOneTarget("ictsUser4", ictsUser4, true);
	}

	public IctsUser getIctsUser4()
	{
		return (IctsUser) this.readProperty("ictsUser4");
	}

	public void setPaymentMethod(final PaymentMethod paymentMethod)
	{
		this.setToOneTarget("paymentMethod", paymentMethod, true);
	}

	public PaymentMethod getPaymentMethod()
	{
		return (PaymentMethod) this.readProperty("paymentMethod");
	}

	public void setPaymentTerm(final PaymentTerm paymentTerm)
	{
		this.setToOneTarget("paymentTerm", paymentTerm, true);
	}

	public PaymentTerm getPaymentTerm()
	{
		return (PaymentTerm) this.readProperty("paymentTerm");
	}

	public void setRevisedBookCompBank(final AccountBankInfo revisedBookCompBank)
	{
		this.setToOneTarget("revisedBookCompBank", revisedBookCompBank, true);
	}

	public AccountBankInfo getRevisedBookCompBank()
	{
		return (AccountBankInfo) this.readProperty("revisedBookCompBank");
	}

}
