package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.WbContract;

/**
 * Class _WbContractTcConfig was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WbContractTcConfig extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_CONTR_KEY_PK_COLUMN = "fldchrContrKey";

	public static final Property<Integer> PORT_NUM = new Property<Integer>("portNum");
	public static final Property<Integer> PROV_HIRE_COST_NUM = new Property<Integer>("provHireCostNum");
	public static final Property<String> PROV_HIRE_ENABLED = new Property<String>("provHireEnabled");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<WbContract> WB_CONTRACT = new Property<WbContract>("wbContract");

	public void setPortNum(Integer portNum)
	{
		writeProperty("portNum", portNum);
	}

	public Integer getPortNum()
	{
		return (Integer) readProperty("portNum");
	}

	public void setProvHireCostNum(Integer provHireCostNum)
	{
		writeProperty("provHireCostNum", provHireCostNum);
	}

	public Integer getProvHireCostNum()
	{
		return (Integer) readProperty("provHireCostNum");
	}

	public void setProvHireEnabled(String provHireEnabled)
	{
		writeProperty("provHireEnabled", provHireEnabled);
	}

	public String getProvHireEnabled()
	{
		return (String) readProperty("provHireEnabled");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setWbContract(WbContract wbContract)
	{
		setToOneTarget("wbContract", wbContract, true);
	}

	public WbContract getWbContract()
	{
		return (WbContract) readProperty("wbContract");
	}

}
