package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.WbConsumptionTypes;

/**
 * Class _WbContractConsumptions was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WbContractConsumptions extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_CMDTY_CODE_PK_COLUMN = "fldchrCmdtyCode";
	public static final String FLDCHR_CONTR_VSL_KEY_PK_COLUMN = "fldchrContrVslKey";
	public static final String FLDCHR_CSPT_TYPE_CODE_PK_COLUMN = "fldchrCsptTypeCode";

	public static final Property<String> FLDCHR_CMDTY_UMCODE = new Property<String>("fldchrCmdtyUMCode");
	public static final Property<String> FLDCHR_REC_ID = new Property<String>("fldchrRecId");
	public static final Property<String> FLDCHR_TEMP_UMCODE = new Property<String>("fldchrTempUMCode");
	public static final Property<String> FLDCHR_TIME_UNIT_UMCODE = new Property<String>("fldchrTimeUnitUMCode");
	public static final Property<BigDecimal> FLDDEC_CSPT = new Property<BigDecimal>("flddecCspt");
	public static final Property<BigDecimal> FLDDEC_TEMP = new Property<BigDecimal>("flddecTemp");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<WbConsumptionTypes> WB_CONSUMPTION_TYPES = new Property<WbConsumptionTypes>("wbConsumptionTypes");

	public void setFldchrCmdtyUMCode(String fldchrCmdtyUMCode)
	{
		writeProperty("fldchrCmdtyUMCode", fldchrCmdtyUMCode);
	}

	public String getFldchrCmdtyUMCode()
	{
		return (String) readProperty("fldchrCmdtyUMCode");
	}

	public void setFldchrRecId(String fldchrRecId)
	{
		writeProperty("fldchrRecId", fldchrRecId);
	}

	public String getFldchrRecId()
	{
		return (String) readProperty("fldchrRecId");
	}

	public void setFldchrTempUMCode(String fldchrTempUMCode)
	{
		writeProperty("fldchrTempUMCode", fldchrTempUMCode);
	}

	public String getFldchrTempUMCode()
	{
		return (String) readProperty("fldchrTempUMCode");
	}

	public void setFldchrTimeUnitUMCode(String fldchrTimeUnitUMCode)
	{
		writeProperty("fldchrTimeUnitUMCode", fldchrTimeUnitUMCode);
	}

	public String getFldchrTimeUnitUMCode()
	{
		return (String) readProperty("fldchrTimeUnitUMCode");
	}

	public void setFlddecCspt(BigDecimal flddecCspt)
	{
		writeProperty("flddecCspt", flddecCspt);
	}

	public BigDecimal getFlddecCspt()
	{
		return (BigDecimal) readProperty("flddecCspt");
	}

	public void setFlddecTemp(BigDecimal flddecTemp)
	{
		writeProperty("flddecTemp", flddecTemp);
	}

	public BigDecimal getFlddecTemp()
	{
		return (BigDecimal) readProperty("flddecTemp");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setWbConsumptionTypes(WbConsumptionTypes wbConsumptionTypes)
	{
		setToOneTarget("wbConsumptionTypes", wbConsumptionTypes, true);
	}

	public WbConsumptionTypes getWbConsumptionTypes()
	{
		return (WbConsumptionTypes) readProperty("wbConsumptionTypes");
	}

}
