package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _WbContractTcvalue was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WbContractTcvalue extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<String> FLDCHR_CHARTER_TYPE = new Property<String>("fldchrCharterType");
	public static final Property<String> FLDCHR_CONTR_KEY = new Property<String>("fldchrContrKey");
	public static final Property<String> FLDCHR_MONTH = new Property<String>("fldchrMonth");
	public static final Property<String> FLDCHR_YEAR = new Property<String>("fldchrYear");
	public static final Property<BigDecimal> FLDDBL_VALUE = new Property<BigDecimal>("flddblValue");

	public void setFldchrCharterType(String fldchrCharterType)
	{
		writeProperty("fldchrCharterType", fldchrCharterType);
	}

	public String getFldchrCharterType()
	{
		return (String) readProperty("fldchrCharterType");
	}

	public void setFldchrContrKey(String fldchrContrKey)
	{
		writeProperty("fldchrContrKey", fldchrContrKey);
	}

	public String getFldchrContrKey()
	{
		return (String) readProperty("fldchrContrKey");
	}

	public void setFldchrMonth(String fldchrMonth)
	{
		writeProperty("fldchrMonth", fldchrMonth);
	}

	public String getFldchrMonth()
	{
		return (String) readProperty("fldchrMonth");
	}

	public void setFldchrYear(String fldchrYear)
	{
		writeProperty("fldchrYear", fldchrYear);
	}

	public String getFldchrYear()
	{
		return (String) readProperty("fldchrYear");
	}

	public void setFlddblValue(BigDecimal flddblValue)
	{
		writeProperty("flddblValue", flddblValue);
	}

	public BigDecimal getFlddblValue()
	{
		return (BigDecimal) readProperty("flddblValue");
	}

}
