package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _WbContractBunkersMtmMrkt was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WbContractBunkersMtmMrkt extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String CONTRACT_KEY_PK_COLUMN = "contract_key";

	public static final Property<Integer> IFO_COMMKT_KEY = new Property<Integer>("ifoCommktKey");
	public static final Property<Integer> MDO_COMMKT_KEY = new Property<Integer>("mdoCommktKey");

	public void setIfoCommktKey(Integer ifoCommktKey)
	{
		writeProperty("ifoCommktKey", ifoCommktKey);
	}

	public Integer getIfoCommktKey()
	{
		return (Integer) readProperty("ifoCommktKey");
	}

	public void setMdoCommktKey(Integer mdoCommktKey)
	{
		writeProperty("mdoCommktKey", mdoCommktKey);
	}

	public Integer getMdoCommktKey()
	{
		return (Integer) readProperty("mdoCommktKey");
	}

}
