package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.CostContractLinks;
import com.tc.app.exchangemonitor.model.cayenne.persistent.WbContract;

/**
 * Class _WbContractTcCosts was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WbContractTcCosts extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String ID_PK_COLUMN = "id";

	public static final Property<Date> END_DATE = new Property<Date>("endDate");
	public static final Property<String> REMARKS = new Property<String>("remarks");
	public static final Property<Boolean> REVERSE_TO_VOYAGE = new Property<Boolean>("reverseToVoyage");
	public static final Property<Date> START_DATE = new Property<Date>("startDate");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<CostContractLinks> COST_CONTRACT_LINKS = new Property<CostContractLinks>("costContractLinks");
	public static final Property<WbContract> WB_CONTRACT = new Property<WbContract>("wbContract");

	public void setEndDate(Date endDate)
	{
		writeProperty("endDate", endDate);
	}

	public Date getEndDate()
	{
		return (Date) readProperty("endDate");
	}

	public void setRemarks(String remarks)
	{
		writeProperty("remarks", remarks);
	}

	public String getRemarks()
	{
		return (String) readProperty("remarks");
	}

	public void setReverseToVoyage(Boolean reverseToVoyage)
	{
		writeProperty("reverseToVoyage", reverseToVoyage);
	}

	public Boolean getReverseToVoyage()
	{
		return (Boolean) readProperty("reverseToVoyage");
	}

	public void setStartDate(Date startDate)
	{
		writeProperty("startDate", startDate);
	}

	public Date getStartDate()
	{
		return (Date) readProperty("startDate");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setCostContractLinks(CostContractLinks costContractLinks)
	{
		setToOneTarget("costContractLinks", costContractLinks, true);
	}

	public CostContractLinks getCostContractLinks()
	{
		return (CostContractLinks) readProperty("costContractLinks");
	}

	public void setWbContract(WbContract wbContract)
	{
		setToOneTarget("wbContract", wbContract, true);
	}

	public WbContract getWbContract()
	{
		return (WbContract) readProperty("wbContract");
	}

}
