package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _WbContractOffHireRob was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WbContractOffHireRob extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final Property<Double> EXCHANGE_RATE = new Property<Double>("exchangeRate");
	public static final Property<String> FLDCHR_COMMODITY_CODE = new Property<String>("fldchrCommodityCode");
	public static final Property<String> FLDCHR_CONTR_KEY = new Property<String>("fldchrContrKey");
	public static final Property<String> FLDCHR_CURRENCY_PRICE = new Property<String>("fldchrCurrencyPrice");
	public static final Property<String> FLDCHR_OP_ID = new Property<String>("fldchrOpId");
	public static final Property<Integer> FLDCHR_REC_ID = new Property<Integer>("fldchrRecId");
	public static final Property<BigDecimal> FLDDEC_CMDTY_PRICE = new Property<BigDecimal>("flddecCmdtyPrice");
	public static final Property<BigDecimal> FLDDEC_ROB_ACTUAL_DIFF = new Property<BigDecimal>("flddecRobActualDiff");
	public static final Property<BigDecimal> FLDDEC_ROB_AT_END_DATE = new Property<BigDecimal>("flddecRobAtEndDate");
	public static final Property<BigDecimal> FLDDEC_ROB_AT_START_DATE = new Property<BigDecimal>("flddecRobAtStartDate");
	public static final Property<BigDecimal> FLDDEC_ROB_DIFF = new Property<BigDecimal>("flddecRobDiff");

	public void setExchangeRate(Double exchangeRate)
	{
		writeProperty("exchangeRate", exchangeRate);
	}

	public Double getExchangeRate()
	{
		return (Double) readProperty("exchangeRate");
	}

	public void setFldchrCommodityCode(String fldchrCommodityCode)
	{
		writeProperty("fldchrCommodityCode", fldchrCommodityCode);
	}

	public String getFldchrCommodityCode()
	{
		return (String) readProperty("fldchrCommodityCode");
	}

	public void setFldchrContrKey(String fldchrContrKey)
	{
		writeProperty("fldchrContrKey", fldchrContrKey);
	}

	public String getFldchrContrKey()
	{
		return (String) readProperty("fldchrContrKey");
	}

	public void setFldchrCurrencyPrice(String fldchrCurrencyPrice)
	{
		writeProperty("fldchrCurrencyPrice", fldchrCurrencyPrice);
	}

	public String getFldchrCurrencyPrice()
	{
		return (String) readProperty("fldchrCurrencyPrice");
	}

	public void setFldchrOpId(String fldchrOpId)
	{
		writeProperty("fldchrOpId", fldchrOpId);
	}

	public String getFldchrOpId()
	{
		return (String) readProperty("fldchrOpId");
	}

	public void setFldchrRecId(Integer fldchrRecId)
	{
		writeProperty("fldchrRecId", fldchrRecId);
	}

	public Integer getFldchrRecId()
	{
		return (Integer) readProperty("fldchrRecId");
	}

	public void setFlddecCmdtyPrice(BigDecimal flddecCmdtyPrice)
	{
		writeProperty("flddecCmdtyPrice", flddecCmdtyPrice);
	}

	public BigDecimal getFlddecCmdtyPrice()
	{
		return (BigDecimal) readProperty("flddecCmdtyPrice");
	}

	public void setFlddecRobActualDiff(BigDecimal flddecRobActualDiff)
	{
		writeProperty("flddecRobActualDiff", flddecRobActualDiff);
	}

	public BigDecimal getFlddecRobActualDiff()
	{
		return (BigDecimal) readProperty("flddecRobActualDiff");
	}

	public void setFlddecRobAtEndDate(BigDecimal flddecRobAtEndDate)
	{
		writeProperty("flddecRobAtEndDate", flddecRobAtEndDate);
	}

	public BigDecimal getFlddecRobAtEndDate()
	{
		return (BigDecimal) readProperty("flddecRobAtEndDate");
	}

	public void setFlddecRobAtStartDate(BigDecimal flddecRobAtStartDate)
	{
		writeProperty("flddecRobAtStartDate", flddecRobAtStartDate);
	}

	public BigDecimal getFlddecRobAtStartDate()
	{
		return (BigDecimal) readProperty("flddecRobAtStartDate");
	}

	public void setFlddecRobDiff(BigDecimal flddecRobDiff)
	{
		writeProperty("flddecRobDiff", flddecRobDiff);
	}

	public BigDecimal getFlddecRobDiff()
	{
		return (BigDecimal) readProperty("flddecRobDiff");
	}

}
