package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;

/**
 * Class _WbContractRob was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WbContractRob extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_CMDTY_CODE_PK_COLUMN = "fldchrCmdtyCode";
	public static final String FLDCHR_CONTR_VSL_KEY_PK_COLUMN = "fldchrContrVslKey";

	public static final Property<String> FLDCHR_CMDTY_UMCODE = new Property<String>("fldchrCmdtyUMCode");
	public static final Property<String> FLDCHR_REC_ID = new Property<String>("fldchrRecId");
	public static final Property<BigDecimal> FLDDEC_END_ROB = new Property<BigDecimal>("flddecEndRob");
	public static final Property<BigDecimal> FLDDEC_END_UNIT_PRICE = new Property<BigDecimal>("flddecEndUnitPrice");
	public static final Property<BigDecimal> FLDDEC_START_ROB = new Property<BigDecimal>("flddecStartRob");
	public static final Property<BigDecimal> FLDDEC_START_UNIT_PRICE = new Property<BigDecimal>("flddecStartUnitPrice");
	public static final Property<String> FLDVCH_BUNKER_CONDITIONS = new Property<String>("fldvchBunkerConditions");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<Commodity> COMMODITY1 = new Property<Commodity>("commodity1");

	public void setFldchrCmdtyUMCode(String fldchrCmdtyUMCode)
	{
		writeProperty("fldchrCmdtyUMCode", fldchrCmdtyUMCode);
	}

	public String getFldchrCmdtyUMCode()
	{
		return (String) readProperty("fldchrCmdtyUMCode");
	}

	public void setFldchrRecId(String fldchrRecId)
	{
		writeProperty("fldchrRecId", fldchrRecId);
	}

	public String getFldchrRecId()
	{
		return (String) readProperty("fldchrRecId");
	}

	public void setFlddecEndRob(BigDecimal flddecEndRob)
	{
		writeProperty("flddecEndRob", flddecEndRob);
	}

	public BigDecimal getFlddecEndRob()
	{
		return (BigDecimal) readProperty("flddecEndRob");
	}

	public void setFlddecEndUnitPrice(BigDecimal flddecEndUnitPrice)
	{
		writeProperty("flddecEndUnitPrice", flddecEndUnitPrice);
	}

	public BigDecimal getFlddecEndUnitPrice()
	{
		return (BigDecimal) readProperty("flddecEndUnitPrice");
	}

	public void setFlddecStartRob(BigDecimal flddecStartRob)
	{
		writeProperty("flddecStartRob", flddecStartRob);
	}

	public BigDecimal getFlddecStartRob()
	{
		return (BigDecimal) readProperty("flddecStartRob");
	}

	public void setFlddecStartUnitPrice(BigDecimal flddecStartUnitPrice)
	{
		writeProperty("flddecStartUnitPrice", flddecStartUnitPrice);
	}

	public BigDecimal getFlddecStartUnitPrice()
	{
		return (BigDecimal) readProperty("flddecStartUnitPrice");
	}

	public void setFldvchBunkerConditions(String fldvchBunkerConditions)
	{
		writeProperty("fldvchBunkerConditions", fldvchBunkerConditions);
	}

	public String getFldvchBunkerConditions()
	{
		return (String) readProperty("fldvchBunkerConditions");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setCommodity1(Commodity commodity1)
	{
		setToOneTarget("commodity1", commodity1, true);
	}

	public Commodity getCommodity1()
	{
		return (Commodity) readProperty("commodity1");
	}

}
