package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _WbOpsCargo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WbOpsCargo extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_LOT_KEY_PK_COLUMN = "fldchrLotKey";
	public static final String FLDCHR_OP_ID_PK_COLUMN = "fldchrOpId";

	public static final Property<String> FLDCHR_BALLAST_WATER_UMCODE = new Property<String>("fldchrBallastWaterUMCode");
	public static final Property<String> FLDCHR_CARGO_MODE_FLAG = new Property<String>("fldchrCargoModeFlag");
	public static final Property<String> FLDCHR_CMDTY_CODE = new Property<String>("fldchrCmdtyCode");
	public static final Property<String> FLDCHR_CREATION_USER = new Property<String>("fldchrCreationUser");
	public static final Property<String> FLDCHR_DENSITY_UMCODE = new Property<String>("fldchrDensityUMCode");
	public static final Property<String> FLDCHR_LGHTN_FLAG = new Property<String>("fldchrLghtnFlag");
	public static final Property<String> FLDCHR_LGHTN_LLOYDS_REF_NUM = new Property<String>("fldchrLghtnLloydsRefNum");
	public static final Property<String> FLDCHR_NOMINAL_QTY_UMCODE = new Property<String>("fldchrNominalQtyUMCode");
	public static final Property<String> FLDCHR_OP_KEY = new Property<String>("fldchrOpKey");
	public static final Property<String> FLDCHR_PARENT_OP_KEY = new Property<String>("fldchrParentOpKey");
	public static final Property<String> FLDCHR_QTY_ACTUAL_FLAG = new Property<String>("fldchrQtyActualFlag");
	public static final Property<String> FLDCHR_TEMP_UMCODE = new Property<String>("fldchrTempUMCode");
	public static final Property<String> FLDCHR_UPDATE_USER = new Property<String>("fldchrUpdateUser");
	public static final Property<BigDecimal> FLDDEC_API_DEGREE = new Property<BigDecimal>("flddecApiDegree");
	public static final Property<BigDecimal> FLDDEC_BALLAST_WATER_QTY = new Property<BigDecimal>("flddecBallastWaterQty");
	public static final Property<BigDecimal> FLDDEC_BSW_PCTG = new Property<BigDecimal>("flddecBswPctg");
	public static final Property<BigDecimal> FLDDEC_DENSITY = new Property<BigDecimal>("flddecDensity");
	public static final Property<BigDecimal> FLDDEC_GROSS_QTY_BLL = new Property<BigDecimal>("flddecGrossQtyBLL");
	public static final Property<BigDecimal> FLDDEC_GROSS_QTY_MTQ = new Property<BigDecimal>("flddecGrossQtyMTQ");
	public static final Property<BigDecimal> FLDDEC_GROSS_QTY_TNE = new Property<BigDecimal>("flddecGrossQtyTNE");
	public static final Property<BigDecimal> FLDDEC_NET_QTY_BLL = new Property<BigDecimal>("flddecNetQtyBLL");
	public static final Property<BigDecimal> FLDDEC_NET_QTY_MTQ = new Property<BigDecimal>("flddecNetQtyMTQ");
	public static final Property<BigDecimal> FLDDEC_NET_QTY_TNE = new Property<BigDecimal>("flddecNetQtyTNE");
	public static final Property<BigDecimal> FLDDEC_NOMINAL_QTY = new Property<BigDecimal>("flddecNominalQty");
	public static final Property<BigDecimal> FLDDEC_TEMP = new Property<BigDecimal>("flddecTemp");
	public static final Property<BigDecimal> FLDDEC_VISCOSITY = new Property<BigDecimal>("flddecViscosity");
	public static final Property<Date> FLDSDT_BLDATE = new Property<Date>("fldsdtBLDate");
	public static final Property<Date> FLDSDT_CREATION_DATE = new Property<Date>("fldsdtCreationDate");
	public static final Property<Date> FLDSDT_OP_END = new Property<Date>("fldsdtOpEnd");
	public static final Property<Date> FLDSDT_OP_START = new Property<Date>("fldsdtOpStart");
	public static final Property<Date> FLDSDT_UPDATE_DATE = new Property<Date>("fldsdtUpdateDate");
	public static final Property<Short> FLDSMI_DTL_COUNTER = new Property<Short>("fldsmiDtlCounter");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");

	public void setFldchrBallastWaterUMCode(String fldchrBallastWaterUMCode)
	{
		writeProperty("fldchrBallastWaterUMCode", fldchrBallastWaterUMCode);
	}

	public String getFldchrBallastWaterUMCode()
	{
		return (String) readProperty("fldchrBallastWaterUMCode");
	}

	public void setFldchrCargoModeFlag(String fldchrCargoModeFlag)
	{
		writeProperty("fldchrCargoModeFlag", fldchrCargoModeFlag);
	}

	public String getFldchrCargoModeFlag()
	{
		return (String) readProperty("fldchrCargoModeFlag");
	}

	public void setFldchrCmdtyCode(String fldchrCmdtyCode)
	{
		writeProperty("fldchrCmdtyCode", fldchrCmdtyCode);
	}

	public String getFldchrCmdtyCode()
	{
		return (String) readProperty("fldchrCmdtyCode");
	}

	public void setFldchrCreationUser(String fldchrCreationUser)
	{
		writeProperty("fldchrCreationUser", fldchrCreationUser);
	}

	public String getFldchrCreationUser()
	{
		return (String) readProperty("fldchrCreationUser");
	}

	public void setFldchrDensityUMCode(String fldchrDensityUMCode)
	{
		writeProperty("fldchrDensityUMCode", fldchrDensityUMCode);
	}

	public String getFldchrDensityUMCode()
	{
		return (String) readProperty("fldchrDensityUMCode");
	}

	public void setFldchrLghtnFlag(String fldchrLghtnFlag)
	{
		writeProperty("fldchrLghtnFlag", fldchrLghtnFlag);
	}

	public String getFldchrLghtnFlag()
	{
		return (String) readProperty("fldchrLghtnFlag");
	}

	public void setFldchrLghtnLloydsRefNum(String fldchrLghtnLloydsRefNum)
	{
		writeProperty("fldchrLghtnLloydsRefNum", fldchrLghtnLloydsRefNum);
	}

	public String getFldchrLghtnLloydsRefNum()
	{
		return (String) readProperty("fldchrLghtnLloydsRefNum");
	}

	public void setFldchrNominalQtyUMCode(String fldchrNominalQtyUMCode)
	{
		writeProperty("fldchrNominalQtyUMCode", fldchrNominalQtyUMCode);
	}

	public String getFldchrNominalQtyUMCode()
	{
		return (String) readProperty("fldchrNominalQtyUMCode");
	}

	public void setFldchrOpKey(String fldchrOpKey)
	{
		writeProperty("fldchrOpKey", fldchrOpKey);
	}

	public String getFldchrOpKey()
	{
		return (String) readProperty("fldchrOpKey");
	}

	public void setFldchrParentOpKey(String fldchrParentOpKey)
	{
		writeProperty("fldchrParentOpKey", fldchrParentOpKey);
	}

	public String getFldchrParentOpKey()
	{
		return (String) readProperty("fldchrParentOpKey");
	}

	public void setFldchrQtyActualFlag(String fldchrQtyActualFlag)
	{
		writeProperty("fldchrQtyActualFlag", fldchrQtyActualFlag);
	}

	public String getFldchrQtyActualFlag()
	{
		return (String) readProperty("fldchrQtyActualFlag");
	}

	public void setFldchrTempUMCode(String fldchrTempUMCode)
	{
		writeProperty("fldchrTempUMCode", fldchrTempUMCode);
	}

	public String getFldchrTempUMCode()
	{
		return (String) readProperty("fldchrTempUMCode");
	}

	public void setFldchrUpdateUser(String fldchrUpdateUser)
	{
		writeProperty("fldchrUpdateUser", fldchrUpdateUser);
	}

	public String getFldchrUpdateUser()
	{
		return (String) readProperty("fldchrUpdateUser");
	}

	public void setFlddecApiDegree(BigDecimal flddecApiDegree)
	{
		writeProperty("flddecApiDegree", flddecApiDegree);
	}

	public BigDecimal getFlddecApiDegree()
	{
		return (BigDecimal) readProperty("flddecApiDegree");
	}

	public void setFlddecBallastWaterQty(BigDecimal flddecBallastWaterQty)
	{
		writeProperty("flddecBallastWaterQty", flddecBallastWaterQty);
	}

	public BigDecimal getFlddecBallastWaterQty()
	{
		return (BigDecimal) readProperty("flddecBallastWaterQty");
	}

	public void setFlddecBswPctg(BigDecimal flddecBswPctg)
	{
		writeProperty("flddecBswPctg", flddecBswPctg);
	}

	public BigDecimal getFlddecBswPctg()
	{
		return (BigDecimal) readProperty("flddecBswPctg");
	}

	public void setFlddecDensity(BigDecimal flddecDensity)
	{
		writeProperty("flddecDensity", flddecDensity);
	}

	public BigDecimal getFlddecDensity()
	{
		return (BigDecimal) readProperty("flddecDensity");
	}

	public void setFlddecGrossQtyBLL(BigDecimal flddecGrossQtyBLL)
	{
		writeProperty("flddecGrossQtyBLL", flddecGrossQtyBLL);
	}

	public BigDecimal getFlddecGrossQtyBLL()
	{
		return (BigDecimal) readProperty("flddecGrossQtyBLL");
	}

	public void setFlddecGrossQtyMTQ(BigDecimal flddecGrossQtyMTQ)
	{
		writeProperty("flddecGrossQtyMTQ", flddecGrossQtyMTQ);
	}

	public BigDecimal getFlddecGrossQtyMTQ()
	{
		return (BigDecimal) readProperty("flddecGrossQtyMTQ");
	}

	public void setFlddecGrossQtyTNE(BigDecimal flddecGrossQtyTNE)
	{
		writeProperty("flddecGrossQtyTNE", flddecGrossQtyTNE);
	}

	public BigDecimal getFlddecGrossQtyTNE()
	{
		return (BigDecimal) readProperty("flddecGrossQtyTNE");
	}

	public void setFlddecNetQtyBLL(BigDecimal flddecNetQtyBLL)
	{
		writeProperty("flddecNetQtyBLL", flddecNetQtyBLL);
	}

	public BigDecimal getFlddecNetQtyBLL()
	{
		return (BigDecimal) readProperty("flddecNetQtyBLL");
	}

	public void setFlddecNetQtyMTQ(BigDecimal flddecNetQtyMTQ)
	{
		writeProperty("flddecNetQtyMTQ", flddecNetQtyMTQ);
	}

	public BigDecimal getFlddecNetQtyMTQ()
	{
		return (BigDecimal) readProperty("flddecNetQtyMTQ");
	}

	public void setFlddecNetQtyTNE(BigDecimal flddecNetQtyTNE)
	{
		writeProperty("flddecNetQtyTNE", flddecNetQtyTNE);
	}

	public BigDecimal getFlddecNetQtyTNE()
	{
		return (BigDecimal) readProperty("flddecNetQtyTNE");
	}

	public void setFlddecNominalQty(BigDecimal flddecNominalQty)
	{
		writeProperty("flddecNominalQty", flddecNominalQty);
	}

	public BigDecimal getFlddecNominalQty()
	{
		return (BigDecimal) readProperty("flddecNominalQty");
	}

	public void setFlddecTemp(BigDecimal flddecTemp)
	{
		writeProperty("flddecTemp", flddecTemp);
	}

	public BigDecimal getFlddecTemp()
	{
		return (BigDecimal) readProperty("flddecTemp");
	}

	public void setFlddecViscosity(BigDecimal flddecViscosity)
	{
		writeProperty("flddecViscosity", flddecViscosity);
	}

	public BigDecimal getFlddecViscosity()
	{
		return (BigDecimal) readProperty("flddecViscosity");
	}

	public void setFldsdtBLDate(Date fldsdtBLDate)
	{
		writeProperty("fldsdtBLDate", fldsdtBLDate);
	}

	public Date getFldsdtBLDate()
	{
		return (Date) readProperty("fldsdtBLDate");
	}

	public void setFldsdtCreationDate(Date fldsdtCreationDate)
	{
		writeProperty("fldsdtCreationDate", fldsdtCreationDate);
	}

	public Date getFldsdtCreationDate()
	{
		return (Date) readProperty("fldsdtCreationDate");
	}

	public void setFldsdtOpEnd(Date fldsdtOpEnd)
	{
		writeProperty("fldsdtOpEnd", fldsdtOpEnd);
	}

	public Date getFldsdtOpEnd()
	{
		return (Date) readProperty("fldsdtOpEnd");
	}

	public void setFldsdtOpStart(Date fldsdtOpStart)
	{
		writeProperty("fldsdtOpStart", fldsdtOpStart);
	}

	public Date getFldsdtOpStart()
	{
		return (Date) readProperty("fldsdtOpStart");
	}

	public void setFldsdtUpdateDate(Date fldsdtUpdateDate)
	{
		writeProperty("fldsdtUpdateDate", fldsdtUpdateDate);
	}

	public Date getFldsdtUpdateDate()
	{
		return (Date) readProperty("fldsdtUpdateDate");
	}

	public void setFldsmiDtlCounter(Short fldsmiDtlCounter)
	{
		writeProperty("fldsmiDtlCounter", fldsmiDtlCounter);
	}

	public Short getFldsmiDtlCounter()
	{
		return (Short) readProperty("fldsmiDtlCounter");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

}
