package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.LloydsShipParticulars;
import com.tc.app.exchangemonitor.model.cayenne.persistent.WbContract;

/**
 * Class _WbPreVoyage was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WbPreVoyage extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_LOT_ID_PK_COLUMN = "fldchrLotId";
	public static final String FLDCHR_LOT_YEAR_PK_COLUMN = "fldchrLotYear";

	public static final Property<String> FLDCHR_CHART_MODE_FLAG = new Property<String>("fldchrChartModeFlag");
	public static final Property<String> FLDCHR_COASTWISE_FLAG = new Property<String>("fldchrCoastwiseFlag");
	public static final Property<String> FLDCHR_DOMESTIC_FLAG = new Property<String>("fldchrDomesticFlag");
	public static final Property<String> FLDCHR_LOT_KEY = new Property<String>("fldchrLotKey");
	public static final Property<String> FLDCHR_REF_MONTH = new Property<String>("fldchrRefMonth");
	public static final Property<String> FLDCHR_REF_YEAR = new Property<String>("fldchrRefYear");
	public static final Property<String> FLDCHR_SENT_FLAG = new Property<String>("fldchrSentFlag");
	public static final Property<Date> FLDSDT_END_DATE = new Property<Date>("fldsdtEndDate");
	public static final Property<Date> FLDSDT_START_DATE = new Property<Date>("fldsdtStartDate");
	public static final Property<LloydsShipParticulars> LLOYDS_SHIP_PARTICULARS = new Property<LloydsShipParticulars>("lloydsShipParticulars");
	public static final Property<WbContract> WB_CONTRACT = new Property<WbContract>("wbContract");

	public void setFldchrChartModeFlag(String fldchrChartModeFlag)
	{
		writeProperty("fldchrChartModeFlag", fldchrChartModeFlag);
	}

	public String getFldchrChartModeFlag()
	{
		return (String) readProperty("fldchrChartModeFlag");
	}

	public void setFldchrCoastwiseFlag(String fldchrCoastwiseFlag)
	{
		writeProperty("fldchrCoastwiseFlag", fldchrCoastwiseFlag);
	}

	public String getFldchrCoastwiseFlag()
	{
		return (String) readProperty("fldchrCoastwiseFlag");
	}

	public void setFldchrDomesticFlag(String fldchrDomesticFlag)
	{
		writeProperty("fldchrDomesticFlag", fldchrDomesticFlag);
	}

	public String getFldchrDomesticFlag()
	{
		return (String) readProperty("fldchrDomesticFlag");
	}

	public void setFldchrLotKey(String fldchrLotKey)
	{
		writeProperty("fldchrLotKey", fldchrLotKey);
	}

	public String getFldchrLotKey()
	{
		return (String) readProperty("fldchrLotKey");
	}

	public void setFldchrRefMonth(String fldchrRefMonth)
	{
		writeProperty("fldchrRefMonth", fldchrRefMonth);
	}

	public String getFldchrRefMonth()
	{
		return (String) readProperty("fldchrRefMonth");
	}

	public void setFldchrRefYear(String fldchrRefYear)
	{
		writeProperty("fldchrRefYear", fldchrRefYear);
	}

	public String getFldchrRefYear()
	{
		return (String) readProperty("fldchrRefYear");
	}

	public void setFldchrSentFlag(String fldchrSentFlag)
	{
		writeProperty("fldchrSentFlag", fldchrSentFlag);
	}

	public String getFldchrSentFlag()
	{
		return (String) readProperty("fldchrSentFlag");
	}

	public void setFldsdtEndDate(Date fldsdtEndDate)
	{
		writeProperty("fldsdtEndDate", fldsdtEndDate);
	}

	public Date getFldsdtEndDate()
	{
		return (Date) readProperty("fldsdtEndDate");
	}

	public void setFldsdtStartDate(Date fldsdtStartDate)
	{
		writeProperty("fldsdtStartDate", fldsdtStartDate);
	}

	public Date getFldsdtStartDate()
	{
		return (Date) readProperty("fldsdtStartDate");
	}

	public void setLloydsShipParticulars(LloydsShipParticulars lloydsShipParticulars)
	{
		setToOneTarget("lloydsShipParticulars", lloydsShipParticulars, true);
	}

	public LloydsShipParticulars getLloydsShipParticulars()
	{
		return (LloydsShipParticulars) readProperty("lloydsShipParticulars");
	}

	public void setWbContract(WbContract wbContract)
	{
		setToOneTarget("wbContract", wbContract, true);
	}

	public WbContract getWbContract()
	{
		return (WbContract) readProperty("wbContract");
	}

}
