package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.Commodity;
import com.tc.app.exchangemonitor.model.cayenne.persistent.LocationStorages;
import com.tc.app.exchangemonitor.model.cayenne.persistent.WbTemplates;

/**
 * Class _WbTemplatesOps was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WbTemplatesOps extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_VOYG_TEMPLATE_ID_PK_COLUMN = "fldchrVoygTemplateId";
	public static final String FLDSMI_OP_ORDER_PK_COLUMN = "fldsmiOpOrder";

	public static final Property<String> FLDCHR_CMDTY_QTY_UMCODE = new Property<String>("fldchrCmdtyQtyUMCode");
	public static final Property<String> FLDCHR_LOAD_PORT = new Property<String>("fldchrLoadPort");
	public static final Property<String> FLDCHR_OP_TYPE_FLAG = new Property<String>("fldchrOpTypeFlag");
	public static final Property<String> FLDCHR_REC_ID = new Property<String>("fldchrRecId");
	public static final Property<String> FLDCHR_UNLD_PORT = new Property<String>("fldchrUnldPort");
	public static final Property<BigDecimal> FLDDEC_CMDTY_QTY = new Property<BigDecimal>("flddecCmdtyQty");
	public static final Property<Integer> FLDINT_RCVR_ACCT_NUM = new Property<Integer>("fldintRcvrAcctNum");
	public static final Property<Integer> FLDINT_SHPR_ACCT_NUM = new Property<Integer>("fldintShprAcctNum");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<Commodity> COMMODITY = new Property<Commodity>("commodity");
	public static final Property<WbTemplates> FLDCHR_VOYG_TEMPLATE = new Property<WbTemplates>("fldchrVoygTemplate");
	public static final Property<LocationStorages> LOCATION_STORAGES = new Property<LocationStorages>("locationStorages");
	public static final Property<LocationStorages> LOCATION_STORAGES1 = new Property<LocationStorages>("locationStorages1");

	public void setFldchrCmdtyQtyUMCode(String fldchrCmdtyQtyUMCode)
	{
		writeProperty("fldchrCmdtyQtyUMCode", fldchrCmdtyQtyUMCode);
	}

	public String getFldchrCmdtyQtyUMCode()
	{
		return (String) readProperty("fldchrCmdtyQtyUMCode");
	}

	public void setFldchrLoadPort(String fldchrLoadPort)
	{
		writeProperty("fldchrLoadPort", fldchrLoadPort);
	}

	public String getFldchrLoadPort()
	{
		return (String) readProperty("fldchrLoadPort");
	}

	public void setFldchrOpTypeFlag(String fldchrOpTypeFlag)
	{
		writeProperty("fldchrOpTypeFlag", fldchrOpTypeFlag);
	}

	public String getFldchrOpTypeFlag()
	{
		return (String) readProperty("fldchrOpTypeFlag");
	}

	public void setFldchrRecId(String fldchrRecId)
	{
		writeProperty("fldchrRecId", fldchrRecId);
	}

	public String getFldchrRecId()
	{
		return (String) readProperty("fldchrRecId");
	}

	public void setFldchrUnldPort(String fldchrUnldPort)
	{
		writeProperty("fldchrUnldPort", fldchrUnldPort);
	}

	public String getFldchrUnldPort()
	{
		return (String) readProperty("fldchrUnldPort");
	}

	public void setFlddecCmdtyQty(BigDecimal flddecCmdtyQty)
	{
		writeProperty("flddecCmdtyQty", flddecCmdtyQty);
	}

	public BigDecimal getFlddecCmdtyQty()
	{
		return (BigDecimal) readProperty("flddecCmdtyQty");
	}

	public void setFldintRcvrAcctNum(Integer fldintRcvrAcctNum)
	{
		writeProperty("fldintRcvrAcctNum", fldintRcvrAcctNum);
	}

	public Integer getFldintRcvrAcctNum()
	{
		return (Integer) readProperty("fldintRcvrAcctNum");
	}

	public void setFldintShprAcctNum(Integer fldintShprAcctNum)
	{
		writeProperty("fldintShprAcctNum", fldintShprAcctNum);
	}

	public Integer getFldintShprAcctNum()
	{
		return (Integer) readProperty("fldintShprAcctNum");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setCommodity(Commodity commodity)
	{
		setToOneTarget("commodity", commodity, true);
	}

	public Commodity getCommodity()
	{
		return (Commodity) readProperty("commodity");
	}

	public void setFldchrVoygTemplate(WbTemplates fldchrVoygTemplate)
	{
		setToOneTarget("fldchrVoygTemplate", fldchrVoygTemplate, true);
	}

	public WbTemplates getFldchrVoygTemplate()
	{
		return (WbTemplates) readProperty("fldchrVoygTemplate");
	}

	public void setLocationStorages(LocationStorages locationStorages)
	{
		setToOneTarget("locationStorages", locationStorages, true);
	}

	public LocationStorages getLocationStorages()
	{
		return (LocationStorages) readProperty("locationStorages");
	}

	public void setLocationStorages1(LocationStorages locationStorages1)
	{
		setToOneTarget("locationStorages1", locationStorages1, true);
	}

	public LocationStorages getLocationStorages1()
	{
		return (LocationStorages) readProperty("locationStorages1");
	}

}
