package com.tc.app.exchangemonitor.model.cayenne.persistent.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.tc.app.exchangemonitor.model.cayenne.persistent.WbVoyageComments;

/**
 * Class _WbVoyage was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WbVoyage extends CayenneDataObject
{

	private static final long serialVersionUID = 1L;

	public static final String FLDCHR_LOT_ID_PK_COLUMN = "fldchrLotId";
	public static final String FLDCHR_LOT_YEAR_PK_COLUMN = "fldchrLotYear";

	public static final Property<String> FLDCHR_ABSTIME_CHARTER_FLAG = new Property<String>("fldchrABSTimeCharterFlag");
	public static final Property<String> FLDCHR_ADDITIONAL_FREIGHT_SIGN = new Property<String>("fldchrAdditionalFreightSign");
	public static final Property<String> FLDCHR_BUNKER_CRNCY_CODE = new Property<String>("fldchrBunkerCrncyCode");
	public static final Property<String> FLDCHR_CHART_MODE_FLAG = new Property<String>("fldchrChartModeFlag");
	public static final Property<String> FLDCHR_COASTWISE_FLAG = new Property<String>("fldchrCoastwiseFlag");
	public static final Property<String> FLDCHR_CONTR_KEY = new Property<String>("fldchrContrKey");
	public static final Property<String> FLDCHR_COSTAMT_CRNCY_CODE = new Property<String>("fldchrCostamtCrncyCode");
	public static final Property<String> FLDCHR_CREATION_USER = new Property<String>("fldchrCreationUser");
	public static final Property<String> FLDCHR_DELETE_VOYAGE_FLAG = new Property<String>("fldchrDeleteVoyageFlag");
	public static final Property<String> FLDCHR_DOMESTIC_FLAG = new Property<String>("fldchrDomesticFlag");
	public static final Property<String> FLDCHR_FIXTURE_PREFIX = new Property<String>("fldchrFixturePrefix");
	public static final Property<String> FLDCHR_FLAG_GEDOST = new Property<String>("fldchrFlagGedost");
	public static final Property<String> FLDCHR_FREIGHT_ACTUAL_FLAG = new Property<String>("fldchrFreightActualFlag");
	public static final Property<String> FLDCHR_FREIGHT_CRNCY_CODE = new Property<String>("fldchrFreightCrncyCode");
	public static final Property<String> FLDCHR_LLOYDS_REF_NUM = new Property<String>("fldchrLloydsRefNum");
	public static final Property<String> FLDCHR_MARK_MARKET_CRNCY_CODE = new Property<String>("fldchrMarkMarketCrncyCode");
	public static final Property<String> FLDCHR_PREV_VOYG_LOCT_KEY = new Property<String>("fldchrPrevVoygLoctKey");
	public static final Property<String> FLDCHR_REF_MONTH = new Property<String>("fldchrRefMonth");
	public static final Property<String> FLDCHR_REF_YEAR = new Property<String>("fldchrRefYear");
	public static final Property<String> FLDCHR_SPOT_FREIGH_TYPE_IND = new Property<String>("fldchrSpotFreighTypeInd");
	public static final Property<String> FLDCHR_TBNCRNCY_CODE = new Property<String>("fldchrTBNCrncyCode");
	public static final Property<String> FLDCHR_TBN_FLAG = new Property<String>("fldchrTbnFlag");
	public static final Property<String> FLDCHR_UPDATE_USER = new Property<String>("fldchrUpdateUser");
	public static final Property<String> FLDCHR_VOYG_CONFIRMATION_FLAG = new Property<String>("fldchrVoygConfirmationFlag");
	public static final Property<String> FLDCHR_VOYG_OFFH_FLAG = new Property<String>("fldchrVoygOffhFlag");
	public static final Property<String> FLDCHR_VOYG_STATUS_FLAG = new Property<String>("fldchrVoygStatusFlag");
	public static final Property<String> FLDCHR_WORK_AREA_CODE = new Property<String>("fldchrWorkAreaCode");
	public static final Property<BigDecimal> FLDDEC_ADDITIONAL_FREIGHT = new Property<BigDecimal>("flddecAdditionalFreight");
	public static final Property<BigDecimal> FLDDEC_BUNKER_AMOUNT = new Property<BigDecimal>("flddecBunkerAmount");
	public static final Property<BigDecimal> FLDDEC_BUNKER_TOTAL_QTY = new Property<BigDecimal>("flddecBunkerTotalQty");
	public static final Property<BigDecimal> FLDDEC_FLAT_RATE = new Property<BigDecimal>("flddecFlatRate");
	public static final Property<BigDecimal> FLDDEC_FREIGHT = new Property<BigDecimal>("flddecFreight");
	public static final Property<BigDecimal> FLDDEC_MARK_MARKET_FLAT_RATE = new Property<BigDecimal>("flddecMarkMarketFlatRate");
	public static final Property<BigDecimal> FLDDEC_MARK_MARKET_FREIGHT = new Property<BigDecimal>("flddecMarkMarketFreight");
	public static final Property<BigDecimal> FLDDEC_MARK_MARKET_WS_RATE = new Property<BigDecimal>("flddecMarkMarketWsRate");
	public static final Property<BigDecimal> FLDDEC_MARKET_QTY = new Property<BigDecimal>("flddecMarketQty");
	public static final Property<BigDecimal> FLDDEC_MARKET_VALUE = new Property<BigDecimal>("flddecMarketValue");
	public static final Property<BigDecimal> FLDDEC_TBNTOTAL_PRICE = new Property<BigDecimal>("flddecTBNTotalPrice");
	public static final Property<BigDecimal> FLDDEC_WS_RATE = new Property<BigDecimal>("flddecWsRate");
	public static final Property<Double> FLDFLT_COSTAMT_TOTAL_NOLO = new Property<Double>("fldfltCostamtTotalNolo");
	public static final Property<Date> FLDSDT_CONCLUDED_DATE = new Property<Date>("fldsdtConcludedDate");
	public static final Property<Date> FLDSDT_CREATION_DATE = new Property<Date>("fldsdtCreationDate");
	public static final Property<Date> FLDSDT_END_DATE = new Property<Date>("fldsdtEndDate");
	public static final Property<Date> FLDSDT_PREV_VOYG_DEP_DATE = new Property<Date>("fldsdtPrevVoygDepDate");
	public static final Property<Date> FLDSDT_START_DATE = new Property<Date>("fldsdtStartDate");
	public static final Property<Date> FLDSDT_UPDATE_DATE = new Property<Date>("fldsdtUpdateDate");
	public static final Property<Short> FLDSMI_OP_COUNTER = new Property<Short>("fldsmiOpCounter");
	public static final Property<Short> FLDSMI_VLCCSPOT_RATE_IND = new Property<Short>("fldsmiVLCCSpotRateInd");
	public static final Property<Short> FLDSMI_VOYG_COUNTER = new Property<Short>("fldsmiVoygCounter");
	public static final Property<String> FLDVCH_FIXTURE_NUMBER = new Property<String>("fldvchFixtureNumber");
	public static final Property<String> FLDVCH_FREIGHT_REMARKS = new Property<String>("fldvchFreightRemarks");
	public static final Property<Integer> TRANS_ID = new Property<Integer>("transId");
	public static final Property<String> USER_INIT = new Property<String>("userInit");
	public static final Property<WbVoyageComments> WB_VOYAGE = new Property<WbVoyageComments>("wbVoyage");

	public void setFldchrABSTimeCharterFlag(String fldchrABSTimeCharterFlag)
	{
		writeProperty("fldchrABSTimeCharterFlag", fldchrABSTimeCharterFlag);
	}

	public String getFldchrABSTimeCharterFlag()
	{
		return (String) readProperty("fldchrABSTimeCharterFlag");
	}

	public void setFldchrAdditionalFreightSign(String fldchrAdditionalFreightSign)
	{
		writeProperty("fldchrAdditionalFreightSign", fldchrAdditionalFreightSign);
	}

	public String getFldchrAdditionalFreightSign()
	{
		return (String) readProperty("fldchrAdditionalFreightSign");
	}

	public void setFldchrBunkerCrncyCode(String fldchrBunkerCrncyCode)
	{
		writeProperty("fldchrBunkerCrncyCode", fldchrBunkerCrncyCode);
	}

	public String getFldchrBunkerCrncyCode()
	{
		return (String) readProperty("fldchrBunkerCrncyCode");
	}

	public void setFldchrChartModeFlag(String fldchrChartModeFlag)
	{
		writeProperty("fldchrChartModeFlag", fldchrChartModeFlag);
	}

	public String getFldchrChartModeFlag()
	{
		return (String) readProperty("fldchrChartModeFlag");
	}

	public void setFldchrCoastwiseFlag(String fldchrCoastwiseFlag)
	{
		writeProperty("fldchrCoastwiseFlag", fldchrCoastwiseFlag);
	}

	public String getFldchrCoastwiseFlag()
	{
		return (String) readProperty("fldchrCoastwiseFlag");
	}

	public void setFldchrContrKey(String fldchrContrKey)
	{
		writeProperty("fldchrContrKey", fldchrContrKey);
	}

	public String getFldchrContrKey()
	{
		return (String) readProperty("fldchrContrKey");
	}

	public void setFldchrCostamtCrncyCode(String fldchrCostamtCrncyCode)
	{
		writeProperty("fldchrCostamtCrncyCode", fldchrCostamtCrncyCode);
	}

	public String getFldchrCostamtCrncyCode()
	{
		return (String) readProperty("fldchrCostamtCrncyCode");
	}

	public void setFldchrCreationUser(String fldchrCreationUser)
	{
		writeProperty("fldchrCreationUser", fldchrCreationUser);
	}

	public String getFldchrCreationUser()
	{
		return (String) readProperty("fldchrCreationUser");
	}

	public void setFldchrDeleteVoyageFlag(String fldchrDeleteVoyageFlag)
	{
		writeProperty("fldchrDeleteVoyageFlag", fldchrDeleteVoyageFlag);
	}

	public String getFldchrDeleteVoyageFlag()
	{
		return (String) readProperty("fldchrDeleteVoyageFlag");
	}

	public void setFldchrDomesticFlag(String fldchrDomesticFlag)
	{
		writeProperty("fldchrDomesticFlag", fldchrDomesticFlag);
	}

	public String getFldchrDomesticFlag()
	{
		return (String) readProperty("fldchrDomesticFlag");
	}

	public void setFldchrFixturePrefix(String fldchrFixturePrefix)
	{
		writeProperty("fldchrFixturePrefix", fldchrFixturePrefix);
	}

	public String getFldchrFixturePrefix()
	{
		return (String) readProperty("fldchrFixturePrefix");
	}

	public void setFldchrFlagGedost(String fldchrFlagGedost)
	{
		writeProperty("fldchrFlagGedost", fldchrFlagGedost);
	}

	public String getFldchrFlagGedost()
	{
		return (String) readProperty("fldchrFlagGedost");
	}

	public void setFldchrFreightActualFlag(String fldchrFreightActualFlag)
	{
		writeProperty("fldchrFreightActualFlag", fldchrFreightActualFlag);
	}

	public String getFldchrFreightActualFlag()
	{
		return (String) readProperty("fldchrFreightActualFlag");
	}

	public void setFldchrFreightCrncyCode(String fldchrFreightCrncyCode)
	{
		writeProperty("fldchrFreightCrncyCode", fldchrFreightCrncyCode);
	}

	public String getFldchrFreightCrncyCode()
	{
		return (String) readProperty("fldchrFreightCrncyCode");
	}

	public void setFldchrLloydsRefNum(String fldchrLloydsRefNum)
	{
		writeProperty("fldchrLloydsRefNum", fldchrLloydsRefNum);
	}

	public String getFldchrLloydsRefNum()
	{
		return (String) readProperty("fldchrLloydsRefNum");
	}

	public void setFldchrMarkMarketCrncyCode(String fldchrMarkMarketCrncyCode)
	{
		writeProperty("fldchrMarkMarketCrncyCode", fldchrMarkMarketCrncyCode);
	}

	public String getFldchrMarkMarketCrncyCode()
	{
		return (String) readProperty("fldchrMarkMarketCrncyCode");
	}

	public void setFldchrPrevVoygLoctKey(String fldchrPrevVoygLoctKey)
	{
		writeProperty("fldchrPrevVoygLoctKey", fldchrPrevVoygLoctKey);
	}

	public String getFldchrPrevVoygLoctKey()
	{
		return (String) readProperty("fldchrPrevVoygLoctKey");
	}

	public void setFldchrRefMonth(String fldchrRefMonth)
	{
		writeProperty("fldchrRefMonth", fldchrRefMonth);
	}

	public String getFldchrRefMonth()
	{
		return (String) readProperty("fldchrRefMonth");
	}

	public void setFldchrRefYear(String fldchrRefYear)
	{
		writeProperty("fldchrRefYear", fldchrRefYear);
	}

	public String getFldchrRefYear()
	{
		return (String) readProperty("fldchrRefYear");
	}

	public void setFldchrSpotFreighTypeInd(String fldchrSpotFreighTypeInd)
	{
		writeProperty("fldchrSpotFreighTypeInd", fldchrSpotFreighTypeInd);
	}

	public String getFldchrSpotFreighTypeInd()
	{
		return (String) readProperty("fldchrSpotFreighTypeInd");
	}

	public void setFldchrTBNCrncyCode(String fldchrTBNCrncyCode)
	{
		writeProperty("fldchrTBNCrncyCode", fldchrTBNCrncyCode);
	}

	public String getFldchrTBNCrncyCode()
	{
		return (String) readProperty("fldchrTBNCrncyCode");
	}

	public void setFldchrTbnFlag(String fldchrTbnFlag)
	{
		writeProperty("fldchrTbnFlag", fldchrTbnFlag);
	}

	public String getFldchrTbnFlag()
	{
		return (String) readProperty("fldchrTbnFlag");
	}

	public void setFldchrUpdateUser(String fldchrUpdateUser)
	{
		writeProperty("fldchrUpdateUser", fldchrUpdateUser);
	}

	public String getFldchrUpdateUser()
	{
		return (String) readProperty("fldchrUpdateUser");
	}

	public void setFldchrVoygConfirmationFlag(String fldchrVoygConfirmationFlag)
	{
		writeProperty("fldchrVoygConfirmationFlag", fldchrVoygConfirmationFlag);
	}

	public String getFldchrVoygConfirmationFlag()
	{
		return (String) readProperty("fldchrVoygConfirmationFlag");
	}

	public void setFldchrVoygOffhFlag(String fldchrVoygOffhFlag)
	{
		writeProperty("fldchrVoygOffhFlag", fldchrVoygOffhFlag);
	}

	public String getFldchrVoygOffhFlag()
	{
		return (String) readProperty("fldchrVoygOffhFlag");
	}

	public void setFldchrVoygStatusFlag(String fldchrVoygStatusFlag)
	{
		writeProperty("fldchrVoygStatusFlag", fldchrVoygStatusFlag);
	}

	public String getFldchrVoygStatusFlag()
	{
		return (String) readProperty("fldchrVoygStatusFlag");
	}

	public void setFldchrWorkAreaCode(String fldchrWorkAreaCode)
	{
		writeProperty("fldchrWorkAreaCode", fldchrWorkAreaCode);
	}

	public String getFldchrWorkAreaCode()
	{
		return (String) readProperty("fldchrWorkAreaCode");
	}

	public void setFlddecAdditionalFreight(BigDecimal flddecAdditionalFreight)
	{
		writeProperty("flddecAdditionalFreight", flddecAdditionalFreight);
	}

	public BigDecimal getFlddecAdditionalFreight()
	{
		return (BigDecimal) readProperty("flddecAdditionalFreight");
	}

	public void setFlddecBunkerAmount(BigDecimal flddecBunkerAmount)
	{
		writeProperty("flddecBunkerAmount", flddecBunkerAmount);
	}

	public BigDecimal getFlddecBunkerAmount()
	{
		return (BigDecimal) readProperty("flddecBunkerAmount");
	}

	public void setFlddecBunkerTotalQty(BigDecimal flddecBunkerTotalQty)
	{
		writeProperty("flddecBunkerTotalQty", flddecBunkerTotalQty);
	}

	public BigDecimal getFlddecBunkerTotalQty()
	{
		return (BigDecimal) readProperty("flddecBunkerTotalQty");
	}

	public void setFlddecFlatRate(BigDecimal flddecFlatRate)
	{
		writeProperty("flddecFlatRate", flddecFlatRate);
	}

	public BigDecimal getFlddecFlatRate()
	{
		return (BigDecimal) readProperty("flddecFlatRate");
	}

	public void setFlddecFreight(BigDecimal flddecFreight)
	{
		writeProperty("flddecFreight", flddecFreight);
	}

	public BigDecimal getFlddecFreight()
	{
		return (BigDecimal) readProperty("flddecFreight");
	}

	public void setFlddecMarkMarketFlatRate(BigDecimal flddecMarkMarketFlatRate)
	{
		writeProperty("flddecMarkMarketFlatRate", flddecMarkMarketFlatRate);
	}

	public BigDecimal getFlddecMarkMarketFlatRate()
	{
		return (BigDecimal) readProperty("flddecMarkMarketFlatRate");
	}

	public void setFlddecMarkMarketFreight(BigDecimal flddecMarkMarketFreight)
	{
		writeProperty("flddecMarkMarketFreight", flddecMarkMarketFreight);
	}

	public BigDecimal getFlddecMarkMarketFreight()
	{
		return (BigDecimal) readProperty("flddecMarkMarketFreight");
	}

	public void setFlddecMarkMarketWsRate(BigDecimal flddecMarkMarketWsRate)
	{
		writeProperty("flddecMarkMarketWsRate", flddecMarkMarketWsRate);
	}

	public BigDecimal getFlddecMarkMarketWsRate()
	{
		return (BigDecimal) readProperty("flddecMarkMarketWsRate");
	}

	public void setFlddecMarketQty(BigDecimal flddecMarketQty)
	{
		writeProperty("flddecMarketQty", flddecMarketQty);
	}

	public BigDecimal getFlddecMarketQty()
	{
		return (BigDecimal) readProperty("flddecMarketQty");
	}

	public void setFlddecMarketValue(BigDecimal flddecMarketValue)
	{
		writeProperty("flddecMarketValue", flddecMarketValue);
	}

	public BigDecimal getFlddecMarketValue()
	{
		return (BigDecimal) readProperty("flddecMarketValue");
	}

	public void setFlddecTBNTotalPrice(BigDecimal flddecTBNTotalPrice)
	{
		writeProperty("flddecTBNTotalPrice", flddecTBNTotalPrice);
	}

	public BigDecimal getFlddecTBNTotalPrice()
	{
		return (BigDecimal) readProperty("flddecTBNTotalPrice");
	}

	public void setFlddecWsRate(BigDecimal flddecWsRate)
	{
		writeProperty("flddecWsRate", flddecWsRate);
	}

	public BigDecimal getFlddecWsRate()
	{
		return (BigDecimal) readProperty("flddecWsRate");
	}

	public void setFldfltCostamtTotalNolo(Double fldfltCostamtTotalNolo)
	{
		writeProperty("fldfltCostamtTotalNolo", fldfltCostamtTotalNolo);
	}

	public Double getFldfltCostamtTotalNolo()
	{
		return (Double) readProperty("fldfltCostamtTotalNolo");
	}

	public void setFldsdtConcludedDate(Date fldsdtConcludedDate)
	{
		writeProperty("fldsdtConcludedDate", fldsdtConcludedDate);
	}

	public Date getFldsdtConcludedDate()
	{
		return (Date) readProperty("fldsdtConcludedDate");
	}

	public void setFldsdtCreationDate(Date fldsdtCreationDate)
	{
		writeProperty("fldsdtCreationDate", fldsdtCreationDate);
	}

	public Date getFldsdtCreationDate()
	{
		return (Date) readProperty("fldsdtCreationDate");
	}

	public void setFldsdtEndDate(Date fldsdtEndDate)
	{
		writeProperty("fldsdtEndDate", fldsdtEndDate);
	}

	public Date getFldsdtEndDate()
	{
		return (Date) readProperty("fldsdtEndDate");
	}

	public void setFldsdtPrevVoygDepDate(Date fldsdtPrevVoygDepDate)
	{
		writeProperty("fldsdtPrevVoygDepDate", fldsdtPrevVoygDepDate);
	}

	public Date getFldsdtPrevVoygDepDate()
	{
		return (Date) readProperty("fldsdtPrevVoygDepDate");
	}

	public void setFldsdtStartDate(Date fldsdtStartDate)
	{
		writeProperty("fldsdtStartDate", fldsdtStartDate);
	}

	public Date getFldsdtStartDate()
	{
		return (Date) readProperty("fldsdtStartDate");
	}

	public void setFldsdtUpdateDate(Date fldsdtUpdateDate)
	{
		writeProperty("fldsdtUpdateDate", fldsdtUpdateDate);
	}

	public Date getFldsdtUpdateDate()
	{
		return (Date) readProperty("fldsdtUpdateDate");
	}

	public void setFldsmiOpCounter(Short fldsmiOpCounter)
	{
		writeProperty("fldsmiOpCounter", fldsmiOpCounter);
	}

	public Short getFldsmiOpCounter()
	{
		return (Short) readProperty("fldsmiOpCounter");
	}

	public void setFldsmiVLCCSpotRateInd(Short fldsmiVLCCSpotRateInd)
	{
		writeProperty("fldsmiVLCCSpotRateInd", fldsmiVLCCSpotRateInd);
	}

	public Short getFldsmiVLCCSpotRateInd()
	{
		return (Short) readProperty("fldsmiVLCCSpotRateInd");
	}

	public void setFldsmiVoygCounter(Short fldsmiVoygCounter)
	{
		writeProperty("fldsmiVoygCounter", fldsmiVoygCounter);
	}

	public Short getFldsmiVoygCounter()
	{
		return (Short) readProperty("fldsmiVoygCounter");
	}

	public void setFldvchFixtureNumber(String fldvchFixtureNumber)
	{
		writeProperty("fldvchFixtureNumber", fldvchFixtureNumber);
	}

	public String getFldvchFixtureNumber()
	{
		return (String) readProperty("fldvchFixtureNumber");
	}

	public void setFldvchFreightRemarks(String fldvchFreightRemarks)
	{
		writeProperty("fldvchFreightRemarks", fldvchFreightRemarks);
	}

	public String getFldvchFreightRemarks()
	{
		return (String) readProperty("fldvchFreightRemarks");
	}

	public void setTransId(Integer transId)
	{
		writeProperty("transId", transId);
	}

	public Integer getTransId()
	{
		return (Integer) readProperty("transId");
	}

	public void setUserInit(String userInit)
	{
		writeProperty("userInit", userInit);
	}

	public String getUserInit()
	{
		return (String) readProperty("userInit");
	}

	public void setWbVoyage(WbVoyageComments wbVoyage)
	{
		setToOneTarget("wbVoyage", wbVoyage, true);
	}

	public WbVoyageComments getWbVoyage()
	{
		return (WbVoyageComments) readProperty("wbVoyage");
	}

}
